### ISSUE TITLE
Support rnpm

### ISSUE THREAD

**Issue by sibeliusseraphini** [ivpusic/react-native-image-crop-picker#1]

**Comment by ivpusic** [comment]
currently I have no plans of supporting rnpm. Lib depends on few external dependencies, and for now it is easier to manage this with package manager gradle/cocoapods. 

PR to support rnpm is welcome

**Comment by tomazahlin** [comment]
Looks like I will not use this library, just because there is no rnpm support.

**Comment by ivpusic** [comment]
feel free to submit PR

**Comment by ivpusic** [comment]
supported now https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.7.0
