### ISSUE TITLE
Video compression in android.

### ISSUE THREAD

**Issue by harikrishna1213** [ivpusic/react-native-image-crop-picker#1005]
Video Compression is not available in android right now? It is available for IOS only. When can we expect the release video compression for the android platform?

### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.?.?
- react-native v0.?.?

### Platform
Tell us to which platform this issue is related

- iOS
- Android

### Steps to reproduce

1.

2.

3.

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by ivpusic** [comment]
no plans in the near future
