### ISSUE TITLE
The callback openPicker() exists in module ImageCropPicker, but only one callback may be registered to a function in a native module.

### ISSUE THREAD

**Issue by ronshn** [ivpusic/react-native-image-crop-picker#1008]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker 0.24.0
- react-native 0.59.8

### Platform
Tell us to which platform this issue is related

- iOS

### Expected behaviour
Cancel cpropper and reject to home or select another image agin normally.

### Actual behaviour
Cancel the cropper and stay at image list, but select another image get the error.

### Steps to reproduce

1.openPicker with cropping true.

2.select a image get the cropping page.

3.click cancel button back to image list page.

4. select another image to cropping , click choose button get the error.

5. from 3th step click the back button , click cancel button get the error too.

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by nicholasrq** [comment]
+1. really weird behaivor

**Comment by amilcarj** [comment]
check this out 
https://github.com/ivpusic/react-native-image-crop-picker/issues/994
