### ISSUE TITLE
How to take a Video?

### ISSUE THREAD

**Issue by MingYe-dz** [ivpusic/react-native-image-crop-picker#101]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.?.?
- react-native v0.?.?

### Platform
Tell us to which platform this issue is related

- iOS
- Android

### Steps to reproduce

1.

2.

3.

### Attachments

// stacktrace or any other useful debug info

**Comment by ivpusic** [comment]
currently you can just select video but not record it and then send it. PR supporting this feature would be welcome

**Comment by Jyrno42** [comment]
@ivpusic There are currently two open PRs implementing this feature (#700 and #729)
