### ISSUE TITLE
Xcode 10.2.1  QBImagePicker.storyboard:-1: Compilation Failed

### ISSUE THREAD

**Issue by Link-Kou** [ivpusic/react-native-image-crop-picker#1011]
- react-native-image-crop-picker 0.21.3
- react-native v0.57
- xcode 10.2.1 (10E1001)

Xcode Build
QBImagePicker.storyboard:  Compilation Failed

**Comment by Elf2707** [comment]
Clean the project CMD + Shift + Alt + K and reboot the computer after Xcode update magically solved the issue for me.

**Comment by gevorg94** [comment]
Thanks @Elf2707 it helps!

**Comment by firmaydani** [comment]
thx broo @Elf2707

**Comment by alexkendall** [comment]
Still getting this error after following your instructions @Elf2707

**Comment by PavanGangireddy** [comment]
@all

I could still get this error and i have tried almost all the solutions in the top 20 google searches, but no results.

Any heads up on this?

**Comment by monikarani** [comment]
Compilation failed 
QBImagePicker.storyboard
I am using version :-
react-native-image-crop-picker 0.37.2
react-native v0.64.1
xcode 13.2.1
MacBook Air M1

**Comment by filipsavicfireside** [comment]
I lost an entire day on this... in the end I updated my MacOS and XCode and my build passed...

**Comment by PiggyBottle** [comment]
> I lost an entire day on this... in the end I updated my MacOS and XCode and my build passed...

Thanks for leaving this comment, I faced a similar issue and fix, saved me a couple hours seeing your comment.

**Comment by vivek-neoito** [comment]
Iam still having this issue 

/Users../node_modules/react-native-image-crop-picker/ios/QBImagePicker/QBImagePicker/QBImagePicker.storyboard Compilation Failed.

**Comment by kingfun2015** [comment]
> Iam still having this issue
> 
> /Users../node_modules/react-native-image-crop-picker/ios/QBImagePicker/QBImagePicker/QBImagePicker.storyboard Compilation Failed.

can you solve it? I also have this issue.

**Comment by Aakash359** [comment]
<img width="1440" alt="Screenshot 2022-09-22 at 10 53 48 AM" src="https://user-images.githubusercontent.com/54428958/191664903-83705a8e-8df9-43eb-a800-160b9ccf1492.png">
Hi can any one let me know what is this issues and how i can be resolve this... why it is occurring in iOS i am using react native version 0.69.1

**Comment by filipsavicfireside** [comment]
@Aakash359 try updating your MacOS and XCode and restarting your computer 😁

**Comment by AryanFavarr** [comment]
@filipsavicfireside I have tried that once it worked but after that it's not working. if I restart computer and re-run the build on XCode it throws this error [import of module 'glog.glog.log_severity' appears within namespace 'google'](https://github.com/facebook/react-native/issues/26217). after removing derivedData and other two folders nameSpace error is gone  it throws QBImagePicker.storyboard error.

**Comment by saibbyweb** [comment]
> 

In my case, just a simple restart fixed the problem.

**Comment by Mutai-Gilbert** [comment]
Thank you for the tips @Elf2707. Restarting macOS fixed the issue. I wasted the whole day fixing this problem.

**Comment by jackteng666** [comment]
RN 0.76.0
react-native-image-crop-picker: "^0.37.3"
Restarting did nothing for me
