### ISSUE TITLE
maxFiles (ios only)? can you fix it on android? I am using this compants on official app. so if you can solve it , I am very much obliged to you!

### ISSUE THREAD

**Issue by MingYe-dz** [ivpusic/react-native-image-crop-picker#102]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.?.?
- react-native v0.?.?

### Platform
Tell us to which platform this issue is related

- iOS
- Android

### Steps to reproduce

1.

2.

3.

### Attachments

// stacktrace or any other useful debug info

**Comment by ivpusic** [comment]
on android side native gallery picker is used, and for now it doesnt support limiting number of selected files.

**Comment by VigneshwaranEswaramoorthy** [comment]
want maxCount for android

**Comment by lyseiha** [comment]
any update for that?
