### ISSUE TITLE
Picker Always converting photos to jpeg

### ISSUE THREAD

**Issue by tximpa91** [ivpusic/react-native-image-crop-picker#1026]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.21.3
- react-native v0.59.4

### Platform
Tell us to which platform this issue is related

iOS
Android

### Expected behaviour

The picker maintain format of the file

### Actual behaviour

When an user select a png image the file is converted to jpeg always

### Steps to reproduce

1. Open The gallery select png photo

2. Response object if you get the mime always says jpeg

**Comment by ivpusic** [comment]
currently this is expected behaviour because temporary files are created for selected images.

**Comment by charon120** [comment]
> currently this is expected behaviour because temporary files are created for selected images.

Is there any solution？

**Comment by nareshOpenxcell** [comment]
any solution on this?

**Comment by anhquoc-bic** [comment]
any solution on this?
