### ISSUE TITLE
Control where Move and Scale appears in iOS

### ISSUE THREAD

**Issue by varungupta85** [ivpusic/react-native-image-crop-picker#103]
Is there a way to move the `Move and Scale` title up during cropping. It sometimes appears over the image (screenshot attached) which doesn't provide a good user experience.

### Version
- react-native-image-crop-picker v0.9.7
- react-native v0.34.1

### Platform
- iOS

### Expected behaviour
`Move and Scale` should not appear over the image

### Actual behaviour
`Move and Scale` appears over the image

### Steps to reproduce

1. Use the config in the first example in README in iOS simulator
```
ImagePicker.openPicker({
  width: 300,
  height: 400,
  cropping: true
}).then(image => {
  console.log(image);
});
```

2. Use one of the existing images and observe Move and Scale appearing over the image

### Attachments
![screen shot 2016-10-10 at 4 57 23 pm](https://cloud.githubusercontent.com/assets/7475133/19234711/0b5b297a-8f0b-11e6-96d3-eaf34a53f7d7.png)

**Comment by ivpusic** [comment]
unfortunately currently this is not possible

**Comment by varungupta85** [comment]
Okay. Thanks for the quick response and an awesome library.
