### ISSUE TITLE
why maxFiles not support in android, how can i set maxfiles in android?

### ISSUE THREAD

**Issue by miraclesumail** [ivpusic/react-native-image-crop-picker#1031]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.?.?
- react-native v0.?.?

### Platform
Tell us to which platform this issue is related

- iOS
- Android

### Steps to reproduce

1.

2.

3.

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by ivpusic** [comment]
on android stock gallery is used, which does not support this feature. currently, you would have to implement some logic inside your app to achieve something similar.

**Comment by msqar** [comment]
As @ivpusic said, you would need to only pick the first N of photos corresponding to your desired maxLimit. That's the only way for now, sad but true.

**Comment by sumitgoodwork** [comment]
Is this fixed in latest, or do we have to live with it?

Thanks

**Comment by dprajapati1179** [comment]
Why closed?  , The support is still not there

**Comment by muhammad-kumail** [comment]
Still facing issue in android
