### ISSUE TITLE
Is there a way to provide a callback on each image selection?

### ISSUE THREAD

**Issue by aterribili** [ivpusic/react-native-image-crop-picker#1032]
Hello, congrats for the project, I'd been using this for almost two years and it's great.

I'm trying to create something close to Instagram image upload experience, by uploading image right after the gallery selection. Is there a quick way to `ImagePicker.openPicker(...)` provides a stream of images selected instead of beeing resolved just when the user selected all the images or pressed done? If yes, could you please provide me a guidance to start?

**Comment by ivpusic** [comment]
unfortunately currently this feature does not exist.

**Comment by aterribili** [comment]
@ivpusic but is it possible to add this feature? I could help.

**Comment by ShrutiGarg019** [comment]
> @ivpusic but is it possible to add this feature? I could help.

Please help and do the same we really need this feature as maxFile selection is not supported
