### ISSUE TITLE
maxFile feature not supported by Android

### ISSUE THREAD

**Issue by tvhimanshu** [ivpusic/react-native-image-crop-picker#1047]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.24.1
- react-native v57.7

### Platform
 - Android

### Expected behaviour
maxFile feature should support by Android

### Actual behaviour
maxFile feature not supported by Android

**Comment by ivpusic** [comment]
yes, this is currently not supported

**Comment by Dror-Bar** [comment]
@ivpusic Is this on the roadmap? or is it not possible to implement?
Great library btw.
