### ISSUE TITLE
iOS build failed with QBImagePicker/QBImagePicker.h file not found

### ISSUE THREAD

**Issue by max-vasin** [ivpusic/react-native-image-crop-picker#105]
### Version

- react-native-image-crop-picker v0.9.7
- react-native v0.33.1

### Platform

- iOS

### Expected behaviour

Successful build without any modifications.

### Actual behaviour

Maybe i missed something, but build failed with 
```
QBImagePicker/QBImagePicker.h file not found. 
```
When i changed the value of **Framework Search Paths** for **imageCropPicker** build target to
```
$(PROJECT_DIR)/RSKImageCropper/build/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
$(PROJECT_DIR)/QBImagePicker/build/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
```
then i got successful build.

### Steps to reproduce

*  npm install react-native-image-crop-picker on empty project

*  react-native link

* add *RSKImageCropper.framework* & *QBImagePicker.framework* both to **Embedded Binaries** & **Linked Frameworks and Libraries**

* add 
```
${PROJECT_DIR}/../node_modules/react-native-image-crop-picker/ios/QBImagePicker/build/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
${PROJECT_DIR}/../node_modules/react-native-image-crop-picker/ios/RSKImageCropper/build/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
```
to **Framework Search Paths** for react-native project

* build for simulator or device

* failure

**Comment by ivpusic** [comment]
cannot reproduce this. Did `react-native link react-native-image-crop-picker` throw any errors?

**Comment by max-vasin** [comment]
> Did react-native link react-native-image-crop-picker throw any errors?

No. In fact, i don't perform react-native link on every build (automated). I have already linked ios react-native xcode project in git. I have tried to relink today - the problem still appears. Currently i wrote a patch script to set framework search paths in ImageCropPicker.xcodeproj just after npm install. It works, but ugly. Maybe something wrong with a version of something...

Another way to reproduce same issue.

* rm -rf node_modules
* npm install ("react-native-image-crop-picker": "^0.9.7" within package.json)
* open node_modules/react-native-image-crop-picker/ios/ImageCropPicker.xcodeproj in Xcode (currenlty i have Version 8.0 (8A218a))
* pick target imageCropPicker (static library)
* build
* :(

**Comment by ivpusic** [comment]
my suggestion...use cocoapods to get these dependencies. Check readme file. It will be much easier

**Comment by max-vasin** [comment]
Migrating to cocoapods reveals real problem. It is not with this component but with auto-created schemes in Xcode. If you open Xcode just after installing npm packages and pods - everything will be fine. But if you use xcodebuild without opening Xcode - things goes bad. 

Adding ruby script to recreate user schemes just before xcodebuild seems to resolve this problem, but very ugly. No matter, this does not related to this component. Thanks for helping.

**Comment by kelset** [comment]
I had a similar issue, with the RSKImageCropper header. The explanation provided by @max-vasin is correct.

**Comment by kelset** [comment]
Unluckily, this issue keeps resurfacing for me, so for future me and other people that may find this issue (tbh I think @ivpusic you should try to understand why this happens - apparently something breaks after every time I Archive the xcode project)

So, for me to solve this issue the "definitive" list of things to do is:

1. in XCode, run both `Clean` and `Clean Folder...`
2. close XCode
3. Remove the `DerivedData` folder of the related project (in `<user>/Library/Developer/Xcode/DerivedData` )
4. from command line, in the project folder, run `react-native unlink react-native-image-crop-picker`
5. in `<project folder>/ios` remove the `Pods` folder and the pod lock file
6. in `<project folder>` remove the `nome_modules` folder and the `yarn.lock` file
7. Empty recycle bin
8. run `sudo yarn`
9. chmod 777 the node_modules folder
10. go into `<project folder>/ios` and run a pod install
11. from command line, in the project folder, run `react-native link react-native-image-crop-picker`
12. Open Xcode
13. Wait for indexing process to be over

Hope this helps, cheers.

**Comment by rogerkerse** [comment]
The problem still exists. @kelset solution kind of worked, but it does not seem like a sustainable solution.

**Comment by kelset** [comment]
Keeps happening to me too.
Today, I did all the procedure I listed above (thanks, past me) but I still got the error. I closed and reopened Xcode, re run the Archive command without doing anything else, and this time it worked. I'm baffled.

**Comment by rogerkerse** [comment]
this solution helped out once again.. it happens all the time.. very difficult to use this library conveniently because of this

**Comment by jr-k** [comment]
I'm using cocoapods. I got this issue, then I closed xcode then re-opened it and it worked.

**Comment by varungupta85** [comment]
This is really weird. I start to see this issue now out of now where for `RSKImageCropper.h` file. I have run this successfully for more than 100 times and started to get this issue now. Tried cleaning the project, reopening Xcode, reboot the machine (old windows user :)) but no help. I wanted to check if there someone has find a more definitive solution to this problem before trying out other things such as removing the package etc. Weird thing is that I can control click the file and it opens the `RSKImageCropper.h` file. So, Xcode is able to find and resolve the file name but not during archiving.

**Comment by TheDirtyCalvinist** [comment]
I was able to fix this by running a local `xcodebuild` until it works, then checking in the resultant pbxproj file. It looks like it changes 
```shellScript = "diff \"${PODS_ROOT}/../Podfile.lock\" \"${PODS_ROOT}/Manifest.lock\" > /dev/null\nif [ $? != 0 ] ; then\n    # print error to STDERR\n    echo \"error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.\" >&2\n    exit 1\nfi\n";```

 to

```shellScript = "diff \"${PODS_PODFILE_DIR_PATH}/Podfile.lock\" \"${PODS_ROOT}/Manifest.lock\" > /dev/null\nif [ $? != 0 ] ; then\n    # print error to STDERR\n    echo \"error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.\" >&2\n    exit 1\nfi\n";```

**Comment by rogerkerse** [comment]
Any updates on such an old issue that still keeps happening every time?

**Comment by zkrige** [comment]
I deleted my schemes then autorecreated them and it seemed to fix the problem

**Comment by wildQueequeg** [comment]
This happens most often when archiving, even when the project builds and runs normally.

**Comment by uusa35** [comment]
still i am suffering for this package .. any help ? !

**Comment by garydevenay** [comment]
I've been suffering from this issue too. Is there any intention of this being fixed - or an alternative that's not causing headaches?

**Comment by wikieswan** [comment]
i try all methods on internet, but failed.
unstare this repo
remove react-native-image-crop-picker from my project clear
use react-native-image-picker instate

**Comment by diegolmello** [comment]
After get the lib working with manual linking, I tried to release a feature with it.
I use fastlane, so it was a big mess.
Then I removed and installed via cocoapods, but I was still getting errors.
I fixed it by making sure manual linking was completely removed.
