### ISSUE TITLE
Not working with react-native v0.60.0

### ISSUE THREAD

**Issue by immortalx** [ivpusic/react-native-image-crop-picker#1050]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.24.1
- react-native v0.60.0

### Platform
- iOS

### Expected behaviour
To compile with pod install

### Actual behaviour
It won't compile

### Steps to reproduce

1. react-native init app

2. cd app/ios

3. pod install

// stacktrace or any other useful debug info
[!] CocoaPods could not find compatible versions for pod "React/Core":
  In Podfile:
    RNImageCropPicker (from `/Users/testuser/rntestsix/node_modules/react-native-image-crop-picker`) was resolved to 0.24.1, which depends on
      React/Core

None of your spec sources contain a spec satisfying the dependency: `React/Core`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

**Comment by oleksandr-dziuban** [comment]
👍 Same issue. It would be great to add react-native@0.60.0 support

**Comment by tueht** [comment]
You can temporary do a workaround by changing
`s.dependency 'React/Core'` 
to 
`s.dependency 'React-Core'
  s.dependency 'React-RCTImage'`
in RNImageCropPicker.podspec file then `pod install` again.

**Comment by immortalx** [comment]
> You can temporary do a workaround by changing
> `s.dependency 'React/Core'`
> to
> `s.dependency 'React-Core'`
> ` s.dependency 'React-RCTImage'`
> in RNImageCropPicker.podspec file then `pod install` again.

Yes it was just that, it works fine now. 
Thank you @tueht for the workaround!

**Comment by oleksandr-dziuban** [comment]
> You can temporary do a workaround by changing
> `s.dependency 'React/Core'`
> to
> `s.dependency 'React-Core'`
> ` s.dependency 'React-RCTImage'`
> in RNImageCropPicker.podspec file then `pod install` again.

Thanks, but it is not really good solution for production projects. I have automated builds on CI, so changing something in node_modules will not work at all, because installation of packages is fully automated.

Thank you

**Comment by danilobuerger** [comment]
@oleksandr-dziuban Use https://github.com/ds300/patch-package

**Comment by mehdihz** [comment]
Already patched this problem and just requires merge. Please merge it

https://github.com/ivpusic/react-native-image-crop-picker/pull/1019

**Comment by rouge3351** [comment]
have same problom,
can you tell me when this branch is going to merged ?

**Comment by oleksandr-dziuban** [comment]
@ivpusic Could you please bump npm package version with this fix?

**Comment by ivpusic** [comment]
version with support for androidx and react-native 0.60 released.

**Comment by engineerahkhani** [comment]
user version 0.25.0 instead of the last version  worked for me

**Comment by hoanghungbk93** [comment]
> user version 0.25.0 instead of the last version worked for me

It worked for me. Thank you
