### ISSUE TITLE
There is no androidx.core.app 

### ISSUE THREAD

**Issue by lifan-github** [ivpusic/react-native-image-crop-picker#1056]
### Version
- react-native-image-crop-picker v0.25.0
- react-native v0.60.0

I according to the steps the link, but tell me wrong

### Android

![屏幕快照 2019-07-12 11 03 49](https://user-images.githubusercontent.com/17446427/61099410-ccd2e880-a494-11e9-9aa6-d7f75b6762e7.png)
![屏幕快照 2019-07-12 11 03 54](https://user-images.githubusercontent.com/17446427/61099415-ce9cac00-a494-11e9-91ac-9a4b1f83788f.png)

**Comment by joshmcoffman** [comment]
This is because you aren't using androidx. 

You can use v0.24.1. It doesn't have androidx in the AndroidManifest.xml
