### ISSUE TITLE
Fail to introduce either ios or android with v0.24.1, v0.25.0

### ISSUE THREAD

**Issue by nitaking** [ivpusic/react-native-image-crop-picker#1057]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.24.1, 0.25.0
- react-native v0.59.10

### Platform
Tell us to which platform this issue is related

- iOS
- Android

### About

In RN 0.59.10, but I made the project compatible with androidX.

In that case, the ios build succeeds in crop-picker@v0.24.1, but the android build (apk generate only) fails.

AndroidX support seems to be done in crop-picker@v0.25.0, so when you change the version, the android build succeeded.

However, ios now fails with `pod install`.

I cleared this phenomenon by stopping the react-native link and manually linking.

I think that the document needs to be updated. Why is this happening?

↓pod error
```
[!] Unable to find a specification for `React-Core` depended upon by `RNImageCropPicker`

```

**Comment by ivpusic** [comment]
you have to use react-native >= 0.60 for androidx and 0.25.0

**Comment by nitaking** [comment]
@ivpusic 

Why close?

The problem is not solved if you close mechanically.
I think that versioning of android is strange

**Comment by nitaking** [comment]
I resolved.

## install
1. edit package.json

```
...

    "react-native-image-crop-picker": "^0.25.0",
    "react-native-image-crop-picker-ios": "git+https://github.com/ivpusic/react-native-image-crop-picker#v0.24.1",
...
```

2. `react-native link react-native-image-crop-picker`

3. edit podfile

```
  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker-ios'
```

4. `pod install`

## use

CropPicker.android.js

```
import CropPicker from 'react-native-image-crop-picker';

export default CropPicker;
```

CropPicker.ios.js

```
import CropPicker from 'react-native-image-crop-picker-ios';

export default CropPicker;
```

```
import CropPicker from './CropPicker';

# using...
```
