### ISSUE TITLE
Unable to find a specification for `React-Core` depended upon by `RNImageCropPicker`

### ISSUE THREAD

**Issue by joeljerushan** [ivpusic/react-native-image-crop-picker#1059]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.25.0
- react-native v0.59.4

### Platform
Tell us to which platform this issue is related

- iOS

### Expected behaviour
pod install complete

### Actual behaviour
![image](https://user-images.githubusercontent.com/10111309/61128147-c95c5300-a4ce-11e9-9101-056d6f9e6237.png)

### Steps to reproduce

1. pod init

2. added following 
![image](https://user-images.githubusercontent.com/10111309/61128233-fe68a580-a4ce-11e9-960d-972cd8803c7a.png)

3. ran `pod install` command

**Comment by ivpusic** [comment]
you have to use react native 0.60 to be able to use version 0.25.0

**Comment by basha777** [comment]
got the same error while installing **react-native-image-crop-picker v0.25.0** for react-native version **0.59.9,** after reinstalling **react-native-image-crop-picker v0.24.0**  fixed the issue.

**Comment by elgrones** [comment]
fixed using `npm i react-native-image-crop-picker@0.24.0 --save`

**Comment by tuannguyenhoangit-droid** [comment]
if you are using react-native 0.59 above, just change pod spec of crop-picker from React/Core to   s.dependency 'React-Core'
