### ISSUE TITLE
crash on android 4.4.4

### ISSUE THREAD

**Issue by tza17313** [ivpusic/react-native-image-crop-picker#106]
### Version

- react-native-image-crop-picker v0.9.7
- react-native v0.35.0
- com.android.tools.build:gradle:1.3.1(it's react-native default version)

### Platform

- Android

### Expected behaviour
no crash

### Actual behaviour
crash

### Description
It's working properly in android 5.1.0.
but on android 4.4.4,i got this error in attachment.
I tried change gradle version，got error in run `react-native run-android`.

### Steps to reproduce

1.  steup follow with guide

2.  `react-native run-android`

### Attachments
![error](https://cloud.githubusercontent.com/assets/2976095/19300920/74496ee4-908f-11e6-9379-e2776043b212.png)

// stacktrace or any other useful debug info

**Comment by ivpusic** [comment]
http://stackoverflow.com/questions/39091521/vector-drawables-flag-doesnt-work-on-support-library-24 this helpes?

**Comment by tza17313** [comment]
use  `buildToolsVersion "24.0.3"`  nothing changed ,just got same error .
that question is different from mine,my question is only appeared **under api level 21**.

**Comment by ivpusic** [comment]
hm, do you have a chance to debug it? I cannot reproduce this issue, so it is hard for me to help you.

**Comment by tza17313** [comment]
use `'com.android.tools.build:gradle:2.1.2' ` can resolve this problem. 

Thanks for your reply. @ivpusic
