### ISSUE TITLE
0.60.0 change broke example pod install

### ISSUE THREAD

**Issue by twelve17** [ivpusic/react-native-image-crop-picker#1061]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker (sha) 881f96623b7adf043dc04be0269057ff382f4b84
- react-native v0.60.0?

### Platform
Tell us to which platform this issue is related

- iOS

### Expected behaviour

Can peform pod install in example app

### Actual behaviour

```
react-native-image-crop-picker alex$ cd example/ios/
mango:ios alex$ pod install
Detected React Native module pods for RNImageCropPicker and react-native-video
Analyzing dependencies
Fetching podspec for `RNImageCropPicker` from `../`
[!] No podspec found for `RNImageCropPicker` in `../`
```

### Steps to reproduce

1. clone https://github.com/ivpusic/react-native-image-crop-picker

2. cd example

3. npm install

4. cd ios

5. pod install

**Comment by ivpusic** [comment]
works for me. please try again
