### ISSUE TITLE
openPicker returns full image not cropped one

### ISSUE THREAD

**Issue by rawadrifai** [ivpusic/react-native-image-crop-picker#1064]
Hi - at the risk of this being an easy solution, I'm new to this library.
I have the following code. My issue is that the returned image is the full one not the cropped one. How can I get the cropped image?

```
ImagePicker.openPicker({
      width: 100,
      height: 100,
      cropping: true,
      compressImageQuality: 0.25,
    }).then(async image => {
      console.log(image);
      await uploadImage(image.sourceURL)
    });
```

**Comment by luizzenha** [comment]
Same here

**Comment by rawadrifai** [comment]
I'm following it with an openCropper in order to get it cropped. It's redundant but whatever.
