### ISSUE TITLE
cannot find images  data

### ISSUE THREAD

**Issue by HKbool** [ivpusic/react-native-image-crop-picker#107]
ImagePicker.openPicker({
  width: 300,
  height: 400,
  cropping: true
}).then(image => {
  Alert.alert("",image)    //Could not find image 
});

react-native-image-crop-picker v0.8.3
react-native v0.32.0

**Comment by ivpusic** [comment]
Can you please provide me stacktrace when this issue happens? Knowing what is happening just from your description is nearly impossible.

**Comment by ivpusic** [comment]
closing this one because of insufficient data provided.

**Comment by ninjz** [comment]
@HKbool Were you able to resolve this issue?
