### ISSUE TITLE
import android.support.v4.app.ActivityCompat;

### ISSUE THREAD

**Issue by HeiSiBaby** [ivpusic/react-native-image-crop-picker#1071]
> Task :react-native-image-crop-picker:compileDebugJavaWithJavac
D:\HM\HM-master\node_modules\react-native-image-crop-picker\android\src\main\java\com\reactnative\ivpusic\imagepicker\PickerModule.java:16: 错误: 找不到符号
import android.support.v4.app.ActivityCompat;
                             ^
  符号:   类 ActivityCompat
  位置: 程序包 android.support.v4.app
D:\HM\HM-master\node_modules\react-native-image-crop-picker\android\src\main\java\com\reactnative\ivpusic\imagepicker\PickerModule.java:223: 错误: 找不到符号
            int status = ActivityCompat.checkSelfPermission(activity, permission);
                         ^
  符号:   变量 ActivityCompat
  位置: 类 PickerModule

**Comment by HeiSiBaby** [comment]
help me

**Comment by HeiSiBaby** [comment]
please

**Comment by ivpusic** [comment]
you should use version 0.25 if you are using react-native 0.60, or <= 0.24 if you are using react-native bellow 0.60

**Comment by tiffanym19** [comment]
how did it fix?

**Comment by irajwani** [comment]
Hi, I can confirm this issue also shows up on 0.24.0. Im using react native 0.59.9.

The folllowing two imports won't resolve:
import android.support.v4.app.ActivityCompat;
import android.support.v4.content.FileProvider;

I replaced "import android.support.annotation.RequiresApi;" with "import androidx.annotation.RequiresApi;" and that is now fine. However I'm stumped on what to do about the above mentioned imports. Is there a core library for android.support that I'm supposed to place somewhere?

**Comment by guohuihot** [comment]
> Hi, I can confirm this issue also shows up on 0.24.0. Im using react native 0.59.9.
> 
> The folllowing two imports won't resolve:
> import android.support.v4.app.ActivityCompat;
> import android.support.v4.content.FileProvider;
> 
> I replaced "import android.support.annotation.RequiresApi;" with "import androidx.annotation.RequiresApi;" and that is now fine. However I'm stumped on what to do about the above mentioned imports. Is there a core library for android.support that I'm supposed to place somewhere?

me too

**Comment by apostolou** [comment]
Hi @irajwani, @guohuihot I have the same issue as you. Did you manage to find a fix? 
Thanks

**Comment by apostolou** [comment]
FYI I managed to fix this issue by replacing the 3 imports that don't resolve with 
`import androidx.annotation.RequiresApi;
import androidx.core.app.ActivityCompat;
import androidx.core.content.FileProvider;` 
and then changing in file node_modules/react-native-image-crop-picker/android/src/main/AndroidManifest.xml the line 
`android:name="android.support.v4.content.FileProvider"` by `android:name="androidx.core.content.FileProvider" `.
