### ISSUE TITLE
Android openCamera Error / IOS openPicker Error

### ISSUE THREAD

**Issue by sharingjingang050241** [ivpusic/react-native-image-crop-picker#108]
### Version
"react-native-image-crop-picker": "^0.9.7",
"react-native": "0.33.0", 

### Platform
Tell us to which platform this issue is related

- iOS
I'm not sure this way could or not useful,when I add RSKxxx.framework and QBIxxx.framework to Embedded Binaries ,click + and chose one of framework ,it didn't add to Embedded Binaries .So ,I add these to Linked Frameworks and Libraries first, then I click + under Embedded Binaries and add these.Is this way valid ?
An other question after I do that, on IOS Emulator,"undefined is not an object(evaluating '_reactNativeImageCropPicker2.default.openPicker')";
 
There are my function:

openPicker(){
      ImagePicker.openPicker({
        width: 300,
        height: 300,
        cropping: true
        }).then(image => {
        console.log(image);
        this.setState({
            image: {uri: image.path, width: image.width, height: image.height},
            images: null
        });
        }).catch(e => alert(e));
  }

  openCamera(){
      ImagePicker.openCamera({
        width: 300,
        height: 300,
        cropping: true
        }).then(image => {
        console.log(image);
        }).catch(e => alert(e));
  }

- Android
On Android ,Select from gallery can be using,but  Select from camera send Error :Required permission missing; 
Its just only add '<uses-permission android:name="android.permission.CAMERA"/>' to AndroidManifest.xml when I use android?

//Grammar is not very accurate, forgive me! And Im a newb.

![iosgereral](https://cloud.githubusercontent.com/assets/20335157/19342072/daef86fa-9162-11e6-8b95-20cd34189c35.png)
![ioserror](https://cloud.githubusercontent.com/assets/20335157/19342076/e4358b42-9162-11e6-83af-f669a87485b9.png)

**Comment by ivpusic** [comment]
for android to use camera you have to add camera permission to android manifest. For ios, linking project failed. Please ensure that react-native link react-native-image-crop-picker did not throw any errors.

**Comment by sharingjingang050241** [comment]
![android](https://cloud.githubusercontent.com/assets/20335157/19342617/160f871a-9165-11e6-8362-02ec1e57550c.png)
this is AndroidManifest.xml.
![ios](https://cloud.githubusercontent.com/assets/20335157/19342646/3fb7427e-9165-11e6-8ea4-3240593b66d5.png)
this is react-native link react-native-image-crop-picker.

**Comment by ivpusic** [comment]
hm, at least on iOS side I can tell you that module is not linked properly. Please try unlinking and linking module again. Also check if imageCropPicker is under "link binary with libraries" section

**Comment by sharingjingang050241** [comment]
how to unlink ? replace link with unlink?
 
![errors](https://cloud.githubusercontent.com/assets/20335157/19343773/24a9b34a-916a-11e6-89cd-8e8e7f6b6c32.png)
does this mean module is not linked ?

**Comment by ivpusic** [comment]
this means that xcode is trying to link to dynamic library which doesn't exist. So yes, this is part of the problem. I suggest to you to try cocoapods. It is much easier to get it working with pods than without. `react-native unlink react-native-image-crop-picker` to unlink.

**Comment by sharingjingang050241** [comment]
What's cocoa pods ?Do u have any Introduction？

**Comment by ivpusic** [comment]
https://medium.com/5-step-ios-tutorials/how-to-use-cocoapods-137df1bbb89a#.daub23fwz

**Comment by sharingjingang050241** [comment]
thank u very

**Comment by ivpusic** [comment]
will close this issue. post questions if you have some

**Comment by sharingjingang050241** [comment]
I'm solved it.Download  ImageCropPickerSDK,and add QBImagePicker.framework and RSKImageCropper.framework from ImageCropPickerSDK,it' running normally。Thank you very much to give me suggestion.

**Comment by zfiratselim** [comment]
Help me!
Platform: Android
react: "16.0.0-alpha.12"
react-native: "0.51.0"

![26855448_1592548554127163_1442966732_n](https://user-images.githubusercontent.com/30474437/34916307-3e21a454-f947-11e7-922a-79bc53259360.png)

**Comment by sharingjingang050241** [comment]
@zfiratselim  have you `react-native run-android`  after install this component ？

**Comment by Y-JH** [comment]
I have solved it. Here is it : https://blog.csdn.net/junhuahouse/article/details/89574511
