### ISSUE TITLE
 error: package androidx.core.app does not exist import androidx.core.app.ActivityCompat;

### ISSUE THREAD

**Issue by tiffanym19** [ivpusic/react-native-image-crop-picker#1080]
![Screenshot_7](https://user-images.githubusercontent.com/50227625/61932723-b0679d80-afb6-11e9-8278-8f6d1a6c117e.png)

### Version
- react-native : 0.59.8

### Platform
- Android

**Comment by chakrihacker** [comment]
Please install the version based on this docs

If you are using react-native >= 0.60 use react-native-image-crop-picker version >= 0.25.0. Otherwise use version < 0.25.0.

**Comment by tiffanym19** [comment]
I am using 0.25 version

**Comment by tiffanym19** [comment]
can you open again the issue

**Comment by tiffanym19** [comment]
I am using react-native-image-crop-picker@0.25.0  the version is fin, why do I keep having this issue?

**Comment by tiffanym19** [comment]
THANK YOU! :D

**Comment by ivpusic** [comment]
because you are using react-native 0.59.8 in combination with 0.25. you should upgrade to react-native 0.60.x if you want to use 0.25.0.

**Comment by jhondavila** [comment]
lost version 0.24.3 in  npm, please help

**Comment by FMaz008** [comment]
I use 0.21.1 and I am facing the same issue. npx jetifier does not seem to help
