### ISSUE TITLE
How to navigate to Camera Roll by default

### ISSUE THREAD

**Issue by pisacode** [ivpusic/react-native-image-crop-picker#1081]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.24.0
- react-native v0.59.8

### Platform
Tell us to which platform this issue is related

- iOS
- Android

**How can we navigate user to Camera Roll when image picker is prompted.**

Whatsapp is directing users to camera roll by default. User mostly goes to camera roll to pick files, therefore, making user to choose camera roll everytime might not be the best experience. Is it possible to this with this package?

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by ivpusic** [comment]
currently not possible

**Comment by caojianfeng** [comment]
What about now? @ivpusic

**Comment by equinox7** [comment]
Is it possible now @ivpusic ?

**Comment by billxie1988** [comment]
Try this on iOS work for  me #1983 
```
-(void)viewDidLoad {
    ...
    [self directPushViewAlbumController];
    ...
}

```
```
-(void)directPushViewAlbumController {
    NSBundle *assetBundle = [NSBundle bundleForClass:[QBImagePickerController class]];
    NSString *bundlePath = [assetBundle pathForResource:@"QBImagePicker"     ####ofType:@"bundle"];
    if (bundlePath) {
        assetBundle = [NSBundle bundleWithPath:bundlePath];
    }
   
    UIStoryboard *storyboard = [UIStoryboard storyboardWithName:@"QBImagePicker" bundle: assetBundle];
    QBAssetsViewController *assetsViewController = [storyboard instantiateViewControllerWithIdentifier:@"QBAssetsViewController"];
   
    assetsViewController.imagePickerController = self.imagePickerController;
    assetsViewController.assetCollection = self.assetCollections[0];
   
    [self.navigationController pushViewController:assetsViewController animated:NO];
}
```

**Comment by hdjhdjhdj** [comment]
Is it possible now @ivpusic ?
