### ISSUE TITLE
Camera roll gallery opens to oldest images (iOS)

### ISSUE THREAD

**Issue by joshallison** [ivpusic/react-native-image-crop-picker#1087]
Hello,

when opening the camera roll gallery, the scroll position is automatically set to the top of the gallery (oldest images / videos).

Is there a way to open the camera roll gallery at the bottom (most recent) images like the iOS native photos app? 

Thank you so much for your help.

React native: 0.57.8
react-native-image-crop-picker: 0.24.1

<img width="464" alt="Screen Shot 2019-07-31 at 12 23 07 pm" src="https://user-images.githubusercontent.com/11746893/62178907-027d3a00-b38e-11e9-80f9-5d6b6f0630ef.png">

**Comment by jhondavila** [comment]
I have the same problem brother, I have also published the same

https://github.com/ivpusic/react-native-image-crop-picker/issues/1089

**Comment by migue1s** [comment]
I created a newly merged PR that allows you to modify the sort order, where you could sort the photos by creation date (newest first), would this help you @joshallison?

Note: this code is on master, it's not on any release yet

https://github.com/ivpusic/react-native-image-crop-picker/pull/1090

**Comment by jhondavila** [comment]
> Creé un RP recién fusionado que te permite modificar el orden de clasificación, donde puedes ordenar las fotos por fecha de creación (la más nueva primero), ¿te ayudaría esto @joshallison ?
> 
> Nota: este código está en el maestro, aún no está en ninguna versión
> 
> [# 1090](https://github.com/ivpusic/react-native-image-crop-picker/pull/1090)

thank you,

**Comment by jhondavila** [comment]
Could you show us an example of how to use it? we have tried using the new sortOrder configuration and we have not been successful with the order of the images


`ImagePicker.openPicker({
                compressImageQuality: 0.7,
                compressImageMaxWidth: 1200,
                mediaType: "photo",
                includeBase64: true,
                //smartAlbums: ["RecentlyAdded"]
                sortOrder : "asc"
            }).then(image => {
                this.props.onCaptureImage(
                    {
                        uri: image.path,
                        type: image.mime, // or photo.type
                        name: image.filename || `photo.jpg`
                    }
                );
                this.onCancel();
            }).catch((e) => {
                this.onCancel();
            });`

**Comment by migue1s** [comment]
You probably want “sortOrder: ‘desc’”. Since it’s by date of creation, the most recent dates are bigger and thus you must sort it the other way around. As it is right now, “asc” and “none”(default) are basically equal with the exception that the default order depends on the OS and thus might change over time.

~Miguel

**Comment by jhondavila** [comment]
I managed to solve the problem, I had to uninstall the dependency and reinstall it. apparently the npm was not updating the files correctly

**Comment by betranthanh** [comment]
This is just a **temporary** solution if you don't want to update `react-native` and `react-native-image-crop-picker version`. 

Open file: ```Pods/QBImagePickerController/QBImagePicker/QBAssetsViewController.m```

Search this line:
```
self.fetchResult = [PHAsset fetchAssetsInAssetCollection:self.assetCollection options:options];
```

Insert this line above it: 
```
options.sortDescriptors = @[[NSSortDescriptor sortDescriptorWithKey:@"creationDate" ascending: NO]];
```

This is result
```
options.sortDescriptors = @[[NSSortDescriptor sortDescriptorWithKey:@"creationDate" ascending: NO]];

self.fetchResult = [PHAsset fetchAssetsInAssetCollection:self.assetCollection options:options];
```

**Comment by bneigher** [comment]
@betranthanh this change should be added to the QBAssetsViewController.m for sure

**Comment by jhondavila** [comment]
no found react-native-image-crop-picker: 0.24.2 o 0.24.3  in npm

**Comment by betranthanh** [comment]
> @betranthanh this change should be added to the QBAssetsViewController.m for sure

=> yep, that why I said: "This is just a temporary solution" ;)

**Comment by hongsa** [comment]
@betranthanh I use this solution, but not working.
How can I solve this?

**Comment by rosskhanas** [comment]
> @betranthanh I use this solution, but not working.
> How can I solve this?

I confirm the solution works well.

**Comment by DavitVosk** [comment]
Guys, I tried to install the latest release of the package, but the `desc` `sortOrder` is not working there again. When we expect to have a release with fix?

**Comment by DavitVosk** [comment]
Also @betranthanh, yes adding that line in `ios/Pods/QBImagePickerController/QBImagePicker/QBAssetsViewController.m` works. But what file should we change to have that line included in `ios/Pods/QBImagePickerController/QBImagePicker/QBAssetsViewController.m` file itself?

**Comment by rosskhanas** [comment]
@DavitVosk u can make post-install script to fix the code when you update pods.

How to patch files guide: http://stephenjungels.com/jungels.net/articles/diff-patch-ten-minutes.html

In case of this particular issue:

1. Generate a patch file:

```
diff -u Pods/QBImagePickerController/QBImagePicker/QBAssetsViewController.m patches/QBAssetsViewController.m > patches/QBAssetsViewController.patch
```

2. Add the following code to your pod file:

```

post_install do |installer|
  puts 'Patching QBAssetsViewController'
  %x(patch Pods/QBImagePickerController/QBImagePicker/QBAssetsViewController.m < patches/QBAssetsViewController.patch)
end
```

😃

**Comment by ivanguimam** [comment]
@rosskhanas @betranthanh  your solution works, however, in dark mode the gallery gets ugly, in conflict with this modification

**Comment by msqar** [comment]
Guys, do you know when are we getting an official fix for this instead of patching and patching?

**Comment by ivpusic** [comment]
added sortOrder ios property to version 0.27.0

**Comment by msqar** [comment]
@ivpusic is the iPhone XS/XR fix also for the new pictures first on the list?
