### ISSUE TITLE
How to open the cropper with a custom image tmp path ?

### ISSUE THREAD

**Issue by MustaphaGhlissi** [ivpusic/react-native-image-crop-picker#1088]
Hello everybody , 

I am working with this amazing library , 

My need now is How to open an image in the cropper without show the file explorer 

Example : I have a tmp path to image , I want to open this image directly in the cropper  

Does there any solution like this for example:

```
openCropper = (index) => {
        ImagePicker.openPicker({
            includeBase64: true,
            mediaType: 'photo', 
            tmpPath: 'file:///....................................',  /// Any config like this one for example .!!!!!!!!!!!!!!!!!!!!!!
        }).then(image => {
            this.onUpdatePhoto(index, image.data, image.path);
        });
    }
```

Any solution for that ? 

I didn't find any method or extra config to do 

Your help please 

Thanks

**Comment by hich-dev** [comment]
Hey @MustaphaGhlissi I think this is what you are looking for:

```
ImagePicker.openCropper({
  path: 'my-file-path.jpg',
  width: 300,
  height: 400
}).then(image => {
  // do something here
});
```

**Comment by MustaphaGhlissi** [comment]
@hich-dev thanks
