### ISSUE TITLE
add the RSKImageCropper.podspec to ios/RSKImageCropper so that we can use the locally vendored copy in the Podfile

### ISSUE THREAD

**Issue by mmerickel** [ivpusic/react-native-image-crop-picker#1100]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.25.0
- react-native v0.60.5

### Platform

- iOS

### Expected behaviour

Point Podfile at local RSKImageCropper just like you can do with QBImagePickerController so that we know we're using the correct version for this release.

```
pod 'RSKImageCropper', :path => '../node_modules/react-native-image-cropper/ios/RSKImageCropper`
pod 'QBImagePickerController', :path => '../node_modules/react-native-image-crop-picker/ios/QBImagePicker'
```

### Actual behaviour

RSKImageCropper is installed from remote cocoapod instead of locally checked out copy.

**Comment by jhau** [comment]
for v0.25.1 I had to add the following lines to make pod install work, RSKImageCropper.podsepc is taken from [https://github.com/ruslanskorb/RSKImageCropper/blob/master/RSKImageCropper.podspec](url)


`pod 'QBImagePickerController', :podspec => '../node_modules/react-native-image-crop-picker/ios/QBImagePicker/QBImagePickerController.podspec'
`
`pod 'RSKImageCropper', :podspec =>  './RSKImageCropper.podspec' `

**Comment by zkkg2018** [comment]
<img width="131" alt="WX20191015-165501@2x" src="https://user-images.githubusercontent.com/41882148/66816396-982b6d00-ef6c-11e9-8e7d-61980a3c5f4a.png">

Pod::Spec.new do |s|
  s.name          = 'RSKImageCropper'
  s.version       = '2.2.3'
  s.summary       = 'An image cropper for iOS like in the Contacts app with support for landscape orientation.'
  s.homepage      = 'https://github.com/ruslanskorb/RSKImageCropper'
  s.license       = { :type => 'MIT', :file => 'LICENSE' }
  s.authors       = { 'Ruslan Skorb' => 'ruslan.skorb@gmail.com' }
  s.source        = { :git => 'https://github.com/ruslanskorb/RSKImageCropper.git', :tag => s.version.to_s }
  s.platform      = :ios, '6.0'
  s.module_map    = 'RSKImageCropper/RSKImageCropper.modulemap'
  s.source_files  = 'RSKImageCropper/*.{h,m}'
  s.resources     = 'RSKImageCropper/RSKImageCropperStrings.bundle'
  s.frameworks    = 'QuartzCore', 'UIKit'
  s.requires_arc  = true
end

<img width="1065" alt="WX20191015-165613@2x" src="https://user-images.githubusercontent.com/41882148/66816501-bee9a380-ef6c-11e9-958f-0cf51f3229b7.png">
pod 'RSKImageCropper', :path => '../node_modules/react-native-image-crop-picker/ios/RSKImageCropper/RSKImageCropper.podspec'

**Comment by ivpusic** [comment]
RSKImageCropper is not used anymore. please try latest version with TOCropViewController
