### ISSUE TITLE
sortOrder not found on object of type QBImagePickerController

### ISSUE THREAD

**Issue by Eddiwar** [ivpusic/react-native-image-crop-picker#1101]
Hi,

has anyone encountered this problem? or could perhaps offer a solution? 

Many Thanks.

### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.25.0
- react-native v0.60.4

### Platform
Tell us to which platform this issue is related

- iOS

### Expected behaviour

Build passes. (does so for android)

### Actual behaviour

Build fails.

Note: cocoapods is being used to link dependencies, post install instructions have been double checked.

### Steps to reproduce

1. react-native run-ios

### Attachments

..../node_modules/react-native-image-crop-picker/ios/src/ImageCropPicker.m
:
320
:
35
: error: property 'sortOrder' not found on object of type 'QBImagePickerController *'
            imagePickerController.sortOrder = [self.options objectForKey:@"sortOrder"];

**Comment by nadav2051** [comment]
Hey,

I think you need to include this in your Podfile:
  pod 'QBImagePickerController', :path => '../node_modules/react-native-image-crop-picker/ios/QBImagePicker'

It seems like your code is not using the RN-image-crop-picker provided QBImagePickerController, thus you get the error of the missing functionality (which is only present at the local library)

**Comment by Martian2Lee** [comment]
Same issue!

**Comment by sunnylqm** [comment]
This is because the version of QBImagePicker on cocoapods is different from the embeded one. It's 
 been modified in this commit https://github.com/ivpusic/react-native-image-crop-picker/pull/1090/files
cc @ivpusic @migue1s

**Comment by KingAmo** [comment]
@sunnylqm  so is there any solution ? thanks

**Comment by sunnylqm** [comment]
@KingAmo I suggest use 0.25.0 as a workaround

**Comment by KingAmo** [comment]
@sunnylqm thanks a lot, i'll have a try. by the way, really fast reply...

**Comment by vigneshwaranoptisol** [comment]
@sunnylqm  same issue facing in 0.25.1

![Screenshot 2019-09-11 at 1 12 23 PM](https://user-images.githubusercontent.com/20220464/64677758-d9c08800-d495-11e9-9f49-ea6a32f2f66f.png)

**Comment by sunnylqm** [comment]
@vigneshwaranoptisol so what?

**Comment by Eddiwar** [comment]
Im not able to verify/test this but could it be that pod install is installing the original questbeat/QBImagePickerController rather than the modified one embedded in this project because in react-native-image-picker's podspec it links, as a dependency, to QBImagePicker? if so would copying node_modules/React-native-Image-Crop-Picker/ios/QBImagePicker/QBImagePicker directory into ios/Pods/QBImagePickerController and overwrite the existing QBImagePicker directory after running pod install fix it?

**Comment by vigneshwaranoptisol** [comment]
@sunnylqm @Eddiwar  It is looks like strange for me 
I have already used very older version of 0.20.3 for long time.
have updated to 0.25.1 using 

> npm install —save react-native-image-crop-picker@0.25.1

Then completely removed iOS/Pods folder
Then done pod install.

Even though QBImagepicker library in my pods folder does not updated.
But with in the node modules folder it have updated QBImagepicker code

copying node_modules/React-native-Image-Crop-Picker/ios/QBImagePicker/QBImagePicker directory into ios/Pods/QBImagePickerController is worked for me.

**Comment by sunnylqm** [comment]
@vigneshwaranoptisol What's strange?
The QBImagepicker in podfile linked to a remote version which does not have `sortOrder`, while the 0.25.1 version modified a local copy which was not refereneced in podfile. Isnt the issue clear enough?

**Comment by Eddiwar** [comment]
Hi all, the first reply by Nadav2051 provides a solution that is permanent. There is also the copy paste route but is only a temporary work around and is reset by pod install

**Comment by sunnylqm** [comment]
@Eddiwar Why closing before it's fixed?

**Comment by Eddiwar** [comment]
@sunnylqm sorry first time posting an issue I thought a temporary fix was sufficient but youre right it should stay up until a fix is merged.

**Comment by ivpusic** [comment]
sortOrder commit is reverted because the feature was added to the local copy of QBImagePicker, which is something I would like to avoid

**Comment by Eddiwar** [comment]
@ivpusic Sorry not extremely familiar with everything thats going on, but how does the future look for features that need to be implemented in QBImagePicker such as sort order?

**Comment by ivpusic** [comment]
currently I have no plans of adding this feature myself, but if somebody from the community is having a time to add it, but without modifying local copy of QBImagePicker, I would gladly accept PR.

**Comment by ivpusic** [comment]
sortOrder is available in version 0.27.0

**Comment by jqn** [comment]
@ivpusic the same problem occurs in version 0.27.0

**Comment by williamgoodhew** [comment]
@ivpusic I am getting the same error with v0.27.0 as well

**Comment by ivpusic** [comment]
you need to add this https://github.com/ivpusic/react-native-image-crop-picker#using-local-qbimagepicker

**Comment by sunnylqm** [comment]
@ivpusic  Why not add to subspec https://guides.cocoapods.org/syntax/podspec.html#subspec

**Comment by ivpusic** [comment]
because of https://github.com/CocoaPods/CocoaPods/issues/3276

**Comment by ivpusic** [comment]
subspec added in https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.28.0
