### ISSUE TITLE
iOS 13 dark mode support.

### ISSUE THREAD

**Issue by tr3v3r** [ivpusic/react-native-image-crop-picker#1105]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.25.0
- react-native v0.60.5

### Platform
Tell us to which platform this issue is related

- iOS

### Expected behaviour

Image picker should looks properly in dark mode. 
( background color, text color )

### Actual behaviour

Picker background partly white. The albums titles are not readable.

### Steps to reproduce

1. get iPhone XR

2. call openPicker

3. Look at picker styles.

### Attachments
![image](https://user-images.githubusercontent.com/23724142/64622804-9102c380-d3f0-11e9-8771-00dd164852bc.png)

**Comment by bneigher** [comment]
+1

**Comment by cr1s3c** [comment]
I made a fork to add the dark mode support #1129

**Comment by marcoizzo** [comment]
+1

**Comment by jrapala** [comment]
If anyone is still stuck on a react-native < 0.60 project like me, this fix seems to work on < 0.25.0 versions as well.

Thanks @cr1s3c!

**Comment by artshevtsov** [comment]
Thanks, adding a dependency 
```pod 'QBImagePickerController', :path => '../node_modules/react-native-image-crop-picker/ios/QBImagePicker/QBImagePickerController.podspec'```, 
running `pod install` and `Product` > `Clean Build Folder` solves that issue with iOS 13 dark mode for my app.

<img width="379" alt="Снимок экрана 2019-10-18 в 16 17 28" src="https://user-images.githubusercontent.com/8297414/67097818-97d8df00-f1c3-11e9-8017-561e43deeac8.png">

**Comment by Rileyp33** [comment]
> If anyone is still stuck on a react-native < 0.60 project like me, this fix seems to work on < 0.25.0 versions as well.
> 
> Thanks @cr1s3c!

@jrapala -- did you have to edit node_modules directly?

**Comment by jrapala** [comment]
@Rileyp33 Yep, I'm a fan of [patch-package](https://github.com/ds300/patch-package) for making adjustments like this.

**Comment by Rileyp33** [comment]
> patch-package

Thank you!

**Comment by Rileyp33** [comment]
Solution from @jrapala works (for those stuck on a react-native < 0.60 project)!  Found another workaround for anyone in this situation who wants to avoid patching node_modules:

- Clone react-native-image-crop picker > v0.25.3
- In your project's `ios` directory, create a directory called `patch`
- Copy the contents of `react-native-image-crop-picker/ios/QBImagePicker` from the cloned repo and drop it into your new `patch` directory
- Add the following to your Podfile: ```pod 'QBImagePickerController', :path => './patch/QBImagePicker/QBImagePickerController.podspec'```
- `$ cd ios && pod install`

**Comment by GuiltyKirito** [comment]
> If anyone is still stuck on a react-native < 0.60 project like me, this fix seems to work on < 0.25.0 versions as well.
> 
> Thanks @cr1s3c!



> Thanks, adding a dependency
> `pod 'QBImagePickerController', :path => '../node_modules/react-native-image-crop-picker/ios/QBImagePicker/QBImagePickerController.podspec'`,
> running `pod install` and `Product` > `Clean Build Folder` solves that issue with iOS 13 dark mode for my app.
> 
> <img alt="Снимок экрана 2019-10-18 в 16 17 28" width="379" src="https://user-images.githubusercontent.com/8297414/67097818-97d8df00-f1c3-11e9-8017-561e43deeac8.png">



> Thanks, adding a dependency
> `pod 'QBImagePickerController', :path => '../node_modules/react-native-image-crop-picker/ios/QBImagePicker/QBImagePickerController.podspec'`,
> running `pod install` and `Product` > `Clean Build Folder` solves that issue with iOS 13 dark mode for my app.
> 
> <img alt="Снимок экрана 2019-10-18 в 16 17 28" width="379" src="https://user-images.githubusercontent.com/8297414/67097818-97d8df00-f1c3-11e9-8017-561e43deeac8.png">

thank you save my hair XDDDDD
