### ISSUE TITLE
Could not determine artifacts for com.github.yalantis:ucrop:2.2.2-native

### ISSUE THREAD

**Issue by snamstorm** [ivpusic/react-native-image-crop-picker#1112]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.25.2 (Also tested on v0.25.0)
- react-native v0.60.3

### Platform
Tell us to which platform this issue is related

- Android

### Steps to reproduce

Had no issue building a release version a week ago (no library versions in our app have updated since) - tried yesterday and started to get the below error `Could not determine artifacts for com.github.yalantis:ucrop:2.2.2-native`.

Saw there were some issues about a year back relating to `yalantis:ucrop:2.2.2-native` and `react-native-image-crop-picker`.

Seems that `ucrop` was migrated to AndroidX 3 days ago, not sure if that is causing this error with `react-native-image-crop-picker`
https://github.com/Yalantis/uCrop/releases

iOS build still works without any issue

### Attachments

Build Error:
```
FAILURE: Build failed with an exception.
* What went wrong:
Could not determine the dependencies of task ':app:compileDevReleaseJavaWithJavac'.
> Could not resolve all dependencies for configuration ':app:devReleaseRuntimeClasspath'.
   > Could not determine artifacts for com.github.yalantis:ucrop:2.2.2-native: Skipped due to earlier error
```

build.gradle
```
allprojects {
    repositories {
        // Add jitpack repository (added by react-native-spinkit)
        maven { url "https://jitpack.io" }
        mavenLocal()
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
            url "https://maven.google.com"
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
    }
}
```

```
buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
	googlePlayServicesAuthVersion = "16.0.1" 
    }
    repositories {
        google()
        jcenter()
        maven { url 'https://maven.fabric.io/public' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.1'
        classpath 'com.google.gms:google-services:4.2.0'
    }
}
```

**Comment by harguus** [comment]
I have the same problem! Any solution?

**Comment by dandevs** [comment]
I too am having the same problems, worked fine before. 
* react-native@0.59.10
* react-native-image-crop-picker@0.24.1

**Comment by rasika-vilankar** [comment]
I'm having a similar issue. Any help would be greatly appreciated.

**Comment by deflorilemarului** [comment]
same thing here. 

All of a sudden the build fails with that error. 

im using latest RN and android studio.

any workaround ?

**Comment by yurkagon** [comment]
Add `www` to` https://jitpack.io` in `build.gradle`

`maven { url "https://www.jitpack.io" }`
(Added www)

I dont know why, but it works

**Comment by harguus** [comment]
> Add `www` to` https://jitpack.io` in `build.gradle`
> 
> `maven { url "https://www.jitpack.io" }`
> (Added www)
> 
> I dont know why, but it works as for me

I didn't find this line in my `build.gradle` file

**Comment by snamstorm** [comment]
@yurkagon 

> Add `www` to `https://jitpack.io` in `build.gradle`

Thanks - tried this and now it works

**Comment by dandevs** [comment]
@ivpusic you should probably put this on the readme

**Comment by gitdevzwt** [comment]
I'm having a similar issue. Any help would be greatly appreciated.

"react-native": "0.60.5",
"react-native-image-crop-picker": "^0.25.2",

**Comment by yangfanyu** [comment]
> Add `www` to` https://jitpack.io` in `build.gradle`
> 
> `maven { url "https://www.jitpack.io" }`
> (Added www)
> 
> I dont know why, but it works as for me

thanks, it works

**Comment by amjiddader** [comment]
> Add `www` to` https://jitpack.io` in `build.gradle`
> 
> `maven { url "https://www.jitpack.io" }` (Added www)
> 
> I dont know why, but it works as for me

Just came here to say Thanks .. It should be www in readme file awell.. 
Anyways thanks.
