### ISSUE TITLE
How to preview a selected image？

### ISSUE THREAD

**Issue by mmgirl** [ivpusic/react-native-image-crop-picker#1117]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.25.2
- react-native v0.60.5

### Platform
Tell us to which platform this issue is related

- iOS
- Android

### Expected behaviour

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by ivpusic** [comment]
you should implement preview feature in your app
