### ISSUE TITLE
Failed to verify bitcode in QBImagePicker.framework

### ISSUE THREAD

**Issue by vivi19** [ivpusic/react-native-image-crop-picker#1119]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.24.0
- react-native v0.59.8

### Platform
Tell us to which platform this issue is related

- iOS

### Actual behaviour
![未命名](https://user-images.githubusercontent.com/40831673/65401315-e7f99700-ddf9-11e9-88ac-11c1d60b2816.png)

### Steps to reproduce

1.
![3a8e8749345f6f0e36049034ad2f8843](https://user-images.githubusercontent.com/40831673/65401250-6570d780-ddf9-11e9-936c-90e5aa537fc2.png)
2.
![d23d30beff38a2f5e7c89d4cc4205f83](https://user-images.githubusercontent.com/40831673/65401259-80434c00-ddf9-11e9-84d2-7fdfe68bd8c0.png)
3.
![20e6a85c3eb42f9a09f1d09318c44667](https://user-images.githubusercontent.com/40831673/65401276-ae289080-ddf9-11e9-8656-952a29b42cce.png)
4.
![Uploading 未命名2.png…]()
5.
![未命名](https://user-images.githubusercontent.com/40831673/65401315-e7f99700-ddf9-11e9-88ac-11c1d60b2816.png)

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by ivpusic** [comment]
if you are not using it already, I suggest that you use cocoapods, otherwise this thread might me helpful https://github.com/ivpusic/react-native-image-crop-picker/issues/61
