### ISSUE TITLE
Build issue on jitpack?

### ISSUE THREAD

**Issue by jlo1** [ivpusic/react-native-image-crop-picker#1125]
### Version
- react-native-image-crop-picker v0.24.1
- react-native v0.59.10

### Platform
- Android

### Expected/Actual behaviour
When trying to build app, seeing the popular issue:
```
Could not resolve all files for configuration ':app:innerTestRuntimeClasspath'.
> Could not resolve com.github.yalantis:ucrop:2.2.2-native.
  Required by:
      project :app > project :react-native-image-crop-picker
   > Skipped due to earlier error
```

Have added both maven and jitpack.io url into `allRepositories` of build.gradle, and it has been working in the past... Something seems to have changed within the last week.

Noticed that jitpack build logs are also erroring out -- is it possible that is a related issue?
https://jitpack.io/com/github/ivpusic/react-native-image-crop-picker/v0.24.1/build.log

```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/jitpack/build/android/build.gradle' line: 53

* What went wrong:
A problem occurred evaluating root project 'android'.
> Could not find method implementation() for arguments [com.facebook.react:react-native:+] on root project 'android'.
```

**Comment by ivpusic** [comment]
if you change url like suggested in PR https://github.com/ivpusic/react-native-image-crop-picker/pull/1115/files, does it work then?

**Comment by nromptea42** [comment]
Worked for me !

**Comment by ivpusic** [comment]
tnx

**Comment by jlo1** [comment]
Perfect, that worked beautifully. Thanks!
