### ISSUE TITLE
How to open "Camera Roll" on iOS directly?

### ISSUE THREAD

**Issue by msqar** [ivpusic/react-native-image-crop-picker#1126]
### Version

- react-native-image-crop-picker 0.25.2
- react-native v0.60.5

### Platform
- iOS

### Expected behaviour
I'd like to open the Camera Roll directly in desc order. (New ones first)

### Actual behaviour
I see a list of all my albums, and whenever I open "All Photos", i see the oldest ones first. Which is also not desired.

This is my current code, i'm simply using openPicker.

```
ImagePicker.openPicker({
            compressImageQuality: 0.7,
            compressImageMaxWidth: 1200,
            cropping: true,
            mediaType: 'photo',
            sortOrder: 'desc' // <--- this doesn't work at all?
        })
```

Any ideas on how I can achieve this? Thanks.

**Comment by ivpusic** [comment]
sortOrder is not supported currently

**Comment by msqar** [comment]
@ivpusic hey iv, thanks for replying, but why closing? I'm still in need on how can this be done. At least, something that lets me open the photos at the latest date and not the oldest. There's nothing like that?

**Comment by ChristopherGillis** [comment]
https://github.com/ivpusic/react-native-image-crop-picker/issues/1081
