### ISSUE TITLE
sourceURL always null on iOS 13 devices and simulators

### ISSUE THREAD

**Issue by mzdon** [ivpusic/react-native-image-crop-picker#1130]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.25.2
- react-native v0.60.5

### Platform
Tell us to which platform this issue is related

iOS 13

### Expected behaviour

The response object in JS returns a sourceURL on iOS when images are selected.

### Actual behaviour

The response object sourceURL property is always null for selected images.

### Steps to reproduce

1. Open the image picker on any iOS 13 device or simulator.

2. Select one or more images (videos are not affected) and press Done.

3. Inspect the response objects in JS and observe that the sourceURL is always null.

### Attachments

It looks like this issue is related to the use of PHImageManager:requestImageDataForAsset which is listed as deprecated on the Apple Developer docs.  The NSDictionary info provided to the resultHandler callback used to contain a PHImageFileURLKey property but this property is no longer provided in iOS 13.  This property was set as the sourceURL.

It looks like there may be other ways to retrieve this info on iOS 13.  https://stackoverflow.com/a/57307250

I'm looking into this as well, but I have limited experience with Objective-C.

**EDIT:**
It seems this is only the case when the writeTempFile flag is false, which is the case for us.  Switching it back to true (the default) resolves that issue.  Maybe this is just a matter of updating documentation if this is an expected behavior?

**Comment by maron-codersinteractive** [comment]
I have the same issue with `ImagePicker.openCamera()` but not with `ImagePicker.openPicker()`. I tested in version < iOS 13

**Comment by boaz-lachman** [comment]
+1 have issue with openpicker

**Comment by ArronJLinton** [comment]
For choosing from gallery and taking a picture, I was able to get through with a successful photo upload by using the path key in the response object.

**Comment by kamilzamerski** [comment]
The same problem... SourceURL is null. Unable to get photo path

**Comment by IvanCaceres** [comment]
using the path key `response.path` works on ios 13 for upload purposes

**Comment by webbhead777** [comment]
You can use `path` to get the tmp file path but if you need to get the file path to the persisted photo (in the cameraroll) `sourceURL` is always `null` so it's not gonna work 😕

**Comment by ivpusic** [comment]
fixed in https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.33.3
