### ISSUE TITLE
null is not an object (evaluating '_reactNativeImageCropPicker.default.openCamera')

### ISSUE THREAD

**Issue by Yyutaa** [ivpusic/react-native-image-crop-picker#1131]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.?.?
- react-native v0.?.?

### Platform
Tell us to which platform this issue is related

- iOS
- Android

### Steps to reproduce

1.

2.

3.

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by ChristopheVandePoel** [comment]
You will need to go to your podfile (`ios/Podfile`) and add the following line in your dependencies:

```
pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker/RNImageCropPicker.podspec'
```
After adding this line, save it and run `pod install` or `bundle exec pod install` if you use Bundler and rebuild the app. It should work now.

It seems that one of the last changes to the README actually removed this crucial step:
https://github.com/ivpusic/react-native-image-crop-picker/commit/938c74dd42b06d739e3e2be8effb8fd94909b281#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by arifinoid** [comment]
@ChristopheVandePoel what about running on android device / emulator??

**Comment by ChristopheVandePoel** [comment]
I did not have any problems installing it in Android. With RN 60+ the autolinking should at least install it automatically and the post-install steps in the docs seem to be pretty much correct.

**Comment by bockc** [comment]
@ChristopheVandePoel nope, autolinking does not work for me for Android. A lot of other packages don't manage well autolinking on Android either. Had to run `react-native link --platforms android react-native-image-crop-picker` in order for it to work. On iOS though, the autolinking works smoothly.

**Comment by falquinho** [comment]
As noted by @bockc the solution was to use the link command. I installed react-native-image-picker-crop before ejecting from expo, maybe that was what caused the error for me.

**Comment by bockc** [comment]
For information, we don't use expo at all, so I don't think it has anything to do with the linking issue. I tried to unlink the package for android and rerun a simple `yarn` for it to trigger the post install scripts which are supposed to autolink the package, but it didn't change the outcome, it still wasn't linked properly.

**Comment by ivpusic** [comment]
cannot reproduce this issue. please make sure that you followed installation steps from readme

**Comment by joeyfigaro** [comment]
> You will need to go to your podfile (`ios/Podfile`) and add the following line in your dependencies:
> 
> ```
> pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker/RNImageCropPicker.podspec'
> ```
> 
> After adding this line, save it and run `pod install` or `bundle exec pod install` if you use Bundler and rebuild the app. It should work now.
> 
> It seems that one of the last changes to the README actually removed this crucial step:
> [938c74d#diff-04c6e90faac2675aa89e2176d2eec7d8](https://github.com/ivpusic/react-native-image-crop-picker/commit/938c74dd42b06d739e3e2be8effb8fd94909b281#diff-04c6e90faac2675aa89e2176d2eec7d8)

Doing this results in this error:
```
[!] There are multiple dependencies with different sources for `RNImageCropPicker` in `Podfile`:

- RNImageCropPicker (from `../node_modules/react-native-image-crop-picker`)
- RNImageCropPicker (from `../node_modules/react-native-image-crop-picker/RNImageCropPicker.podspec`)
```

**Comment by joeyfigaro** [comment]
Currently experiencing this issue for at least iOS using react native `0.64.2` – ran pod install after installing the package and made sure the proper keys/permissions were specified in info.plist. I've tried reinstalling and wiping metro/doing clean restart + build. Anything else I can provide to help triage?
