### ISSUE TITLE
iOS video recording crash. NSInternalInconsistencyException: threading violation: expected the main thread

### ISSUE THREAD

**Issue by teeolendo** [ivpusic/react-native-image-crop-picker#1139]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.25.3
- react-native v0.60.5

### Platform
Tell us to which platform this issue is related

- iOS: 13

### Expected behaviour
After recording a video on my device, the package should return the video object.

### Actual behaviour
App crashes immediately after I select "Use Video".

I use openPicker and openCamera to capture both photos and video. The app only crashes after recording a video on ios. Everything else is fine. 

### Steps to reproduce
I follow all the steps in the install guide. I'm using RN 0.60.5 so my post install steps are

1. pod install. I've also run pod update

2. Update Info.plist with NSCameraUsageDescription, NSMicrophoneUsageDescription, NSPhotoLibraryAddUsageDescription and NSPhotoLibraryUsageDescription entries. All these are successfully displayed to the user and I'm able to accept them appropriately.

3. Update Libraries
<img width="548" alt="Screen Shot 2019-10-10 at 10 08 17 AM" src="https://user-images.githubusercontent.com/2772900/66576626-0bd11280-eb46-11e9-9055-d878ca05e45f.png">

4. Run the app, the code below fails on IOS
`recordVideo() {
    ImagePicker.openCamera({
      includeExif: false,
      mediaType: 'video',
      useFrontCamera: true,
    }).then((video) => {
      this.gotoReview(video);
    })
      .catch((e) => {
        console.log(e);
        // Sentry.captureException(e);
      });
  }`

### Attachments

// stacktrace or any other useful debug info

My stack trace says,
`Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'threading violation: expected the main thread'`
 
I use Sentry for exception handling and this error message I'm getting back
`NSInternalInconsistencyException: threading violation: expected the main thread

  File "node_modules/react-native-image-crop-picker/ios/src/ImageCropPicker.m", line 223, in __71-[ImageCropPicker imagePickerController:didFinishPickingMediaWithInfo:]_block_invoke

  File "node_modules/react-native-image-crop-picker/ios/src/ImageCropPicker.m", line 476, in __75-[ImageCropPicker handleVideo:withFileName:withLocalIdentifier:completion:]_block_invoke

  File "node_modules/react-native-image-crop-picker/ios/src/Compression.m", line 128, in __59-[Compression compressVideo:outputURL:withOptions:handler:]_block_invoke`

# Podfile
Here is my Podfile:

`platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'Connexus' do
Pods for Connexus
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/React'
  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'
  pod 'QBImagePickerController', :path => '../node_modules/react-native-image-crop-picker/ios/QBImagePicker/QBImagePickerController.podspec'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  target 'ConnexusTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
end
`

react-native info:
`System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
    Memory: 19.97 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.8.0 - /usr/local/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 6.10.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 14, 22, 23, 24, 25, 26, 27, 28
      Build Tools: 25.0.3, 26.0.1, 27.0.3, 28.0.1, 28.0.2, 28.0.3, 29.0.0
      System Images: android-27 | Android TV Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-P | Android TV Intel x86 Atom, android-P | China version of Wear OS Intel x86 Atom, android-P | Wear OS Intel x86 Atom, android-P | Google APIs Intel x86 Atom, android-P | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.5 => 0.60.5
  npmGlobalPackages:
    create-react-native-app: 1.0.0
    react-native-cli: 2.0.1`

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by livefire2015** [comment]
Same error here if using Xcode 11.1 to build the app, but no error if using Xcode 10.3, with others being the same.

**Comment by teeolendo** [comment]
> Same error here if using Xcode 11.1 to build the app, but no error if using Xcode 10.3, with others being the same.

Same here, using Xcode 11.1

**Comment by vishaljadav24** [comment]
> > Same error here if using Xcode 11.1 to build the app, but no error if using Xcode 10.3, with others being the same.

Facing same issue on Xcode 11.1 and iOS 13.

**Comment by harishsn** [comment]
Same issue

**Comment by AurangzaibRamzan** [comment]
+1

**Comment by emvigotech** [comment]
We're also facing the same issue in iOS 13 and above.
Please advice a solution ASAP

**Comment by Strate** [comment]
go to `ImageCropPicker.m` file, find `- (void)imagePickerController:(UIImagePickerController *)picker didFinishPickingMediaWithInfo:(NSDictionary *)info {`

method, inside that method find
```
self handleVideo:asset
             withFileName:fileName
      withLocalIdentifier:nil
               completion:^(NSDictionary* video) {
```
and wrap inner contents to 
```
dispatch_async(dispatch_get_main_queue(), ^{ /* code*/ };
```
this helps me.

![image](https://user-images.githubusercontent.com/392644/66938023-1cebb900-f049-11e9-9382-459c892c6d2b.png)

**Comment by Strate** [comment]
You can also check PR to import fix to your project
