### ISSUE TITLE
Crash on selection of video

### ISSUE THREAD

**Issue by francklavisse** [ivpusic/react-native-image-crop-picker#114]
### Version

Tell us which versions you are using: 
- react-native-image-crop-picker v^0.9.6
- react-native v^0.34.1
### Platform

Tell us to which platform this issue is related
- iOS
### Expected behaviour

Using the picker to select a video
### Actual behaviour

When I select a video my app crashes.
See attached files for the stack

I doesn't use thread, I really don't understand where this issue come from ? 
I precise that it's working fine with pictures.
### Steps to reproduce
1. Open a picker
2. Select a video
3. Crash
### Attachments

My code:

![capture d ecran 2016-10-17 a 15 12 06](https://cloud.githubusercontent.com/assets/2026636/19438896/40863f06-947c-11e6-83e5-2d17bd9503c0.png)
![capture d ecran 2016-10-17 a 15 12 53](https://cloud.githubusercontent.com/assets/2026636/19438920/5ef49550-947c-11e6-823e-928c9c4faa20.png)

The stacks:

![capture d ecran 2016-10-17 a 15 11 08](https://cloud.githubusercontent.com/assets/2026636/19438832/ff9faf54-947b-11e6-8136-fb920f9107de.png)
![capture d ecran 2016-10-17 a 15 10 35](https://cloud.githubusercontent.com/assets/2026636/19438831/ff9d6bea-947b-11e6-9d68-f96df4bd9203.png)

**Comment by ivpusic** [comment]
hm, I cannot reproduce this. Do you have a time to debug it? This would be very helpful.

**Comment by francklavisse** [comment]
Yes sure, i'm trying to debug this since few hours :( that's the last feature blocking my release

**Comment by francklavisse** [comment]
I tried several things, like moving my Picker out of my helper, or in another container, but I always have the same issue.

It happens randomly (like said on the stack), but it's more than 50% of the time.
I tried to change options (passing comrpessVideo to false) but it doesn't change anything
I tried few tips founded on stackoverflow, without any result.

I tried few things with dispatch thread in objective-C, but it doesn't change anything

**Comment by ivpusic** [comment]
@francklavisse any progress?

**Comment by francklavisse** [comment]
nop sorry ! I use another picker for video now (I use your's for album of multiples pictures, I don't have issue on this side), I don't have time to search more for the moment :/

**Comment by greatzues** [comment]
I conclude some method through my repeatedly try.Here is my solve step
> you should update your react-native version to 0.32.0+ as well as update react to proper version to fit in.
> use [#84](https://github.com/Yalantis/uCrop/issues/84) to add certain attributes on your app's build.gradle, remember confirm your Gradle Plugin is 1.5 or 2.0+.if your Gradle Plugin is 1.5 and you want to update the version, I would like to share [Gradle Release Notes](https://developer.android.com/studio/releases/gradle-plugin.html) .
### My package dependencies as follow,react 15.3.2, react-native 0.35.0,Gradle version 2.14.1 and Gradle Plugin version is 2.1.3.If your config correct, it will work.
### In addition
If you install `react-native-image-picker`,but wasn't the lastest, Application stop also when choose a image.the way to settle it is update the version or uninstall it from your project(too complex).

Above is my personal expercience to fix this issues, maybe can help.

**Comment by ivpusic** [comment]
https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.10.3 should fix this issue
