### ISSUE TITLE
Help a bit

### ISSUE THREAD

**Issue by HKbool** [ivpusic/react-native-image-crop-picker#115]
ld: embedded dylibs/frameworks are only supported on iOS 8.0 and later (@rpath/RSKImageCropper.framework/RSKImageCropper) for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ivpusic** [comment]
set deployment target to min 8.0. Follow installation instructions https://github.com/ivpusic/react-native-image-crop-picker#ios
