### ISSUE TITLE
No known class method for selector 'labelColor'

### ISSUE THREAD

**Issue by linhmimoza** [ivpusic/react-native-image-crop-picker#1154]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.4.2 and v0.25.3 and v 0.25.0
- react-native v0.60.5

### Platform
- iOS

### Actual behaviour
Error when build

### Steps to reproduce

1. Add   pod 'QBImagePickerController', :path => '../node_modules/react-native-image-crop-picker/ios/QBImagePicker/QBImagePickerController.podspec'

2. pod install

3. Build and Error appear

### Attachments

![Screen Shot 2019-10-24 at 5 39 58 PM 1](https://user-images.githubusercontent.com/33194017/67477978-61003e80-f685-11e9-9a7b-0465eda7d95f.png)

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by linhmimoza** [comment]
I have already found out the way to fix it. Just add QBImagePicker.storyboard to "Copy Bundle Resources" and it works. 
![Screen Shot 2019-10-29 at 1 53 55 PM](https://user-images.githubusercontent.com/33194017/67744301-b062b800-fa53-11e9-8445-504418e64694.png)

**Comment by swapanil** [comment]
Unable to resolve this issue **No known class method for selector 'labelColor'**

React-Native: 0.61.5
Xcode version: 10.1
node version: 10.15.3
Os: Mac OS Mojave(10.14.6)

Steps to reproduce:

npm i react-native-image-crop-picker

cd iOS && pod install

clean & build on Xcode

help me on this

**Comment by whalemare** [comment]
Have the same issue on XCode 11.3.1
On debug it's build perfectly, but on release can not because **No known class method for selector 'labelColor'**

**Comment by lavaraju-sdei** [comment]
> I updated the xcode from 10.3 to 11.1 and it worked

**Comment by MrDrk94** [comment]
Hello, I am using Xcode 10.1 and I can't upgrade it since OS High Sierra doesn't support any newer version. Is there any solution for this problem?
