### ISSUE TITLE
Video not working

### ISSUE THREAD

**Issue by craftmusic** [ivpusic/react-native-image-crop-picker#1155]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.25.3
- react-native v0.6

### Platform
Tell us to which platform this issue is related

- iOS

### Expected behaviour

Choose a video file from the photo library when mediaType is set to ‘any’ or ‘video’

### Actual behaviour

Only lets me choose photos

### Steps to reproduce

import ImagePicker from 'react-native-image-crop-picker';

export default function(orientation) {
  let height = 1080;
  let width = 1920;
  if (orientation === 'portrait') {
    const oldHeight = height;
    height = width;
    width = oldHeight;
  } else if (orientation === 'square') {
    width = height;
  } else if (orientation === 'landscape') {
    height = height;
    width = width;
  }

  return ImagePicker.openPicker({
    mediaType: 'video',
    width,
    height,
    cropping: true,
  });
}

pressUpload = () => {
    cropper('portrait').then(video => {
      console.log(JSON.stringify(video));
    });
  };

**Comment by ivpusic** [comment]
remove `cropping` property

**Comment by craftmusic** [comment]
Lol... what? I thought the point of this library was being able to crop video.

**Comment by nica0012** [comment]
You can't crop videos...?
