### ISSUE TITLE
Link report error 0.24 version

### ISSUE THREAD

**Issue by 1152295219** [ivpusic/react-native-image-crop-picker#1161]
FAILURE: Build failed with an exception.

* Where:
Build file 'D:\reactnative\demo1\node_modules\react-native-image-crop-picker\android\build.gradle' line: 23

* What went wrong:
A problem occurred evaluating project ':react-native-image-crop-picker'.
> Could not find method implementation() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 16.123 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

**Comment by ivpusic** [comment]
probably you had outdated gradle version. try upgrading your gradle version, and use most recent library version (0.27.0)
