### ISSUE TITLE
Picker text is unreadable in DarkMode (iOS)

### ISSUE THREAD

**Issue by swapkids** [ivpusic/react-native-image-crop-picker#1162]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.26.1
- react-native v0.61

### Platform
Tell us to which platform this issue is related

- iOS

### Expected behaviour
Styling of the picker should follow darkMode settings

### Actual behaviour
In DarkMode the colors and backgrounds are not fitting DarkMode and hard to read (and somewhat ugly :-))

### Steps to reproduce

1. Open the picker on iOS in DarkMode

### Attachments
![Simulator Screen Shot - iPhone 11 - 2019-11-04 at 09 10 30](https://user-images.githubusercontent.com/13032789/68106890-547cb100-fee3-11e9-9058-6da6a040806a.png)

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by swapkids** [comment]
I fixed it by changing colors to System Defaults (for backgrounds and texts) in the storyboard ... Should I do a PR?

**Comment by swapkids** [comment]
Better, but still missing som DarkMode compliant thumbnails
![Simulator Screen Shot - iPhone 11 - 2019-11-04 at 09 37 18](https://user-images.githubusercontent.com/13032789/68107956-b7bc1280-fee6-11e9-921a-c5401980bae8.png)

**Comment by ivpusic** [comment]
add this to your podfile

```
pod 'QBImagePickerController', :path => '../node_modules/react-native-image-crop-picker/ios/QBImagePicker/QBImagePickerController.podspec'
```

it includes a proper dark mode support

**Comment by sam17896** [comment]
@ivpusic i have added this to my pod file but still the dark mode issue exist
