### ISSUE TITLE
Hi everyone i am learning react-native i want to upload multiple images using expo with react-native-image-crop-picker

### ISSUE THREAD

**Issue by sivasankarchimata** [ivpusic/react-native-image-crop-picker#1166]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.26.1
- react-native v0.59.3
- expo 35.0.0
### Platform
Tell us to which platform this issue is related

- Android

### Expected behaviour
Hi everyone i am learning react-native i want to upload multiple images using expo with react-native-image-crop-picker . Is it possible to use it ?

### Actual behaviour

If it is possible then please help how can we do it

**Comment by Dihan101** [comment]
> ### Version
> Tell us which versions you are using:
> 
> * react-native-image-crop-picker v0.26.1
> * react-native v0.59.3
> * expo 35.0.0
> 
> ### Platform
> Tell us to which platform this issue is related
> 
> * Android
> 
> ### Expected behaviour
> Hi everyone i am learning react-native i want to upload multiple images using expo with react-native-image-crop-picker . Is it possible to use it ?
> 
> ### Actual behaviour
> If it is possible then please help how can we do it

Unfortunately that includes from expo's limitations. But there is one library created by **hyakt**. I did not try it yet but based on his documentation, it only support images and not applicable in videos.

Take note: When you're gonna start a dedicated project and came up to use expo, please consider first what are the scope of the projects and find from the expo's limitations where your project's requirements are needs in future.
