### ISSUE TITLE
Add support to use this libary for an existing Android-App

### ISSUE THREAD

**Issue by karvulf** [ivpusic/react-native-image-crop-picker#1170]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.26.1
- react-native v0.61.2

### Platform
Tell us to which platform this issue is related

- Android

### Expected behaviour

Using _react-native-image-crop-picker_ only for _react-native_ works fine. 
But in my case, I want to integrate the _react-native_-App to an existing Android-App. Unfortunately I get problems with the user-permissions.
One way to solve this problem is that I override the Methods for `PermissionAwareActivity`. In that case I have problems to handle the permissions because _react-native-image-crop-picker_ also uses it.

### Actual behaviour

In _react-native-image-picker_, they offer to implement the interface `RnImagePickerPermissionsCallback` (https://github.com/react-native-community/react-native-image-picker/tree/master/android/src/main/java/com/imagepicker/permissions). This interface handles the request-permissions-problems.

### Steps to reproduce

1. Build a react-native-app with _react-native-image-crop-picker_.

2. Integrate the functionality to select images from your gallery.

3. Iintegrate the _react-native_-App to an existing Android-Project and try to start your _react-native_-App in Debug-Mode.

4. Open again your gallery, this won't work unless you implement the required methods for `PermissionAwareActivity`

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by ivpusic** [comment]
unfortunately currently no plans to add such feature like `RnImagePickerPermissionsCallback`

**Comment by karvulf** [comment]
That's sad. For the people who might get problems with that, I found this solution in stackoverflow and it works fine -> https://stackoverflow.com/questions/42841719/react-native-cant-request-location-permissions-using-permissionsandroid/45879293#45879293
