### ISSUE TITLE
Error - Can't pick a video : invalid column latitude

### ISSUE THREAD

**Issue by DamienCastello** [ivpusic/react-native-image-crop-picker#1171]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker V0.26.1
- react-native v0.61.0

### Platform
Tell us to which platform this issue is related

- Android

Hi everyone !
I using react-native and i'm a junior developer so i will try to explain my problem simply and clearly as i can.
So i'm using the library react-native-image-crop-picker and i try to pick a video but i have an error when i pick it (error: invalid column latitude). I put in attachment the screenshot of error.
I specify that i had this error 3 or 4 weeks ago, and i just upgrade the version of the library to latest and it works.
Now i have the same error, and make an upgrade didn't fix it ... I have no idea to why it happen & how i can fix it.
Any idea ?
Thanks very much !

### Attachments
https://www.casimages.com/i/191113051003615775.png.html

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by F4OST** [comment]
I'm having the same issue, any solutions ?

**Comment by DamienCastello** [comment]
Hello everyone ! 
Issue solved :)
I tell you how i solved the problem in case other developper would encounter the same issue.
Given the error: "error: invalid column latitude" error message it suggests to me that maybe when selecting a video in the gallery, the phone may send with the photo, metaData related to geolocation to the library react-native-image-crop-picker. This was only a guess but if the configuration of my simulator does not allow to recover the geolocation, it would explain the error message. To check this hypothesis, I installed the application on a smartphone android (physically) and try to add a video from the gallery and it works which verifies my hypothesis.

Thanks & have a good day !
