### ISSUE TITLE
App crashed in IOS after openPicker

### ISSUE THREAD

**Issue by approached** [ivpusic/react-native-image-crop-picker#1179]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.26.1?
- react-native v0.61.4?

### Platform
- iOS

### Expected behaviour
App crash in IOS after openPicker

### Actual behaviour
openPicker to choice the photo.

### Steps to reproduce

1. Open picker
```
ImagePicker.openPicker({
  width: 300,
  height: 400,
  cropping: true
}).then(image => {
  console.log(image);
});
```

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by MuhammadAdnanRiaz** [comment]
it, because you may haven't followed post-installation steps,  
have you added **NSPhotoLibraryUsageDescription** into Info.plist

**Comment by approached** [comment]
Thank you. Now it works.

But this step: **Under Embedded Binaries click + and add RSKImageCropper.framework and QBImagePicker.framework**

Is wrong i have changed to:

![Screenshot 2019-12-02 at 22 55 53](https://user-images.githubusercontent.com/3439330/69998595-f29d7e80-1556-11ea-97b9-e338cc641582.png)

I hope it is correct.
