### ISSUE TITLE
Can the camera show the all controls 

### ISSUE THREAD

**Issue by ilibilibom** [ivpusic/react-native-image-crop-picker#1181]
Hi 
I'm looking for this kind of functionality: 
![Screen Shot 2019-11-22 at 11 25 10](https://user-images.githubusercontent.com/12745414/69414141-d6117300-0d1a-11ea-97ea-cd39b029b10e.png)

Is there a way to do so with this library?

**Comment by ivpusic** [comment]
you can create this control on your side, and just bind buttons to functions of this library

**Comment by erikfenriz** [comment]
@ilibilibom did you find the library with this type of functionality?

**Comment by ivpusic** [comment]
@erikfenriz you could use this one for example https://github.com/beefe/react-native-actionsheet
