### ISSUE TITLE
Double confirmation when using Camera

### ISSUE THREAD

**Issue by iamclaytonray** [ivpusic/react-native-image-crop-picker#1188]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker `v0.26.1`
- react-native `v0.61.2`

### Platform
Tell us to which platform this issue is related

- [x] iOS
- [ ] Android

### Expected behaviour
User takes a picture, selects `Choose`, and they are done.

### Actual behaviour
User takes a picture, selects `Use Photo`, is shown basically the same screen with new options, `Cancel` and `Choose`, and after selecting both `Use Photo` and `Choose`, they are done.

### Steps to reproduce

1. Choose `Camera` as your source.

2. Take a picture.

3. You'll see two screens asking essentially the same thing. (`Use Photo` on the first screen, `Choose` on the next.

### Attachments

Will add by EOD today.

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

### Misc.

This seems related to #1177.

**Comment by vijayanandof** [comment]
@iamclaytonray Have you found a way to achieve this?
