### ISSUE TITLE
ios问题

### ISSUE THREAD

**Issue by memorybx** [ivpusic/react-native-image-crop-picker#1191]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.15.1
- react-native v0.59.6

- Android 没问题
- iOS

Showing All Issues
/Users/libingxue/pansky/project/sxls/sxlssapp/node_modules/react-native/React/Base/RCTBridgeModule.h:52:16: Redefinition of 'RCTMethodInfo'

/Users/libingxue/pansky/project/sxls/sxlssapp/node_modules/react-native/React/Base/RCTBridgeModule.h:56:3: Typedef redefinition with different types ('struct (anonymous struct at /Users/libingxue/Library/Developer/Xcode/DerivedData/sxlssApp-enenwvmmqgzzvggnlwdqbprglrru/Build/Products/Debug-iphoneos/include/React/RCTBridgeModule.h:52:16)' vs 'struct RCTMethodInfo')

/Users/libingxue/pansky/project/sxls/sxlssapp/node_modules/react-native/React/Base/RCTBridgeModule.h:63:11: Duplicate protocol definition of 'RCTBridgeModule' is ignored

/Users/libingxue/pansky/project/sxls/sxlssapp/node_modules/react-native/React/Base/RCTBridgeModule.h:340:12: Duplicate protocol definition of 'RCTTurboModuleLookupDelegate' is ignored

/Users/libingxue/pansky/project/sxls/sxlssapp/node_modules/react-native/React/Base/RCTBridge.h:89:20: Reference to 'RCTBridgeModule' is ambiguous

/Users/libingxue/pansky/project/sxls/sxlssapp/node_modules/react-native/React/Base/RCTBridge.h:89:20: Cannot find protocol declaration for 'RCTBridgeModule'; did you mean 'RCTBridgeMethod'?

/Users/libingxue/pansky/project/sxls/sxlssapp/node_modules/react-native/React/Base/RCTBridge.h:166:45: Reference to 'RCTTurboModuleLookupDelegate' is ambiguous

/Users/libingxue/pansky/project/sxls/sxlssapp/node_modules/react-native/React/Base/RCTBridge.h:166:45: No type or protocol named 'RCTTurboModuleLookupDelegate'

/Users/libingxue/pansky/project/sxls/sxlssapp/node_modules/react-native/React/Base/RCTURLRequestHandler.h:15:33: Reference to 'RCTBridgeModule' is ambiguous

/Users/libingxue/pansky/project/sxls/sxlssapp/node_modules/react-native/React/Base/RCTURLRequestHandler.h:15:33: Cannot find protocol declaration for 'RCTBridgeModule'; did you mean 'RCTBridgeMethod'?

/Users/libingxue/pansky/project/sxls/sxlssapp/node_modules/react-native/Libraries/Image/RCTImageLoader.h:61:39: Reference to 'RCTBridgeModule' is ambiguous

/Users/libingxue/pansky/project/sxls/sxlssapp/node_modules/react-native/Libraries/Image/RCTImageLoader.h:61:39: Cannot find protocol declaration for 'RCTBridgeModule'; did you mean 'RCTBridgeMethod'?

/Users/libingxue/pansky/project/sxls/sxlssapp/node_modules/react-native/Libraries/Image/RCTImageLoader.h:61:39: Cannot find protocol definition for 'RCTBridgeMethod'

/Users/libingxue/pansky/project/sxls/sxlssapp/node_modules/react-native/Libraries/Image/RCTImageLoader.h:61:56: Cannot find protocol definition for 'RCTURLRequestHandler'

/Users/libingxue/pansky/project/sxls/sxlssapp/node_modules/react-native/Libraries/Image/RCTImageLoader.h:168:30: Reference to 'RCTBridgeModule' is ambiguous

/Users/libingxue/pansky/project/sxls/sxlssapp/node_modules/react-native/Libraries/Image/RCTImageLoader.h:168:30: Cannot find protocol declaration for 'RCTBridgeModule'; did you mean 'RCTBridgeMethod'?

/Users/libingxue/pansky/project/sxls/sxlssapp/node_modules/react-native/Libraries/Image/RCTImageLoader.h:224:32: Reference to 'RCTBridgeModule' is ambiguous

/Users/libingxue/pansky/project/sxls/sxlssapp/node_modules/react-native/Libraries/Image/RCTImageLoader.h:224:32: Cannot find protocol declaration for 'RCTBridgeModule'; did you mean 'RCTBridgeMethod'?

/Users/libingxue/pansky/project/sxls/sxlssapp/node_modules/react-native-image-crop-picker/ios/ImageCropPicker.h:35:3: Reference to 'RCTBridgeModule' is ambiguous

/Users/libingxue/pansky/project/sxls/sxlssapp/node_modules/react-native-image-crop-picker/ios/ImageCropPicker.h:35:3: Cannot find protocol declaration for 'RCTBridgeModule'; did you mean 'RCTBridgeMethod'?

/Users/libingxue/pansky/project/sxls/sxlssapp/node_modules/react-native-image-crop-picker/ios/ImageCropPicker.h:35:3: Cannot find protocol definition for 'RCTBridgeMethod'

/Users/libingxue/pansky/project/sxls/sxlssapp/node_modules/react-native-image-crop-picker/ios/ImageCropPicker.m:44:13: Property implementation must have its declaration in interface 'ImageCropPicker' or one of its extensions

/Users/libingxue/pansky/project/sxls/sxlssapp/node_modules/react-native-image-crop-picker/ios/ImageCropPicker.m:140:25: Assigning to 'id<UINavigationControllerDelegate,UIImagePickerControllerDelegate> _Nullable' from incompatible type 'ImageCropPicker *const __strong'

/Users/libingxue/pansky/project/sxls/sxlssapp/node_modules/react-native-image-crop-picker/ios/ImageCropPicker.m:287:11: Property 'bridge' not found on object of type 'ImageCropPicker *'

[https://shimo.im/docs/T36xpVW36XKqhgtG/ ](url)

你好，询问一下。

**Comment by ivpusic** [comment]
cannot reproduce this issue. please make sure that you followed installation steps from readme
