### ISSUE TITLE
裁剪

### ISSUE THREAD

**Issue by itnnnn** [ivpusic/react-native-image-crop-picker#1194]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.24.1
- react-native v0.59.8

### Platform
Tell us to which platform this issue is related

- Android 10

### Actual behaviour
android 10环境在上传和拍照过后裁剪过程中会卡死

![Peek 2019-12-04 11-58](https://user-images.githubusercontent.com/43125703/70111555-8ec9a180-168d-11ea-914a-4f1fe6d95eb3.gif)

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by ihaodi** [comment]
me too

**Comment by itnnnn** [comment]
@ivpusic @ihaodi @joeferraro @vitalyrotari @johncblandii  有人了解么

**Comment by ivpusic** [comment]
please try version v0.30.0
