### ISSUE TITLE
Build Failed In IOS

### ISSUE THREAD

**Issue by xiangfengsu** [ivpusic/react-native-image-crop-picker#12]
RCTBridgeModule.h file not found

How should I set ？thanks!

**Comment by ivpusic** [comment]
https://github.com/ivpusic/react-native-image-crop-picker#ios-1

for detailed instructions you can check this https://github.com/ivpusic/react-native-image-crop-picker/issues/6#issuecomment-222647477

**Comment by ivpusic** [comment]
will close this one. if you still have issues, please reopen

**Comment by xuansontrinh** [comment]
I still have this problem after following the instructions.
I am using React Native 0.29.
This is my pod file:


```
platform :ios, '9.3'

target 'NhapHoc' do

  # Pods for NhapHoc

  source 'https://github.com/CocoaPods/Specs.git'
  pod 'React', :subspecs => ['Core', 'RCTImage', 'RCTNetwork', 'RCTText', 'RCTWebSocket'], :path => '../node_modules/react-native'
  pod 'react-native-image-crop-picker', :path => '../node_modules/react-native-image-crop-picker/ios'

end
```

I hope to get response from you soon. Thank you.
