### ISSUE TITLE
Image quality is very poor and unable to resize cropping box

### ISSUE THREAD

**Issue by manjeet-dobble** [ivpusic/react-native-image-crop-picker#120]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker 0.10.1
- react-native v0.34.1

### Expected behaviour
- we should be able to resize crop box by providing height and width.
-quality of image need to be good after cropping 

### Actual behaviour
- unable to resize crop box by providing different height and width in the options object
-image quality is very poor , no way to handle that.

### Steps to reproduce

1.added and linked library as suggested in read me

2.Defined options as const imageOptions = {
      width: 10,
      height: 10,
      includeBase64:true,
      cropping: true
};

3.ImagePicker.openPicker(imageOptions).then(image => {
            console.log(image);
  });
using source =require({uri:image.path})   to show image,

but quality is to bad,

**Comment by ivpusic** [comment]
you used width and height 10/10, which is the reason for bad result image quality. I cannot reproduce the issue that you cannot resize cropping box. Eg: If you provide width: 40, height: 100 crop box should have rectangular shape. Just to be sure we are on the same page, user cannot resize crop box, it will be set programatically.
