### ISSUE TITLE
When I crop a png image ,it will save two picture to 'Pictures' folder ,but only return one path.( 裁剪选择png时，Pictures 目录下会多出一张图片，而且路径没返回)

### ISSUE THREAD

**Issue by st167566** [ivpusic/react-native-image-crop-picker#1201]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.26.1
- react-native v0.61.4

### Platform
- Android

### Expected behaviour
裁剪选择png时，Pictures 目录下会多出一张图片，而且路径没返回，这导致了图片残留，给用户造成困扰。

### Steps to reproduce

1.onopenCamera() then choose a 'PNG'

2.clean()

3.but still one picture left over

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by ows-ali** [comment]
@st167566 did you solve this issue? I am facing the same issue, it is saving two images in /storage/emulated/0/Pictures, how to get path of both images? i dont want them to be saved.

**Comment by ows-ali** [comment]
#863 discussing same issue
