### ISSUE TITLE
iOS dark mode photo albuns names are black and thus can't be read

### ISSUE THREAD

**Issue by fmcruz** [ivpusic/react-native-image-crop-picker#1202]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.26.1
- react-native v0.61.1

### Platform
- iOS

### Expected behaviour
In iOS when in dark mode the album names in the picker should be a different color from black.

### Actual behaviour
Now the album names text color is black so it can't be distinguished from the dark background.

**Comment by sezginriggs** [comment]
I have the same problem too.

**Comment by ivpusic** [comment]
for proper dark mode support please add this to your Podfile

```
pod 'QBImagePickerController', :path => '../node_modules/react-native-image-crop-picker/ios/QBImagePicker/QBImagePickerController.podspec'
```

**Comment by sezginriggs** [comment]
@ivpusic that solved the problem. thank you.
