### ISSUE TITLE
Restrict based on image/video size  before processing for compression?

### ISSUE THREAD

**Issue by rabindrachhachan** [ivpusic/react-native-image-crop-picker#1204]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.24.1
- react-native v0.59.10

### Platform
Tell us to which platform this issue is related

- iOS
- Android

### Expected behaviour,
I wanted to know does this library allow with configuration or some work around  to pick only files with certain max file size? Currently I am facing problem with large file size (20MB), in some devices like Xiomi redmi note 4/5 series. When I select a image with size more than 20 MB, the app crash silently. So to solve this problem , can we check the image size while picking the image, and validate before send for compression or can we list only files with a specific max image size, e.g list images with size less than 20MB?
I don't know whether this kind of behaviour is support or not . Let me know if anyone know.

### Actual behaviour
 List images with size less than 20MB(X MB) or pick image with size less than 20MB(X MB). Can we do this via configuration options? something like 
configOption = {
                compressImageMaxWidth: 360,
                compressImageMaxHeight: 360,
                includeBase64: true,
                multiple: multiple,
                mediaType:'photo',
                showsSelectedCount: true,
               max_file_size: 20 MB  // should list images with less than 20 MB.
            };

**Comment by ivpusic** [comment]
unfortunetly something like this is not yet supported. if you have some time to try to implement such feature, would accept a PR
