### ISSUE TITLE
Couldn't upload taken image 

### ISSUE THREAD

**Issue by hanaechahid** [ivpusic/react-native-image-crop-picker#1208]
### Version
I'm using: 

- react-native-image-crop-picker v^0.23.1
- react-native v0.59.0

### Platform
Tell us to which platform this issue is related

- iOS
- Android

### Expected behaviour

a screen with edit photo title and the taken image 

### Actual behaviour

A black screen with the same title and loading didn't stop

**Comment by ivpusic** [comment]
you can use FormData to upload selected image
