### ISSUE TITLE
Could not find a storyboard named 'QBImagePicker'

### ISSUE THREAD

**Issue by coy102** [ivpusic/react-native-image-crop-picker#1215]
hello, i need help with this error. 

i got error when use mediaType photo or video

`2020-01-20 13:38:53.199769+0700 EmployeeService[328:40253] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Could not find a storyboard named 'QBImagePicker' in bundle NSBundle </var/containers/Bundle/Application/DF784106-0637-4E85-B8A8-61FF7DA3ADB5/EmployeeService.app> (loaded)'
*** First throw call stack:`

thanks

**Comment by endigo** [comment]
@ivpusic I faced the same issue. Can you pay some attention to this? Or is there anyone who has a solution?

**Comment by coy102** [comment]
i got the solutions, srry not updated this issue

add QBImagePicker.storyboard to Build Phases > Copy bundle Resources

![WhatsApp Image 2020-01-22 at 5 19 26 PM](https://user-images.githubusercontent.com/13234170/73509201-e9bf1100-4410-11ea-97eb-1ff7c5f2b2af.jpeg)

**Comment by reactunlimited** [comment]
@coy102 Your solution is working properly. All we need to open Build Phases -> Copy Bundle Resources -> Click on '+' icon -> Click on 'Add Another' button.

Now select from 'node_modules/react-native-image-crop-picker/ios/QBImagePicker/QBImagePicker/QBImagePicker.storyboard'

Now, All you need to require rerun the project.

**Comment by YuhanYue** [comment]
> @coy102 Your solution is working properly. All we need to open Build Phases -> Copy Bundle Resources -> Click on '+' icon -> Click on 'Add Another' button.
> 
> Now select from 'node_modules/react-native-image-crop-picker/ios/QBImagePicker/QBImagePicker/QBImagePicker.storyboard'
> 
> Now, All you need to require rerun the project.

It works THANK YOU !!!!
I ran it by using `yarn ios` in ITerm2 but nothing shows and it just crashed.  I should run it in Xcode.

**Comment by shwangson** [comment]
> @coy102 Your solution is working properly. All we need to open Build Phases -> Copy Bundle Resources -> Click on '+' icon -> Click on 'Add Another' button.
> 
> Now select from 'node_modules/react-native-image-crop-picker/ios/QBImagePicker/QBImagePicker/QBImagePicker.storyboard'
> 
> Now, All you need to require rerun the project.

Thanks！It works for me！ But here's what happens: Multiple languages cannot display Chinese


![19391638087622_ pic](https://user-images.githubusercontent.com/74443185/143735057-1aba0db8-e049-4224-923d-ca209c394b80.jpg)

**Comment by Aakash359** [comment]
> i got the solutions, srry not updated this issue
> 
> add QBImagePicker.storyboard to Build Phases > Copy bundle Resources
> 
> ![WhatsApp Image 2020-01-22 at 5 19 26 PM](https://user-images.githubusercontent.com/13234170/73509201-e9bf1100-4410-11ea-97
<img width="1440" alt="Screenshot 2022-09-22 at 10 53 48 AM" src="https://user-images.githubusercontent.com/54428958/191667320-77a54c63-7651-4388-a9a0-2d30362e9959.png">
eb-1ff7c5f2b2af.jpeg)

i had tried your solution( copy the QBImagepicker.storyboard in bundle resources)  but it's not working can anyone let me know other solution or hack to fix thi
<img width="1440" alt="Screenshot 2022-09-22 at 11 15 16 AM" src="https://user-images.githubusercontent.com/54428958/191667616-d8123c95-a325-4a4f-b951-827c0e4dd4bb.png">
s issue

**Comment by PrakharTyagiDev** [comment]
@Aakash359 

> > i got the solutions, srry not updated this issue
> > add QBImagePicker.storyboard to Build Phases > Copy bundle Resources
> > ![WhatsApp Image 2020-01-22 at 5 19 26 PM](https://user-images.githubusercontent.com/13234170/73509201-e9bf1100-4410-11ea-97
> 
> <img alt="Screenshot 2022-09-22 at 10 53 48 AM" width="1440" src="https://user-images.githubusercontent.com/54428958/191667320-77a54c63-7651-4388-a9a0-2d30362e9959.png">
> 
> eb-1ff7c5f2b2af.jpeg)
> i had tried your solution( copy the QBImagepicker.storyboard in bundle resources) but it's not working can anyone let me know other solution or hack to fix this error. <img alt="Screenshot 2022-09-22 at 11 15 16 AM" width="1440" src="https://user-images.githubusercontent.com/54428958/191667616-d8123c95-a325-4a4f-b951-827c0e4dd4bb.png"> s issue

Have you found a solution for this error, I am also getting this same error.

**Comment by azrulhaifan** [comment]
> @Aakash359
> 
> > > i got the solutions, srry not updated this issue
> > > add QBImagePicker.storyboard to Build Phases > Copy bundle Resources
> > > ![WhatsApp Image 2020-01-22 at 5 19 26 PM](https://user-images.githubusercontent.com/13234170/73509201-e9bf1100-4410-11ea-97
> > 
> > 
> > <img alt="Screenshot 2022-09-22 at 10 53 48 AM" width="1440" src="https://user-images.githubusercontent.com/54428958/191667320-77a54c63-7651-4388-a9a0-2d30362e9959.png">
> > eb-1ff7c5f2b2af.jpeg)
> > i had tried your solution( copy the QBImagepicker.storyboard in bundle resources) but it's not working can anyone let me know other solution or hack to fix this error. <img alt="Screenshot 2022-09-22 at 11 15 16 AM" width="1440" src="https://user-images.githubusercontent.com/54428958/191667616-d8123c95-a325-4a4f-b951-827c0e4dd4bb.png"> s issue
> 
> Have you found a solution for this error, I am also getting this same error.

i've solved the issue by adding requestAnimationFrame to call my crop function

**Comment by LCseniordev** [comment]
> > @coy102 Your solution is working properly. All we need to open Build Phases -> Copy Bundle Resources -> Click on '+' icon -> Click on 'Add Another' button.
> > Now select from 'node_modules/react-native-image-crop-picker/ios/QBImagePicker/QBImagePicker/QBImagePicker.storyboard'
> > Now, All you need to require rerun the project.
> 
> Thanks！It works for me！ But here's what happens: Multiple languages cannot display Chinese
> 
> ![19391638087622_ pic](https://user-images.githubusercontent.com/74443185/143735057-1aba0db8-e049-4224-923d-ca209c394b80.jpg)

Hi, have you found a solution? Facing the same issue
Thanks!
