### ISSUE TITLE
Property 'sortOrder' not found on object of type 'QBImagePickerController

### ISSUE THREAD

**Issue by c-fitzmaurice** [ivpusic/react-native-image-crop-picker#1217]
### Version
- react-native-image-crop-picker v0.27.0
- react-native v0.61.5

### Platform
Tell us to which platform this issue is related

- iOS

### Actual behaviour

Building the application fails with `Property 'sortOrder' not found on object of type 'QBImagePickerController *'`

`ImageCropPicker.m`
`323: imagePickerController.sortOrder = [self.options objectForKey:@"sortOrder"];`

### Steps to reproduce

1. Install

2. Try to build the iOS Application

**Comment by JerakRus** [comment]
@c-fitzmaurice Hello! I have this problem too.  
Did you find a solution?

**Comment by ItsSinoan** [comment]
@JerakRus I had the same issue and the answer from #1101 worked for me.
You need to add 
`pod 'QBImagePickerController', :path => '../node_modules/react-native-image-crop-picker/ios/QBImagePicker/QBImagePickerController.podspec'`
To your podfile and run pod install.

Fixed the issue for me

**Comment by kitkline** [comment]
Does indeed fix the issue...In documentation: section Step 2
iOS it might be worth adding "and run pod install" AFTER the instruction to add Add following to your Podfile. That's what caught me out

**Comment by JerakRus** [comment]
@ItsSinoan @kitkline  Thx! 
I have been using the library for a long time, but I did not see that the installation method has changed
