### ISSUE TITLE
Property 'sortOrder' not found on object of type 'QBImagePickerController *'

### ISSUE THREAD

**Issue by nicomontanari** [ivpusic/react-native-image-crop-picker#1218]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.27.0
- react-native v0.61.5

### Platform
Tell us to which platform this issue is related
- iOS

### Expected behaviour
Application compiled correctly

### Actual behaviour
../node_modules/react-native-image-crop-picker/ios/src/ImageCropPicker.m:323:35: Property 'sortOrder' not found on object of type 'QBImagePickerController *'

### Steps to reproduce

Compile application

**Comment by KamranKhankhail** [comment]
adding following line in Podfile solved the problem for me 
`pod 'QBImagePickerController', :path => '../node_modules/react-native-image-crop-picker/ios/QBImagePicker/QBImagePickerController.podspec'`

as mentioned in the readme [here]((https://github.com/ivpusic/react-native-image-crop-picker#using-local-qbimagepicker)

**Comment by ivpusic** [comment]
@nicomontanari please use @KamranKhankhail suggestion
