### ISSUE TITLE
Not working on an iOS simulator

### ISSUE THREAD

**Issue by karlmarxlopez** [ivpusic/react-native-image-crop-picker#1227]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.28.0
- react-native v0.61.5

### Platform
Tell us to which platform this issue is related

- iOS

### Expected behaviour
.openPicker should work on simulator

### Actual behaviour
It is crashing on `Main.m` line 14.

### Steps to reproduce

1. Attach .openPicker to a button

2. Tap it, and it should crash.

**Comment by candy4290** [comment]
I have the same question

**Comment by Stringsaeed** [comment]
also crashes with physical devices

**Comment by candy4290** [comment]
insert these into Info.plist:
<key>NSPhotoLibraryUsageDescription</key>
<string>此 App 需要您的同意才能读取媒体资料库</string>

**Comment by karlmarxlopez** [comment]
@candy4290 I've already added an entry for that.

```
<key>NSPhotoLibraryUsageDescription</key>
<string>Upload fur baby photos and videos</string>
```

**Comment by karlmarxlopez** [comment]
@candy4290 I've already added an entry for that.

```
<key>NSPhotoLibraryUsageDescription</key>
<string>Some text here</string>
```

**Comment by candy4290** [comment]
You can run you project in xcode and it will tell you what's wrong

**Comment by Allyday** [comment]
I have the same error. Here's what's logged in my Xcode: 
`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Could not find a storyboard named 'QBImagePicker' in bundle NSBundle <userFolder>/Library/Developer/CoreSimulator/Devices/D0444D87-A1DD-4B27-A7E9-A29F911E6633/data/Containers/Bundle/Application/DCEC74B6-A5B1-4728-B3B0-0AB7B3FBDEE3/<projectName>.app> (loaded)'`

**Comment by karlmarxlopez** [comment]
> I have the same error. Here's what's logged in my Xcode:
> `*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Could not find a storyboard named 'QBImagePicker' in bundle NSBundle <userFolder>/Library/Developer/CoreSimulator/Devices/D0444D87-A1DD-4B27-A7E9-A29F911E6633/data/Containers/Bundle/Application/DCEC74B6-A5B1-4728-B3B0-0AB7B3FBDEE3/<projectName>.app> (loaded)'`

Try to add `QBImagePicker` manually on your `Pod.file`

**Comment by karlmarxlopez** [comment]
https://github.com/ivpusic/react-native-image-crop-picker/issues/1215#issuecomment-580561416
