### ISSUE TITLE
[iOS] Prop to disable video and only allow selecting images

### ISSUE THREAD

**Issue by negativetwelve** [ivpusic/react-native-image-crop-picker#123]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.10.1
- react-native v0.35.0

### Platform
Tell us to which platform this issue is related

- iOS
- Android

### Proposed PR

Right now we use this library to upload profile photos. Currently, users are allowed to select videos from the photo library, is there a way to disable that?

I found this in the iOS source https://github.com/ivpusic/react-native-image-crop-picker/blob/master/ios/ImageCropPicker.m#L211 which seems to set the type to image if cropping is true, however, I think that option should be independent.

It might make sense to expose the enum for selecting the type of image allowed.

If this is something you're open to, I would love to submit the PR for this!

### Steps to reproduce

1. Open photo library.

2. Select video even though you want a photo.

**Comment by ivpusic** [comment]
you can try using `smartAlbums` and skip 'Videos'. 

For now I have no plans doing this feature, but if `smartAlbums` doesn't work for you I would gladly discuss PR and accept it.
