### ISSUE TITLE
Error:         Attribute activity#com.yalantis.ucrop.UCropActivity@theme value=(@style/Theme.AppCompat.Light.NoActionBar) from [:react-native-image-crop-picker] 

### ISSUE THREAD

**Issue by whereiscode** [ivpusic/react-native-image-crop-picker#1230]
version:0.28.0
rn:0.60.5
android
----------------
iOS is ok, but android ...
-----------
Error:
        Attribute activity#com.yalantis.ucrop.UCropActivity@theme value=(@style/Theme.AppCompat.Light.NoActionBar) from [:react-native-image-crop-picker] AndroidManifest.xml:25:13-69
        is also present at [com.github.LuckSiege.PictureSelector:picture_library:v2.3.8] AndroidManifest.xml:36:13-58 value=(@style/Base.Theme.NoActionBar).
        Suggestion: add 'tools:replace="android:theme"' to <activity> element at AndroidManifest.xml:23:9-25:72 to override.

**Comment by ivpusic** [comment]
cannot reproduce this issue. please make sure that you followed installation steps from readme. you can also take a look into example project.

**Comment by puneetkansal04** [comment]
Geeting same errror, followed all the steps still getting error in android

**Comment by CrazyMan2** [comment]
我也遇到了同样的问题，不知道句问题在哪里

**Comment by CrazyMan2** [comment]
tools:replace="android:allowBackup,android:theme"

**Comment by yhbyOff** [comment]
same problem

**Comment by iamabdulhaseeb** [comment]
Any one solved this issue?

**Comment by aminmahrami** [comment]
This is still an issue. It happens when both this library and [react-native-image-crop-picker](https://github.com/ivpusic/react-native-image-crop-picker#readme) are installed at the same time @ivpusic

**Comment by kockok** [comment]
> This is still an issue. It happens when both this library and [react-native-multiple-image-picker](https://github.com/baronha/react-native-multiple-image-picker#readme) are installed at the same time @ivpusic


It's true, why close this issue?

**Comment by Bsingh2697** [comment]
> This is still an issue. It happens when both this library and [react-native-multiple-image-picker](https://github.com/baronha/react-native-multiple-image-picker#readme) are installed at the same time @ivpusic

Yes it worked Thanks
