### ISSUE TITLE
how to set video quality?

### ISSUE THREAD

**Issue by pyeonjaesik** [ivpusic/react-native-image-crop-picker#1235]
video which is picked with this api is too big. I want to compress video size. 
Can I set video quality to get low size?

**Comment by ivpusic** [comment]
you can use compressVideoPreset. check readme file

**Comment by aravi365** [comment]
@ivpusic  But that works only in ios. Is there anyway to limit the video to be choosen to a particular file size, for example 5MB.

**Comment by raindev32** [comment]
any sugestion ?

**Comment by emeagenciadigital** [comment]
+1
