### ISSUE TITLE
TypeScript Warning --React Native

### ISSUE THREAD

**Issue by ImAbhishekTomar** [ivpusic/react-native-image-crop-picker#1236]
Code is working what how can i resolve this path property issue?
![Screenshot 2020-02-25 at 04 29 41](https://user-images.githubusercontent.com/6933841/75198962-e3118880-5787-11ea-9696-567d0a2d20a6.png)

**Comment by dburdan** [comment]
This is a TypeScript typeguard issue. Since `image` can be an array (if multiple is true), the `path` variable might not exist. Try this:
```js
.then((image) => {
  if ('path' in image) {
    setPhoto(image.path);
  }
}
```
or, if you later allow multiple images:
```js
.then((image) => {
  if (Array.isArray(image)) {
    setPhoto(image[0].path);
  } else {
    setPhoto(image.path);
  }
}
```

**Comment by ImAbhishekTomar** [comment]
Thanks for the support.
