### ISSUE TITLE
In iOS return path dose not exist

### ISSUE THREAD

**Issue by GuiltyKirito** [ivpusic/react-native-image-crop-picker#1237]
In iOS, I use openCamera and set `mediaType: "video"` , When i rec video retrun me a path , but when i use  this path  , feedback me `Error: File does not exist at path`
path e.g. `file:///private/var/mobile/Containers/Data/Application/29181948-B5F9-4254-A817-5C9A4D757366/tmp/react-native-image-crop-picker/ABBA75F2-2D02-49BB-ACEB-47C6EA3ABB06.mp4`

**Comment by fattomhk** [comment]
In my case, I am uploading video with RNFetchBlob and i need to remove`file://`  of the path to get success

**Comment by ShepelievD** [comment]
@GuiltyKirito looks like you are using RNFetchBlob

**Comment by GuiltyKirito** [comment]
i use RNfs could fixed this question

**Comment by johnhalliwell78** [comment]
> 

Could u please help me which solution you did to solve this problem, I faced the same issue with photo type

**Comment by GuiltyKirito** [comment]
> > 
> 
> Could u please help me which solution you did to solve this problem, I faced the same issue with photo type

i choice RNfs plugin solution this question。
