### ISSUE TITLE
Cropped image doesn't correspond to a selected for cropping area if zoom was used

### ISSUE THREAD

**Issue by meteorra** [ivpusic/react-native-image-crop-picker#1240]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.28.0
- react-native v0.61.5

### Platform
Tell us to which platform this issue is related

- iOS
- Android

### Expected behaviour
Even if the picture was zoomed, the resulting cropped image should correspond to the area, selected for cropping.

### Actual behaviour
If the picture was first zoomed, the resulting cropped image doesn't correspond to the area, selected for cropping.

### Steps to reproduce

1. Select a picture

2. Zoom in & select for cropping an area in the middle (in the middle is required, because moving far from the middle doesn't give such an evident effect)

3. Crop the image & compare resulting image with area that was selected for cropping (see attached files)

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by meteorra** [comment]
![cropping-area](https://user-images.githubusercontent.com/29917962/75460111-19225880-5992-11ea-92b4-b3b6b1f89315.jpeg)
![result](https://user-images.githubusercontent.com/29917962/75460129-217a9380-5992-11ea-8d0c-e44ad481b707.png)

**Comment by Volekss** [comment]
Same here, how did you fix that?
