### ISSUE TITLE
Show counter instead of checkmark on selected items?

### ISSUE THREAD

**Issue by dzpt** [ivpusic/react-native-image-crop-picker#1244]
### Version
Any

- react-native-image-crop-picker v0.28.0
- react-native v0.61.x

### Platform
Tell us to which platform this issue is related

- iOS

### Expected behaviour
I wonder is there any way to show counter on selected items instead of blue checkmark?
like this:
https://cloud.githubusercontent.com/assets/4034956/15001931/254805de-119c-11e6-9f68-d815ccc712cd.gif
from BSImagePicker

### Actual behaviour
Show blue checkmark only

**Comment by ivpusic** [comment]
we use https://github.com/questbeat/QBImagePicker, and this is not possible with it currently

**Comment by dzpt** [comment]
@ivpusic hi, i already update QBImagePicker to support counter.
https://github.com/dzpt/QBImagePicker
if you would like to review i'm going to send the pull request
