### ISSUE TITLE
run on terminal with"react-native run-ios" , crashing at once

### ISSUE THREAD

**Issue by NewYoungPG** [ivpusic/react-native-image-crop-picker#1248]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.24.1
- react-native v0.59.6

### Platform
iOS 12.4 

 It is working fine using Xcode. But When I run on terminal with"react-native run-ios" , crashing at once，and I can't get any errors. How can I fix ? thanks

**Comment by daniel-sudz** [comment]
Just started encountering this aswell

**Comment by ivpusic** [comment]
cannot reproduce this issue. please make sure that you followed installation steps from readme

**Comment by VikasSahu** [comment]
@NewYoungPG - did you get any solution ?
