### ISSUE TITLE
Multiple language support 

### ISSUE THREAD

**Issue by springwq** [ivpusic/react-native-image-crop-picker#125]
Hi @ivpusic ,

Looks like the RSKImageCropper is supporting [multiple language ](https://github.com/ruslanskorb/RSKImageCropper/commit/933561fa73e40abb8a62efc959b1f9e447c3ad70), does react-native-image-crop-picker also has the multi language support ? This moment, when I am cropping image, the buttons only display English text.

**Comment by ivpusic** [comment]
right now no.

**Comment by tokinonagare** [comment]
if just change language follow system， in iOS，edit **info.plist** like:
	
`<key>CFBundleLocalizations</key>`
`<array>`
`	<string>en</string>`
`	<string>zh_CN</string>`
`</array>`

**Comment by springwq** [comment]
@tokinonagare Thanks! It works.

**Comment by tranvannhat** [comment]
in android? :( please support me

**Comment by zhoujinzong** [comment]
@tokinonagare Thanks very much!

**Comment by crcommons** [comment]
@ivpusic Is there support for this in android? Thanks!

**Comment by Arwantys** [comment]
> @springwq if just change language follow system， in iOS，edit **info.plist** like:
> 
> `<key>CFBundleLocalizations</key>`
> `<array>`
> ` <string>en</string>`
> ` <string>zh_CN</string>`
> `</array>`
> 
> [react-native-community/react-native-image-picker#150](https://github.com/react-native-community/react-native-image-picker/issues/150)

Don't work for me, I added the French language, I rebuild but nothing changes, I still have the writing in English, a solution?
