### ISSUE TITLE
RN 0.61.5. After installation android can not start-up. iOS is ok

### ISSUE THREAD

**Issue by Everynothing** [ivpusic/react-native-image-crop-picker#1250]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.28.0
- react-native v0.61.5

### Platform
Android

### Steps to reproduce

1.After installation android can not start-up  iOS is ok

2.

3.

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by ivpusic** [comment]
cannot reproduce this issue. please make sure that you followed installation steps from readme
