### ISSUE TITLE
framework not found RSKImageCropper

### ISSUE THREAD

**Issue by PeiQingNi** [ivpusic/react-native-image-crop-picker#1255]
### Version 
"react-native": "0.59.8",
"react-native-image-crop-picker": "^0.28.0"

### Platform
- iOS

### Actual behaviour
ld: framework not found RSKImageCropper
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### Steps to reproduce
I don't use cocoapod.
This is normal in Debug and Release mode.
When I configure a new pre-production environment in Configuration,recompile,i got this error.

### Attachments
Ld /Users/mac/Library/Developer/Xcode/DerivedData/MyApp-crkbwupotvepxxclhjlnlqhzgdmd/Build/Products/Dlocal-iphonesimulator/MyApp.app/MyApp normal x86_64 (in target: MyApp)
    cd /Users/mac/Desktop/MyApp/ios
    export IPHONEOS_DEPLOYMENT_TARGET=9.0
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.4.sdk -L/Users/mac/Library/Developer/Xcode/DerivedData/MyApp-crkbwupotvepxxclhjlnlqhzgdmd/Build/Products/Dlocal-iphonesimulator -L/Users/mac/Library/Developer/Xcode/DerivedData/MyApp-crkbwupotvepxxclhjlnlqhzgdmd/Build/Products/Release-iphonesimulator -L/Users/mac/Desktop/MyApp/ios/../node_modules/react-native-image-crop-picker/ios/RSKImageCropper -F/Users/mac/Library/Developer/Xcode/DerivedData/MyApp-crkbwupotvepxxclhjlnlqhzgdmd/Build/Products/Dlocal-iphonesimulator -filelist /Users/mac/Library/Developer/Xcode/DerivedData/MyApp-crkbwupotvepxxclhjlnlqhzgdmd/Build/Intermediates.noindex/MyApp.build/Dlocal-iphonesimulator/MyApp.build/Objects-normal/x86_64/MyApp.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -mios-simulator-version-min=9.0 -Xlinker -object_path_lto -Xlinker /Users/mac/Library/Developer/Xcode/DerivedData/MyApp-crkbwupotvepxxclhjlnlqhzgdmd/Build/Intermediates.noindex/MyApp.build/Dlocal-iphonesimulator/MyApp.build/Objects-normal/x86_64/MyApp_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -ObjC -lc++ -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/mac/Library/Developer/Xcode/DerivedData/MyApp-crkbwupotvepxxclhjlnlqhzgdmd/Build/Intermediates.noindex/MyApp.build/Dlocal-iphonesimulator/MyApp.build/MyApp.app-Simulated.xcent -framework JavaScriptCore -framework RSKImageCropper /Users/mac/Library/Developer/Xcode/DerivedData/MyApp-crkbwupotvepxxclhjlnlqhzgdmd/Build/Products/Release-iphonesimulator/libRCTBlob.a /Users/mac/Library/Developer/Xcode/DerivedData/MyApp-crkbwupotvepxxclhjlnlqhzgdmd/Build/Products/Release-iphonesimulator/libRCTAnimation.a /Users/mac/Library/Developer/Xcode/DerivedData/MyApp-crkbwupotvepxxclhjlnlqhzgdmd/Build/Products/Release-iphonesimulator/libReact.a /Users/mac/Library/Developer/Xcode/DerivedData/MyApp-crkbwupotvepxxclhjlnlqhzgdmd/Build/Products/Release-iphonesimulator/libRCTActionSheet.a /Users/mac/Library/Developer/Xcode/DerivedData/MyApp-crkbwupotvepxxclhjlnlqhzgdmd/Build/Products/Release-iphonesimulator/libRCTGeolocation.a /Users/mac/Library/Developer/Xcode/DerivedData/MyApp-crkbwupotvepxxclhjlnlqhzgdmd/Build/Products/Release-iphonesimulator/libRCTImage.a /Users/mac/Library/Developer/Xcode/DerivedData/MyApp-crkbwupotvepxxclhjlnlqhzgdmd/Build/Products/Release-iphonesimulator/libRCTLinking.a /Users/mac/Library/Developer/Xcode/DerivedData/MyApp-crkbwupotvepxxclhjlnlqhzgdmd/Build/Products/Release-iphonesimulator/libRCTNetwork.a /Users/mac/Library/Developer/Xcode/DerivedData/MyApp-crkbwupotvepxxclhjlnlqhzgdmd/Build/Products/Release-iphonesimulator/libRCTSettings.a /Users/mac/Library/Developer/Xcode/DerivedData/MyApp-crkbwupotvepxxclhjlnlqhzgdmd/Build/Products/Release-iphonesimulator/libRCTText.a /Users/mac/Library/Developer/Xcode/DerivedData/MyApp-crkbwupotvepxxclhjlnlqhzgdmd/Build/Products/Release-iphonesimulator/libRCTVibration.a /Users/mac/Library/Developer/Xcode/DerivedData/MyApp-crkbwupotvepxxclhjlnlqhzgdmd/Build/Products/Release-iphonesimulator/libRCTWebSocket.a -framework QBImagePicker -Xlinker -dependency_info -Xlinker /Users/mac/Library/Developer/Xcode/DerivedData/MyApp-crkbwupotvepxxclhjlnlqhzgdmd/Build/Intermediates.noindex/MyApp.build/Dlocal-iphonesimulator/MyApp.build/Objects-normal/x86_64/MyApp_dependency_info.dat -o /Users/mac/Library/Developer/Xcode/DerivedData/MyApp-crkbwupotvepxxclhjlnlqhzgdmd/Build/Products/Dlocal-iphonesimulator/MyApp.app/MyApp

ld: framework not found RSKImageCropper
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by ivpusic** [comment]
RSKImageCropper is not used anymore. please try latest version with TOCropViewController
