### ISSUE TITLE
can not display the selected photo on UI

### ISSUE THREAD

**Issue by gerard0315** [ivpusic/react-native-image-crop-picker#126]
the library is kinda awesome but I cant really display the selected photo using the return image path by setting the state of image source. react-native says 'Invalid props source' supplied to Image.
this is my Image component 
`<Image style = {styles.avatar} source = {this.state.avatarSource}/>`

and I set the image source in 
`ImagePicker.openPicker({
        width: 500,
        height: 500,
        cropping: true
      }).then(image => {
        console.log(image.path);
        this.setState({avatarSource: image.path});
      });`

**Comment by ivpusic** [comment]
check how image is set here https://github.com/ivpusic/react-native-image-crop-picker/blob/master/example/app.js. You have to provide uri key.
