### ISSUE TITLE
Cropping Videos

### ISSUE THREAD

**Issue by nica0012** [ivpusic/react-native-image-crop-picker#1266]
After installing this package to replace react-native-image-picker specifically for video cropping, it's sad to see it not here.

The description basically says video cropping and I can't see anything in the docs about it, unless maybe there's something I am missing?

If it doesn't already exist it would be absolutely amazing to add, react-native-video-processing, another great package I'm working with has video cropping functionality but no UI to support it (like the existing photo cropping component here) - maybe something to look into?

**Comment by ivpusic** [comment]
unfortunately this package does not support video cropping, and nowhere in the docs it says that :).
