### ISSUE TITLE
Is there a way to display picker while on camera view?

### ISSUE THREAD

**Issue by tae-at-speer** [ivpusic/react-native-image-crop-picker#1267]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.26.1
- react-native v0.62.0

### Platform
Tell us to which platform this issue is related

- iOS
- Android

### Expected behaviour
Want to display image picker while on camera view like the native camera view on both ios and android.

### Actual behaviour
Just display camera without picker

### Steps to reproduce

1.

2.

3.

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by metinaltinbas** [comment]
Would be great if there is functionality like that.

**Comment by ivpusic** [comment]
currently not possible
