### ISSUE TITLE
Need region prop in response when take multiple photos from gallery 

### ISSUE THREAD

**Issue by hanzoow** [ivpusic/react-native-image-crop-picker#1269]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.24.0
- react-native v0.59.9

### Platform
Tell us to which platform this issue is related

- iOS
- Android

When i use includeExif in Request Object, i got an object exif={SubSecTimeDigitized: null
Orientation: "0"
DateTimeDigitized: null
GPSProcessingMethod: null
Model: null
Make: null
ISOSpeedRatings: null
ImageWidth: "1080"
SubSecTime: null
GPSLongitude: null
ImageLength: "2220"
WhiteBalance: null
GPSTimeStamp: null
ExposureTime: null
FocalLength: null
GPSLatitudeRef: null
GPSDateStamp: null
GPSAltitudeRef: null
GPSLatitude: null
SubSecTimeOriginal: null
GPSLongitudeRef: null
DateTime: null
GPSAltitude: null
Flash: null
FNumber: null}
I need the region property include latitude, longitude from response. Can you please help send region property to response ?
Thank you

**Comment by hanzoow** [comment]
This is what i got from exif in iOS
![image](https://user-images.githubusercontent.com/44063254/79215960-95a3c480-7e76-11ea-8204-485bc9076f69.png)
but in android
![image](https://user-images.githubusercontent.com/44063254/79216064-c126af00-7e76-11ea-83f8-547960225f86.png)

**Comment by hanzoow** [comment]
I need the GPS object in android like iOS can get right there ? so can i modify your lib or hopefully u can handle this

**Comment by alexeyvax** [comment]
The same for me

**Comment by hanzoow** [comment]
@alexeyvax Thank you so much..............
