### ISSUE TITLE
Get original dimensions when cropping is set to true.

### ISSUE THREAD

**Issue by sankhadeeproy007** [ivpusic/react-native-image-crop-picker#127]
Hi, thanks for this component! I was trying to upload a photo and and then save it to my DB only if it has a minimum width/height of 375px. I also want the cropping functionality to be available with this component. However when I log the response, it shows a constant height and width of 200. I'll attach screenshots so that it is clear to you. When I set cropping to false, I get the real dimensions.
![screen shot 2016-11-04 at 4 35 01 pm](https://cloud.githubusercontent.com/assets/10998047/20011835/393e1edc-a2ad-11e6-927e-9938fa4bdd8a.png)
![screen shot 2016-11-04 at 4 34 34 pm](https://cloud.githubusercontent.com/assets/10998047/20011836/39435686-a2ad-11e6-8af0-9e2483196495.png)

**Comment by sankhadeeproy007** [comment]
And this is when cropping is set to false
![screen shot 2016-11-04 at 4 38 38 pm](https://cloud.githubusercontent.com/assets/10998047/20011855/4bb143e6-a2ad-11e6-949f-778c10ac5d63.png)
![screen shot 2016-11-04 at 4 38 29 pm](https://cloud.githubusercontent.com/assets/10998047/20011856/4bb23ce2-a2ad-11e6-8913-8f9acd8bf9b6.png)

**Comment by sankhadeeproy007** [comment]
I'm on react-native .33 and image-picker 10.1 if that helps.

**Comment by ivpusic** [comment]
you can specify width and height you want for result image. Check readme

**Comment by sankhadeeproy007** [comment]
@ivpusic What if the image is only 64 pixels and I resize it to 200? It won't look great I guess. So I was just wondering if I could reject the image straight away and ask the user for a different photo. So it'd be great if I could get the dimensions of the Image itself.

**Comment by ivpusic** [comment]
hmm, unfortunetly something like this is currently not supported :/

**Comment by sankhadeeproy007** [comment]
That's fine. Thanks anyways! @ivpusic Could you tell me if that is possible to achieve and if it is, how should I go about doing it? Or is there any way I can enable crop only after calculating the dimensions?

**Comment by ivpusic** [comment]
with current setup you cannot achieve this. Option would be to extend library in a way that it returns original dimensions of selected image, something like `originalWidth` and `originalHeight`. However currently I have no plans supporting this feature, but I would accept PR is you are willing to implement this for iOS and Android.
