### ISSUE TITLE
Neither Andorid nor Ios builds

### ISSUE THREAD

**Issue by fredyonge** [ivpusic/react-native-image-crop-picker#1270]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker latest
- react-native latest

### Platform
Tell us to which platform this issue is related

- iOS
- Android

### Actual behaviour
> Task :react-native-image-crop-picker:javaPreCompileDebug FAILED

He is doing this for roughly 4 minutes
<============-> 98% EXECUTING [2m 48s]
> Transforming artifact ucrop-2.2.2-native.aar (com.github.yalantis:ucrop:2.2.2-native) with JetifyTransform > ucrop-2.
> Transforming artifact ucrop-2.2.2-native.aar (com.github.yalantis:ucrop:2.2.2-native) with JetifyTransform

### Steps to reproduce

1. Install

2. Exceute

3.Cry

### Attachments

AWS Amplify installed
// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by ivpusic** [comment]
cannot reproduce this issue. please make sure that you followed installation steps from readme
