### ISSUE TITLE
'React/RCTImageURLLoader.h' file not found

### ISSUE THREAD

**Issue by batosai** [ivpusic/react-native-image-crop-picker#1274]
### Version

- react-native-image-crop-picker v0.28.0
- react-native v0.62.0

### Platform

- iOS

### Steps to reproduce

1. pod install
2. clean xcode
3. build xcode

Reproduct in :

- react-native-image-crop-picker v0.27.0/v0.26.0
- react-native v0.61.5

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by ivpusic** [comment]
cannot reproduce this issue. please make sure that you followed installation steps from readme
