### ISSUE TITLE
[android 10] open failed: EACCES (Permission denied) 

### ISSUE THREAD

**Issue by vantuan88291** [ivpusic/react-native-image-crop-picker#1277]
when using compressImageQuality or cropping: true at config, android 10 fail. please fix it

**Comment by ivpusic** [comment]
please try https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.29.0

**Comment by L-Thirunavukkarasu** [comment]
@vantuan88291 try read this article and try...i fixed this issue to following below article..

link : https://medium.com/@sriramaripirala/android-10-open-failed-eacces-permission-denied-da8b630a89df

Thanks.
