### ISSUE TITLE
video compression on android like facebook, whastsapp, instagram

### ISSUE THREAD

**Issue by luigbren** [ivpusic/react-native-image-crop-picker#1279]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.?.?
- react-native v0.?.?

### Platform
Tell us to which platform this issue is related

- Android

video compression on android?? like facebook, whastsapp, instagram...

i'm uploading mp4 files recorded with my camera and they all exceed 30 mb, some way to compress the quality of the video on android? like facebook, whatsapp and instagram does when publishing videos

**Comment by ivpusic** [comment]
this is missing currently. if you have some time to send a PR, would gladly accept it

**Comment by ar0692** [comment]
I have done it in fork https://github.com/ar0692/react-native-image-crop-picker

For any type of help you can reach-out to me on https://www.mobileexperthelp.com

**Comment by AlkanV** [comment]
@ivpusic is there any way to merge what @ar0692 have done in his fork?

**Comment by kuls14** [comment]
I need video compression for android, Is there anything that can be done? like merging @ar0692 work in this repo ?

**Comment by SherifSamir5** [comment]
any updates for this issue? is it still missing
