### ISSUE TITLE
Crop header inactive

### ISSUE THREAD

**Issue by tapz** [ivpusic/react-native-image-crop-picker#1285]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.30.0
- react-native v0.62.2

### Platform
Tell us to which platform this issue is related

- Android

Samsung Galaxy S8+, Android 9

### Expected behaviour

Toolbar and cancel/accept buttons not darkened

### Actual behaviour

Toolbar darkened

### Steps to reproduce

1. Select image from gallery

### Attachments

![screencap](https://user-images.githubusercontent.com/11726387/80955472-0b60d780-8e08-11ea-8a2d-00d64b9a4893.png)

**Comment by ivpusic** [comment]
this is UI from ucrop (https://github.com/Yalantis/uCrop)

**Comment by tapz** [comment]
Right, I'll move the issue there.
