### ISSUE TITLE
Android Gallery issue

### ISSUE THREAD

**Issue by JeanB762** [ivpusic/react-native-image-crop-picker#1286]
### Version
- react-native-image-crop-picker@^0.28.0:
- react-native: 0.61.5

### Platform
- Android

### Expected behaviour
Be able to select multiple pictures from Android native gallery, but it's don't work.

### Actual behaviour
When the function is called, it's open a file explorer on Android, and the multiple select works well, but if I choose the native gallery from Android, the long press don't work, and becomes impossible to select more than one picture. It's a problem with android native gallery or has any solution to this issue?

### Steps to reproduce

1. Call the function with "multiple: true;"

2. Choose "from Gallery", on android

3. The multiple selection don't work

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by ivpusic** [comment]
behaviour is dependent on stock gallery, which in this case seems not to support multiple image picking
