### ISSUE TITLE
Croping is not desireable and quality is very low

### ISSUE THREAD

**Issue by AahilShahzad** [ivpusic/react-native-image-crop-picker#1289]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker: ^0.30.0
- react-native: 0.61.3

### Platform
Tell us to which platform this issue is related

- iOS
- Android

### Expected behaviour

https://github.com/ivpusic/react-native-image-crop-picker/blob/master/images/ios_normal_crop.png?raw=true

need like this cropper in this image

### Actual behaviour

cropped image quality is very low 

### Steps to reproduce

1.

2.

3.

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by ivpusic** [comment]
install version v0.31.1 for cropped like on reference image. for better quality increase value of width/height options

**Comment by AahilShahzad** [comment]
> install version v0.31.1 for cropper like on reference image. for better quality increase value of width/height options

thank you for your response 
let me try

**Comment by itvignes09** [comment]
@ivan-magda  I tried the v0.31.1 but still image quality is poor in iOS

**Comment by itvignes09** [comment]
After reading some guy on a different bug ticket, and reading the docs... it says you need to set height and width. It's used for the cropping option as the final resolution. Depending on how high you set it there, the better the quality after cropping.

**Comment by AahilShahzad** [comment]
> install version v0.31.1 for cropper like on reference image. for better quality increase value of width/height options

thanks to you it's really helpful

**Comment by tuledev** [comment]
In my case, increasing width and height solved the issue on Android

**Comment by bychung** [comment]
If you use ReactNative.Image to show the image, it would be helpful for using resizeMethod={'scale'} property.
It's not the problem of the picker, but of the ReactNative.Image.
