### ISSUE TITLE
File type?

### ISSUE THREAD

**Issue by tonygriv** [ivpusic/react-native-image-crop-picker#129]
### Version
- react-native-image-crop-picker v0.9.7
- react-native v0.34.1

### Platform
- Android

Hi. Maybe here somebody could help me. I need to download multiple files from react native app throw relayjs mutation. Files array after use this lib looks like:

```
[
    {uri: 'file:///path/to/file.jpg', mime: 'image/jpg'},
    {uri: 'file:///path/to/file2.jpg', mime: 'image/jpg'},
]
```

I founded in the doc function getFiles() https://facebook.github.io/relay/docs/api-reference-relay-mutation.html#getfiles

What is File type in react-native?

**Comment by ivpusic** [comment]
sorry but currently I have no knowledge of relay.

**Comment by tonygriv** [comment]
May be you know about File type in react-native?

**Comment by tonygriv** [comment]
For people, who struggle

http://stackoverflow.com/questions/40201274/getfiles-in-react-native-with-relayjs-mutations
