### ISSUE TITLE
Circle crop, causes image to show circle only. Cropped part is white.

### ISSUE THREAD

**Issue by bvelasquez** [ivpusic/react-native-image-crop-picker#1290]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.31.1
- react-native v0.62.2

### Platform
Tell us to which platform this issue is related

- iOS
- Android

### Expected behaviour

Create a cropped square image given the width and height.

### Actual behaviour

![b4c7df49-c41d-11e3-a732-00142273155d](https://user-images.githubusercontent.com/2302210/81758732-85800480-9477-11ea-8bb2-4cb619461dc0.png)

Image is cropped as a square image, but with only a circle with the original image, rest is white background. It used to produce a square image without the white mask in the background.

### Steps to reproduce

1. use openPicker to crop an image with cropping: true, and cropperCircleOverlay: true.

2. 

3.

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by tastafur** [comment]
In my version in Android circle not crop

**Comment by joshjens** [comment]
same issue here, expect a circular crop mask to still produce a square image. Adding the white frame matte can result in weirdness when using a borderRadius on a view to crop on display

**Comment by skizzo** [comment]
+1, I'd also expect that `cropperCircleOverlay={true}` doesn't actually remove the content on the edges. Is there a way to achieve that? Thanks!

**Comment by jcharbo** [comment]
Simply remove this method from imagecroppicker.m and you will get back a square.
`- (void)cropViewController:(TOCropViewController *)cropViewController didCropToCircularImage:(UIImage *)image withRect:(CGRect)cropRect angle:(NSInteger)angle {
    [self imageCropViewController:cropViewController didCropImage:image usingCropRect:cropRect];
}`

**Comment by ivpusic** [comment]
fixed in https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.33.0

**Comment by skizzo** [comment]
Amazing, thank you!
