### ISSUE TITLE
sourceURL is always null in ios

### ISSUE THREAD

**Issue by Rishabh-spec** [ivpusic/react-native-image-crop-picker#1293]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.31.1
- react-native v0.61.3

### Platform
Tell us to which platform this issue is related

- iOS

### Expected behaviour
sourceURL can not be null

### Actual behaviour
sourceURL getting null in ios

### Steps to reproduce

1. Open Image Picker

2. Select Multiple image

3. Click Done 

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by Jackychen8** [comment]
Same thing is happening for me now. It had worked as recently as June 14th, 2020 though. I had only started working with this library a few days before that.

**Comment by hengkx** [comment]
how to resolve?

**Comment by hengkx** [comment]
https://stackoverflow.com/questions/57202965/phimageresultisdegradedkey-phimagefileurlkey-is-not-found

**Comment by hengkx** [comment]
#1130

**Comment by ivpusic** [comment]
fixed in https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.33.3
