### ISSUE TITLE
SAMSUNG SM-G5500 - 5.1.1 Can not open camera .

### ISSUE THREAD

**Issue by sharingjingang050241** [ivpusic/react-native-image-crop-picker#130]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v^0.10.2
- react-native v0.36.0

### Platform
SAMSUNG  SM-G5500 - 5.1.1

- Android

Can not open camera .

![365395f96e03053538a1923209584228](https://cloud.githubusercontent.com/assets/20335157/20093914/de978d94-a5d9-11e6-80ae-08d6042653d4.jpg)

**Comment by ivpusic** [comment]
can you please try installing version v0.10.1? In latest version we introduce one change which may be the reason why this is happening

**Comment by sharingjingang050241** [comment]
Thanks ,its solved ,I close issue by myself.

**Comment by ivpusic** [comment]
@sharingjingang050241 it is solved by downgrade or something else?

**Comment by sharingjingang050241** [comment]
yeah,it is solved by downgrade.
