### ISSUE TITLE
Support for native "Take Photo" or "Choose from Library"prompt?

### ISSUE THREAD

**Issue by dquessenberry** [ivpusic/react-native-image-crop-picker#1302]
### Version
- react-native-image-crop-picker v0.31.1
- react-native v0.62.2

### Platform
- iOS
- Android

### Expected behaviour
I would like to present the user with an option of either taking a photo or choosing from their photo library. This is the same default feature in the [react-native-image-picker](https://github.com/react-native-community/react-native-image-picker). I can create my own components to simulate this native prompt, but I'm curious is this library has something like that built into it. Example:

|         iOS         |      Android     |
| ------------- | ------------- |
|  ![iOS Prompt](https://raw.githubusercontent.com/react-native-community/react-native-image-picker/master/images/ios-image.png)  |  ![Android prompt](https://raw.githubusercontent.com/react-native-community/react-native-image-picker/master/images/android-image.png) |

### Actual behaviour
No prompt option. Must code to either open the camera or open the library.

**Comment by dquessenberry** [comment]
Just realized that RN offers something called ActionSheetIOS, which accomplishes the same prompt. Anyone know the proper type of prompt component for Android?

**Comment by cesar3030** [comment]
Hi @dquessenberry !

I was running into the same issue and I ended up using this library: https://github.com/expo/react-native-action-sheet.
It has the exact same API as ActionSheetIOS so the switch was really easy.

Hope this helps

**Comment by MOwais** [comment]
I need the same for both Android and iOS. I ended up creating my own custom prompt identical to the native Android prompt but dont want to do the same for iOS...
