### ISSUE TITLE
freeStyleCropEnabled in iOS

### ISSUE THREAD

**Issue by victorwpbastos** [ivpusic/react-native-image-crop-picker#1308]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.26.1
- react-native v0.62.2

### Platform
Tell us to which platform this issue is related

- iOS

### Expected behaviour

iOS should enable free crop.

### Actual behaviour

Only Android respect the `freeStyleCropEnabled` property.

**Comment by victorwpbastos** [comment]
My bad. I didn't realize that last version already has `freeStyleCropEnabled` support for iOS too. Thanks!

**Comment by s4sebin** [comment]
So can I use "freeStyleCropEnabled: false" to keep the aspect ratio?

**Comment by ychekan** [comment]
Pls, fix everything in the documentation)) Thx, freeStyleCropEnabled - work for me too.

**Comment by sandeepg1220** [comment]
How to set default to original while capture the image from camera. Currently it's showing as a square default.

**Comment by nabilfreeman** [comment]
@sandeepg1220 I managed to achieve this by patching `ImageCropPicker.m`.

```patch
diff --git a/node_modules/react-native-image-crop-picker/ios/src/ImageCropPicker.m b/node_modules/react-native-image-crop-picker/ios/src/ImageCropPicker.m
index 7101410..f597206 100644
--- a/node_modules/react-native-image-crop-picker/ios/src/ImageCropPicker.m
+++ b/node_modules/react-native-image-crop-picker/ios/src/ImageCropPicker.m
@@ -58,9 +58,9 @@ RCT_EXPORT_MODULE();
             @"compressVideo": @YES,
             @"minFiles": @1,
             @"maxFiles": @5,
-            @"width": @200,
+            @"width": @2000,
             @"waitAnimationEnd": @YES,
-            @"height": @200,
+            @"height": @2000,
             @"useFrontCamera": @NO,
             @"avoidEmptySpaceAroundImage": @YES,
             @"compressImageQuality": @0.8,
@@ -72,7 +72,8 @@ RCT_EXPORT_MODULE();
             @"sortOrder": @"none",
             @"cropperCancelText": @"Cancel",
             @"cropperChooseText": @"Choose",
-            @"cropperRotateButtonsHidden": @NO
+            @"cropperRotateButtonsHidden": @NO,
+            @"originalAspectRatio": @NO
         };
         self.compression = [[Compression alloc] init];
     }
@@ -874,13 +875,17 @@ RCT_EXPORT_METHOD(openCropper:(NSDictionary *)options
             cropVC = [[TOCropViewController alloc] initWithCroppingStyle:TOCropViewCroppingStyleCircular image:image];
         } else {
             cropVC = [[TOCropViewController alloc] initWithImage:image];
-            CGFloat widthRatio = [[self.options objectForKey:@"width"] floatValue];
-            CGFloat heightRatio = [[self.options objectForKey:@"height"] floatValue];
-            if (widthRatio > 0 && heightRatio > 0){
-                CGSize aspectRatio = CGSizeMake(widthRatio, heightRatio);
-                cropVC.customAspectRatio = aspectRatio;
             
+            if(![[[self options] objectForKey:@"originalAspectRatio"] boolValue]) {
+                CGFloat widthRatio = [[self.options objectForKey:@"width"] floatValue];
+                CGFloat heightRatio = [[self.options objectForKey:@"height"] floatValue];
+                if (widthRatio > 0 && heightRatio > 0){
+                    CGSize aspectRatio = CGSizeMake(widthRatio, heightRatio);
+                    cropVC.customAspectRatio = aspectRatio;
+                    
+                }
             }
+            
             cropVC.aspectRatioLockEnabled = ![[self.options objectForKey:@"freeStyleCropEnabled"] boolValue];
             cropVC.resetAspectRatioEnabled = !cropVC.aspectRatioLockEnabled;
         }
```

I added a new option called `originalAspectRatio: true` which you can pass into options. This will disable the cropper defaulting to the width/height you specified.

The image will be resized to fit within the boundaries you specify (or 2000x2000) if no width or height is set but keep its original / adjusted manually ratio.

And yes, I had to patch the default width and height on iOS. Tiny value of 200 is just dumb.

**Comment by Maker-Mark** [comment]
Here's a complete example patch file to fix this issue for iOS, thanks @nabilfreeman for the fix above. I just added the typing into the patch too.

How to use:
- Create and add this file to the root of your repo: `patches/`
- add `"postinstall": "patch-package",` to your package.json inside `scripts`
- add `patch-package` to your `dependacies` (`npm i patch-package` or yarn add `patch package`)
- Reinstall dependancies(`npm i` or `yarn`) and the patch will run after the install 
- Now the default will be the entire image (as long as you dont have a screen larger than 2000x2000 px heh
[react-native-image-crop-picker+0.38.1.patch](https://github.com/ivpusic/react-native-image-crop-picker/files/10698808/react-native-image-crop-picker%2B0.38.1.patch)

**Comment by Maker-Mark** [comment]
@ivpusic Is there someone that can get this fix in a PR? This is an issue a lot of people are having, thanks 🙏

**Comment by Lakshyakatarmal** [comment]
any update on the PR? is this fixed? @ivpusic

**Comment by Lakshyakatarmal** [comment]
> @sandeepg1220 I managed to achieve this by patching `ImageCropPicker.m`.
> 
> ```diff
> diff --git a/node_modules/react-native-image-crop-picker/ios/src/ImageCropPicker.m b/node_modules/react-native-image-crop-picker/ios/src/ImageCropPicker.m
> index 7101410..f597206 100644
> --- a/node_modules/react-native-image-crop-picker/ios/src/ImageCropPicker.m
> +++ b/node_modules/react-native-image-crop-picker/ios/src/ImageCropPicker.m
> @@ -58,9 +58,9 @@ RCT_EXPORT_MODULE();
>              @"compressVideo": @YES,
>              @"minFiles": @1,
>              @"maxFiles": @5,
> -            @"width": @200,
> +            @"width": @2000,
>              @"waitAnimationEnd": @YES,
> -            @"height": @200,
> +            @"height": @2000,
>              @"useFrontCamera": @NO,
>              @"avoidEmptySpaceAroundImage": @YES,
>              @"compressImageQuality": @0.8,
> @@ -72,7 +72,8 @@ RCT_EXPORT_MODULE();
>              @"sortOrder": @"none",
>              @"cropperCancelText": @"Cancel",
>              @"cropperChooseText": @"Choose",
> -            @"cropperRotateButtonsHidden": @NO
> +            @"cropperRotateButtonsHidden": @NO,
> +            @"originalAspectRatio": @NO
>          };
>          self.compression = [[Compression alloc] init];
>      }
> @@ -874,13 +875,17 @@ RCT_EXPORT_METHOD(openCropper:(NSDictionary *)options
>              cropVC = [[TOCropViewController alloc] initWithCroppingStyle:TOCropViewCroppingStyleCircular image:image];
>          } else {
>              cropVC = [[TOCropViewController alloc] initWithImage:image];
> -            CGFloat widthRatio = [[self.options objectForKey:@"width"] floatValue];
> -            CGFloat heightRatio = [[self.options objectForKey:@"height"] floatValue];
> -            if (widthRatio > 0 && heightRatio > 0){
> -                CGSize aspectRatio = CGSizeMake(widthRatio, heightRatio);
> -                cropVC.customAspectRatio = aspectRatio;
>              
> +            if(![[[self options] objectForKey:@"originalAspectRatio"] boolValue]) {
> +                CGFloat widthRatio = [[self.options objectForKey:@"width"] floatValue];
> +                CGFloat heightRatio = [[self.options objectForKey:@"height"] floatValue];
> +                if (widthRatio > 0 && heightRatio > 0){
> +                    CGSize aspectRatio = CGSizeMake(widthRatio, heightRatio);
> +                    cropVC.customAspectRatio = aspectRatio;
> +                    
> +                }
>              }
> +            
>              cropVC.aspectRatioLockEnabled = ![[self.options objectForKey:@"freeStyleCropEnabled"] boolValue];
>              cropVC.resetAspectRatioEnabled = !cropVC.aspectRatioLockEnabled;
>          }
> ```
> 
> I added a new option called `originalAspectRatio: true` which you can pass into options. This will disable the cropper defaulting to the width/height you specified.
> 
> The image will be resized to fit within the boundaries you specify (or 2000x2000) if no width or height is set but keep its original / adjusted manually ratio.
> 
> And yes, I had to patch the default width and height on iOS. Tiny value of 200 is just dumb.




any update for android?
