### ISSUE TITLE
When I uploaded the image on Android, it returned istrusted: false, but everything was fine on ios

### ISSUE THREAD

**Issue by jimmywong123** [ivpusic/react-native-image-crop-picker#1311]
The code works fine on ios, but on android it just return {istrusted: false},  seems like the network request is not sent.

i use XMLHttpRequest to upload the selected file, use FormData to load them.

I don't know where this error comes from, it may be a cross-domain problem, or Android access permissions, or back-end api problems.

here is my code
```const parts = file.path.split('/');
      const fileName = parts[parts.length - 1];
      upload({
        action: 'https://uploadurl,
        filename: fileName,
        file: {
          uri: file.path,
          type: file.mime,
          name: fileName,
          // size: file.size
        },
        data: { token },
        headers: { 'Content-Type': "multipart/form-data" },
        onProgress: e => {
          this.setState({ visible: true, percent: e.percent })
        },
        onSuccess: res => {
          this.setState({ visible: false, percent: 0 });
          if(onSuccessAfter) {
            onSuccessAfter({
              title: file.filename,
              url: `${origin}/${res.key}`,
              uuid: ' ',
            })
          }
        },
        onError: err => {
          console.log('err>>>', err);
        },
      });
```

### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.28.0
- react-native v0.62.1

### Platform
Tell us to which platform this issue is related

- Android

### Expected behaviour
upload file

### Actual behaviour
it just return {istrusted: false}, nothing else.

**Comment by jimmywong123** [comment]
I found a solution on this link, the final code is as follows.
[https://github.com/facebook/react-native/issues/12903#issuecomment-411447062](url)
```
ImagePicker.openPicker({
      // cropping: true
      // mediaType: "video",
    }).then(file => {
      if(this.beforeUpload(file)) {
        const arr = file.path.split('/');
        const filename = arr[arr.length - 1];
        RNFetchBlob.fetch('POST', 'https://uploadurl', {
          'Content-Type' : 'multipart/form-data',
        }, [
          { name : 'file', filename, type: file.mime, data: RNFetchBlob.wrap(file.path)},
          { name : 'token', data: token},
        ]).uploadProgress((written, total) => {
          this.setState({ visible: true, percent: written / total });
        }).then(({ data }) => {
          this.setState({ visible: false, percent: 0 });
          if(onSuccessAfter) {
            onSuccessAfter({
              title: filename,
              url: `${origin}/${JSON.parse(data).key}`,
              uuid: ' ',
            })
          }
        }).catch((err) => {
          console.log('err',err);
        })
      }
    });
```

**Comment by martinatti** [comment]
Hey @jimmywong123, could you explain what was happen with your code.
I'm facing the same issue. It's OK on iOS, but Android return error and the message {istrusted: false}.
I'm using XMLHttpRequest to upload a file.

`
async futch(url, opts, onProgress) {

    return new Promise( (res, rej)=>{

        var xhr = new XMLHttpRequest();
        xhr.open('post', url);
        xhr.setRequestHeader( 'Content-Type',   'multipart/form-data' );
        xhr.setRequestHeader('Authorization', 'Bearer ' + this.props.superToken);

        //for (var k in opts.headers||{}) xhr.setRequestHeader(k, opts.headers[k]);

        xhr.onload = e => res(e.target);

        xhr.onerror = rej;

        if (xhr.upload && onProgress)
            xhr.upload.onprogress = onProgress;

        xhr.send(opts);

    });
`

**Comment by ggchicote** [comment]
@martinatti did u finally find the solution?

**Comment by redexp** [comment]
Check your `file.uri`. My problem was that I expected that `uri` will be in format `/path/to/file` that's why I added `file://`. But now `uri` comes in format `content://..` and I don't need that `file://` any more.

**Comment by mohamedsl22** [comment]
just remove headers: { 'Content-Type': "multipart/form-data" },

**Comment by camboYY** [comment]
it does not work

**Comment by yeoung004** [comment]
> just delete the line: headers: { 'Content-Type': "multipart/form-data" },

YOU'RE MY SAVIOR
