### ISSUE TITLE
Toolbar title color

### ISSUE THREAD

**Issue by Miraj98** [ivpusic/react-native-image-crop-picker#1315]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.32.0?
- react-native v0.61.2

### Platform
- Android

### Expected behaviour

Be able to change cropper toolbar title's color. 

### Actual behaviour

Default toolbar title color is black and there is no way to change that

**Comment by ivpusic** [comment]
can you provide code sample which does not work for you?

**Comment by Miraj98** [comment]
```
await ImagePicker.openCropper({
        path,
        freeStyleCropEnabled: true,
        cropperToolbarColor: '#000000',
        cropperStatusBarColor: '#000000',
        hideBottomControls: true,
        cropping: true,
});
```

Here the Toolbar color is set to black and with that I want to  set the toolbar title color to white (Default text color is black). But I think thats not possible right now because there is no option like `cropperToolbarTitleColor` or something.

**Comment by DevanshaniR** [comment]
I have experienced the same issue
