### ISSUE TITLE
null is not an object (evaluating 'imagepickermanager showimagepicker)

### ISSUE THREAD

**Issue by sureshhallyali** [ivpusic/react-native-image-crop-picker#1327]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.?.?
->>>>>^0.32.0

- react-native v0.?.?
 ->>>>"react-native": "~0.62.2",

### Platform
Tell us to which platform this issue is related

- iOS
- Android

### Expected behaviour
open galay or pop for selecting image

### Steps to reproduce

1.

2.

3.

### Attachments
![WhatsApp Image 2020-06-29 at 1 02 29 AM](https://user-images.githubusercontent.com/57383836/85957312-f3da4100-b9a9-11ea-8f55-c7d6d5c9c1ff.jpeg)

> 

- [ ]  #``

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

> 

> 

1.

**Comment by vikastechment** [comment]
Hi @sureshhallyali 
did you find any solution for the same?

**Comment by VikasSahu** [comment]
@sureshhallyali  did you run command pod install, I was getting same error because due to some reason pod was not installed.

**Comment by sureshhallyali** [comment]
yes solved, if you are running on ios platform then  you must open folder ios  in xcode  else in android studio open folder "android->build.gradle"  because   to build file and  You need to give permission   in android
path -> /android/app/src/main/ AndroidManifest.xml

<uses-permission android:name="android.permission.INTERNET"/>
<uses-permission android:name="android.permission.CAMERA"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
for ios search in google

**Comment by sureshhallyali** [comment]
> yes solved, if you are running on ios platform then you must open folder ios in xcode else in android studio open folder "android->build.gradle" because to build file and You need to give permission in android
> path -> /android/app/src/main/ AndroidManifest.xml
> 
> for ios search in google

**Comment by 99percent6** [comment]
> yes solved, if you are running on ios platform then you must open folder ios in xcode else in android studio open folder "android->build.gradle" because to build file and You need to give permission in android
> path -> /android/app/src/main/ AndroidManifest.xml
> 
> for ios search in google

Hi, can you give more details how you solved the problem for iOS? Maybe some links .

**Comment by sureshhallyali** [comment]
Ok ,go throw this video  https://youtu.be/ts9AM790NPQ

**Comment by 99percent6** [comment]
> Ok ,go throw this video https://youtu.be/ts9AM790NPQ

Thanks
