### ISSUE TITLE
Missing video duration field

### ISSUE THREAD

**Issue by Adigezalov** [ivpusic/react-native-image-crop-picker#1328]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.32.0
- react-native v0.61.4

### Platform
Tell us to which platform this issue is related

- iOS
- Android

There is no video duration in the response object after selecting a video

**Comment by ivpusic** [comment]
available in version https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.32.2
