### ISSUE TITLE
Poor/bad image quality after cropping

### ISSUE THREAD

**Issue by Tobinho7** [ivpusic/react-native-image-crop-picker#1336]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.32.2
- react-native v0.61.5

### Platform
Tell us to which platform this issue is related

- Android

### Expected behaviour
I set a fix height and width (getting from Device dimensions) in openPicker and set cropping to true. Same height and width in Image Element. After cropping, the image quality should still be good. 

### Actual behaviour
After cropping, the image quality is very bad. 

### Steps to reproduce

let window = Dimensions.get("window");
const imageWidth = window.width;
const imageHeight = (window.height/3);

ImagePickerCrop.openPicker({
          width: imageWidth,
          height: imageHeight,
          compressImageMaxWidth: imageWidth,
          compressImageMaxHeight: imageHeight,
          cropping: true,
          includeBase64: true,
          showCropGuidelines: false,
          showCropFrame: true,
          compressImageQuality: 1.0,
          outMimeType:"image/png",
        }).then(image => {
           this.setState({ photo: image })
           RNFetchBlob.fs.readFile(this.state.photo.path, 'base64')
        });

            <Image
                source={{ uri: photo.path }}
                style={{width: imageWidth, height: imageHeight }}
            />

### Attachments

![Before cropping](https://user-images.githubusercontent.com/50517494/87173665-674b4f00-c2d6-11ea-8f17-3054b2314e99.jpg)
![After cropping](https://user-images.githubusercontent.com/50517494/87173695-7205e400-c2d6-11ea-9946-8515e36563fe.jpg)

I've already tried many suggestions. However, none of them work for me. Has anyone else this issue?

**Comment by Jackychen8** [comment]
Yes, same issue here. The file size is way smaller (and image quality is way lower) after cropping on iOS. I was previously avoiding this issue by taking the cropRect and the sourceURL but now I'm getting sourceURL = null.

Expo's Image Picker also yields a similarly smaller image on iOS after cropping and I had swapped that out for this in order to get around it with the strategy above. Now, that is impossible with a null sourceURL.

**Comment by Tobinho7** [comment]
Hi Jackychen8, thank you. I will try the expo-image-picker on Android today and I will give feedback if it works 👍

**Comment by SunskyXH** [comment]
Same issue here, and I try to multiply my given width/height by `PixelRatio.get()` and it works.

**Comment by Tobinho7** [comment]
Expo image picker works fine and the photo quality is good.

**Comment by Hunt-David** [comment]
This is still an issue with this particular package, I think this issue should be reopened.

**Comment by ar0692** [comment]
yes I am facing same issue , this issue should be fix

**Comment by ar0692** [comment]
> Same issue here, and I try to multiply my given width/height by `PixelRatio.get()` and it works.



> Same issue here, and I try to multiply my given width/height by `PixelRatio.get()` and it works.

@SunskyXH  could you please share code snapshot for your fix

**Comment by Hunt-David** [comment]
Created a new issue here https://github.com/ivpusic/react-native-image-crop-picker/issues/1356

**Comment by bmabsout** [comment]
I think the problem is on ios the quality is /100 meaning you want to set it to 80

**Comment by zaheradev** [comment]
I believe they divide by 100 on ios at least meaning you might need to set the quality to 80 not 0.8
