### ISSUE TITLE
Android crash after choosing picture from gallery or making camera photo (Android API 28)

### ISSUE THREAD

**Issue by Luckygirlllll** [ivpusic/react-native-image-crop-picker#1340]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.32.2
- react-native v0.61.4

### Platform
Tell us to which platform this issue is related

- Android

### Expected behaviour

App doesn't crash 

### Actual behaviour

App crash

### Steps to reproduce
```
chooseFromGallery = () => {
      ImagePicker.openPicker({
        includeBase64:true,
        width: 300,
        height: 300,
        cropping: false,
      }).then(image => {
        console.log(image);
        const source = { uri: image.path };
        this.setState({imagePath: source})
        this.setState({image: image})
      });
    }

    chooseFromCamera = () => {
      ImagePicker.openCamera({
        includeBase64:true,
        width: 300,
        height: 300,
        useFrontCamera: true,
      }).then(image => {
        const source = { uri: image.path };
        this.setState({imagePath: source})
        this.setState({image: image})
        this.savePictureGallery(image.path)
      });
    }

```
### Attachments

I tested on Android API 30, 29 (Android 10) and it works fine, however it crashes on Android API 28. 

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by jontacky** [comment]
I am experiencing the same issue

**Comment by Luckygirlllll** [comment]
@jontacky Did you find any solution? I have tried `react-native-image-picker `library, but it also has this problem.

**Comment by codebetterme** [comment]
hi,
You could workaround with version react-native-image-crop-picker v0.25.0

**Comment by Luckygirlllll** [comment]
@codebetterme it's crashing on v.0.25.0 as well.

**Comment by codebetterme** [comment]
> @codebetterme it's crashing on v.0.25.0 as well.

open Android Studio and paste error logs in here

**Comment by Luckygirlllll** [comment]
Messages in logs: 

```
D/TSLocationManager: [c.t.l.l.TSLocationManager calculateMedianAccuracy] Median accuracy: 5.0
2020-07-17 12:51:39.080 19692-20040/com.myapp D/MediaScannerConnection: Scanned /storage/emulated/0/DCIM/38504eb0-ea1c-4077-97fc-24c846130918.jpg to content://media/external_primary/images/media/61
```

**Comment by codebetterme** [comment]
You try add 
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"
                 android:maxSdkVersion="28" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"
                 android:maxSdkVersion="28" />
to AndroidManifest.xml

**Comment by Luckygirlllll** [comment]
I just have tried it, the same result, nothing changed.

**Comment by Luckygirlllll** [comment]
I found what was causing the problem. My problem had two parts. 

1) I didn't have all required settings: 

Add `useSupportLibrary (android/app/build.gradle)`
```
android {
    ...

    defaultConfig {
        ...
        vectorDrawables.useSupportLibrary = true
        ...
    }
    ...
} 
```
And I didn't have this: 

 If you want to use front camera, also add following to `app/src/main/ AndroidManifest.xml`

```
<uses-feature android:name="android.hardware.camera" android:required="false" />
<uses-feature android:name="android.hardware.camera.front" android:required="false" />
```

2). I had my my own automatic redirects inside of the app, which was also causing the problem.

**Comment by Kunalpaul12** [comment]
What help me 

```
project.ext.react = [
    enableHermes: false,  // clean and rebuild if changing
    extraPackagerArgs: [ '--minify=false' ]
]
```

put this on top of the index.js

import 'react-native-gesture-handler';
