### ISSUE TITLE
[Android]Images are not displayed as the order they are selected

### ISSUE THREAD

**Issue by emclab** [ivpusic/react-native-image-crop-picker#1345]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.32.2
- react-native v0.62.2

### Platform
Tell us to which platform this issue is related

Android 8.1 emulator

### Expected behaviour
Maintain the order as how the multiple images were selected. For example, the first image select is the first in array returned.

### Actual behaviour
The images selected seems ordered by name

Here is the options:

        var options = {
                mediaType: mediaType, //<<=='photo' by default
                cropping:cropping,
                sortOrder:'none',
                waitAnimationEnd: false,
                includeExif:true,
            };

### Steps to reproduce

1. select 2 images and remember which one is the first one

2.display on screen

3.select the same 2 images in reverse order as step 1.

4. Display on screen. Are they in different order? It is not in my case.

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by ivpusic** [comment]
currently not supported

**Comment by emclab** [comment]
@ivpusic, Is it possible to be included in future release? If user picks up multiple images for a subject, she/he likely want to show images in the same order as they were picked. For example, a real estate agent  may want to show the bird view of a house as first image before presenting other detail of the house. Thanks.

**Comment by ivpusic** [comment]
no plans to add this in near future. after selecting images you could build your own component to rearrange them by drag & drop

**Comment by iKoru** [comment]
I also want this feature, too. please consider it as planned..

**Comment by jamesshaw49** [comment]
@ivpusic thanks for building this library, it has been very useful for our project so far. While maintaining the selected order is currently not supported, the user would expect this behaviour. It creates a sub optimal user experience if the user then has to then go back and change the order. Look at the user experience when creating an Instagram post for an example.
