### ISSUE TITLE
[ Feature Request ] List images in the order they are picked from album

### ISSUE THREAD

**Issue by AbhiShrek** [ivpusic/react-native-image-crop-picker#1350]
**Feature**: openPicker should list images in the order they are picked.

Images picked by openPicker [does not guarantee](https://github.com/ivpusic/react-native-image-crop-picker/issues/1345#issuecomment-660860233) the order, in which they are picked.

It becomes really annoying to app users, when they want to order the selected images, but cant.
We have to use additional code and logic like providing draggable lists separately, to make this this simple ordering work.

It's a request, to ensure the ordering. It will make this awesome library ... more awesome, and lives of many developers better.

Thanks

**Comment by emclab** [comment]
Can't agree more. I asked for the same feature in[#1345](https://github.com/ivpusic/react-native-image-crop-picker/issues/1345)

**Comment by ivpusic** [comment]
currently I have no plans to implement feature. however if somebody have time to create a PR, would accept such feature
