### ISSUE TITLE
Is Expo supported by now?

### ISSUE THREAD

**Issue by sunviwo** [ivpusic/react-native-image-crop-picker#1363]
### Version

- react-native-image-crop-picker v0.32.2
- react-native v0.63
- Expo SDK 38

### Platform

- Android

### Expected behaviour

Hi, I like the package and I'd like to know if it is compatible with Expo by now. Thks

**Comment by danghung97** [comment]
i also hope to have this soon

**Comment by gotexis** [comment]
+1 it doesnt seem to work for me

**Comment by Svarto** [comment]
+1

**Comment by masarufuruya** [comment]
+1

**Comment by ozanbatuhankurucu** [comment]
+1

**Comment by qiliangya** [comment]
Up to now, I have the same needs

**Comment by aliaydins** [comment]
+1

**Comment by QiYuNew** [comment]
+1, I like this package

**Comment by ivpusic** [comment]
unfortunetly it is not supported. there are no short-term plans to support it

**Comment by bryanltobing** [comment]
is is supported by now ?

**Comment by segun-flexible** [comment]
is it supported by now?
i really love this package

**Comment by 415brian** [comment]
Looking at this issue and comments to understand Expo compatibility
