### ISSUE TITLE
Cropping png yields white bg

### ISSUE THREAD

**Issue by jordangrant** [ivpusic/react-native-image-crop-picker#1366]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.32.2
- react-native v0.63 or something

### Platform
Tell us to which platform this issue is related

- **iOS** 
- Android

### Expected behaviour
Cropping a png returns another png

### Actual behaviour
cropping png fills the transparent layer with a white bg

### Steps to reproduce

1. feed ImagePicker.openCropper a remote uri to a png

2. crop

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by jordangrant** [comment]
Similar to https://github.com/ivpusic/react-native-image-crop-picker/issues/1026

**Comment by mahcloud** [comment]
@jordangrant I feel like I must be missing something. When I use the circular cropper the base64 image is a square with white background around my circular image. Is this expected?

**Comment by jordangrant** [comment]
@mahcloud I want to preserve a transparent background.

**Comment by mahcloud** [comment]
@jordangrant but it comes back as a jpeg. It can't be transparent as a jpeg, right? I'm seeing
```
"mime": "image/jpeg"
```

**Comment by mahcloud** [comment]
@jordangrant thanks for responding so quickly, btw

**Comment by jordangrant** [comment]
@mahcloud That's correct. Here's a video https://youtu.be/DyBPipfPk4M

**Comment by mahcloud** [comment]
@jordangrant I think I see the confusion. We are using the cropperCircleOverlay setting. If we use the square cropper and then manually style after, it works fine. We just really like the circular cropper UI for our customer, but we will have to stop using it if it provides white background.

**Comment by truongduyng** [comment]
black background for android. Why not preserve png format and transparent background?

**Comment by Kaizodo** [comment]
any update on this issue ? i am on latest version and when i select png image with transparent pixels it returns a blank background png image in android
