### ISSUE TITLE
unable to custmize width and height Together

### ISSUE THREAD

**Issue by ignivanishant** [ivpusic/react-native-image-crop-picker#137]
i am using react-native
- react-native-image-crop-picker ^0.10.2
- react-native 0.37.0

### Platform
- iOS

pickSingle() {
    ImagePicker.openPicker({
      width: 80,
      height: 60,
      cropping: true,
    }).then(image => {
      console.log('received image', image);
      this.setState({
        image: {uri: image.path, width: image.width, height: image.height, mime: image.mime},
        images: null
      });
    }).catch(e => {
      console.log(e.code);
      alert(e);
    });
  }

this is the code i am using but when it open window to crop image it unable to adjust width, if decrese width then its not picking given height

**Comment by ivpusic** [comment]
hmm, does this happens only when you specify small width/height or also on values like 800/600?

**Comment by ignivanishant** [comment]
yes

**Comment by ivpusic** [comment]
okey, which statement of above two did you confirm? 😄

**Comment by ivpusic** [comment]
will close this issue as it seems obsolete and autor is not responding. please reopen if still actual
