### ISSUE TITLE
Android 10 - OpenCamera and OpenPicker do not work

### ISSUE THREAD

**Issue by jpsolero** [ivpusic/react-native-image-crop-picker#1372]
### Version
Tell us which versions you are using: 
- react-native-image-crop-picker v0.32.2
- react-native v0.63.3

### Platform
- Android with targetSdkVersion = 29

### Expected behaviour
OpenCamera and Open picker should work

### Actual behaviour
You recieve an error:
Open Camera => E_FAILED_TO_OPEN_CAMERA Permission denied 
Open Picker => E_NO_IMAGE_DATA_FOUND

### Steps to reproduce

1. Install The last RN Version as a new App

2. Try to open de picker or the camera

3. Crash happens

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by jpsolero** [comment]
Fixed by adding this to the AndroidManifest.xml:

<application
   ...
    android:requestLegacyExternalStorage="true"
   ...
  >

This is a temporary solution and will fail once this is built to Target Level 30 API. (targetSdkVersion = 30)

**Comment by komdil** [comment]
Any updates, solution?

**Comment by itvignes09** [comment]
This issue fixed on latest react-native-image-crop-picker library

update the package using **npm i react-native-image-crop-picker@latestversion**

**Comment by Rushabhgedam** [comment]
Somehow it just opened but after capturing the image app crashes and restarts from the initial splash screen

**Comment by scblason** [comment]
I'm using latest version of library and I'm facing this issue. All permissions dialogs pop up, allow all of them and before showing the camera, the app crashes. Using emulator with Android 10 to test target api level 29. I didn't had issues with emulated camera before. My gradle is:

buildscript {
    ext {
        buildToolsVersion = "29.0.2"
        minSdkVersion = 16
        compileSdkVersion = 29
        targetSdkVersion = 29
        supportLibVersion = "28.0.0"
        googlePlayServicesVersion = "16.0.0"
    }

**Comment by ivpusic** [comment]
try version https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.35.0

**Comment by scblason** [comment]
> try version https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.35.0

I was using an emulator where the emulated camera was not working properly (camera app in emulator was not working).
Once I fixed that, image picker worked as expected with 0.34.1 version

**Comment by LohithaYalavarthi1** [comment]
@ivpusic I was using   "react-native": "^0.59.10"
and using  buildToolsVersion = "28.0.3"
        minSdkVersion = 21
        compileSdkVersion = 28
        targetSdkVersion = 29
        supportLibVersion = "28.0.0"
        googlePlayServicesAuthVersion = "15.0.1"
        googlePlayServicesVersion = "16.+"

I cant be able to install a react-native-image-crop-picker more than 0.25.0,

The above solutions don't work for me.Is there any other solution for this?

**Comment by mehdiChibani** [comment]
i updated react-native-image-crop-picker to the latest version 0.39.0 and it worked properly
