### ISSUE TITLE
[Android] Invalid image selected for Google Photos/System Gallery

### ISSUE THREAD

**Issue by jmahatpure01** [ivpusic/react-native-image-crop-picker#1378]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.32.2
- react-native v0.63.2

### Platform
Tell us to which platform this issue is related
- Android 10
Device: Realme XT

### Expected behaviour
Picker Should be able to select image from google photos and system photos App.

### Actual behaviour
After selecting the image it throws "Invalid image selected"

### Steps to reproduce

1. I'm calling
 selectImage() {
        ImagePicker.openPicker({
            cropping: false,
            mediaType: 'photo'
          }).then(image => {
            this.setState({cover: image})
          });
    }

2. then selecting image from Google Photos or Photos(system gallery) App.

I'm able to select image from recent images and also by going through folders.

### Attachments

//Screenshot of stacktrace
![Screenshot_2020-08-23-19-33-03-39](https://user-images.githubusercontent.com/17550665/90980333-471adb00-e578-11ea-9c39-ad9bcb7db4eb.jpg)

**Comment by shiweiwei114** [comment]
Same here.
I am on Pixel 2 XL, Android X with react-native-image-crop-picker: 0.33.2.

I am able to select the "recent images on phone" and "Google Photos" (only Photos folder), can't pick all other pics within "Device Folders" (like Camera, Screenshots, Picture, Messenger, Facebook Folder etc..)

**Comment by shiweiwei114** [comment]
@jmahatpure01 I have added the following line in the AndroidManifest.xml, it seems working fine now:

android:usesCleartextTraffic="true"
android:requestLegacyExternalStorage="true"

Referred this: 
- https://github.com/ivpusic/react-native-image-crop-picker/issues/1372
- https://github.com/ivpusic/react-native-image-crop-picker/issues/1318
- https://medium.com/@sriramaripirala/android-10-open-failed-eacces-permission-denied-da8b630a89df

**Comment by jmahatpure01** [comment]
@shiweiwei114  thankyou it worked for me.

**Comment by vishwa1937** [comment]
@shiweiwei114 Thank you. It worked for me also. It should be included in document also.

**Comment by panda6412** [comment]
> android:usesCleartextTraffic="true"
> android:requestLegacyExternalStorage="true"

Is this ```android:usesCleartextTraffic="true"``` config necessary?

**Comment by doublelam** [comment]
> > android:usesCleartextTraffic="true"
> > android:requestLegacyExternalStorage="true"
> 
> Is this `android:usesCleartextTraffic="true"` config necessary?

Not necessary, the 2nd line is enough for me

**Comment by panda6412** [comment]
> > > android:usesCleartextTraffic="true"
> > > android:requestLegacyExternalStorage="true"
> > 
> > 
> > Is this `android:usesCleartextTraffic="true"` config necessary?
> 
> Not necessary, the 2nd line is enough for me

Thanks, already remove this config, and it works!

**Comment by riyas145** [comment]
After adding  android:requestLegacyExternalStorage="true" on android/app/src/main/AndroidManifest.xml still i'm having issues 
Phone : Redmi Note 10 S for samsung that was working fine

**Comment by jonno85** [comment]
I think this line `android:requestLegacyExternalStorage="true"` should mentioned in the main **README**
