### ISSUE TITLE
the option “ multiple: true” , Is not valid on my phone。why?

### ISSUE THREAD

**Issue by liukefu2050** [ivpusic/react-native-image-crop-picker#138]
### Version
    "react": "15.3.1",
    "react-native": "^0.36.1",
    "react-native-image-crop-picker": "^0.10.1",

### Platform
Android

        ImagePicker.openPicker({
            multiple: true
        }).then(images => {
            this.setState({
                images: images.map(i => {
                    console.log('received image', i);
                    return {uri: i.path, width: i.width, height: i.height, mime: i.mime};
                })
            });
        }).catch(e => alert(e));

**Comment by liukefu2050** [comment]
Can only choose a picture,How to choose multiple images,thinks for you help

**Comment by ivpusic** [comment]
https://github.com/ivpusic/react-native-image-crop-picker/issues/122
