### ISSUE TITLE
SDK 29 and  'React/RCTImageURLLoader.h' file not found

### ISSUE THREAD

**Issue by matamicen** [ivpusic/react-native-image-crop-picker#1385]
@ihaodi please update the document :
For RN: 0.61.+, use react-native-image-crop-picker@0.26.0
For RN: <=0.60.6, use react-native-image-crop-picker@25.3

_Originally posted by @Dhanraj-bidchat in https://github.com/ivpusic/react-native-image-crop-picker/issues/1143#issuecomment-576624546_

**Comment by matamicen** [comment]
Hi @ivpusic and many thanks for this library :)

So we have RN 060.4 and we are using react-native-image-crop-picker 0.25.3 without problem, the thing is Google is telling us to upgrade to SDK 29, so we did it and then we had to install the latest version 0.33.2 to fix the SDK 29 permission thing and we found the error **'React/RCTImageURLLoader.h' file not found** mentioned in the post above. So in order to keep using this library we must update RN ? or there is any workaround? Thnaks again!

Matt.

**Comment by eNale** [comment]
Same issue here

**Comment by matamicen** [comment]
@eNale We had to update RN ... and everything is working now ...

**Comment by eNale** [comment]
> @eNale We had to update RN ... and everything is working now ...

I updated RN as well and I can confirm it works.
