### ISSUE TITLE
openPicker can't work, Error: User cancelled image selection

### ISSUE THREAD

**Issue by 0-Captain** [ivpusic/react-native-image-crop-picker#1386]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.33.2
- react-native v0.63.2

### Platform
Tell us to which platform this issue is related

- Android

### Expected behaviour
The image selection page appears

### Actual behaviour
No image selection page, file crash

js catch error：User cancelled image selection

### Steps to reproduce

【android R】【redmi k30 pro】
1. npx react-native init myApp
2. yarn add react-native-image-crop-picker
3. rewrite App.js
```
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow strict-local
 */

import React from 'react';
import {
  SafeAreaView,
  StyleSheet,
  ScrollView,
  View,
  Text,
  Button,
  StatusBar,
} from 'react-native';

import {
  Header,
  LearnMoreLinks,
  Colors,
  DebugInstructions,
  ReloadInstructions,
} from 'react-native/Libraries/NewAppScreen';
import ImagePicker from 'react-native-image-crop-picker';

const App: () => React$Node = () => {
  return (
    <>
      <StatusBar barStyle="dark-content" />
      <SafeAreaView>
        <ScrollView contentInsetAdjustmentBehavior="automatic">
          <Header />
          <View>
            <Button
              title="click me"
              onPress={() =>
                ImagePicker.openPicker({
                  width: 300,
                  height: 400,
                  cropping: true,
                })
                  .then((image) => {
                    console.log(image);
                  })
                  .catch((err) => {
                    console.log(err);
                  })
              }
            />
          </View>
        </ScrollView>
      </SafeAreaView>
    </>
  );
};

export default App;

```

### Attachments

// stacktrace or any other useful debug info
"User cancelled image selection"

**Comment by 0-Captain** [comment]
this error maybe caused by system. It's work when I update system version.

**Comment by kabus202** [comment]
@0-Captain i have the same problem ob xiaomi poco f2 android 11, did you manage to solve this completely?

**Comment by manjunathgk22** [comment]
Is this fixed? facing same issue on redmi phones

**Comment by jiangyu816** [comment]
vivoY3也有，android  9

**Comment by hellojayjay** [comment]
> vivoY3也有，android 9

兄弟，你咋解决的？
