### ISSUE TITLE
openCamera not working on targetSdkVersion = 30

### ISSUE THREAD

**Issue by makserge** [ivpusic/react-native-image-crop-picker#1392]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.33.2
- react-native v0.63.2

### Platform
Tell us to which platform this issue is related

- Android

### Expected behaviour

openCamera opens camera

### Actual behaviour

nothing - rejects promise with "Cannot launch camera"

### Steps to reproduce

1. Trying to take photos via openCamera() on Google Pixel 4 XL Android 11

Debugged source code and it returned null on 
https://github.com/ivpusic/react-native-image-crop-picker/blob/4d97c7c9c5ef909672b087ff7531456da92bac69/android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java#L327

It seems in Android 11 we should ask for available cameras in phone and since it require to update Gradle and changes in AndroidManifest

Related thread on StackOverflow

https://stackoverflow.com/questions/63246442/android-11-r-return-empty-list-when-querying-intent-for-action-image-capture

**Comment by makserge** [comment]
As workaround just removed lines 327-330

if (cameraIntent.resolveActivity(activity.getPackageManager()) == null) {
                resultCollector.notifyProblem(E_CANNOT_LAUNCH_CAMERA, "Cannot launch camera");
                return;
            }

from 
react-native-image-crop-picker/android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java

**Comment by hassan-kiffgo** [comment]
+1

**Comment by ivpusic** [comment]
should be fixed in version https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.35.0
