### ISSUE TITLE
v0.33.3 [!] [Xcodeproj] Generated duplicate UUIDs

### ISSUE THREAD

**Issue by ddave09** [ivpusic/react-native-image-crop-picker#1397]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.33.3
- react-native v0.61.5

### Platform
- iOS

### Expected behaviour
command `pod update` should be successful.

### Actual behaviour
v0.33.3 [!] [Xcodeproj] Generated duplicate UUIDs

### Steps to reproduce

1. npm install react-native-image-crop-picker (version 0.31.0 or higher)

2. cd ios

3. pod update

Up to version 0.30.0 all good! Issue starts occurring at and after 0.31.0.
Based on the reason note "(ios) replace RSKImageCropper with TOCropViewController", `TOCropVeiwController` seems to be the issue.

### Workaround
add below line in ios/Podfile right below `require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules`

```install! 'cocoapods', :deterministic_uuids => false```

I found the workaround from [CocoaPods](https://github.com/CocoaPods/CocoaPods/issues/4370) repo.

**Comment by zaid0077** [comment]
Are you able to build your project after that?

**Comment by ddave09** [comment]
> Are you able to build your project after that?

Yes! And it works as expected. Did some tests on iOS and android

**Comment by zaid0077** [comment]
i am getting the [Xcodeproj] Generated duplicate UUIDs after i do pod install... I am not able to build the project on iOS after that. Android works fine

**Comment by ddave09** [comment]
Even after adding ‘install! 'cocoapods', :deterministic_uuids => false’?

After adding the above line run ‘pod update again’

**Comment by TPXP** [comment]
Same issue here, I'm guessing this may be an issue in `TOCropVeiwController`, since there is a similar report there: https://github.com/TimOliver/TOCropViewController/issues/424

**Comment by zaid0077** [comment]
> Even after adding ‘install! 'cocoapods', :deterministic_uuids => false’?
> 
> After adding the above line run ‘pod update’ again

Yes cant build even after doing this

**Comment by ddave09** [comment]
> > Even after adding ‘install! 'cocoapods', :deterministic_uuids => false’?
> > After adding the above line run ‘pod update’ again
> 
> Yes cant build even after doing this

Sorry to hear that @zaid0077, but unfortunately that's the only workaround I have at the moment

**Comment by sufyan297** [comment]
@ddave09 Thanks man!! You save my day 👍  , tried with latest version **0.35.0** it works

**Comment by ashfurrow** [comment]
Hi there 👋 I was seeing this warning too and I fixed it in this PR: https://github.com/TimOliver/TOCropViewController/pull/432 . The maintainer has released a new version of the TOCropViewController library so you should be able to solve this with the following command:

```
pod update TOCropViewController
```

I've verified that this works locally in our app: https://github.com/artsy/eigen/pull/3956 Let me know if that works for all of you!

**Comment by ddave09** [comment]
Updated to version 0.35. The issue is not occurring any longer.

**Comment by ashfurrow** [comment]
Yay! I'm so glad to hear that 😄

**Comment by a-eid** [comment]
getting this issue using `^0.35.1` 
`RNImageCropPicker (0.35.1)` 
`TOCropViewController (2.5.4)`

![Uploading Screen Shot 2020-10-28 at 2.00.45 PM.png…]()

**Comment by slife518** [comment]
projectname > ios >
1.  pod update
2. sudo gem install cocoapods

**Comment by houmie** [comment]
The issue is back with `1.10.1` again.
