### ISSUE TITLE
Unable to build React Native iOs app installing react-native-image crop picker

### ISSUE THREAD

**Issue by zaid0077** [ivpusic/react-native-image-crop-picker#1398]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker: 0.34.1
- react-native 0.63.2
- platform :ios, '10.0'

### Platform
Tell us to which platform this issue is related

- iOS is having issues
- Android is working perfectly fine

### Expected behaviour

Successfully build iOS app after installation of react-native-image-crop-picker.

### Actual behaviour

When i using pod install my terminal is showing. -- [!] [Xcodeproj] Generated duplicate UUIDs:
and when i do react-native run-ios the build is failing. It happens only with this library

### Steps to reproduce

1. npm install react-native-image-crop-picker

2. cd ios

3. pod install

4. react-native run-ios

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by emmaielle** [comment]
Also happening in Android for me

**Comment by snaik2064** [comment]
Any updates on this issue ?

**Comment by zaid0077** [comment]
I used a different library. Cant solve the issue

**Comment by ivpusic** [comment]
this issue was caused by TOCropViewController. some days ago fix was published. in order to fix it run `pod update` from your `ios` directory
