### ISSUE TITLE
Is it possible to add live in detection of edges 

### ISSUE THREAD

**Issue by rlokesh1234** [ivpusic/react-native-image-crop-picker#1404]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.?.?
- react-native v0.?.?

### Platform
Tell us to which platform this issue is related

- iOS
- Android

### Steps to reproduce

1.

2.

3.

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by ivpusic** [comment]
currently not possible

**Comment by loijwdev** [comment]
@rlokesh1234, if you have some time, could you take a quick look at this repo?
https://github.com/loijwdev/react-native-live-detect-edges
