### ISSUE TITLE
Setting "cropping: true" disables videos.

### ISSUE THREAD

**Issue by michaelhelvey** [ivpusic/react-native-image-crop-picker#141]
### Version

- react-native-image-crop-picker v0.10.1
- react-native v0.37

### Platform

- iOS

### Expected behaviour

It should still allow the user to pick videos, since I haven't disabled them in any way, when I set `cropping` to true.

### Actual behaviour

It doesn't allow the the user to pick videos.  Is this for Android compatibility?  Because it's quite unnecessary for iOS, it seems.

This behavior is caused by https://github.com/ivpusic/react-native-image-crop-picker/blob/master/ios/ImageCropPicker.m#L211, but commenting out these lines doesn't break anything for iOS.

I'd be glad to submit a PR if this is unexpected behavior.

**Comment by ivpusic** [comment]
this is expected. if you say cropping true, that means you want image to be selected, because you cannot crop video. Showing videos when cropping is true does not make sense

**Comment by michaelhelvey** [comment]
The trouble with this is that it's not configurable by the developer.  For example, if you wanted to be able to have a picker that can choose both videos, and crop photos, you couldn't currently.  It's less about what makes sense, and more about whether or not you want an API that enforces a particular behavior.  I think it should up to the developer to decide what "makes sense," in his use case, rather than up to the library itself.

If the developer wanted to disable videos, it would be trivial to simply use the "Smart Albums" option to disable them, while still maintaining freedom in the API.
