### ISSUE TITLE
Can we config processing step to happen in background

### ISSUE THREAD

**Issue by siriwatknp** [ivpusic/react-native-image-crop-picker#1410]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.28.0
- react-native v0.61.5

### Current behaviour
If user choose huge video from react-native-image-crop-picker, they will see processing screen for a very long time.

### Expected behaviour
Can we do the processing in the background so that user can do other stuff in the app.

**Comment by ivpusic** [comment]
currently not possible
