### ISSUE TITLE
Build fail on version 0.35.0

### ISSUE THREAD

**Issue by idanavr** [ivpusic/react-native-image-crop-picker#1414]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.35.0
- react-native v0.63.2

### Platform
Tell us to which platform this issue is related

- Android

### Expected behaviour

Build successfully

### Actual behaviour

Build failed

### Attachments

// stacktrace or any other useful debug info
![image](https://user-images.githubusercontent.com/28144178/94302098-58d71000-ff74-11ea-81ee-4caf694c72b8.png)

I've downgraded to 0.34.1 and it builds just fine, so I guess it has something to do with the latest changes.

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by ivpusic** [comment]
check https://github.com/ivpusic/react-native-image-crop-picker/issues/1406
