### ISSUE TITLE
Build failing after installing react-native-image-crop-picker

### ISSUE THREAD

**Issue by PavanTank4631** [ivpusic/react-native-image-crop-picker#1416]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.35.0
- react-native v0.63.2

### Platform
Tell us to which platform this issue is related

- Android => Not working
- IOS => Working 

### Actual behaviour

* What went wrong:
```
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     D:\Project\node_modules\react-native-image-crop-picker\android\build\intermediates\library_manifest\debug\AndroidManifest.xml:10:5-14:15: AAPT: error: unexpected element <queries> found in <manifest>.

```
### Steps to reproduce

Just open android studio, and try to run app, it will show this error

I have found same issue here. she downgrade to lower version, I am hoping to use latest version with your fix.
https://stackoverflow.com/questions/64022942/build-failing-after-installing-react-native-image-crop-picker

**Comment by SUMITIOS** [comment]
@PavanTank4631  The solution is there in the same stackoverflow link that you have provided:
No need to downgrade to 0.33.

Upgrade your `gradle` version by adding `classpath 'com.android.tools.build:gradle:4.0.1'` in your **android/build.gradle** file:
`
buildscript {
    dependencies {
        classpath 'com.android.tools.build:gradle:4.0.1'
     }
}
`

**Comment by SUMITIOS** [comment]
And also run `cd android` then `./gradlew clean` (for mac) after upgrading and rebuild the app. The issue will be gone.

**Comment by ninkambazi** [comment]
> gradlew clean

if you still have some new complicated errors you can also delete the **build file** in android/app/build and run the app it will then work fine

**Comment by oleksandr-dziuban** [comment]
@ivpusic Hello, can this issue be addressed to maintainers? Thanks a lot

**Comment by bhsrampage** [comment]
its not working Plz address the issue ASAP....

**Comment by jacquesdev** [comment]
I had to do the following to get it working:
1. Upgrade your gradle version by adding classpath 'com.android.tools.build:gradle:4.0.1' in your android/build.gradle
2. In gradle-wrapper.properties, update the path to `services.gradle.org/distributions/gradle-6.1.1-all.zip` (upgrade to version 6)

I am using react-native v0.61.5

**Comment by ivpusic** [comment]
Minimum Gradle version if you are using react-native-image-crop-picker >= 0.35.0

```
3.3.3
3.4.3
3.5.4
3.6.4
4.0.1
```

Reference for more details https://github.com/ivpusic/react-native-image-crop-picker/issues/1406

**Comment by vishalveerareddy** [comment]
Still the issue is persisting

**Comment by oleksandr-dziuban** [comment]
@ivpusic This is not a cache problem. Issue reproducible locally and on CI for all build from scratch, please reopen

**Comment by ivpusic** [comment]
gradle upgrade is required in order to use 0.35.0 version. if you cannot upgrade, please use version <0.35.0

**Comment by a-eid** [comment]
I'm having this issue still.

**Comment by kaunghtethein977** [comment]
I have done adding `classpath('com.android.tools.build:gradle:4.0.1')` in `android/build.gradle`. And I started running `react-native run-adroid`. It is stuck at 99% **:app:installDebug**. What should I do?

**Comment by MedDimessi** [comment]
I upgraded to `classpath('com.android.tools.build:gradle:4.0.1')` it told me to update the `gradle-wrapper.properties` `distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-all.zip`.  It managed to work on debug mode, however, when generating the release apk after `./gradlew clean` and `./gradlew assembleRelease` , the app crashes the second it opens!! any idea why upgrading the gradle causes this immediate crash on release mode but not on debug mode??

**Comment by leejoonhwan** [comment]
add buildscript ext supportLibVersion = "28.0.0"

like this

buildscript {
    ext {
        buildToolsVersion = "29.0.2"
        minSdkVersion = 16
        compileSdkVersion = 29
        targetSdkVersion = 27
        supportLibVersion = "28.0.0"
    }

**Comment by maheenriaz** [comment]
> @PavanTank4631 The solution is there in the same stackoverflow link that you have provided:
> No need to downgrade to 0.33.
> 
> Upgrade your `gradle` version by adding `classpath 'com.android.tools.build:gradle:4.0.1'` in your **android/build.gradle** file:
> `buildscript { dependencies { classpath 'com.android.tools.build:gradle:4.0.1' } }`

Great solution!!!!
It worked <3

**Comment by michael-monty** [comment]
I tried 

```
classpath 'com.android.tools.build:gradle:4.0.1'
distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip
```

and then did ./gradlew clean, ./gradlew cleanBuildCache

but it didn't work


I then ignored/undid changes mentioned in this step:

Use Android SDK >= 26 (android/app/build.gradle)
```
  android {
      compileSdkVersion 27
      buildToolsVersion "27.0.3"
      ...
      
      defaultConfig {
        ...
        targetSdkVersion 27
        ...
      }
      ...
  }
```
And it built (I kept the upgraded gradle 4.0.1/6.1.1

**Comment by AbdullahAnsarii** [comment]
> And also run `cd android` then `./gradlew clean` (for mac) after upgrading and rebuild the app. The issue will be gone.

also do '.\gradlew --refresh-dependencies' after `./gradlew clean`

**Comment by AliZia110** [comment]
Hi,In the project that I created two weeks ago and older projects, when I install this library, I encounter the same error, but when I initiated a new project, it was successful, now I do not know why it does not appear on  my previous project,thank you if help me

**Comment by AliZia110** [comment]
for android

**Comment by ravindra3003** [comment]
I am facing same issue

 "react-native": "0.64.2"
"react-native-image-crop-picker": "^0.32.2",

also I have tried 0.35.0

My current gradlew

classpath("com.android.tools.build:gradle:4.1.0")
distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip

`1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-image-crop-picker:compileDebugLibraryResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > 1 exception was raised by workers:
     com.android.builder.internal.aapt.v2.Aapt2InternalException: AAPT2 aapt2-4.0.1-6197926-osx Daemon #0: Daemon startup failed
     This should not happen under normal circumstances, please file an issue if it does.`


Also I got some Warning like this

Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/03 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: unexpected element (uri:"", local:"base-extension"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
