### ISSUE TITLE
Any news on development of this repository?

### ISSUE THREAD

**Issue by DanielBoening** [ivpusic/react-native-image-crop-picker#1423]
Hello,

while this library looks helpful and promising, the lack of support seems to be a problem. 51 unresolved Pull Requests seem like a missed potential. Are there any news on whether this repository will be maintained again?

**Comment by ivpusic** [comment]
currently my free time is limited. I will try to keep existing features working, accept important PRs which are complete (there are a lot of them which are half complete, which is a problem), but cannot promise on how much time I will spend on adding completely new features
