### ISSUE TITLE
Build fails for iOS 14

### ISSUE THREAD

**Issue by snaik2064** [ivpusic/react-native-image-crop-picker#1426]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.35.0
- react-native v0.63.2

### Platform
Tell us to which platform this issue is related

- iOS

### Expected behaviour
Successfully build iOS app after installation of react-native-image-crop-picker.

### Actual behaviour
1. The issue is `only for iOS 14` not for previous version.
2. First it gives the [Xcodeproj] Generated duplicate UUIDs error
3.  After running `react-native run-ios` build fails

### Steps to reproduce

1.  yarn add react-native-image-crop-picker
2. cd ios
3. pod install
4. npx react-native run-ios

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by leelandclay** [comment]
I had a similar error when I first updated. I deleted node_modules and Pods directories, ran npm i and pod install and it seemed to fix it for me.

**Comment by snaik2064** [comment]
The bug was caused by `TOCropViewController` version mismatch. 
Which I was able to solve by updating `pod update TOCropViewController` or simply `pod update`.

**Comment by gremlin529** [comment]
I'm hitting this same error on 0.40.0 when trying to upgrade to ios14, nothing I've done has fixed it.
