### ISSUE TITLE
Image is saved at Disk and at cache at same time

### ISSUE THREAD

**Issue by koraniar** [ivpusic/react-native-image-crop-picker#143]
### Version
- react-native-image-crop-picker v0.10.3
- react-native v0.35

### Platform
- iOS (I have not tried it here)
- Android 7.0

I am taking a picture and cropping it,
The app return this image path: "file:///data/user/0/com.larnia/cache/react-native-image-crop-picker/90e9e92f-faf6-463b-98b7-f5a0da5aae99.jpg" (image at **cache**)
All right

But when I enter to my photo gallery, I see the same photo without cropping at the path: "file:///storage/emulated/0/Pictures/image-2010b3a6-b74d-420c-baea-de8390da184a71335456.jpg" (image at **DISK**)

I tried to no crop the photo but the App returns directly the image path in local disk
I can delete this photo manually but only if I not crop it because when I crop it, the App return me the image path in **cache** and not the image at **disk**

I would like to save this picture at cache or delete it after use it

This function only delete images saved on cache

```
ImagePicker.clean().then(() => {
  console.log('removed all tmp images from tmp directory');
}).catch(e => {
  alert(e);
});
```

**Comment by ivpusic** [comment]
currently I don't have plans of changing this. Feel free to submit PR to support described behaviour.
