### ISSUE TITLE
Gallery and Camera open and then close instantly.

### ISSUE THREAD

**Issue by edkahara** [ivpusic/react-native-image-crop-picker#1433]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.35.0
- react-native v0.63.2

### Platform
Tell us to which platform this issue is related

- iOS 13.5

### Expected behaviour
Gallery opens, I select a photo and crop it successfully.
Camera opens, I take a photo and crop it successfully.

### Actual behaviour
Gallery opens and closes instantly.
Camera opens and closes instantly.

![Screen Recording 2020-10-12 at 17 08 36](https://user-images.githubusercontent.com/20911240/95756552-98109b00-0cae-11eb-8262-e49b0edbae40.gif)

### Steps to reproduce

Here is my code
```
ImagePicker.openPicker({
          mediaType: 'photo',
          compressImageMaxWidth: 500,
          compressImageMaxHeight: 500,
          compressImageQuality: 0.5,
          includeBase64: true,
          cropping: true,
          cropperCircleOverlay: true,
}).then(image => {
          const source = { uri: 'data:image/jpeg;base64,' + image.data };
          console.log(source);
}).catch(e => console.log(e));
```

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by edkahara** [comment]
Never mind, I've found the issue. The issue has to do with the closing of the modal. It is not a problem with the package.

**Comment by rohithZE** [comment]
Hey @edkahara, I'm also facing a similar issue when opening the camera or picking from the gallery. Could you please tell me how you were able to solve this issue? Thanks in advance.

**Comment by edkahara** [comment]
@rohithZE In my case, there was a modal that would appear to allow give the options of either opening the camera or opening the gallery. The issue on iOS was that upon making the selection, it would open while the modal was still closing, leading to the issue. So what I did was use a setTimeout to give the modal time to close before opening the selection. In my case, my modal was taking 300ms to close so I put a setTimeout of 350ms, and then open either the gallery or camera.

**Comment by Polinak87** [comment]
@edkahara thank you for comment, it saves my day before deadline!

**Comment by fermmm** [comment]
Thanks!!! I came across this issue because I had the same problem with `expo-image-picker` I was using a context menu library and I was closing the context menu before calling the image picker, it seems that in IOS closing something that seems to be totally unrelated interferes with the picker

**Comment by Shahzaib114** [comment]
> @rohithZE In my case, there was a modal that would appear to allow give the options of either opening the camera or opening the gallery. The issue on iOS was that upon making the selection, it would open while the modal was still closing, leading to the issue. So what I did was use a setTimeout to give the modal time to close before opening the selection. In my case, my modal was taking 300ms to close so I put a setTimeout of 350ms, and then open either the gallery or camera.

it worked, thank you. This issue is only on IOS
