### ISSUE TITLE
Permissions denied even after allowing permissions , the camera doesnt open 

### ISSUE THREAD

**Issue by LohithaYalavarthi1** [ivpusic/react-native-image-crop-picker#1434]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker ^0.22.0
- react-native ^0.59.10

### Platform
Tell us to which platform this issue is related
- Android

buildToolsVersion = "28.0.3"
minSdkVersion = 21
compileSdkVersion = 28
targetSdkVersion = 29
supportLibVersion = "28.0.0"
googlePlayServicesAuthVersion = "15.0.1"
googlePlayServicesVersion = "16.+"

### Expected behaviour

OpenCamera and Open picker should work

### Actual behaviour

You recieve an error:
Open Camera => E_FAILED_TO_OPEN_CAMERA Permission denied
Open Picker => E_NO_IMAGE_DATA_FOUND

### Steps to reproduce

1.Install The last RN Version as a new App

2.Try to open de picker or the camera

3.Crash happens

**Comment by LohithaYalavarthi** [comment]
This issue is resolved thanks

**Comment by LohithaYalavarthi1** [comment]
> ### Version
> Tell us which versions you are using:
> 
> * react-native-image-crop-picker ^0.22.0
> * react-native ^0.59.10
> 
> ### Platform
> Tell us to which platform this issue is related
> 
> * Android
> 
> buildToolsVersion = "28.0.3"
> minSdkVersion = 21
> compileSdkVersion = 28
> targetSdkVersion = 29
> supportLibVersion = "28.0.0"
> googlePlayServicesAuthVersion = "15.0.1"
> googlePlayServicesVersion = "16.+"
> 
> ### Expected behaviour
> OpenCamera and Open picker should work
> 
> ### Actual behaviour
> You recieve an error:
> Open Camera => E_FAILED_TO_OPEN_CAMERA Permission denied
> Open Picker => E_NO_IMAGE_DATA_FOUND
> 
> ### Steps to reproduce
> 1.Install The last RN Version as a new App
> 
> 2.Try to open de picker or the camera
> 
> 3.Crash happens
> 
> ### Attachments

**Comment by LohithaYalavarthi1** [comment]
#I have solved this by installing the react-native-image-picker 0.29.0
