### ISSUE TITLE
64 duplicate symbols for architecture x86_64

### ISSUE THREAD

**Issue by EhsanSarshar** [ivpusic/react-native-image-crop-picker#1443]
I am using react native 0.63.2
and "react-native-image-crop-picker": "^0.35.1"

**Comment by varunshukla** [comment]
Hey @EhsanSarshar , How did you resolve this issue? I seem to be facing same issue, but nothing seems to work apart from  downgrading to v0.27.0

**Comment by EhsanSarshar** [comment]
just upgrade your react-native version to 0.63.3.
clean the project

**Comment by sataporn8063** [comment]
in my case i upgrade version from 0.26.1 to 0.36.0
and remove this line in Podfile 
_pod 'QBImagePickerController', :path => '../node_modules/react-native-image-crop-picker/ios/QBImagePicker/QBImagePickerController.podspec'_
