### ISSUE TITLE
[Android] album  open success but click 

### ISSUE THREAD

**Issue by zhengqizhang** [ivpusic/react-native-image-crop-picker#145]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.10.3
- react-native v0.37.0

### Platform
Tell us to which platform this issue is related

- Android

### Expected behaviour
select one picture and edit it 

### Actual behaviour
when i click the album  this modal slide down

### Steps to reproduce

1.

2.

3.

### Attachments

// stacktrace or any other useful debug info

**Comment by ivpusic** [comment]
can you please elaborate you issue a little bit better?

**Comment by zhengqizhang** [comment]
sorry， my english is poor...   and the problem i had solved.  my custom module is  conflict with this.
