### ISSUE TITLE
[iOS] App Crashes when calling ImagePicker.openPicker

### ISSUE THREAD

**Issue by Moistbobo** [ivpusic/react-native-image-crop-picker#1466]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.35.1
- react-native v0.63.3

### Platform
Tell us to which platform this issue is related

- iOS

### Expected behaviour

ImagePicker appears up

### Actual behaviour

App crashes, xcode shows strange error

### Steps to reproduce

1. Call `ImagePicker.openPicker`

### Attachments
<img width="896" alt="image" src="https://user-images.githubusercontent.com/29080587/99380923-8b164580-2905-11eb-98d2-258988286f38.png">

// stacktrace or any other useful debug info
- This happens after requesting PHOTO_LIBRARY permissions using react-native-permissions
- My Podfile is set for ios 10
- ImagePicker.openCamera works fine
- picker works fine on android as well

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by Moistbobo** [comment]
Resolved with #1215 (Include QBImagePicker.storyboard in Copy Bundle Resources)

If you are building for iOS 10, don't forget to request the relevant permissions, in my case I had to request PHOTO_LIBRARY permissions before launching the image picker

**Comment by AmirDiafi** [comment]
worked for me; thanks a lot.

[(https://github.com/ivpusic/react-native-image-crop-picker/issues/1466#issuecomment-729333079)](url)
