### ISSUE TITLE
Is it possible to detect video duration?

### ISSUE THREAD

**Issue by eraldoforgoli** [ivpusic/react-native-image-crop-picker#1484]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker ^0.31.1
- react-native v0.62.2"

I was wondering if this library is able to provide the video duration after choosing a video from the gallery?

**Comment by cenaHara** [comment]
hi @eraldoforgoli  what version you upgraded

**Comment by eraldoforgoli** [comment]
@cenaHara Hi
i upgraded to    `react-native-image-crop-picker": "^0.32.2` .
The picker returns an array of files, each file has a property `duration: number | null`

**Comment by cenaHara** [comment]
oh than @eraldoforgoli  very much ^_^
