### ISSUE TITLE
Show images in order of selection??

### ISSUE THREAD

**Issue by philanthalim** [ivpusic/react-native-image-crop-picker#1486]
### Version
Tell us which versions you are using: 

 "react-native-image-crop-picker": "^0.35.1",
"react-native": "0.63.2",

### Platform
Tell us to which platform this issue is related
- iOS

### Expected behaviour
Show images according to order selected

### Actual behaviour
Images are shown in random order.
Is it possible to show images in order of selection using this package? If not, is there any other package that orders the images selected?

**Comment by kkusanagi** [comment]
Currently is not supported. Depends on developer too. I'm also trying to check the source code see if anything can be changed for this features

**Comment by q-muller** [comment]
Have you find something ?

**Comment by ivpusic** [comment]
currently this is not supported. it is limitation of qbimagepickercontroller

**Comment by oarsoy** [comment]
Did anyone find a solution for this?
