### ISSUE TITLE
could not invoke ImageCropPicker.openPicker

### ISSUE THREAD

**Issue by woshizja** [ivpusic/react-native-image-crop-picker#149]
### Version
- react-native-image-crop-picker v0.10.5
- react-native v0.36.0

### Platform
- Android

### Expected behaviour
open gallery，choose image

### Actual behaviour
crash，throw error： could not invoke ImageCropPicker.openPicker
```
invoke
BaseJavaModule.java:331
invoke
JavaModuleWrapper.java:158
run
NativeRunnable.java:2
......
run
Thread.java:818
```

### Steps to reproduce

1.  npm i react-native-image-crop-picker --save
2.  react-native link react-native-image-crop-picker（already linked）
3.  then，

```
ImagePicker.openPicker({
          width: 300,
          height: 300,
          cropping: true,
        }).then(image => {
          // this.setState({
          //   image: {uri: image.path, width: image.width, height: image.height, mime: image.mime}
          // });
        });
```

I have read all the information can be google，still unresolved， someone can help？

**Comment by woshizja** [comment]
build.gradle
```
compileSdkVersion 23
    buildToolsVersion "23.0.1"

    defaultConfig {
        applicationId "com.helloworld"
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
```
setting.gradle
```
include ':react-native-image-crop-picker'
project(':react-native-image-crop-picker').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-image-crop-picker/android')
```

**Comment by ivpusic** [comment]
maybe this helps https://github.com/ivpusic/react-native-image-crop-picker/issues/132?

**Comment by woshizja** [comment]
I check the files，they are ok.
And already relink，rebuild and clean.
Still could not invoke ImageCropPicker.openPicker.
I didn't get the error：
W/ReactNativeJS(15493): Possible Unhandled Promise Rejection (id: 0):
W/ReactNativeJS(15493): Can only use lower 16 bits for requestCode

I also change：
W/ReactNativeJS(15493): Possible Unhandled Promise Rejection (id: 0):
W/ReactNativeJS(15493): Can only use lower 16 bits for requestCode

**Comment by woshizja** [comment]
I debug in a real mobile before，so I try the emulator，then I got the warn：
Possible Unhandled Promise Rejection (id: 0):
once I change IMAGE_PICKER_REQUEST  and CAMERA_PICKER_REQUEST ，anything I should do to make it effective？

**Comment by woshizja** [comment]
it's similar with #121

**Comment by ivpusic** [comment]
hm, would be great if you can turn on android studio and check stacktrace and get more debug info about error

**Comment by ivpusic** [comment]
@woshizja any updates here?

**Comment by woshizja** [comment]
sorry，I didn't use Android Studio（I am a FE engineer），I didn't solve the problem.
I decided to use [react-native-image-picker](https://github.com/marcshilling/react-native-image-picker).
anyway， thanks for your replay and code.

**Comment by joeferraro** [comment]
Experiencing a similar crash on iOS, followed install instructions multiple times to make sure
