### ISSUE TITLE
couldn't customize the text,i want to  localize

### ISSUE THREAD

**Issue by YuiGakki** [ivpusic/react-native-image-crop-picker#151]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.9.7
- react-native v0.36.0

### Platform
Tell us to which platform this issue is related

- iOS

### Steps to reproduce

1.

2.

3.

### Attachments

// stacktrace or any other useful debug info

**Comment by YuiGakki** [comment]
![image](https://cloud.githubusercontent.com/assets/19790418/20623327/03441462-b342-11e6-8dcb-626c11fd3544.png)
It doesn't work,always English

**Comment by ivpusic** [comment]
currently I have no plans of supporting this. If you are in for PR, will be very welcome.
