### ISSUE TITLE
[iOS]  openPicker cannot open modal until react native <Modal/> could be closed 0.63.4 

### ISSUE THREAD

**Issue by retyui** [ivpusic/react-native-image-crop-picker#1511]
### Version

- react-native-image-crop-picker v0.35.2
- react-native v0.63.4

### Platform

- iOS

### Expected behaviour

Work perfectly on react native 0.63.x

### Actual behaviour

After update to the latest react-native version 

Method `openPicker({multiple: true})` 
- open modal once on  iOS 13,14 devices
- never resolve promise on iOS 14 emulator

I use xcode debug and the next methood seems invoke each time but nothing happend (
```clang
[[self getRootVC] presentViewController:imagePickerController animated:YES completion:nil];
```

### Attachments

https://user-images.githubusercontent.com/4661784/104317261-647c2180-54e6-11eb-81db-ad17e28964f0.mp4

**Comment by christophemenager** [comment]
I have the exact same issue @retyui ! How did you solve it ? :)

**Comment by retyui** [comment]
@christophemenager 
You have to wait when the modal closed and then only invoke `openPicker`

**Comment by christophemenager** [comment]
Thanks :)

**Comment by vegerot12** [comment]
Hi , can you let me know how to handle it better , i have shared my implementation below, i have called the modal close before opening the picker but it doesnt seem to work. 

`const selectMultipleImages = async () => {
    await refRBSheet.current.close();
    ImagePicker.openPicker({
      mediaType:'photo',
      multiple: true,
      forceJpg: true, //only works in ios
      compressImageQuality: 0.8,
      maxFiles: 10, //only works in ios
    })`

**Comment by Rc85** [comment]
Happens with openCamera as well on iOS.

> Hi , can you let me know how to handle it better , i have shared my implementation below, i have called the modal close before opening the picker but it doesnt seem to work.
> 
> `const selectMultipleImages = async () => { await refRBSheet.current.close(); ImagePicker.openPicker({ mediaType:'photo', multiple: true, forceJpg: true, //only works in ios compressImageQuality: 0.8, maxFiles: 10, //only works in ios })`

Put the openPicker in setTimeout with 0.5ms
