### ISSUE TITLE
Create Custom Toolbar on Camera 

### ISSUE THREAD

**Issue by dl-husky73** [ivpusic/react-native-image-crop-picker#1514]
### Version
RNIMCP - ^0.35.2
RN - ^0.63.2

### Platform
- iOS
- Android

### Expected behaviour
Love this package!  I want to create custom buttons from Launch openCamera. Apple & iOS Camera App has a toolbar below image with buttons to open gallery or switch to video. I would like to add those buttons but can't seem to figure out how.

**Comment by ivpusic** [comment]
currently this is no possible. if you need custom camera view maybe try https://github.com/react-native-camera/react-native-camera
