### ISSUE TITLE
default crop area

### ISSUE THREAD

**Issue by zoom2009** [ivpusic/react-native-image-crop-picker#1516]
Is it possible when open cropping, crop area should full width height of image.

thank you

**Comment by sandeepg1220** [comment]
Looking for the same. Not able to crop with full width and height of image.

**Comment by tostavio** [comment]
Just remove `width` and `height` from params. The crop area will stay at image borders.

**Comment by jagwingchoy** [comment]
Hi there, I have tried removing both `width` and `height` from options, 
but the cropping area remains as a square inside iOS. Is it a normal case?
I want to let user freely resize the cropping area with different width and height.

**Comment by sandeepg1220** [comment]
@jagwingchoy  same for me too

**Comment by alexpluto** [comment]
Same for us as well on iOS

**Comment by alexpluto** [comment]
@zoom2009 are you able to replicate this on iOS?

**Comment by Maker-Mark** [comment]
Here's a complete example patch file to fix this issue for iOS, thanks @nabilfreeman for the fix above. I just added the typing into the patch too.

How to use:
- Create and add this file to the root of your repo: `patches/`
- add `"postinstall": "patch-package",` to your package.json inside `scripts`
- add `patch-package` to your `dependancies` (`npm i patch-package` or yarn add `patch package`)
- Reinstall dependancies(`npm i` or `yarn`) and the patch will run after the install 
- Now the default will be the entire image (as long as you dont have a screen larger than 2000x2000 px heh
[react-native-image-crop-picker+0.38.1.patch](https://github.com/ivpusic/react-native-image-crop-picker/files/10698808/react-native-image-crop-picker%2B0.38.1.patch)
