### ISSUE TITLE
Latest version (0.35.3) was not published to npm

### ISSUE THREAD

**Issue by ronfogel** [ivpusic/react-native-image-crop-picker#1524]
### Version
- react-native-image-crop-picker v0.35.2
- react-native v0.63.4

### Platform
npm

### Expected behaviour
when installing react-native-image-crop-picker it should install the latest version (unless stated other version)

### Actual behaviour
installing 0.35.2. it appears that the new version was not published to npm registry.

### Attachments
<img width="579" alt="Screen Shot 2021-02-01 at 16 22 46" src="https://user-images.githubusercontent.com/16741829/106471165-09689980-64aa-11eb-9d9e-13a4d15b4252.png">

**Comment by ivpusic** [comment]
tnx, just published
