### ISSUE TITLE
Multiple Image Selection for Android

### ISSUE THREAD

**Issue by yfng96** [ivpusic/react-native-image-crop-picker#1535]
### Version
- react-native-image-crop-picker v0.33.4
- react-native v0.63.3

### Platform
- Android

### Expected behaviour
 This package only provide maxFile for iOS, is there any method to limit the photo selection in Android?

**Comment by ivpusic** [comment]
currently not

**Comment by newyangkun** [comment]
@ivpusic When to add this feature? thanks
