### ISSUE TITLE
Nothing returned after selecting

### ISSUE THREAD

**Issue by ithieund** [ivpusic/react-native-image-crop-picker#154]
Hi,
I tried with openPicker and openCamera, the UI seems good, but then nothing returned after selecting images.

This happens in both AVD and Physical Android devices.
Please help.

Thanks.

**Comment by ivpusic** [comment]
Can you please provide stacktrace when this happens? You can take it from Android Studio

**Comment by ithieund** [comment]
@ivpusic ,
It worked now, I had something wrong with console.log() so that the result was not displayed.

Thank you very much for the awesome plugin.
