### ISSUE TITLE
iOS - unable to select more than 5 images at once

### ISSUE THREAD

**Issue by MOwais** [ivpusic/react-native-image-crop-picker#1544]
### Version
Tell us which versions you are using: 
"react-native-image-crop-picker": "^0.25.3",
"react-native": "0.62.2",

### Platform
Tell us to which platform this issue is related
iOS 12.5.1 iPad Air

### Expected behaviour
select more than 5 images at once

### Actual behaviour
unable to select more than 5 images at once

### Steps to reproduce

```
ImagePicker.openPicker({
  multiple: true
}).then(images => {
  console.log(images);
});
```

When image gallery is open, try to select more than 5 images at once. 

This works fine in Android.

**Comment by ivpusic** [comment]
use maxFiles option to specify max amount of files you want to select
