### ISSUE TITLE
How can I do this in Webstorm?

### ISSUE THREAD

**Issue by seymafirat** [ivpusic/react-native-image-crop-picker#1545]
No need to downgrade to 0.33.
Upgrade your gradle version ```classpath 'com.android.tools.build:gradle:4.0.1'``` or ```classpath('com.android.tools.build:gradle:4.0.1')```

_Originally posted by @Onibenjo in https://github.com/ivpusic/react-native-image-crop-picker/issues/1406#issuecomment-698246433_

**Comment by Onibenjo** [comment]
Same way. Just locate the build.gradle file and edit it

**Comment by seymafirat** [comment]
> Same way. Just locate the build.gradle file and edit it

Thank you, i fixed it
