### ISSUE TITLE
ios turkish language support

### ISSUE THREAD

**Issue by tufanlodos** [ivpusic/react-native-image-crop-picker#1549]
### Version

- react-native-image-crop-picker v0.35.0
- react-native v0.62.0

### Platform
- iOS

### Expected behaviour
turkish language support for ios

### Actual behaviour
does not support

**Comment by demirhancosku** [comment]
Actually, I can do that when I find some time. I'll let you know when I create a pr!

**Comment by ivpusic** [comment]
it merged here https://github.com/ivpusic/react-native-image-crop-picker/pull/1548
