### ISSUE TITLE
ios not working for me

### ISSUE THREAD

**Issue by Jaafar-abusair** [ivpusic/react-native-image-crop-picker#155]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker ^0.10.2
- react-native 0.37.0

### Platform

- iOS

### Expected behaviour
OpenCamera and imagePicker, will open the camera or image picker

### Actual behaviour
The application closed with no exceptoin

### Steps to reproduce

  ImagePicker
                .openCamera({cropping: true, width: 420, height: 300, includeBase64: true})
                .then(image => this._handleImageReceived(image))
                .catch((error) => {
                    console.debug(error);
                    // show error to the user
                });

### Attachments

// stacktrace or any other useful debug info

**Comment by Jaafar-abusair** [comment]
Needed to add the new permission methodology to plist file for camera and gallery and it worked

**Comment by ivpusic** [comment]
yes, it is new in ios 10
