### ISSUE TITLE
why Manifest.permission.WRITE_EXTERNAL_STORAGE required?

### ISSUE THREAD

**Issue by Jaafar-abusair** [ivpusic/react-native-image-crop-picker#156]
### Platform
Tell us to which platform this issue is related

- Android

### Attachments

// stacktrace or any other useful debug info

**Comment by ivpusic** [comment]
Good point. I just did a cleanup in following commit https://github.com/ivpusic/react-native-image-crop-picker/commit/65f3eccd42b5e3e5161b602517d6579c3e4ea12a. Could you please check on your side if still everything works?

**Comment by Jaafar-abusair** [comment]
Good point. I just did a cleanup in following commit 65f3ecc. Could you please check on your side if still everything works?

No it's not working

**Comment by ivpusic** [comment]
yes, I edited my comment and did revert of mentioned commit. Use version https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.10.7
