### ISSUE TITLE
no podspec found for 'react-native-image-crop-picker'

### ISSUE THREAD

**Issue by estemilia** [ivpusic/react-native-image-crop-picker#157]
**### Version**
- macOS version : sierra 10.12.1
- react-native-image-crop-picker v0.10.5
- react-native v0.38.1

**### Platform**
- iOS

**### Expected behaviour**
pod install react-native-image-crop-picker successfully

**### Actual behaviour**
$ pod install
Analyzing dependencies
Fetching podspec for `React` from `../node_modules/react-native`
Fetching podspec for `react-native-image-crop-picker` from `../node_modules/react-native-image-crop-picker/ios`
[!] No podspec found for `react-native-image-crop-picker` in `../node_modules/react-native-image-crop-picker/ios`

**### Steps to reproduce**

1. pod install, and i got message.
 "no podspec for 'react-native-image-crop-picker' in '../node_modules/react-native-image-crop-picker/ios'." 

2. so i try create new react-native app for test pod install again.
( https://github.com/ivpusic/react-native-image-crop-picker/issues/6#issuecomment-222647477 )

did i miss something?
please help.

**### Attachments**
iMac:~/Documents$ cd picker
iMac:~/Documents/picker$ npm i react-native-image-crop-picker --save
picker@0.0.1 /Users/username/Documents/picker
└── react-native-image-crop-picker@0.10.5
                                                                                                                                      
iMac:~/Documents/picker$ react-native link react-native-image-crop-picker
rnpm-install info Linking react-native-image-crop-picker android dependency
rnpm-install info Android module react-native-image-crop-picker has been successfully linked
rnpm-install info Linking react-native-image-crop-picker ios dependency
rnpm-install info iOS module react-native-image-crop-picker has been successfully linked

iMac:~/Documents/picker$ cd ios
iMac:~/Documents/picker/ios$ pod init
iMac:~/Documents/picker/ios$ ls
Podfile         picker          picker.xcodeproj    pickerTests

iMac:~/Documents/picker/ios$ pod install
Analyzing dependencies
Fetching podspec for `React` from `../node_modules/react-native`
Fetching podspec for `react-native-image-crop-picker` from `../node_modules/react-native-image-crop-picker/ios`
[!] No podspec found for `react-native-image-crop-picker` in `../node_modules/react-native-image-crop-picker/ios`

### podfile
```
 platform :ios, '8.0'

 target 'picker' do

   # Pods for picker
   pod 'RSKImageCropper'
   pod 'QBImagePickerController'
   pod 'React', :path => '../node_modules/react-native'
   pod 'react-native-image-crop-picker', :path => '../node_modules/react-native-image-crop-picker/ios'


   target 'pickerTests' do
     inherit! :search_paths
     # Pods for testing
   end

 end
```

### package json (i install react, react-native, react-native-image-crop-picker)
 ```
{
   "name": "picker",
   "version": "0.0.1",
   "private": true,
   "scripts": {
     "start": "node node_modules/react-native/local-cli/cli.js start",
     "test": "jest"
   },
   "dependencies": {
     "react": "15.4.1",
     "react-native": "0.38.1",
     "react-native-image-crop-picker": "^0.10.5"
   },
   "jest": {
     "preset": "react-native"
   },
   "devDependencies": {
     "babel-jest": "17.0.2",
     "babel-preset-react-native": "1.9.0",
     "jest": "17.0.3",
     "react-test-renderer": "15.4.1"
   }
 }


```

**Comment by ivpusic** [comment]
please follow installation steps described here https://github.com/ivpusic/react-native-image-crop-picker#install.

**Comment by ashusdn** [comment]
@ivpusic  I have followed same steps as described but when to try to install pod it gives an error:

No podspec found for `react-native-image-crop-picker` in `../node_modules/react-native-image-crop-picker`

=======Pod file Code =============================

# Uncomment the next line to define a global platform for your project
 platform :ios, ‘8.0’

target 'Planzz' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Planzz
	pod 'react-native-image-crop-picker',
       :path => '../node_modules/react-native-image-crop-picker'
  target 'PlanzzTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

==================================================

  "react-native": "0.45.1",
"react-native-image-crop-picker": "^0.15.1",


Can you please provide any solution for it.

**Comment by ivpusic** [comment]
I just published new version to npm which includes Podfile. I tried it by myself and it seems that there are still some issues with cocoapods. However, currently, I don't have time to fix this. Would be very helpful if you can try latest version and try to get it working.

**Comment by codingplayboy** [comment]
I add my own podspec file as:

```
package = JSON.parse(File.read(File.join(__dir__, "../", "package.json")))
version = package['dependencies']['react-native-image-crop-picker']

Pod::Spec.new do |s|
  s.name             = "RNImageCropPicker"
  s.version          = version
  s.summary          = "RNImageCropPicker"
  s.requires_arc = true
  s.license      = 'MIT'
  s.homepage     = 'n/a'
  s.authors      = { "ivpusic" => "" }
  s.source       = { :git => "https://github.com/ivpusic/react-native-image-crop-picker.git", :tag => "v#{s.version}"}
  s.source_files = 'ios/src/*.{h,m}'
  s.platform     = :ios, "8.0"
  s.dependency 'RSKImageCropper'
  s.dependency 'QBImagePickerController'
  s.dependency 'React/Core'
end
```

Then in Podfile, just link my own podspec fiel:

```
pod 'RNImageCropPicker',  :podspec => './Podspecs/react-native-image-crop-picker.podspec'
```

it will be ok.

**Comment by ravi-thokal** [comment]
Step 1:
npm i react-native-image-crop-picker --save

Step 2 :
cd ios
pod install

Step 3 :
cd .. 

Step 4 : 
npx react-native run-ios

Hope this will help!!

**Comment by sandiptarsariya** [comment]
> ec for `react-native-image-crop-picker` from `../node_modules/react-native-image-crop-picker/ios`

change our profiles file  remove this line
`react-native-image-crop-picker` from `../node_modules/react-native-image-crop-picker/ios`
after install pod

**Comment by lavisar** [comment]
> Try
> 
> ### pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'
> worked for me Step 1 : add above line to Podfile Step 2 : cd ios && pod install && pod update

This solution worked for me also
My package version
react-native: 0.74
react-native-image-crop-picker: 0.41.2
