### ISSUE TITLE
How tto use this library as peer dependency

### ISSUE THREAD

**Issue by priyankagupta23pg** [ivpusic/react-native-image-crop-picker#1576]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.?.?36.0
- react-native v0.?.?tried 64 and 62.2

### Platform

- iOS
- Android

### Expected behaviour
I am trying to use this library in my react library so added it in peer dependency in package.json
But still getting as umdefined to open picker

### Actual behaviour
It should work

Please suggest steps for this
### Steps to reproduce

1.

2.

3.

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by ivpusic** [comment]
unfortunately cannot offer a help with this one
