### ISSUE TITLE
[HELP REQUIRED]: Selected Image gets blurry on IOS. Is there an option to disable image compression?

### ISSUE THREAD

**Issue by suryateja77** [ivpusic/react-native-image-crop-picker#1577]
Version
- react-native-image-crop-picker v^0.34.1
- react-native v0.63.3

Platform
- iOS
- Android

Current behavior
- According to the docs, compressImageQuality defaults to 0.8 for IOS and 1 for Android

Is there a way to disable the compression?

**Comment by 1275741406** [comment]
https://github.com/ivpusic/react-native-image-crop-picker/issues/1564

**Comment by suryateja77** [comment]
Adding a fixed height and width worked for me. Here is the sample code.
ImagePicker.openPicker({
      freeStyleCropEnabled: true,
      cropping: true,
      height: 1000,
      width: 1000,
      writeTempFile: false,
      compressImageQuality: 0.8,
    })
    .then(()=>{})
    .catch(()=>{})

**Comment by blackirishmec** [comment]
I almost missed the fix here. If you are using freeStyleCropEnabled with openPicker or openCropper you **still** need to have a set height and width or else the resulting image gets blurry af compared to what you see when you press 'choose' on the cropper.
