### ISSUE TITLE
Jitpack.io is down. Is there a way around using it?

### ISSUE THREAD

**Issue by cellis** [ivpusic/react-native-image-crop-picker#1578]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.36.0?
- react-native v0.63.4

### Platform

Android

### Expected behaviour

While building a release, expect it to complete successfully with an APK file.

### Actual behaviour

```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:mergeReleaseAssets'.
> Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.
   > Could not resolve com.github.yalantis:ucrop:2.2.6-native.
     Required by:
         project :app > project :react-native-image-crop-picker
      > Could not resolve com.github.yalantis:ucrop:2.2.6-native.
         > Could not get resource 'https://www.jitpack.io/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom'.
            > Could not GET 'https://www.jitpack.io/com/github/yalantis/ucrop/2.2.6-native/ucrop-2.2.6-native.pom'.
               > Read timed out
```

### Steps to reproduce

1. Create new CRA native project

2. Attempt to build with no jitpack repo cache

### Attachments

See here: https://github.com/jitpack/jitpack.io/issues/4539

**Comment by mickamy** [comment]
Guess you can publish it to mavenLocal and use it in your project.
Clone com.github.yalantis:ucrop:2.2.6-native and run `./gradlew publishToMavenLocal`.
And in your project build.gradle, add following lines.
```
allprojects {
    repositories {
        mavenLocal()
        // other maven repos...
    }
}
```

https://docs.gradle.org/current/userguide/publishing_maven.html

If you were to build it on CI or somewhere, you can build the module as a .jar file and include it in your project.

**Comment by tommeier** [comment]
https://twitter.com/jitpack/status/1389766485057363968?s=20

**Comment by Seanmclem** [comment]
I had to update react-native-braintree-dropin-ui to the latest version, with something like `yarn upgrade react-native-braintree-dropin-ui`
