### ISSUE TITLE
Could support Chinese when crop image on IOS

### ISSUE THREAD

**Issue by sharingjingang050241** [ivpusic/react-native-image-crop-picker#158]
Can this component change to Chinese when crop image 
  @@![b16b19c7-c2a1-4ce1-844c-3d1dd41b96f8](https://cloud.githubusercontent.com/assets/20335157/20921985/7c7074b4-bbe1-11e6-9211-be53c1dbdfc7.png)

**Comment by ivpusic** [comment]
currently I have no plans of adding this feature

**Comment by litingjun2015** [comment]
@sharingjingang050241 ，
http://blog.csdn.net/rnclcl/article/details/41749749

设置Localization native development region的字段
该字段默认为en即英文，改为china即可将该app内的软件设为中文，实测ok

![fix](https://cloud.githubusercontent.com/assets/13675353/22056516/74fdf1d0-dd9b-11e6-8a5b-41855b7cc89f.png)

**Comment by HankinsPan** [comment]
@litingjun2015 thanks for You!

**Comment by bozaigao** [comment]
@litingjun2015 问题解决,非常感谢!
