### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by quadsurf** [ivpusic/react-native-image-crop-picker#160]
react-native-image-crop-picker version: the latest
react-native version: 0.39
platforms: both

rather than requesting features, i would love to PR some of the features mentioned below, but unfortunately i'm brand new to coding so it's beyond my current capabilities... pls forgive

1. is support for RNMP rather than cocoapods on the roadmap, and if so, is there a projected release date?
2. is the "useFrontCamera" property for Android on the roadmap, and if so, is there a projected release date?
3. is the "compressVideo" property for Android on the roadmap, and if so, is there a projected release date?
4. does the "compressVideo" property have a preset that compresses video using a predefined schema, or are there hidden compression parameters that I can tweak in your core code to set for example a custom bit rate? And if yes, where exactly in your library's code is that?

**Comment by ivpusic** [comment]
1. what is RNMP?
2. PR welcome
3. PR welcome
4. You can check out this function to get more info what is happening under the hood for ios video compression https://github.com/ivpusic/react-native-image-crop-picker/blob/master/ios/ImageCropPicker.m#L228

**Comment by quadsurf** [comment]
RNPM is a more efficient alternative to Cocoapods, and in the last year has become the new standard for installing platform dependent packages. It's been so successful and widely adopted, that React Native finally adopted it into the React Native Core.

https://github.com/rnpm/rnpm

Thank you for sharing with me the exact line of code where video compression occurs. Much appreciated.

**Comment by ivpusic** [comment]
ahaa, you mean rnpm not "nnmp". Installation with rnpm is already supported. Cocoapods is used as alternative for adding required external dependencies. It is not required to use cocoa. Check readme file for more details.
