### ISSUE TITLE
 TypeError: _reactNativeImageCropPicker.default.openCamera is not a function. (In '_reactNativeImageCropPicker.default.openCamera({           width: 300,           height: 400,           cropping: true         })', '_reactNativeImageCropPicker.default.openCamera' is undefined)

### ISSUE THREAD

**Issue by lavinagandhi14** [ivpusic/react-native-image-crop-picker#1602]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v"^0.4.4"
- react-native v"^0.63.3"

### Platform
iOS and Android both
- iOS
- Android

### Expected behaviour
On clicking ImagePicker.openCamera(), I want the camera to get open.

### Actual behaviour
but getting error as 
 TypeError: _reactNativeImageCropPicker.default.openCamera is not a function. (In '_reactNativeImageCropPicker.default.openCamera({
          width: 300,
          height: 400,
          cropping: true
        })', '_reactNativeImageCropPicker.default.openCamera' is undefined)
        
[](url)

### Steps to reproduce

1.

2.

3.

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by ivpusic** [comment]
looks like library was not properly installed. could you check installation steps from readme file?
