### ISSUE TITLE
TypeError: _reactNativeImageCropPicker.default.openCamera is not a function.

### ISSUE THREAD

**Issue by lavinagandhi** [ivpusic/react-native-image-crop-picker#1603]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v"^0.4.4"
- react-native v"^0.63.3"

### Platform
Tell us to which platform this issue is related
- iOS
- Android
![Simulator Screen Shot - iPhone 12 - 2021-06-03 at 10 42 53](https://user-images.githubusercontent.com/79911852/120594940-45fbd000-c45f-11eb-9b0d-4369c58887b7.png)

### Expected behaviour
On calling the function ImagePicker.openCamera(), I want that the camera should open

### Actual behaviour
but getting this error with a red screen:
 TypeError: _reactNativeImageCropPicker.default.openCamera is not a function. (In '_reactNativeImageCropPicker.default.openCamera({
          width: 300,
          height: 400,
          cropping: true

### Steps to reproduce

1.

2.

3.

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by krunalbad** [comment]
this is something maybe related to pods are not installed. can you check if its properly installed or not

**Comment by heerma** [comment]
the same issue happens for me as well with Expo. Did somebody find out what it is about? you don't have to link packages there

**Comment by ivpusic** [comment]
looks like library is not properly installed. please follow readme for instructions
