### ISSUE TITLE
Custom SVG shape for crop overlay

### ISSUE THREAD

**Issue by beshur** [ivpusic/react-native-image-crop-picker#1605]
Hello.

Is is possible to set a custom crop overlay - instead of circle or square I want to use a custom SVG shape.

I still want to get a rectangular image in output, just need a UI effect.

**Comment by ivpusic** [comment]
currently not possible. we are using uCrop for cropping

**Comment by unstopp** [comment]
This would be great.. any way this can be done? Maybe at least overlaying the shape somehow and still use the original cropper?
