### ISSUE TITLE
Package not getting installed

### ISSUE THREAD

**Issue by 16ntu1120** [ivpusic/react-native-image-crop-picker#1614]
npm ERR! File exists: D:\React Native\test\test\test\node_modules\.bin\yarn
npm ERR! Remove the existing file and try again, or run npm

Whenever I try to install this package get this error how can I resolve it and easily install the app?
Help needed urgently.
Thanks in advance!

**Comment by ivpusic** [comment]
looks like error is not related to this library. closing this one
