### ISSUE TITLE
How can I select Videos?

### ISSUE THREAD

**Issue by ithieund** [ivpusic/react-native-image-crop-picker#162]
Hi,
I haven't tested it in iOS but in Android, the Image Picker shows images only, I can't find  any video to select.

Can you please help?
Thanks.

**Comment by ivpusic** [comment]
videos should be shown by default

**Comment by superandrew213** [comment]
@ivpusic I'm having the same issue. Videos don't show up on Android.

**Comment by ivpusic** [comment]
are you using android 7? if yes, then this is known issue currently. On Android 7 when you put multiple mime types into intent, only one mime type gets shown.

**Comment by superandrew213** [comment]
I'm using Android 6. The issue seems to be [here](https://github.com/ivpusic/react-native-image-crop-picker/blob/master/android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java#L305)

There seem to be different ways to set multiple MIME types:

```
galleryIntent.setType("image/*,video/*");

galleryIntent.setType("image/*|video/*");

galleryIntent.setType("image/* video/*");
```
(only the first MIME types seems to get picked here)

OR
```
String[] mimetypes = {"image/*", "video/*"};
galleryIntent.putExtra(Intent.EXTRA_MIME_TYPES, mimetypes);
```

None of them seem to be working properly

**Comment by superandrew213** [comment]
@ivpusic this works:
```
String[] mimetypes = {"image/*", "video/*"};
galleryIntent.setType("*/*");
galleryIntent.putExtra(Intent.EXTRA_MIME_TYPES, mimetypes);
```

```galleryIntent.setType("*/*");``` is required but selections are still limited to images and videos.

Let me know if you want a PR to test

**Comment by ivpusic** [comment]
this looks great. could you just do some additional checks if files except images/videos can be picked?

**Comment by superandrew213** [comment]
Looks like that. I only have PDFs on my phone and they are greyed out and can't be selected

**Comment by ivpusic** [comment]
then let's go with PR. I will also try it :). Tnx

**Comment by ithieund** [comment]
@ivpusic ,
When will this be fixed?

Thanks.

**Comment by superandrew213** [comment]
@ithieund this has already been fixed. Are you using the latest version of react-native-image-crop-picker?

**Comment by ithieund** [comment]
@superandrew213 ,
I'll try and let you know.

Thanks.

**Comment by Strate** [comment]
Just fall into exactly same issue on android with fresh version of the library.
