### ISSUE TITLE
Is it possible to capture multiple images at a time from camera ?

### ISSUE THREAD

**Issue by bhaskarpraveen61** [ivpusic/react-native-image-crop-picker#1621]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.36.2
- react-native v0.64.2

### Platform
Tell us to which platform this issue is related

- iOS
- Android

### Expected behaviour
Allowing multiple images to capture when camera is launched

### Actual behaviour
Allows to capture one image at a time

**Comment by ivpusic** [comment]
no possible currently

**Comment by VM8198** [comment]
Any updates here? Any libraries which can do this? Capture multiple images at a time?
