### ISSUE TITLE
IOS Give option to free style crop instead of 1:1 square crop option.

### ISSUE THREAD

**Issue by c-info** [ivpusic/react-native-image-crop-picker#1626]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.36.2
- react-native v0.64.2

### Platform
- iOS

### Expected behaviour
IOS user can only crop in square form mean 1:1 how user can crop free style or give options to crop in other ratio as Android uCrop gives 

### Actual behaviour
User can only crop image in square form. 

### Steps to reproduce

1. Pick image using any picker

2. crop image in IOS 

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by prashen** [comment]
@c-info Is that solved? That is why you closed it. I am still facing it. How to find android like crop options in ios with different ratios.

**Comment by oguzturker8** [comment]
It's not solved. Having same issue.
For a workaround use reset button before cropping

Before resetting             |  After resetting
:-------------------------:|:-------------------------:
<img src="https://user-images.githubusercontent.com/33129613/140439901-d45ef067-ee99-42a0-a8e1-467c4ac7fa7c.png" alt="drawing" width="369"/> |  <img src="https://user-images.githubusercontent.com/33129613/140439794-bb38d580-7aee-46d2-b2f5-4c1f4efc3483.png" alt="drawing" width="369"/>

**Comment by Maker-Mark** [comment]
Here's a complete example patch file to fix this issue for iOS, thanks @nabilfreeman for the fix above. I just added the typing into the patch too.

How to use:
- Create and add this file to the root of your repo: `patches/`
- add `"postinstall": "patch-package",` to your package.json inside `scripts`
- add `patch-package` to your `dependacies` (`npm i patch-package` or yarn add `patch package`)
- Reinstall dependancies(`npm i` or `yarn`) and the patch will run after the install 
- Now the default will be the entire image (as long as you dont have a screen larger than 2000x2000 px heh
[react-native-image-crop-picker+0.38.1.patch](https://github.com/ivpusic/react-native-image-crop-picker/files/10698808/react-native-image-crop-picker%2B0.38.1.patch)
