### ISSUE TITLE
java.util.List android.net.Uri.getPathSegments()

### ISSUE THREAD

**Issue by rocwangv** [ivpusic/react-native-image-crop-picker#163]
### Version

- react-native-image-crop-picker :  v0.10.8
- react-native v0.38.0
- gradle :v2.10

### Platform
- Android (Xiaomi MI 5 [android 6.0.1, api 23])

### Error

when I call ` ImagePicker.openPicker`,  open the photo album and select one photo , error appears:
> [Error: Attempt to invoke virtual method 'java.util.List android.net.Uri.getPathSegments()' on a null object reference] framesToPop: 1, code: 'E_NO_IMAGE_DATA_FOUND' }

**Comment by rocwangv** [comment]
My code wrote like this:
>ImagePicker.openPicker({
            multiple: true,
            maxFiles: 6
        }).then(images => {
           //TODO
        }).catch(err=> {
            console.log(err)
        });

**Comment by ivpusic** [comment]
could you provide full stacktrace when this error happens? Thanks

**Comment by rocwangv** [comment]
Thank you for replying;
Here are my Android Studio's log :
>12-09 17:29:09.002 15919-15919/com.xxx.yyy E/unknown:React: Received an ACTION_CANCEL touch event for which we have no corresponding ACTION_DOWN
12-09 17:29:09.718 15919-16026/com.xxx.yyy I/Timeline: Timeline: Activity_launch_request time:15541238
12-09 17:29:10.234 15919-15934/com.xxx.yyy D/AppForegroundWatcher: 1/app in background
12-09 17:29:13.398 15919-15919/com.xxx.yyy I/openSDK_LOG.Tencent: onActivityResultData() reqcode = 61110, resultcode = -1, data = null ? false, listener = null ? false
12-09 17:29:13.398 15919-15919/com.xxx.yyy I/openSDK_LOG.UIListenerManager: onActivityResult req=61110 res=-1
12-09 17:29:13.399 15919-15919/com.xxx.yyy E/openSDK_LOG.UIListenerManager: getListner action is null! rquestCode=61110
12-09 17:29:13.401 15919-15934/com.xxx.yyy D/AppForegroundWatcher: 1/app on foreground
12-09 17:29:13.412 15919-16025/com.xxx.yyy I/ReactNativeJS: { [Error: Attempt to invoke virtual method 'java.util.List android.net.Uri.getPathSegments()' on a null object reference] framesToPop: 1, code: 'E_NO_IMAGE_DATA_FOUND' }
12-09 17:29:13.422 15919-16014/com.xxx.yyy W/unknown:React: You seem to be running on device. Run 'adb reverse tcp:8081 tcp:8081' to forward the debug server's port to the device.
12-09 17:29:13.437 15919-16480/com.xxx.yyy W/unknown:JSPackagerWebSocketClient: Couldn't connect to packager, will silently retry

**Comment by ivpusic** [comment]
hm, sorry but this didn't help that much 😄. Do you have some time to try to debug it? Would be very helpful because I don't have device you have. On my android 6 devices it works well.

**Comment by rocwangv** [comment]
Thx anyway!!  I will look into it at my spare time. If someone else had this issue too , plz reply me ,thank you guys ! 😄

**Comment by ivpusic** [comment]
@rocwangv could you please try latest version? You still get this issue or?

**Comment by rocwangv** [comment]
I don't know how to solve this issue ,and it doesn't reproduce any more. Perhaps caused by my project config , I'll close this issue !

**Comment by damoguyan8844** [comment]
on android, if you download a gif and  save it to gallery, then open the gif with 'ImagePicker.openPicker' , it will reproduce!

**Comment by damoguyan8844** [comment]
@rocwangv , can you check it?
