### ISSUE TITLE
[ENHANCEMENT] Expose Compression API

### ISSUE THREAD

**Issue by philpettican** [ivpusic/react-native-image-crop-picker#1636]
We are currently using react-native-image-crop-picker in our main app to select images/videos which are then uploaded using an API and it works well.

We also have a share extension that allows the user to share images/videos from their gallery to the app. When the user shares an image/video and selects our app, the share extension passes the file path. When we try to upload the file at this point, depending on the file, it will fail due to file size (because the file hasn't been compressed).

It would be great if the compression API was exposed externally so that we could compress the files by passing a file path and returns a compressed image/video.

**Comment by UsamaAshraf82** [comment]
+1

**Comment by ivpusic** [comment]
currently having no plans of exposing it, but would accept a PR if you have some time to play with it
