### ISSUE TITLE
Guide / Help for Noobs setting up Cocoa Pods

### ISSUE THREAD

**Issue by joncursi** [ivpusic/react-native-image-crop-picker#164]
I have a decently sized React Native app and to this point I haven't had to touch Cocoa Pods at all. I'm a JavaScript developer, so reaching into the world of Cocoa Pods is foreign to me.

I first tried installing this package the manual way to avoid Cocoa Pods, but ran into [production build issues](https://github.com/ivpusic/react-native-image-crop-picker/issues/61) which, from the looks of it, would require manual steps in Xcode every time I want to build. That's a no-go.

From the issue thread linked above and various others, I get the impression that going the Cocoa Pods route means the configuration for this package is done once up front, for both development debugging and production builds, and after that you don't have to worry about it ever again. It "just works". That is what I am after, but unfortunately as a CocoaPods noob I need help getting there with this package.

I have started down the Cocoa Pods route, but ran into trouble. This is what I've done:

1. `yarn add react-native-image-crop-picker`
2. `react-native link`
3. `gem install cocoapods`
4. `cd ios && pod init`
5. Pod file:

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

# Uncomment this line if you’re using Swift
# use_frameworks!

target "MyApp" do
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'
end
```

6. `pod install` (succeeds)
7. Clearing out all of Xcode's derived data: `rm -rf /Users/me/Library/Developer/Xcode/DerivedData/` and restarting the RN packager and Xcode
8. Attempting to build for iPhone 7 from MyApp.xcodeproj, but failing
9. Attempting to build for iPhone 7 from MyApp.xcworkspace instead of MyApp.xcodeproj, but failing

I get this error: https://github.com/ivpusic/react-native-image-crop-picker/issues/27

```
ld: warning: directory not found for option '-L/Users/Kotori/Library/Developer/Xcode/DerivedData/bosspower-estwxlnmygshocelqgoskkpxmitw/Build/Products/Debug-iphonesimulator/QBImagePickerController'
ld: library not found for -lQBImagePickerController
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I'm not sure if this is because I need to do something special to get CocoaPods integrated with React Native (something I am not aware of outside the steps listed above?), or?

Hoping for some insight from someone more versed in CocoaPods than I obviously am. Been struggling on the configuration too much here. Thanks!

**Comment by ivpusic** [comment]
```
react-native init MyApp
cd MyApp
react-native install react-native-image-crop-picker
cd ios
pod init
vim Podfile

# add this to podfile
platform :ios, '8.0'

target 'MyApp' do
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'
end
#

pod install
cd ../
react-native run-ios
# have fun
```

**Comment by adamgins** [comment]
HI I seem to have a similar issue.

My pod file is : 
```
# You Podfile should look similar to this file. Whether you use_frameworks! or not, the following configuration should work.
#
# However if you DO NOT use_frameworks! and you prefer to install pods instead of
# dragging the AirMaps directory into your project, refer to the comments below (steps 1~4)

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

# Change 'buzzy8' to match the target in your Xcode project.
target 'buzzy8' do
  pod 'React', path: '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTActionSheet',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',

  ]

  pod 'RSKImageCropper'
  pod 'QBImagePickerController'

# when not using frameworks  we can do this instead of including the source files in our project (1/4):
# pod 'react-native-maps', path: '../../'
#	pod 'react-native-google-maps', path: '../../'  # <~~ if you need GoogleMaps support on iOS

# when not using frameworks  we can remove this line (2/4):
  pod 'GoogleMaps'  # <~~ remove this line if you do not want to support GoogleMaps on iOS
end

# when not using frameworks this might be necessary, but try without it first and see if `pod install` works (3/4):
# THIS IS ONLY NECESSARY IF YOU NEED GoogleMaps SUPPORT
# pre_install do |installer|
  # # copied from https://github.com/CocoaPods/CocoaPods/issues/2926
  # # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
  # def installer.verify_no_static_framework_transitive_dependencies; end
# end

# when not using frameworks (4/4):
# THIS IS ONLY NECESSARY IF YOU NEED GoogleMaps SUPPORT
# #Crud, this shouldn't be necessary, but https://github.com/CocoaPods/CocoaPods/issues/5429
# post_install do |installer|
#   	installer.pods_project.targets.each do |target|
# 		target.build_configurations.each do |config|
#       		config.build_settings['CLANG_ENABLE_MODULES'] = 'NO'
#     	end
#   	end
# end
```

the result of running `pod install --verbose` is 

```
Integrating target `Pods-buzzy8` (`buzzy8.xcodeproj` project)
  - Running post install hooks
    - cocoapods-stats from `/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-1.0.0/lib/cocoapods_plugin.rb`

Sending stats
      - GoogleMaps, 2.1.1
      - QBImagePickerController, 3.4.0
      - RSKImageCropper, 1.5.2
      - React, 0.40.0

-> Pod installation complete! There are 13 dependencies from the Podfile and 4 total pods installed.

[!] [Xcodeproj] Generated duplicate UUIDs:


```

No not sure if it's the duplicate ID's or that's a separate thing.. I tried lookin that up but have not found and answer yet

Any help appreciated

**Comment by nvme978** [comment]
@joncursi were you able to fix your issue. I'm was in the same boat as you and followed the same steps. 

ld: library not found for -limageCropPicker
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by joncursi** [comment]
I solved my woes with setting this thing up by migrating to https://github.com/react-community/react-native-image-picker

**Comment by wasedaigo** [comment]
@nvme978 Removing libimageCropPicker.a and readding it fixed the issue for me(Originally, the icon of the framework looked wrong in the linker setting). I am using Carthage though.
