### ISSUE TITLE
Getting issue on TestFlight

### ISSUE THREAD

**Issue by krishbhattacharyya** [ivpusic/react-native-image-crop-picker#165]
Thanks for "react-native-image-crop-picker" @ivpusic . This is really helpful & working fine as expected. 

I have used this in my current project but getting error on permissions while uploading in TestFlight. 

Can you help me to uploading the error free upload in TestFlight or in production level. 

If you provide me some screen shots for Xcode setup("react-native-image-crop-picker"), it will be better for me & advanced thanks for your valuable time.

**Comment by Msspl-PrashenjeetRoy** [comment]
I am also facing the issue when uploading to testflight getting email from apple team. It was working nice without the crop picker plugin added. When I added this library and uploaded it to appstore it showing like this.

Dear developer,

We have discovered one or more issues with your recent delivery for "AppName". To process your delivery, the following issues must be corrected:

Invalid Bundle - One or more dynamic libraries that are referenced by your app are not present in the dylib search path. 

In itunes connect page.... 
![screen shot 2016-12-14 at 12 24 41 pm](https://cloud.githubusercontent.com/assets/16461603/21172511/652358e0-c1f8-11e6-8121-5184c82ab0fd.png)

So What are those issue can you please tell us. It will be so much helpful and one more thing is there any live app do you know working on appstore or playstore with your crop picker plugin.

**Comment by Msspl-KrishnenduBhattacharyya** [comment]
By the way I am using "react-native-image-crop-picker : 0.10.5"

**Comment by ivpusic** [comment]
please refer to this issue https://github.com/ivpusic/react-native-image-crop-picker/issues/61. My suggestion is to use cocoa-pods to manage external dependencies, and you won't have a headache about this. I have app on testflight without problems.

**Comment by Msspl-PrashenjeetRoy** [comment]
OK so you are using cocoa-pods. Let me try this them close this issue.

**Comment by ivpusic** [comment]
if you don't have experience with cocoa pods, you can refer to this https://github.com/ivpusic/react-native-image-crop-picker/issues/164

**Comment by Msspl-PrashenjeetRoy** [comment]
# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'myApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ohreactnative
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'

  target 'myAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end


------ 
When I have generated podfile then these options were there. Will this work? I have added two pod file of your plugin and also added platform ios version.

**Comment by ivpusic** [comment]
you can use this

```
platform :ios, '8.0'

target 'myApp' do
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'
end
```

**Comment by Msspl-PrashenjeetRoy** [comment]
I am getting this issue while building on device iphone 5c:

![screen shot 2016-12-14 at 4 10 03 pm](https://cloud.githubusercontent.com/assets/16461603/21179036/3a4c99a4-c218-11e6-8161-8d0af23bd9a4.png)

Now what to do?

**Comment by ivpusic** [comment]
probably try to clean project, do `pod install`, and it should work. Also make sure that `pod install` is not throwing warnings/exceptions

**Comment by Msspl-PrashenjeetRoy** [comment]
hi @ivpusic ,

MSSPLs-iMac-07:ios appdeveloper$ pod install
Analyzing dependencies
Downloading dependencies
Using QBImagePickerController (3.4.0)
Using RSKImageCropper (1.5.1)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 2 dependencies from the Podfile and 2 total pods installed.
MSSPLs-iMac-07:ios appdeveloper$ pod install
Analyzing dependencies
Downloading dependencies
Using QBImagePickerController (3.4.0)
Using RSKImageCropper (1.5.1)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 2 dependencies from the Podfile and 2 total pods installed.


Above msg shown the pods installed successfully. Then what is the problem.

**Comment by ivpusic** [comment]
did you open `myApp.xcworkspace`?

**Comment by Msspl-PrashenjeetRoy** [comment]
yes I have opened it and then creating a build but build failed. showing 14 errors

**Comment by Msspl-PrashenjeetRoy** [comment]
![screen shot 2016-12-14 at 5 27 22 pm](https://cloud.githubusercontent.com/assets/16461603/21181189/b8334cd2-c222-11e6-8ed5-df99eb9b0e36.png)

This is the error when building on iphone-5c
1- i have clean the old builds
2- even I have cleaned derived data
3- then I run the build command 
4- then getting this issue.

Have any idea?

**Comment by ivpusic** [comment]
probably this is the point where you will have to try to figure it out :)

**Comment by Msspl-PrashenjeetRoy** [comment]
What will be the solution ..... ? What do you think?

**Comment by krishbhattacharyya** [comment]
Hi friend @ivpusic ,

If you can find out any solution please add this. This module is basically wonderful but seems to need some work. Please fixed this ASAP.

**Comment by nihp** [comment]
I have the same issue which mentioned above. I don't have any idea to solve this. Kindly let me know your thoughts


>>>>>
We have discovered one or more issues with your recent delivery for "AppName". To process your delivery, the following issues must be corrected:

Invalid Bundle - One or more dynamic libraries that are referenced by your app are not present in the dylib search path.

**Comment by joeljerushan** [comment]
this was a good plugin but im having following issue when i upload archive to Apple Connect :( 

![image](https://user-images.githubusercontent.com/10111309/61326398-4885ba00-a834-11e9-9f23-e08fbd45aadb.png)

cant you give me a quick fix ?

**Comment by mehrapratham** [comment]
if you are not using Cocoapods
-- Click on project General tab
-- Under Deployment Info set Deployment Target to 8.0
-- Under Embedded Binaries click + and add RSKImageCropper.framework and 
     QBImagePicker.framework
Thanks
