### ISSUE TITLE
not working on iOS 15

### ISSUE THREAD

**Issue by domenicoprestia** [ivpusic/react-native-image-crop-picker#1657]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.63.4
- react-native v0.64.2

### Platform
Tell us to which platform this issue is related

- iOS

### Expected behaviour

open gallery and open camera working correctly on iOS 15

### Actual behaviour

open gallery and open camera not working on iOS 15, nothing happens, neither crash or errors

### Steps to reproduce

1. install iOS 15

2. try to use the library on the iOS version

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by jpudysz** [comment]
For me it works on IOS15

**Comment by ivpusic** [comment]
works for me as well. maybe recheck if the problem is something else, and open a bit more specific issue
