### ISSUE TITLE
expo config plugin

### ISSUE THREAD

**Issue by mwegener-com** [ivpusic/react-native-image-crop-picker#1661]
Since expo launched its dev client and config plugins, this library should work in the half-managed workflow.

Is there already a third-party or inbuilt [config plugin](https://docs.expo.dev/guides/config-plugins/) for react-native-image-crop-picker?

**Comment by theobouwman** [comment]
I installed:
```
    "react-native-image-crop-picker": "^0.36.4",
    "with-rn-image-crop-picker": "^0.2.0"
```
And use this code:
```
import ImagePicker from 'react-native-image-crop-picker';
 ImagePicker.openPicker({
            width: 300,
            height: 400,
            cropping: true
        }).then(image => {
            console.log(image);
        });
```

 then get this error...

**Comment by ArthurDias01** [comment]
> I installed:
> 
> ```
>     "react-native-image-crop-picker": "^0.36.4",
>     "with-rn-image-crop-picker": "^0.2.0"
> ```
> 
> And use this code:
> 
> ```
> import ImagePicker from 'react-native-image-crop-picker';
>  ImagePicker.openPicker({
>             width: 300,
>             height: 400,
>             cropping: true
>         }).then(image => {
>             console.log(image);
>         });
> ```
> 
> then get this error...

same error here: TypeError: null is not an object (evaluating 'ImageCropPicker.openPicker')

**Comment by sunset1234321** [comment]
seems this lib not usable in expo yet

**Comment by mwegener-com** [comment]
> seems this lib not usable in expo yet 

Just use the mentioned config plugin.

**Comment by mwegener-com** [comment]
> > I installed:
> 
> > 
> 
> > ```
> 
> >     "react-native-image-crop-picker": "^0.36.4",
> 
> >     "with-rn-image-crop-picker": "^0.2.0"
> 
> > ```
> 
> > 
> 
> > And use this code:
> 
> > 
> 
> > ```
> 
> > import ImagePicker from 'react-native-image-crop-picker';
> 
> >  ImagePicker.openPicker({
> 
> >             width: 300,
> 
> >             height: 400,
> 
> >             cropping: true
> 
> >         }).then(image => {
> 
> >             console.log(image);
> 
> >         });
> 
> > ```
> 
> > 
> 
> > then get this error...
> 
> 
> 
> same error here: TypeError: null is not an object (evaluating 'ImageCropPicker.openPicker')

Expo dev client installed?

**Comment by mwegener-com** [comment]
> seems this lib not usable in expo yet 

It is usable with expo dev client. Just install the mentioned config plugin

**Comment by ArthurDias01** [comment]
> > seems this lib not usable in expo yet
> 
> It is usable with expo dev client. Just install the mentioned config plugin

I've tried everything and couldn't make it to work...

**Comment by mwegener-com** [comment]
> > > seems this lib not usable in expo yet
> 
> > 
> 
> > It is usable with expo dev client. Just install the mentioned config plugin
> 
> 
> 
> I've tried everything and couldn't make it to work...

Are you using expo dev client?

**Comment by sunset1234321** [comment]
After reading the doc, so in "expo go" you couldn't use this library?  since the plugin is a custom native code.  https://docs.expo.dev/bare/using-expo-client/

**Comment by mwegener-com** [comment]
> After reading the doc, so in "expo go" you couldn't use this library?  since the plugin is a custom native code.  https://docs.expo.dev/bare/using-expo-client/         

Correct. You have to use the expo dev client.

**Comment by tnylee** [comment]
I can confirm this config works flawlessly

**Comment by TowhidKashem** [comment]
@mwegener-com Thanks for creating the config plugin my friend, works great on iOS! (haven't tried Android)
