### ISSUE TITLE
Request permission Illegal in China

### ISSUE THREAD

**Issue by davistsin** [ivpusic/react-native-image-crop-picker#1668]
Currently, China continues to impose stricter restrictions on the Internet

### Version
Tell us which versions you are using: 

- react-native-image-crop-picker ^0.36.0
- react-native v0.63.3

### Platform
Tell us to which platform this issue is related

- Android

### Expected behaviour
When opening the camera, only apply for camera permissions. When you need to open the album, apply for storage permissions.

### Actual behaviour
Turn on the camera and apply for camera and storage permissions at the same time.

### Attachments

Government policy link

http://www.gov.cn/xinwen/2019-11/07/content_5449660.htm

Source code

```java
    @ReactMethod
    public void openCamera(final ReadableMap options, final Promise promise) {
        final Activity activity = getCurrentActivity();

        if (activity == null) {
            promise.reject(E_ACTIVITY_DOES_NOT_EXIST, "Activity doesn't exist");
            return;
        }

        if (!isCameraAvailable(activity)) {
            promise.reject(E_CAMERA_IS_NOT_AVAILABLE, "Camera not available");
            return;
        }

        setConfiguration(options);
        resultCollector.setup(promise, false);

        permissionsCheck(activity, promise, Arrays.asList(Manifest.permission.CAMERA, Manifest.permission.WRITE_EXTERNAL_STORAGE), new Callable<Void>() {
            @Override
            public Void call() {
                initiateCamera(activity);
                return null;
            }
        });
    }
```

Thanks Reply

**Comment by hikaaam** [comment]
lmao

**Comment by CoderJWYang** [comment]
@davistsin 请问下为什么close了，你如何解决的？

**Comment by davistsin** [comment]
@CoderJWYang 克隆仓库，修改Java源代码，npm依赖使用git链接方式

**Comment by davistsin** [comment]
@CoderJWYang 因为有个人在这个issue下评论LMAO，虽然他后来删除了评论，有人觉得 permission Illegal in china 是一个搞笑的事情，但是我认为开源社区有全世界各个国家、不同文化的人一起解决问题是一个很棒的，他可以不认同别人，但不必因此嘲笑。
