### ISSUE TITLE
after link react-native-image-crop picker can't open app again

### ISSUE THREAD

**Issue by lee-you** [ivpusic/react-native-image-crop-picker#168]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.10.9
- react-native v0.39.2

### Platform
Tell us to which platform this issue is related

- iOS

### Expected behaviour

can open app again

### Actual behaviour

after react-native link react-native-image-crop picker ,when closed app can't open again,like crash

### Steps to reproduce

1.npm install react-native-image-crop --save

2.react-native link react-native-image-crop picker

3.build app run success , then closed app  open again ,crash! can't open agin

### Attachments

// stacktrace or any other useful debug info

**Comment by ivpusic** [comment]
after doing link there are still some steps to do. Recommended way to be to pull dependencies via cocoapods, but you can read about this in readme file.

**Comment by ivpusic** [comment]
also for ios10 you have to update info.plist with attribute which explains why your app needs photos access. But this is not specific to this package, it is ios10 thing
