### ISSUE TITLE
Blank page with no permission

### ISSUE THREAD

**Issue by moonjava2005** [ivpusic/react-native-image-crop-picker#169]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.10.9
- react-native v0.39.2

### Platform
Tell us to which platform this issue is related

- iOS

Problem 1: When open Image Picker in the first time, platform will show the dialog to confirm whether users allow to access their photo. Then, they select "NO"
Next time to open Image Picker, the Image Picker did request again for permission. It jump directly to Image Picker view with nothing inside
Problem 2: There's no "Camera Roll" only in Smart folder. For example, like WhatsApp, if we need to choose photo from Camera Roll, we could open directly to Camera Roll folder, instead of the root folder with Camera Roll folder and other folders, users need one more step to choose Camera Roll. You should add Camera Roll feature to Smart Folder property

### Expected behaviour
If the App doesn't not permission to access photo, we should request permission again instead of assume that App already has permission

### Steps to reproduce

1.

2.

3.

### Attachments

// stacktrace or any other useful debug info

**Comment by ivpusic** [comment]
1. Yes, this is known issue. Would you be interested in sending PR for this? Basically we should check permission and reject promise if we don't have necessary permissions.

2. Library is using QBImagePicker, so you can refer to readme doc to see available options regarding "smart albums". https://github.com/questbeat/QBImagePicker#specify-the-albums-to-be-shown. Implementation for RN-ICP https://github.com/ivpusic/react-native-image-crop-picker/blob/6c29fb229108a5936cc3bae7cbcd7c9d41cd52ab/ios/ImageCropPicker.m#L199

**Comment by ivpusic** [comment]
any update here?

**Comment by ivpusic** [comment]
fixed in https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.11.1

**Comment by moonjava2005** [comment]
Thanks for your update Ivpusic
Let me try and feedback to you
