### ISSUE TITLE
Cropped Image not showing up in recent view in gallery

### ISSUE THREAD

**Issue by unit-002** [ivpusic/react-native-image-crop-picker#1693]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker: "^0.37.2"
- react-native: "0.63.4"

### Platform
Tell us to which platform this issue is related

- Android

### Cropped image should show preview in recent view in gallery or should show preview when gallery is opened.

I just want to see or preview the cropped images in the gallery just like other photos.

### Cropped images are not showing up or no preview in neither recent view in gallery or when gallery is opened.

After cropping, files are saved in a folder as a jpg file. I can open the image file if I open it in file explorer. 
But if I open the gallery, final cropped images doesn't show up.

### Steps to reproduce

```
ImagePicker.openPicker({
    width: 300,
    height: 300,
    cropping: true,
    showCropFrame: true,
    compressImageQuality: 1,
    includeExif: true,
    mediaType: 'photo',
    cropperToolbarTitle: 'Crop Image',
}).then(url => {
    SaveCropToStorage(url)
  })
  .catch((err) => {
    console.log(err.message);
  });
```

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by Alex1899** [comment]
any update on this ?

**Comment by unit-002** [comment]
If I saved the image to camera dcim folder it will open on the recent folder.
