### ISSUE TITLE
Upoading Image/Video not working from Camera in Android 11

### ISSUE THREAD

**Issue by vineelk8** [ivpusic/react-native-image-crop-picker#1695]
Hi all 

I just upgraded to android 11 and I'm facing the below issue while running the code. Is the anything I missed, please help if any finding

**Error:** unexpected element queries found in manifest application

As suggested I tried mentioned in the bug [#1393 comment ](https://github.com/react-native-image-picker/react-native-image-picker/issues/1393#issuecomment-713299590). Still facing the issue.

I also tried updating build.gradle mentioned in the bug [#stackoverlow](https://stackoverflow.com/questions/62969917/how-to-fix-unexpected-element-queries-found-in-manifest-error)

**android/build.gradle**

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 16
        compileSdkVersion = 30
        targetSdkVersion = 30
        googlePlayServicesVersion = "+"
        firebaseVersion = "+"
    }
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.5.2")
        classpath 'com.google.gms:google-services:4.3.4'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.4.1'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
        maven { url 'https://www.jitpack.io' }
    }
}

```

Added below code in the **AndroidManifest.xml** file

```
<!-- Image capture & Speech to Text fixes -->
      <queries>
        <intent>
            <action android:name="android.media.action.IMAGE_CAPTURE" />
        </intent>
      </queries>
```

**gradle-wrapper.properties**

```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-6.0.1-all.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists

```

**Comment by BLOCKMATERIAL** [comment]
Same proble 
Xiomi Redmi Note 5 
When confrim after croping photo app crashed .

**Comment by vineelk8** [comment]
> Hi all
> 
> I just upgraded to android 11 and I'm facing the below issue while running the code. Is the anything I missed, please help if any finding
> 
> **Error:** unexpected element queries found in manifest application
> 
> As suggested I tried mentioned in the bug [#1393 comment ](https://github.com/react-native-image-picker/react-native-image-picker/issues/1393#issuecomment-713299590). Still facing the issue.
> 
> I also tried updating build.gradle mentioned in the bug [#stackoverlow](https://stackoverflow.com/questions/62969917/how-to-fix-unexpected-element-queries-found-in-manifest-error)
> 
> **android/build.gradle**
> 
> ```
> // Top-level build file where you can add configuration options common to all sub-projects/modules.
> 
> buildscript {
>     ext {
>         buildToolsVersion = "30.0.2"
>         minSdkVersion = 16
>         compileSdkVersion = 30
>         targetSdkVersion = 30
>         googlePlayServicesVersion = "+"
>         firebaseVersion = "+"
>     }
>     repositories {
>         google()
>         jcenter()
>         mavenCentral()
>     }
>     dependencies {
>         classpath("com.android.tools.build:gradle:3.5.2")
>         classpath 'com.google.gms:google-services:4.3.4'
>         classpath 'com.google.firebase:firebase-crashlytics-gradle:2.4.1'
>         // NOTE: Do not place your application dependencies here; they belong
>         // in the individual module build.gradle files
>     }
> }
> 
> allprojects {
>     repositories {
>         mavenLocal()
>         maven {
>             // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
>             url("$rootDir/../node_modules/react-native/android")
>         }
>         maven {
>             // Android JSC is installed from npm
>             url("$rootDir/../node_modules/jsc-android/dist")
>         }
> 
>         google()
>         jcenter()
>         maven { url 'https://www.jitpack.io' }
>     }
> }
> ```
> 
> Added below code in the **AndroidManifest.xml** file
> 
> ```
> 
>       <queries>
>         <intent>
>             <action android:name="android.media.action.IMAGE_CAPTURE" />
>         </intent>
>       </queries>
> ```
> 
> **gradle-wrapper.properties**
> 
> ```
> distributionBase=GRADLE_USER_HOME
> distributionPath=wrapper/dists
> distributionUrl=https\://services.gradle.org/distributions/gradle-6.0.1-all.zip
> zipStoreBase=GRADLE_USER_HOME
> zipStorePath=wrapper/dists
> ```

I made a mistake in **AndroidManifest.xml**. The queries tags should be outside of the application tag in the file. After doing the change the build ran successfully

**Comment by BLOCKMATERIAL** [comment]
@vineelk8 pls ,show example.

**Comment by vineelk8** [comment]
> @vineelk8 pls ,show example.

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.xxxxxxxx">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>      
    </application>

    <!-- Image capture, Video capture & Speech to Text fixes -->
    <queries>
      <intent>
          <action android:name="android.media.action.IMAGE_CAPTURE" />
      </intent>
      <intent>
          <action android:name="android.media.action.VIDEO_CAPTURE" />
      </intent>
      <intent>
          <action android:name="android.speech.RecognitionService" />
      </intent>
    </queries>

</manifest>
```

**Comment by EchoChien007** [comment]
> Same proble Xiomi Redmi Note 5 When confrim after croping photo app crashed .

hey, firends, how you solve the problem finally?

**Comment by Avinash10rr** [comment]
Any Update on this ongoing issue
