### ISSUE TITLE
Can I remove "Select More Photos" dialog at the start of ImagePicker?

### ISSUE THREAD

**Issue by big20scoops** [ivpusic/react-native-image-crop-picker#1726]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.37.2
- react-native v0.65.1

### Platform
Tell us to which platform this issue is related

- iOS

### Expected behavior
No dialog asking for select more photos.

### Actual behavior
Always asking for select more photos every time user returns to the app.

### Steps to reproduce

1. Granted "limited" Photos permission

2. Close App and reopen App

3. Launch ImagePicker

### Attachments
<img width="487" alt="Screen Shot 2565-01-25 at 15 02 00" src="https://user-images.githubusercontent.com/82799397/150936102-3037904d-beb4-4841-aef2-0c58c4beca10.png">

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by big20scoops** [comment]
I found solution here: https://stackoverflow.com/questions/69493888/ios-disable-select-more-photos-alert

**Comment by DevMinhThu** [comment]
@big20scoops  how to add "PHPhotoLibraryPreventAutomaticLimitedAccessAlert" to info.plist?

**Comment by DevMinhThu** [comment]
@big20scoops I added "PHPhotoLibraryPreventAutomaticLimitedAccessAlert" to info.plit but it doesn't remove the dialog. please help me
