### ISSUE TITLE
Could not resolve com.github.yalantis:ucrop:2.2.6-native

### ISSUE THREAD

**Issue by neoswallow** [ivpusic/react-native-image-crop-picker#1756]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.35.1
- react-native v0.63.4

### Platform
Tell us to which platform this issue is related

- Android only

### Expected behaviour
Android build success

### Actual behaviour
Android build failure
This build failure started happening since Mar, 17th.
Build worked on EOD of 18th and for a short time on yesterday (21st) afternoon.
But it's still failing after that.

### Steps to reproduce
react-native run-android

### Attachments
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':react-native-image-crop-picker:compileReleaseAidl'.
> Could not resolve all task dependencies for configuration ':react-native-image-crop-picker:releaseCompileClasspath'.
   > Could not resolve com.github.yalantis:ucrop:2.2.6-native.
     Required by:
         project :react-native-image-crop-picker
      > Skipped due to earlier error
```

**Comment by jfries289** [comment]
Github itself seems to be having some issues lately (https://www.githubstatus.com/). Could this be related to that?

**Comment by neoswallow** [comment]
That's what it sounds like but it still fails now.
If what the status page is indicating is correct, I would have experienced intermittent failure, not constant failure with a tiny duration where it worked.
It's really frustrating that it's been failing for 4 business days.

**Comment by kinigitbyday** [comment]
I'm hitting this as well. jitpack availability has not been great recently which I believe is where the ucrop dep is hosted: https://status.jitpack.io/.

I've had some intermittent successful builds but mostly failures.

**Comment by neoswallow** [comment]
It seems that jitpack.io just handles the routing. It refers to GitHub release so the actual payload is located on GitHub. What I can't figure out is which one is responsible for the error.
Looking at https://github.com/Yalantis/uCrop/issues/826, I guess bintray is involved as well which is known to cause this build failure many times ever since they shutdown the jCenter service. :sigh:

**Comment by neoswallow** [comment]
So it looks like I found a solution.
```
-       maven { url 'https://www.jitpack.io' }
        jcenter()
+       maven { url 'https://www.jitpack.io' }

```
So I previously put jcenter() at the bottom of the allprojects.repositories because of jCenter/bintray outage issue.
But looking at https://github.com/Yalantis/uCrop/issues/826, I decided to try putting jcenter() above jitpack url as I got nothing to loose.
And so far, all build tries so far succeeded.
Maybe when I run into jCenter/bintray url issue, I'll flip it again and see if that helps 🤷🏼‍♂️.
There should be a better solution for this madness with java dependencies.

**Comment by kinigitbyday** [comment]
I've got jcenter at the bottom and my build has been passing since about a 20 hours ago, fwiw, so I don't think it's really a resolution ordering thing. Maybe whichever service was having issues is more stable now 🤷 . 🤞 it stays that way.

**Comment by neoswallow** [comment]
So I have 2 branches, one with jcenter on the bottom and another one with jitpack on the bottom. One with jcenter on the bottom still fails while one with jitpack still succeeds.
So even though I actually don't like the solution (like you said, it may not be proper solution), I have no other option to go with one that builds successfully.
Frankly, above change shouldn't matter.
I'll keep looking for a better/proper solution.

**Comment by nghia11110** [comment]
> So it looks like I found a solution.
> 
> ```
> -       maven { url 'https://www.jitpack.io' }
>         jcenter()
> +       maven { url 'https://www.jitpack.io' }
> ```
> 
> So I previously put jcenter() at the bottom of the allprojects.repositories because of jCenter/bintray outage issue. But looking at [Yalantis/uCrop#826](https://github.com/Yalantis/uCrop/issues/826), I decided to try putting jcenter() above jitpack url as I got nothing to loose. And so far, all build tries so far succeeded. Maybe when I run into jCenter/bintray url issue, I'll flip it again and see if that helps 🤷🏼‍♂️. There should be a better solution for this madness with java dependencies.

@neoswallow I have put jcenter() above jitpack but  it still fails now. do you have any update for this problem?

**Comment by neoswallow** [comment]
@nghia11110 It looks like I kept running into the issue and tried other changes.
```grade
        maven { url 'https://www.jitpack.io' }
        google()
        maven { url 'https://maven.google.com' }
        jcenter()
```
This change was 8 months ago so it's been working for a while for me.
Hope this works for you also.

**Comment by nghia11110** [comment]
@neoswallow thank you so much. i will try this.

**Comment by MunemHabib47** [comment]
tried all none of the solution works server throwing 521 jitpack

**Comment by shyvesCCD** [comment]
same here... @MunemHabib47 find the solution?

**Comment by vinaygregoryjohn183** [comment]
anyone got a solution for this?
