### ISSUE TITLE
Getting Error "User did not grant library permission." in Android 10 with SDk 30 

### ISSUE THREAD

**Issue by ashuOxit** [ivpusic/react-native-image-crop-picker#1757]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker ^0.37.3
- react-native v0.63.4

### Platform
Tell us to which platform this issue is related
- Android

### Expected behaviour
Should open camera and library 

### Actual behaviour
Showing error `User did not grant library permission`

### Steps to reproduce

Run app in android 10 Device 

in React native app I am using 
ext {
        googlePlayServicesVersion = "+" // default: "+"
        firebaseVersion = "+" // default: "+"
        buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
        kotlin_version = "1.5.10"
    }

Working fine in android 11 but in android 10 after giving permission showing error

**Comment by HaroonChelsea** [comment]
Add camera permission in : `android\app\src\main\AndroidManifest.xml`

`<uses-permission android:name="android.permission.CAMERA"/>`

**Comment by steve-rodri** [comment]
Getting same issue. Followed all android steps in the Readme. Added camera permission to AndroidManifest.xml as well.

**Comment by ashuOxit** [comment]
@steve-rodri try above solution that works for me

**Comment by steve-rodri** [comment]
@ashuOxit I failed to build and get this error: The prefix "tools" for attribute "tools:replace" associated with an element type "uses-permission" is not bound.

**Comment by ashuOxit** [comment]
@steve-rodri 
add this too and try 
```
android:requestLegacyExternalStorage="true"
```
for me by adding this with other works
