### ISSUE TITLE
Possible Unhandled Promise Rejection Warning

### ISSUE THREAD

**Issue by activelogic** [ivpusic/react-native-image-crop-picker#176]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.3.9
- react-native v0.39.2

### Platform
Tell us to which platform this issue is related

- Android

### Expected behaviour
When calling ImagePicker.openPicker to open the picker and then using the back button to navigate back, no warning should be thrown.

### Actual behaviour
When calling ImagePicker.openPicker to open the picker and then using the back button to navigate back, a "Possible Unhandled Promise Rejection (id: 2) User cancelled image selection Error: User  cancelled image selection at createErroFromErrorData..."

### Steps to reproduce

1. Call ImagePicker.openPicker from an onPress

2. Let the ImagePicker navigate to the native file picker

3. Click the hardware or screen back button to return to the calling scene

4. See yellow warning

**Comment by ivpusic** [comment]
this is by design. Library is returning promise which should be resolved or rejected. When user closes picker, we reject promose with specific error message and error.code. You should catch rejection and ignore it if it is not interesting for you

**Comment by PatWu16** [comment]
I chose the picture，but returns this warning,what's wrong?

**Comment by WhoJave** [comment]
@PatWu16 Have you fixed this bug ? I came cross the  warning,too 🙁

**Comment by Clowning** [comment]
@ivpusic Yes we can ignore it but on Android, my app crash if i cancel ! It's a big issue!

**Comment by CodySwannGT** [comment]
FWIW, this is still a bug. You can catch the rejected promise, but then the ImagePicker will not open again

**Comment by atishoo** [comment]
@CodySwannGT yes, i found this same issue, do you have solution?

**Comment by 123mcq** [comment]
>选择了允许还是会返回这个警告是什么原因呢，求解

**Comment by 123mcq** [comment]
What is the reason for selecting the permission to allow access or reporting this warning?
