### ISSUE TITLE
crop picker unable to get videos from other app (android and only videos)

### ISSUE THREAD

**Issue by saadbawany97** [ivpusic/react-native-image-crop-picker#1768]
### Version
- react-native-image-crop-picker v0.37.3
- react-native v0.67.1
- 
### Platform 
Android 

LogBox.js:173 Possible Unhandled Promise Rejection (id: 2): Error: /storage/emulated/0/DCIM/ahmed/20220410_162904.mp4 does not exist Error: /storage/emulated/0/DCIM/ahmed/20220410_162904.mp4 does not exist at Object.promiseMethodWrapper [as openPicker] (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=

ImagePicker.openPicker({
  mediaType: "video",
}).then((video) => {
  console.log(video);
});

When i call the function of crop picker mention above its work fine give me videos from recent but if i browse the same video by going my files search the folder and select its giving me error. See in SS1 image all the video which are there in recent i can upload them through crop picker but if i go to gallery/my files or anywhere under the heading browse file from other app . i am unable to upload the videos. This behavior is occuring only for videos by same way i am getting images

![ss1](https://user-images.githubusercontent.com/76789685/162621075-e08cbc4b-81cb-4c5b-b926-3b2a5f0caef1.jpeg)
![ss2](https://user-images.githubusercontent.com/76789685/162621082-6f400b85-5400-4cc6-90be-5cdbcefac5bd.jpeg)

**Comment by pravinsphinx** [comment]
Possible Unhandled Promise Rejection (id: 1):

/storage/emulated/0/DCIM/Camera/20220503_142623.mp4 does not exist
This issue is not fixed, still getting above error .

**Comment by Abhishek2250** [comment]
I'm also getting same issue. Any update?
