### ISSUE TITLE
What is the available choices of compressVideoPreset?

### ISSUE THREAD

**Issue by jaggerwang** [ivpusic/react-native-image-crop-picker#178]
### Question
Not found in the wiki, and search the repository. LowQuality, MediumQuality, HighQuality?

And the video is compressed too much. The origin size is 1920x1080, and the result size is 568x320 with the default options, even set compressVideoPreset option to HighQuality or not set.

### Code
```
ImagePicker.openPicker({
                  multiple: true,
                  maxFiles: 6,
                  compressImageMaxWidth: 1080,
                  compressImageMaxHeight: 810,
                  compressImageQuality: 0.9,
                  compressVideoPreset: 'HighQuality',
                })
```

### ENV
react-native-image-crop-picker: 0.11.0
react-native: 0.39
platform: iOS on simulator

**Comment by ivpusic** [comment]
for all available options check this https://github.com/ivpusic/react-native-image-crop-picker/blob/master/ios/Compression.m#L14.

**Comment by Strate** [comment]
New valid link is https://github.com/ivpusic/react-native-image-crop-picker/blob/master/ios/src/Compression.m#L14
