### ISSUE TITLE
Getting Error - does not exist for video

### ISSUE THREAD

**Issue by pravinsphinx** [ivpusic/react-native-image-crop-picker#1799]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.37.3
- react-native v"0.68.1

### Platform
Tell us to which platform this issue is related
- Android

### Expected behaviour
ImagePicker.openPicker({
                         mediaType: "video",
                    }).then((video) => {
                         console.log(video);
                    });
After this required path, duration and other details.

### Actual behaviour
/storage/emulated/0/DCIM/Camera/20220503_142623.mp4 does not exist

### Steps to reproduce

1. 

2.

3.

### Attachments

// stacktrace or any other useful debug info
![Screenshot 2022-06-13 at 10 23 26 AM](https://user-images.githubusercontent.com/67891787/173282122-936f213d-f2d1-4ef9-a63d-1af2d78d6083.png)

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by Abhishek2250** [comment]
I'm also getting same issue on android 12 while selecting photos from google photos

**Comment by pravinsphinx** [comment]
@Abhishek2250 Add runtime permissions for android 
`const grants = await PermissionsAndroid.requestMultiple([
                         PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE,
                         PermissionsAndroid.PERMISSIONS.READ_EXTERNAL_STORAGE,
                    ]);`
