### ISSUE TITLE
Is there any possible to return duration of the picked video?

### ISSUE THREAD

**Issue by jaggerwang** [ivpusic/react-native-image-crop-picker#181]
I want to limit the duration of video picked by our app's user to short than 30s. At now, the props of object returned by picker including width, height, mime and size, but no duration. And I don't want to do this check on the server side.

**Comment by ivpusic** [comment]
currently this is not possible, but this would be definitely very useful. If you have some time I would accept PR with this feature. My proposal would be to include new property called `metadata`. Here we would put all extra data we know about asset. Asset can be image or video. For images later we can include some image specific information, and for videos as well. Let me know what do you think.

**Comment by jaggerwang** [comment]
I'd like to help, but I have no iOS or Android developing experience, my most programming experience is on server side. I'm sorry for this. Hoping some nice guy will add this feature later.

**Comment by ivpusic** [comment]
No problem. Will close this issue for now, but will keep it in mind.

**Comment by jpmazza** [comment]
+1

**Comment by BaderSerhan** [comment]
did we find a solution for this? i want to implement a feature for uploading a video from library and trimming it, but i am not finding a good solution so far...

**Comment by astraeapark** [comment]
+1

**Comment by Lunziyuan** [comment]
+1

**Comment by Coder108** [comment]
When will this feature appear?

**Comment by kostiantyn-solianyk** [comment]
@ivpusic @astraeapark @Lunziyuan @Coder108 
Maybe it's too late. But I also need this functionality.
So, I've made this issue working on both **ANDROID and IOS**. I hope @ivpusic will look into PR that I sent. https://github.com/ivpusic/react-native-image-crop-picker/compare/master...kostiantyn-solianyk:master

**Comment by ivpusic** [comment]
available in https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.32.2
