### ISSUE TITLE
Request feature

### ISSUE THREAD

**Issue by flaviotobi** [ivpusic/react-native-image-crop-picker#182]
Hi, to start thanks for the great plugin :).

I would like to know if you can add a feature. 
I was hoping that  the text from the buttons could be change. I have a multi language app and i can't have the buttons text and etc... just in english.

It's possible to be able to change this from react-native side??
If yes it's gonna be in a near future ?

Anyway thanks and congrats.

**Comment by ivpusic** [comment]
Hey, currently this is not possible, but I would accept PR if you have some time to add support. If at some point I need this for my apps, then yes, I will add it. Otherwise, I will wait for PR from someone.
