### ISSUE TITLE
Unable to upload image to backend server

### ISSUE THREAD

**Issue by akanz** [ivpusic/react-native-image-crop-picker#1824]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.38.0
- react-native v0.69

### Platform
- iOS
- Android

### Expected behaviour
I want to upload the image and receive a secure url

### Actual behaviour
I always get a 400 error which says invalid file type. NB: I have tried both axios and fetch and tried alot of solutions seen, but none seem to work. any help will be greatly associated. 

<img width="1060" alt="Screenshot 2022-07-28 at 10 24 41" src="https://user-images.githubusercontent.com/33222698/181472070-3055b32c-b64e-481f-841d-01f007258026.png">

<img width="1060" alt="Screenshot 2022-07-28 at 10 24 41" src="https://user-images.githubusercontent.com/33222698/181472639-f3655b8a-b492-46c0-908a-5cd63414e2c6.png">

**Comment by ahmadcitrusbits** [comment]
Any solution for this? Facing the same, It's working fine on ios but cannot upload to the server on Android.

**Comment by akanz** [comment]
I wasn’t able to get it to work on either. can you share your code snippet? android uri is different, also it doesn’t come with filename

**Comment by Onibenjo** [comment]
Any update on this?

**Comment by Onibenjo** [comment]
Fixed.... For my case, the file name wasn't having an extension.

**Comment by akanz** [comment]
Hey guys, I had to upload base64 string, albeit a 0.33 increase in size

**Comment by chganesh** [comment]
fromData.append("file", {
    name:fileName,
    type: ImageOrVideo.mime,
    uri:
      Platform.OS === "android"
        ? ImageOrVideo.path
        : ImageOrVideo.path.replace("file://", "")
  });

 headers: {
        "x-access-token":AppGlobal.auth_token.accessToken,
          "Content-Type": "multipart/form-data",
          Accept: "application/json",
      }

I am unable to upload image  back end server Flask (python)
any one help on this 
thanks in advance
