### ISSUE TITLE
Corrupted .jpg file as a result of cropping .heic file

### ISSUE THREAD

**Issue by tadjik1** [ivpusic/react-native-image-crop-picker#1839]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.38.0
- react-native v0.65.1

### Platform
Tell us to which platform this issue is related

- iOS 15.6

### Expected behavior

Cropping a single photo from the photo library in .heic format should produce a correct image.

### Actual behavior

Cropping the photo in .heic format returns the path to the corrupted .jpg image.
As far as I understood this is a known problem, however, I wasn't able to find the solution, or workaround for this problem. 

Same code works with regular .jpg file just fine, so the problem is only with .heic file.

### Steps to reproduce

1. open picker with the following options:
```
const result = await ImagePicker.openPicker({
  cropping: true,
  multiple: false,
  forceJpg: false,
  writeTempFile: true,
  mediaType: "photo",
  compressImageQuality: 1,
  cropperToolbarTitle: "Select tattoo",
  freeStyleCropEnabled: true,
  includeExif: true,
});
```
2. validate the result:
```
{
"creationDate": "1658593463", 
"cropRect": {"height": 1139, "width": 2516, "x": 239, "y": 1275}, 
"data": null, 
"duration": null, 
"exif": {...}, 
"filename": "IMG_4629.HEIC", 
"height": 90, 
"localIdentifier": "DEF2D210-961E-4C24-8893-476058B0F0D5/L0/001", 
"mime": "image/jpeg", 
"modificationDate": null, 
"path": "/private/var/mobile/Containers/Data/Application/198B0EB2-C719-412E-A3F2-C25382809AA0/tmp/react-native-image-crop-picker/F1227D83-ECE2-49BF-81DC-C2BC4E56CC4D.jpg", 
"size": 19064, 
"sourceURL": "file:///var/mobile/Media/DCIM/104APPLE/IMG_4629.HEIC", 
"width": 200
}
```

3. observe corrupted .jpg file

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by ajlee4** [comment]
how did you solve the problem?
