### ISSUE TITLE
enable cropping on png pic with transparent background returns pic with white background color.

### ISSUE THREAD

**Issue by DoTalkLily** [ivpusic/react-native-image-crop-picker#184]
ImagePicker.openPicker({
            maxWidth: 720,
            maxHeight: 720,
            width: 240,
            height: 108,
            cropping: true
        }).then(image => {});
After cropping my png image which background color is transparent, I got a image width white background.  How to fix it?

**Comment by ivpusic** [comment]
all images are converted to jpg. If you are interested to make this dependent on selected image mime type, I would accept PR.
