### ISSUE TITLE
Selected photos access crash on iOS

### ISSUE THREAD

**Issue by olafuromarsson-toast** [ivpusic/react-native-image-crop-picker#1854]
### Version
- react-native-image-crop-picker **v0.37.2 and v0.38.0**
- react-native **v0.68.1**

### Platform
- iOS

### Expected behaviour
> Context: User has set **Allow Photos Access** in Settings to **Selected Photos**

If a user initially decides to **Keep Current Selection** and then subsequently decides to edit his selection by pressing **Manage** and **Select More Photos** he should be able to edit his selection without a crash.

### Actual behaviour

If a user presses **Keep Current Selection** and then subsequently presses **Manage** and **Select More Photos** the app will crash.

### Steps to reproduce

1. Make sure in settings of the app to set **Photos** access to **Selected Photos**
2. Perform an action that calls `openPicker`
3. When prompted, select **Keep Current Selection**
4. Then press **Manage**.
5. Select **Select More Photos**. App crashes

### Attachments

<img width="930" alt="image" src="https://user-images.githubusercontent.com/113019414/197753267-77131188-1cab-40ad-b853-0ba61acc83cf.png">

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by markholland** [comment]
Fixed in https://github.com/ivpusic/react-native-image-crop-picker/pull/1853
Apply patch for iPad https://github.com/ivpusic/react-native-image-crop-picker/issues/1765#issuecomment-1171403844

**Comment by olafuromarsson-toast** [comment]
@markholland Thank you, no crashing now 🙏
