### ISSUE TITLE
exif data seems to be stripped even though no compression is used

### ISSUE THREAD

**Issue by nico1510** [ivpusic/react-native-image-crop-picker#187]
Hi @ivpusic thanks for this library and the time you put into it. I just wanted to let you know of a problem I encountered which prevents me from using it after v0.11.0

### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.11.0
- react-native v0.40.0

### Platform
- Android
-(maybe iOS too but I didn't test)

### Expected behaviour
when using no compression settings at all, the module should just return the original image with all its original exif meta data attached. Or copy the exif meta data when compressing (creating the compressed new image).

### Actual behaviour

it seems that a new image is created even when no compression settings are used. At least I can't extract any exif meta data on the returned image.

### Steps to reproduce

1. select an image and check the exif data in v.0.40.0 e.g. with https://github.com/francisco-sanchez-molina/react-native-exif like e.g: 

```javascript
    NativeModules.ImagePicker.openPicker()
    .then(image => NativeModules.ReactNativeExif.getExif(image.path.replace('file://', ''))
    .then(console.log)
```
most of the returned exif data is undefined

**Comment by ivpusic** [comment]
fixed in https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.11.2
