### ISSUE TITLE
After zooming and selecting crop area, the image returned is NOT cropped and is full size of original.

### ISSUE THREAD

**Issue by MyPalVikram** [ivpusic/react-native-image-crop-picker#1888]
### Version
Tell us which versions you are using:

- react-native-image-crop-picker v0.38.0
- react-native v0.70.6

### Platform
Tell us to which platform this issue is related

- iOS
- Android

### Expected behaviour

I expect the image that is selected to be the the size and area of the cropping square.

### Actual behaviour

Doesn't matter how much I zoom in or move the cropping area around, the full image is returned.

### Steps to reproduce

1.

2.

3.

### Attachments

```
      await ImageCropPicker.openPicker({
        width: 100,
        height: 100,
        cropping: true,
        compressImageQuality: 0.5,
      })
        .then(image => {
          console.log(image);
          imageData = {
            uri: image.sourceURL,
            type: image.mime,
            name: image.filename,
          };
        })
        .catch(error => {
          throw Error(error.message);
        });
```

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by MyPalVikram** [comment]
I was using the wrong photo path...🥲

**Comment by tragicmj** [comment]
@MyPalVikram what is the correct path? Facing the same issue!!

**Comment by MyPalVikram** [comment]
> @MyPalVikram what is the correct path? Facing the same issue!!

It should be the `image.path` not the `sourceURL`.
