### ISSUE TITLE
Image compress is not working at all

### ISSUE THREAD

**Issue by rogerkerse** [ivpusic/react-native-image-crop-picker#189]
```
ImagePicker.openPicker({
	multiple: true,
	compressImageMaxWidth: 1024,
	compressImageMaxHeight: 1024,
	compressImageQuality: 0.6,
})
```

Code does not compress images at all. I tested original image size and compressed and both are 8MB. No difference at all and the resolution is still bigger.

### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.10.5
- react-native v0.39

### Platform
Tell us to which platform this issue is related

- iOS

### Expected behaviour

I expect to get smaller image size

### Actual behaviour

I get the same image size as the uncompressed on

### Steps to reproduce

On iOS simulator I just add this code to test official images that are on there.

**Comment by ivpusic** [comment]
you are using old version, install new one. the one you are using does not have compression features

**Comment by rogerkerse** [comment]
Ok that worked, thanks.
