### ISSUE TITLE
Error: cannot find symbol ->  symbol:   variable TIRAMISU   location: class VERSION_CODES,  symbol:   variable READ_MEDIA_IMAGES   location: class permission

### ISSUE THREAD

**Issue by Zeeshan404** [ivpusic/react-native-image-crop-picker#1892]
### Version

"react-native": "0.70.6",
"react-native-image-crop-picker": "^0.39.0"

### Platform
- Android

### Expected behavior
Build Successfully

### Actual behaviour
Build Failed

### Steps to reproduce

1. npx react-native init my-app

2. npm i react-native-image-crop-picker and follow other steps here : https://github.com/ivpusic/react-native-image-crop-picker

3. npx react-native run-android

### Attachments
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/54739303/215202003-3873a4b8-3308-4323-a646-b65cbbf3c69b.png">
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/54739303/215202406-b70ac2bc-7d17-4441-a32f-3a05117d07f3.png">

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by bsjaramillo** [comment]
I had the same issue, I fixed upgrading compileSdkVersion and targetSdkVersion to 33 in android/build.gradle.

**Comment by andrei0807** [comment]
I got same error

**Comment by VictorPulzz** [comment]
I got same error
