### ISSUE TITLE
[Android] ImagePicker.openCamera react-navigation is start to didmont again when confirm image from camera

### ISSUE THREAD

**Issue by Poovit-B** [ivpusic/react-native-image-crop-picker#1898]
Android devices that are being used for testing.

- Samsung Galaxy S22 [Working fine]
- Samsung Galaxy A12 [Problem]
- Redmi 9 [Working fine]

![image](https://user-images.githubusercontent.com/61401085/217143294-d8b7fc2c-128a-42cb-9129-027a3f9b66b0.png)

![image](https://user-images.githubusercontent.com/61401085/217143213-18fec278-69da-46f4-96b1-303592e0ed34.png)

### Version

- "react-native": "0.70.6",
- "react-native-image-crop-picker": "^0.38.1",
- "@react-navigation/native": "^6.0.14",
- "@react-navigation/stack": "^6.3.5",

### Platform

- Android

**Comment by lucaslrf** [comment]
What was solution? @Poovit-B
