### ISSUE TITLE
did not show

### ISSUE THREAD

**Issue by JusticeLai** [ivpusic/react-native-image-crop-picker#190]
### Version
- react-native-image-crop-picker v0.11.2
- react-native v0.40

### Platform
- Android

### Actual behaviour
W/ReactNativeJS: Possible Unhandled Promise Rejection (id: 1):
                 Activity doesn't exist
                 createErrorFromErrorData@http://10.0.3.2:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:7279:20
                 http://10.0.3.2:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:7242:59
                 __invokeCallback@http://10.0.3.2:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:7627:15
                 http://10.0.3.2:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:7478:24
                 guard@http://10.0.3.2:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:7397:3
                 invokeCallbackAndReturnFlushedQueue@http://10.0.3.2:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:7477:6
                 invokeCallbackAndReturnFlushedQueue@[native code]

### Steps to reproduce

1.AndroidManifest.xml add permission
2.addPackage(newImagePickerPackage())----in ReactNative Activity
3.settings.gradle add some code
4.build.gradle add some code
5.and rebuild the project

6Android hava a button ,then jump to ReactNative Activity

7.In ReactNative Activity click a button,to show this picker(if only ReactNative is ok,to show picker)

ImagePicker.openCamera({
                                width: 300,
                                height: 400,
                                cropping: true
                            }).then(image => {
                                console.log(image);
                            });

8.Android Studo log Error  on top of Actual behaviour

9.Possible Unhandled Promise Rejection (id: 1):Activity doesn't exist

10.other Component  is ok

![image](https://cloud.githubusercontent.com/assets/13083749/21836251/956e7e32-d7fe-11e6-8e27-f0b5745e550c.png)

**Comment by ivpusic** [comment]
cannot reproduce. do you have some time to debug this?

**Comment by ivpusic** [comment]
@JusticeLai any updates?

**Comment by ivpusic** [comment]
closing as old and no response from author
