### ISSUE TITLE
[🐛] [Android] ImagePicker.openCamera start didmount again after confirm image

### ISSUE THREAD

**Issue by Poovit-B** [ivpusic/react-native-image-crop-picker#1905]
### Description

After clicking confirm, the application received a normal response. However, I encountered a strange issue where the 'didmount' on the current page was restarted, and as a result, the Route Stack was lost. It's worth noting that I'm using 'react-navigation/native'.

Android devices that are being used for testing.

- Samsung Galaxy S22 [Working fine]
- Samsung Galaxy A12 [Problem]
- Redmi 9 [Working fine]

### Additional Information

- Image Picker version: 0.38.1
- React Native version: 0.70.6
- Platform: Android

**Comment by faizanbutt** [comment]
@Poovit-B Can you please tell the Android versions of these devices ?
I think, I am also facing same kind of problem.

**Comment by Poovit-B** [comment]
@faizanbutt For Samsung Galaxy A12 I'm using version 12.
I think it's mostly cause by Samsung Series A.

**Comment by Poovit-B** [comment]
I solved the problem by using react-native-vision-camera
