### ISSUE TITLE
Archiving with different build configuraton - "framework not found QBImagePicker for architecture armv7"

### ISSUE THREAD

**Issue by tobycox** [ivpusic/react-native-image-crop-picker#191]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.11.2
- react-native v0.39

### Platform

- iOS
- Android

### Expected behaviour

Can build and Archive the project in an alternate build configuration.

### Actual behaviour

Linker error:
```
ld: framework not found QBImagePicker for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Steps to reproduce

1. Project with separate build configurations. We have a Release-Staging build configuration which is a clone of our Release build configuration but with a different bundle ID and plist.

<img width="508" alt="screen shot 2017-01-11 at 10 42 56 am" src="https://cloud.githubusercontent.com/assets/4144/21834999/244428cc-d7ec-11e6-9541-be7d0875bd24.png">

2. A Release-Staging scheme that archives using this build configuration.

<img width="732" alt="screen shot 2017-01-11 at 10 53 23 am" src="https://cloud.githubusercontent.com/assets/4144/21835004/34827b94-d7ec-11e6-98e0-3f7232bd22bc.png">

3. Build and Archive using this scheme.

Has anyone run in to a similar issue? Seems like maybe the QBImagePicker framework isn't ending up in right build directory (`Release` instead of `Release-Staging`).

**Comment by mizinin** [comment]
have same issue with custom config schemes(

**Comment by tobycox** [comment]
@mizinin Have you had any luck getting around it? It's making me sad 😢

**Comment by Deno028** [comment]
Getting the same issue. Can anybody solve it?

**Comment by tobycox** [comment]
Still getting this issue. Have tried using the cocoapods method as well as the manual embedding method but neither work.

**Comment by tobycox** [comment]
So I was right in that the frameworks aren't ending up in the right directory. I'm not sure how to actually fix this, but I got around it by adding a Run Script phase to my project before "Compile Sources" which copies the frameworks over in to the correct directory so they can be found for linking.

```
if [ "${CONFIGURATION}" = "Release-Staging" ]; then
    cp -R "${BUILT_PRODUCTS_DIR}/../Release-iphoneos/QBImagePicker.framework" "${BUILT_PRODUCTS_DIR}"
    cp -R "${BUILT_PRODUCTS_DIR}/../Release-iphoneos/RSKImageCropper.framework" "${BUILT_PRODUCTS_DIR}"
fi
```

Replace "Release-Staging" with the name of your custom build configuration.

**Comment by richardgill** [comment]
For me I think the problem was really just related to: https://github.com/facebook/react-native/issues/11813

I fixed using the library: https://github.com/Thinkmill/react-native-schemes-manager

**Comment by ivpusic** [comment]
this is the current react-native limitation. 

As a workaround, follow https://github.com/facebook/react-native/issues/11813#issuecomment-273279257.

After that, create another "User defined setting", name it for example: `REACT_FRAMEWORKS_PATH`, set value `$(BUILD_DIR)/Release-$(PLATFORM_NAME)`, and then in "framework search paths" add `$(REACT_FRAMEWORKS_PATH)`

**Comment by ptgamr** [comment]
Adding to "Linked Frameworks And Libraries" like bellow fixed the problem for me:
<img width="606" alt="screen shot 2017-11-03 at 11 24 09 pm" src="https://user-images.githubusercontent.com/1619740/32369579-88ee4320-c0ee-11e7-9c18-044b2e081fa4.png">

Notice that `QBImagePicker.framework` is not in the list.

The irony is, if  I added `QBImagePicker.framework`, the build would failed.
