### ISSUE TITLE
Can we pass the already selected images to the picker?

### ISSUE THREAD

**Issue by jaggerwang** [ivpusic/react-native-image-crop-picker#192]
It's a bad user experience that after selected a few images, reopen the picker to add more, but lost the images selected before.

**Comment by ivpusic** [comment]
unfortunately this is not possible

**Comment by jaggerwang** [comment]
Why? the underlying sdk not support ?

**Comment by ivpusic** [comment]
yes, for example on ios side library is using https://github.com/questbeat/QBImagePicker, which does not have option for this
