### ISSUE TITLE
(iOS) RSKImageCropper.h not found

### ISSUE THREAD

**Issue by pgwzzz** [ivpusic/react-native-image-crop-picker#193]
I've suffered from the "not found header" error for several days. Sometimes works but sometimes not. Today I found that the error is solved if I remove the following statement in Podfile.

`pod 'RSKImageCropper'`

The sentence has resulted in two RSKImageCropper projects and it sometimes make "not found header" error.

You already have RSKImageCropper inside your library.

**Comment by chuyihuang** [comment]
doing so will not be able to archive or export to ipa. I solved this issue by doing so:

1. pod repo remove master
2. pod setup 
3. pod install

**Comment by BetterFanKai** [comment]
I use CocoaPod and solved this issue by doing:
1.react-native unlink react-native-image-crop-picker
2.npm uninstall react-native-image-crop-picker --save
3.delete  " pod 'RSKImageCropper'" and " pod 'QBImagePickerController'" in Podfile then pod install
4.install react-native-image-crop-picker again by ReadMe Steps
5.clean Xcode and build again

**Comment by cooperka** [comment]
Simply running `pod install` again fixed it for me. Xcode seems to have lost the file after I cleaned (Product > Clean).

**Comment by aforty** [comment]
This is so frustrating. Random and seemingly always pops up again and again. Is there no fix?

**Comment by ivpusic** [comment]
should be fixed with https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.19.1

**Comment by AlmogRnD** [comment]
Has this been fixed I seem to be getting the issue each time I open up my project in xcode
