### ISSUE TITLE
Cropping not working when set width and height.

### ISSUE THREAD

**Issue by DoTalkLily** [ivpusic/react-native-image-crop-picker#195]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.11.2
- react-native v0.39.2

### Platform
Tell us to which platform this issue is related

- iOS

pickSingleTest() {
      ImagePicker.openPicker({
          width: 100,
          height: 100,
          cropping: true
      }).then(image => {
          console.log('received image', image);
      }).catch(e => {
          console.log(e);
          Alert.alert(e.message ? e.message : e);
      });
  }

 Size of cropping rect is not what I set but equals to the width of device. 

![Uploading image.png…]()

**Comment by ivpusic** [comment]
are final image dimensions 100x100? By setting width and height you are giving library a hint about final image dimensions, not about cropping rect (cropping mask) dimensions.

**Comment by DoTalkLily** [comment]
Final image dimensions is correct.  but in the earlier version this means the cropping mask dimensions. Then how to set the mask dimensions?

**Comment by DoTalkLily** [comment]
![image](https://cloud.githubusercontent.com/assets/3271333/21916386/39f08a36-d97b-11e6-8b84-65e9797244f1.png)
Like the example pic.

**Comment by DoTalkLily** [comment]
I suggest this feature be retained.

**Comment by ivpusic** [comment]
I would leave it as it is for now. Having bigger cropping mask is also good, because you have better preview about final result. width and height options are related to final image anyway.
