### ISSUE TITLE
[Request] Open cropper without picker

### ISSUE THREAD

**Issue by braco** [ivpusic/react-native-image-crop-picker#198]
It would be nice to use the cropper without the picker.

Applications that have camera roll selection often have other sources (Facebook) to choose images from.

**Comment by ivpusic** [comment]
currently I have no plans to support this

**Comment by braco** [comment]
@ivpusic - I'll submit a PR, then, any tips before I start?

**Comment by yogurtz** [comment]
@ivpusic why not supported? I agree with @braco, this seems too tightly coupled and can't be reused

**Comment by braco** [comment]
@yogurtz: I had switched to another package, but I guess this feature was added?

https://github.com/ivpusic/react-native-image-crop-picker#crop-picture

**Comment by ivpusic** [comment]
it is
