### ISSUE TITLE
Feature request: Using Camera

### ISSUE THREAD

**Issue by sunnyyants** [ivpusic/react-native-image-crop-picker#20]
Hi there,
I was using react-native-image-picker previously, and it seems like it doesn't support image cropping on Android devices very well. So I switched to this module which help me to achieve the image cropping goal. However, I realized that this module doesn't support selecting picture from camera? Is that possible to add this feature in the future? Thank you very much!

**Comment by ivpusic** [comment]
I am using this module as well and currently I don't need camera, so I don't have plans of adding camera support. PR is welcome

**Comment by ivpusic** [comment]
will close this one....as I said, PR is welcome to support camera feature
