### ISSUE TITLE
Cropping with multiple images

### ISSUE THREAD

**Issue by mschipperheyn** [ivpusic/react-native-image-crop-picker#202]
Is there a way to get to the cropping screen if you have multiple: true?

I could imagine being able to call the crop function separately against an already selected image, after the ImagePicker popup closes.

**Comment by ivpusic** [comment]
currently, I have no plans of adding such functionality. Such feature would introduce additional complexity into both java and objective c codebase, and cropping multiple times in a row is not very common. If you really need something like this, my best suggestion would be to fork library and add code for this purpose.
