### ISSUE TITLE
Manual cropping in stead of fixed window

### ISSUE THREAD

**Issue by mschipperheyn** [ivpusic/react-native-image-crop-picker#203]
The way cropping currently works is by defining a fixed window and scaling the image inside it.

That's one way to do it, but not the most common one. The most common one is to have 8 squares on each side of the image that can be moved (using ALT, you can generally constrain proportion) to get the crop window. Is this anything that could be considered?

**Comment by ivpusic** [comment]
hey, thanks for your suggestion. Currently for "cropping window" https://github.com/ruslanskorb/RSKImageCropper library is used, and you already know how it currently works. I have no plans of changing this by myself, but if you find some other library which could replace RSKImageCropper to introduce functionality you described, I would gladly accept PR from you.
