### ISSUE TITLE
Library not loaded: @rpath/QBImagePicker.framework/QBImagePicker

### ISSUE THREAD

**Issue by mschipperheyn** [ivpusic/react-native-image-crop-picker#204]
I have this weird issue where I can load my app normally from XCode but can no longer start it from the command line. I keep getting and immediate crash on startup with this error

	DYLD_FALLBACK_FRAMEWORK_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks
	DYLD_SHARED_REGION=avoid

	Dyld Error Message:
	  Library not loaded: @rpath/QBImagePicker.framework/QBImagePicker
	  Referenced from: /Users/USER/Library/Developer/CoreSimulator/Devices/77E4C570-BB05-43E6-85C7-D6B6617E6E17/data/Containers/Bundle/Application/522AAEBD-3B63-46EF-AD76-5637CF50B05B/Ology.app/Ology
	  Reason: image not found

I wonder if this has to do with the fact that I removed react-native-image-picker after installing react-native-image-crop-picker

**Comment by mschipperheyn** [comment]
Hmm, adding the the embedded libraries to General => Embedded libraries seems to solve this. Shouldn't `react-native link` take care of this?

**Comment by ivpusic** [comment]
link is not adding to embedded libraries. However I suggest that you use cocoa pods to manage all external dependencies. It will make your life easier. Check this out https://github.com/ivpusic/react-native-image-crop-picker#post-install-steps

**Comment by evernoteHW** [comment]
like this 
![image](https://user-images.githubusercontent.com/6000794/26875779-f2d0f30e-4bb5-11e7-8de2-6d34beefa749.png) This is my solution

**Comment by r01010010** [comment]
Yep, embedding the libraries manually has worked for me too @evernoteHW  @mschipperheyn , thanks for sharing

**Comment by ArsalanReal** [comment]
![screen shot 2018-08-07 at 10 38 30 pm](https://user-images.githubusercontent.com/13534911/43792608-a7061cb0-9a92-11e8-986c-db53b9b86aa7.png)

This is the solution at Xcode 9, Deployment 8.0

**Comment by r01010010** [comment]
does any one knows if the @rpath of the error must be set in pods file?

**Comment by hzz780** [comment]
> You can add two framework , below like this
> ![image](https://user-images.githubusercontent.com/6000794/26875779-f2d0f30e-4bb5-11e7-8de2-6d34beefa749.png) This is my solution

Thanks
mac 10.15.3
rn 0.59.10
"react-native-image-crop-picker": "^0.24.1",
xcode 11.3.1

**Comment by Rushabhgedam** [comment]
What to do in case of android ?
exactly how error is occured 

1. Opening app -> 
2. Reaching the screen in which ImageCropPicker imported & used -> 
3. executing ImageCropPicker.openCamera -> 
4. captures image -> click on right tick -> 
5. splash screen starts.


I saw a logger and found that it is crashing at 3rd step, and since the last 4 days am just doing all the possible solutions I can.
Error occured in Android App.
Willing to see some solution asap.
