### ISSUE TITLE
iOS10 support?

### ISSUE THREAD

**Issue by pheromone** [ivpusic/react-native-image-crop-picker#205]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker 0.11.2
- react-native 1.2.0

### Platform
Tell us to which platform this issue is related

- iOS

iOS10真机上无法使用.是否支持iOS10.
Whether to support iOS10?

**Comment by danrice01** [comment]
I'm on iOS 10.2 and it works fine.

**Comment by ivpusic** [comment]
I am using 10 as well, and works fine.

**Comment by pheromone** [comment]
![2017-01-19 5 33 04](https://cloud.githubusercontent.com/assets/14305431/22101260/aa1bbc3a-de6d-11e6-9500-ee0b617d331a.png)
I use the iPhone's iOS 9 is good, but iOS10 completely installed on the iPhone?

**Comment by ivpusic** [comment]
to me this looks like an installation issue. I suggest you to use cocoapods to manage dependencies. Take a look here https://github.com/ivpusic/react-native-image-crop-picker#post-install-steps
