### ISSUE TITLE
CocoaPods could not find compatible versions for pod "TOCropViewController"

### ISSUE THREAD

**Issue by Etaliya** [ivpusic/react-native-image-crop-picker#2059]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker "^0.41.1",
- react-native "0.72.12",

### Platform
Tell us to which platform this issue is related

- iOS

[!] CocoaPods could not find compatible versions for pod "TOCropViewController":
  In Podfile:
    RNImageCropPicker (from `../node_modules/react-native-image-crop-picker`) was resolved to 0.41.1, which depends on
      TOCropViewController (~> 2.7.4)

    react-native-image-crop-tools (from `../node_modules/react-native-image-crop-tools`) was resolved to 1.6.4, which depends on
      TOCropViewController (= 2.5.3)

3.

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by Deepak-Foodhub** [comment]
@Etaliya  pod install --repo-update has resolved this issue for me

**Comment by maha371** [comment]
@Etaliya pod update will resolve this issue.
