### ISSUE TITLE
picture portrait to landscape rotate feature

### ISSUE THREAD

**Issue by litingjun2015** [ivpusic/react-native-image-crop-picker#206]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v3.10.8
- react-native v0.39.2

### Platform
Tell us to which platform this issue is related

- iOS

### Expected behaviour

picture portrait to landscape rotate

### Actual behaviour

have no this feature

### Steps to reproduce

1. take pitcture

2. try to rotate

### Attachments

// stacktrace or any other useful debug info
![android_is_ok](https://cloud.githubusercontent.com/assets/13675353/22091857/783060ce-de34-11e6-99c1-04112836ded8.jpg)

![ios_notok](https://cloud.githubusercontent.com/assets/13675353/22091861/8813573a-de34-11e6-8da6-aa6c808aaa27.jpg)

Thanks.

**Comment by ivpusic** [comment]
currently there are no plans to introduce such feature on ios. On android it works because it is supported by uCrop library.

**Comment by litingjun2015** [comment]
Thanks for your information.

**Comment by jamesone** [comment]
@ivpusic Are you still sticking by this plan not to support portrait images on IOS?

**Comment by kholiavko-roman** [comment]
@jamesone, @litingjun2015 are you found a solution for rotation image on iOS ?
