### ISSUE TITLE
Can't run on device!

### ISSUE THREAD

**Issue by vnshgrg** [ivpusic/react-native-image-crop-picker#209]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.40.0
- react-native v0.12.1

### Platform
- iOS

### Expected behaviour
I want to run my app on on device.

### Actual behaviour
While I can run my app on a simulator I can't run it on my device.
My app is stuck at Launch Screen with error.

`dyld: Library not loaded: @rpath/RSKImageCropper.framework/RSKImageCropper
  Referenced from: /var/containers/Bundle/Application/09F0FA0F-26C3-4AA2-9D15-48CDA6A255AB/nrnjapan.app/nrnjapan
  Reason: image not found
(lldb) `

I have both the frameworks linked and also set Deployment target to 8.0.

**Comment by ivpusic** [comment]
follow this section https://github.com/ivpusic/react-native-image-crop-picker#non-cocoapods-users. You have to add some frameworks to embedded binaries, otherwise you will get this error. My suggestion is to use cocoapods to manage external libraries, it will make your life easier.

**Comment by vnshgrg** [comment]
@ivpusic I followed both cocoapods and non-cocoapods way. Nothing seem to work for me :(
I have even added frameworks to embedded binaries.

**Comment by ivpusic** [comment]
I tried it both ways, and for me it works. Tried it on the brand new project.
