### ISSUE TITLE
Build failed, no such file libReact.a

### ISSUE THREAD

**Issue by kiliwalk** [ivpusic/react-native-image-crop-picker#21]
Hi @ivpusic , I have a problem when using this package in IOS. Pod install is successful, no warnings. But when I run my project(.xcworkspace) in xcode, an error shows:
```
clang: error: no such file or directory: '/Users/kw/Library/Developer/Xcode/DerivedData/test-fohpnlfelwvgtiaczpjponpxpgyd/Build/Products/Debug-iphonesimulator/libReact.a'
```

**Comment by superandrew213** [comment]
@kiliwalk how did you fix it?

**Comment by kiliwalk** [comment]
@superandrew213 I did nothing essential and useful  about this. It's weird. 
But I could tell you what I did before working:
* Close xcode
* Open .xcproject, and goto menu File->Project Setting to see the `Derived Data` setting. (Nothing changed here)
* Open .xcworkspace
Hope these can help you

**Comment by Thorbenandresen** [comment]
I had to add `-lc++` to `Other Linker Flags` for my **MyProjectTest** target  and everything worked again. This flag was already set to **MyProject** target out of the box.

**Comment by superandrew213** [comment]
Deleting derived data in File->Project Setting and restarting Xcode seems to do the trick

**Comment by chrise86** [comment]
I'm still getting this issue even after removing derived data, adding that linker flag and removing the workspace file and re-installing pods. Any ideas? 😕

After removing the derived data (and cleaning, both methods) I get the following:

```

clang: error: no such file or directory: '/Users/chrisedwards/Library/Developer/Xcode/DerivedData/MyProject-dkunkoutwayvdrfwaifiyxrygrch/Build/Products/Debug-iphoneos/libReact.a'
clang: error: no such file or directory: '/Users/chrisedwards/Library/Developer/Xcode/DerivedData/MyProject-dkunkoutwayvdrfwaifiyxrygrch/Build/Products/Debug-iphoneos/libRCTActionSheet.a'
clang: error: no such file or directory: '/Users/chrisedwards/Library/Developer/Xcode/DerivedData/MyProject-dkunkoutwayvdrfwaifiyxrygrch/Build/Products/Debug-iphoneos/libRCTGeolocation.a'
clang: error: no such file or directory: '/Users/chrisedwards/Library/Developer/Xcode/DerivedData/MyProject-dkunkoutwayvdrfwaifiyxrygrch/Build/Products/Debug-iphoneos/libRCTImage.a'
clang: error: no such file or directory: '/Users/chrisedwards/Library/Developer/Xcode/DerivedData/MyProject-dkunkoutwayvdrfwaifiyxrygrch/Build/Products/Debug-iphoneos/libRCTLinking.a'
clang: error: no such file or directory: '/Users/chrisedwards/Library/Developer/Xcode/DerivedData/MyProject-dkunkoutwayvdrfwaifiyxrygrch/Build/Products/Debug-iphoneos/libRCTNetwork.a'
clang: error: no such file or directory: '/Users/chrisedwards/Library/Developer/Xcode/DerivedData/MyProject-dkunkoutwayvdrfwaifiyxrygrch/Build/Products/Debug-iphoneos/libRCTSettings.a'
clang: error: no such file or directory: '/Users/chrisedwards/Library/Developer/Xcode/DerivedData/MyProject-dkunkoutwayvdrfwaifiyxrygrch/Build/Products/Debug-iphoneos/libRCTText.a'
clang: error: no such file or directory: '/Users/chrisedwards/Library/Developer/Xcode/DerivedData/MyProject-dkunkoutwayvdrfwaifiyxrygrch/Build/Products/Debug-iphoneos/libRCTVibration.a'
clang: error: no such file or directory: '/Users/chrisedwards/Library/Developer/Xcode/DerivedData/MyProject-dkunkoutwayvdrfwaifiyxrygrch/Build/Products/Debug-iphoneos/libRCTWebSocket.a'
```

**Comment by chrise86** [comment]
After clearing derived data as mentioned above, then setting **Build -> Architectures -> Build Active Architecture Only** to **Yes** it clears the 20 errors above but I'm straight back to the initial:

```clang: error: no such file or directory: '/Users/chrisedwards/Library/Developer/Xcode/DerivedData/MyProject-dkunkoutwayvdrfwaifiyxrygrch/Build/Products/Debug-iphoneos/libReact.a'
```

**Comment by chrise86** [comment]
So I just reset all changes (via git), cleaned and tried again and it started working... no idea why.

**Comment by superandrew213** [comment]
@chrise86 did you restart Xcode? After cleaning everything, restarting Xcode made it work for me.

**Comment by kiliwalk** [comment]
I can reproduce this problem in my project now:
1. See project name RNTest, open RNTest. xcworkspace, and select the target device to a simulator(say iPhone 6)
2. Edit the RNTest scheme(press CMD+SHIFT+< or Product->Scheme->Edit Scheme), change Build Configuration to `Release` 
3. Build the project(from Product->Build), the error occurs!

After change the Build Configuration to `Debug` and rebuild, it's ok. 

And after I check more cases(Build Configuration and target devices), only simulator with Release build configuration will cause this problem. I'm confused with that.

**Comment by chrise86** [comment]
@superandrew213 I restarted Xcode multiple, multiple times - it's THE go-to solution with Xcode 😉, but in this case it didn't work. I edited a load of stuff in Xcode to try and make it work, none of which did, then reset all the changes I'd made, cleaned (again) and it magically worked. Very strange

**Comment by superandrew213** [comment]
@chrise86 got the error again and this fixed it properly.

Go to your build phases and remove libReact.a from the linked libraries. Then add libReact.a but select this one:
```
libReact.a from 'React' target in 'Pods' project
```

**Comment by parkerdan** [comment]
@superandrew213, You're the best!

**Comment by anotherstarburst** [comment]
Cheeres @superandrew213 ! Resolved that error, now onto the next :)

**Comment by peacechen** [comment]
After updating libReact in the linked libraries as per @superandrew213, I had to re-run `pod install` in my particular situation.  Seems like these types of errors can result from various & sundry moving parts, usually involving a change to or addition of a native library.

**Comment by giangqaz** [comment]
@superandrew213 
I cannot find `libReact.a from 'React' target in 'Pods' project`
what do i missing?

**Comment by raghunandanr** [comment]
I was facing the same issue as I had space one of the folder name. Once I deleted the space it started working for me.

**Comment by RichardLindhout** [comment]
@giangqaz Did you manage to find a solution?

**Comment by reneldegazon** [comment]
@ @giangqaz did you find a solution?

**Comment by dsemennyuk** [comment]
@superandrew213 Spasibo, bratan :)

**Comment by dhysa** [comment]
@superandrew213 Tq, you save my project !!

**Comment by lekeCoder** [comment]
after trying many previous answers, this is the answer that solved the problem for me:
   

1.  Select Target project
2. Under Build Phases
3. Select Target Dependencies
4. Add the missing library and compile
and it worked for me. This answer was given by [Ken Van](https://stackoverflow.com/questions/14947139/xcodebuild-failure-clangerror-no-such-file-or-directory)

Hope it help someone

**Comment by skyforeverGE** [comment]
reinstall react-native ```npm i react-native```

**Comment by shabeer3508** [comment]
> after trying many previous answers, this is the answer that solved the problem for me:
> 
> 1. Select Target project
> 2. Under Build Phases
> 3. Select Target Dependencies
> 4. Add the missing library and compile
>    and it worked for me. This answer was given by [Ken Van](https://stackoverflow.com/questions/14947139/xcodebuild-failure-clangerror-no-such-file-or-directory)
> 
> Hope it help someone

perfect solution it works, thank you

**Comment by nguyenmtvy** [comment]
i just simply do pod install in my ios/ folder

**Comment by lincolnbf** [comment]
> @chrise86 got the error again and this fixed it properly.
> 
> Go to your build phases and remove libReact.a from the linked libraries. Then add libReact.a but select this one:
> 
> ```
> libReact.a from 'React' target in 'Pods' project
> ```

Thanksssss!

**Comment by cristianmgb** [comment]
> Después de probar muchas respuestas anteriores, esta es la respuesta que resolvió el problema para mí:
> 
> 1. Seleccionar proyecto de destino
> 2. Bajo fases de construcción
> 3. Seleccionar dependencias objetivo
> 4. Agregue la biblioteca que falta y compile 
>    y funcionó para mí. Esta respuesta fue dada por [Ken Van](https://stackoverflow.com/questions/14947139/xcodebuild-failure-clangerror-no-such-file-or-directory)
> 
> Espero que ayude a alguien

Thanks...

**Comment by tahirramzan** [comment]
> I can reproduce this problem in my project now:
> 
> 1. See project name RNTest, open RNTest. xcworkspace, and select the target device to a simulator(say iPhone 6)
> 2. Edit the RNTest scheme(press CMD+SHIFT+< or Product->Scheme->Edit Scheme), change Build Configuration to `Release`
> 3. Build the project(from Product->Build), the error occurs!
> 
> After change the Build Configuration to `Debug` and rebuild, it's ok.
> 
> And after I check more cases(Build Configuration and target devices), only simulator with Release build configuration will cause this problem. I'm confused with that.

Same case, no error in debug but in the release, what is the solution?

**Comment by anmol-appzoy** [comment]
I also had the same problem

**Comment by Peteryar** [comment]
> after trying many previous answers, this is the answer that solved the problem for me:
> 
> 1. Select Target project
> 2. Under Build Phases
> 3. Select Target Dependencies
> 4. Add the missing library and compile
>    and it worked for me. This answer was given by [Ken Van](https://stackoverflow.com/questions/14947139/xcodebuild-failure-clangerror-no-such-file-or-directory)
> 
> Hope it help someone

This solved it for me, thanks man, after more than a week of debugging
