### ISSUE TITLE
iOS build error 'React/RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by L-Jovi** [ivpusic/react-native-image-crop-picker#210]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.12.1
- react-native v0.37.0

### Platform

- iOS

### Expected behaviour

1. build for release mode for production actually device and works fine

2. build for debug mode for develop and works fine

### Steps to reproduce

1. under fresh project, follow the [install](https://github.com/ivpusic/react-native-image-crop-picker/#install) and  in debug mode it works fine

2. compile for production at release mode and encounter error `RSKImageCropper.h not found`

3. follow the [issue 33](https://github.com/ivpusic/react-native-image-crop-picker/issues/33) and I unlink npm module by `react-native unlink react-native-image-crop-picker` and compile for production again, it works

4. and I back to continue develop, then I find that `undefined is not an object evaluating '_reactNativeImageCropPicker2.default.openPicker`.

5. I realize that maybe debug mode rely on npm module so I re-execute `react-native link react-native-image-crop-picker`

6. unlucky, I encounter the error as title say `'React/RCTBridgeModule.h' file not found`

I try many time again and again, I'm confuse that two dependence that one from __npm module for debug mode__ and another one from __cocoapod module for release mode__, maybe some step is missing by me :(

could you help me out, thanks for your smart lib, it help me a lot, I want to solve these issue.

thanks for your time,

regards.

**Comment by ivpusic** [comment]
latest version supports rn 0.40+. Use version 0.11.x for older versions of RN.

**Comment by L-Jovi** [comment]
@ivpusic  thanks for your reply :)
