### ISSUE TITLE
Android 10 error when openPicker after updating to 0.41.4

### ISSUE THREAD

**Issue by FranciscoPDNeto** [ivpusic/react-native-image-crop-picker#2104]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.41.4
- react-native v0.73.9

### Platform

- Android

### Expected behaviour

Android 10 getting permission denied, it should not request WRITE_EXTERNAL_STORAGE permission, since the maxSdkVersion was set to SDK 28 in this last version https://github.com/ivpusic/react-native-image-crop-picker/compare/v0.41.3...v0.41.4

### Actual behaviour

Android 10 getting permission denied

### Steps to reproduce

1. In android 10, call openPicker, see throwing the error "User did not grant library permission."

**Comment by chill-patel** [comment]
@FranciscoPDNeto You can update
 AndroidManifest.xml with the following code:
```xml
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:maxSdkVersion="29" tools:replace="android:maxSdkVersion"/>
```

**Comment by xhirazi** [comment]
Fixed in this [PR: 2103](https://github.com/ivpusic/react-native-image-crop-picker/pull/2103)
