### ISSUE TITLE
Getting Error "User did not grant library permission." in Android 10

### ISSUE THREAD

**Issue by SKHRAPP** [ivpusic/react-native-image-crop-picker#2105]
### Version

- react-native-image-crop-picker v0.41.4
- react-native v0.74.2

### Platform
- Android

### Expected behaviour
getting error in android 10 devices with error User did not grant library permission. recently 

code 

```
  const cropAndSendToBackend = async imagePath => {
    try {
      const croppedImage = await ImagePicker.openCropper({
        path: imagePath,
        width: 200,
        height: 200,
        cropping: true,
        cropperCircleOverlay: false, // Set to true if you want a circular crop
      });
      return croppedImage;
    } catch (error) {
      alert(error);
    } finally {
    }
  };
```

![Screenshot_20241016-103529](https://github.com/user-attachments/assets/b3978279-b516-420f-942c-2cfb93f9810c)

**Comment by Devyadav3001** [comment]
you can use "react-native-image-crop-picker": "^0.40.1",

**Comment by nishadthajudeen001** [comment]
any update on this issue?

**Comment by SSzzPP** [comment]
v0.41.4 has the same problem, downgrade to v0.41.3 fixed it.

**Comment by chill-patel** [comment]
I have updated my AndroidManifest.xml with the following code:
```xml
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:maxSdkVersion="29" tools:replace="android:maxSdkVersion"/>
```
Now it works with version 0.41.4.

**Comment by hieuminh1810** [comment]
I have the same issue

**Comment by xhirazi** [comment]
Fixed in this [PR: 2103](https://github.com/ivpusic/react-native-image-crop-picker/pull/2103)
