### ISSUE TITLE
multiple prop does not work

### ISSUE THREAD

**Issue by jeffreymendez1993** [ivpusic/react-native-image-crop-picker#211]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.11.2
- react-native v0.38.0

### Platform
Tell us to which platform this issue is related

- Android

### Expected behaviour
select multiple images before picker closing

### Actual behaviour

selects single image closes the picker

### Attachments

// stacktrace or any other useful debug info

**Comment by ivpusic** [comment]
duplicate of https://github.com/ivpusic/react-native-image-crop-picker/issues/31
