### ISSUE TITLE
Circular cropping not saving image correctly

### ISSUE THREAD

**Issue by ajonno** [ivpusic/react-native-image-crop-picker#212]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.12.1
- react-native v0.40.0

### Platform
Tell us to which platform this issue is related
- iOS & Android

### Expected behaviour
After choosing an image with the circular crop picker - the saved image should be cropped & seen as a circular image

### Actual behaviour
Looks like the original image

### Steps to reproduce
1. Open the example app from your repo, eg. iOS
2. Choose the "Select Single With Circular Cropping"
3. pick an image
4. move the image inside the 'circle' placeholder to wherever you like
5. tap on "Choose"
6. now go and inspect the saved image using Finder. i was using the absolute path by grabbing it from the renderImage(image) {.. method   eg. console.log('renderImage..: ', image.uri);
7. when you open the image its still the same, 300x300 

### Attachments
see attached

I may be completely misunderstanding the intent and/or the API, but was assuming that this circular crop feature would give me back a circular image

![2017-01-23_12-47-28](https://cloud.githubusercontent.com/assets/3005269/22188800/7abb85cc-e16c-11e6-845c-b85f091d53b4.png)
![be9e57a8-288b-4d6d-a394-63a1c39bb511](https://cloud.githubusercontent.com/assets/3005269/22188822/92ab596e-e16c-11e6-9db0-85f86d16e848.jpg)

**Comment by ivpusic** [comment]
This is expected behavior. When you want to show your images later as rounded, you can use border-radius.
