### ISSUE TITLE
GIF support

### ISSUE THREAD

**Issue by richTheCreator** [ivpusic/react-native-image-crop-picker#213]
### Version

- react-native-image-crop-picker v0.?.?
^0.10.5
- react-native v0.?.?
0.40.0

### Platform

- iOS

### Expected behaviour

GIF support. Mime types for gif.

### Actual behaviour
Every gif returns as "image/jpeg" for the mime type. 

### Steps to reproduce

1. `Call `ImagePicker.openPicker()`
2. pass it `includeBase64:true`, `cropping:false`, `width:x`, `height:x`

**Comment by ivpusic** [comment]
Fow now I have no plans of introducing gif support, but PR would be welcome. Recently there was an attempt to support dynamic mime type, but we closed it. You can check it out here https://github.com/ivpusic/react-native-image-crop-picker/pull/197

**Comment by Adarwall** [comment]
@ivpusic Is there support now?

**Comment by franciscomerdot** [comment]
@ivpusic Is there a gif support, this will be great.

**Comment by Linuhusainnk** [comment]
Is there gif support? or any other gif supporting image cropping library?
