### ISSUE TITLE
Cropper crashed on S3, android 4.3

### ISSUE THREAD

**Issue by vdlindenmark** [ivpusic/react-native-image-crop-picker#214]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.11.2
- react-native v0.39.0

### Platform
Tell us to which platform this issue is related

- Android

### Expected behaviour
Working cropper

### Actual behaviour

After selecting a photo, the cropper crashed

### Attachments

http://crashes.to/s/da63c328a62

**Comment by GalochkinKirov** [comment]
I have the same issue on Lenovo P90 Pro.

**Comment by vdlindenmark** [comment]
Somebody had a fix for this?

**Comment by ivpusic** [comment]
I have s3 on 4.3, and I cannot reproduce this issue. What photo are you trying to crop? Could you please try example project if issue happens there as well?

**Comment by vdlindenmark** [comment]
Hmm, the example works for me fine... 
Can it may be that you have resolve this error in a newer version than mine? Or have i possibly done something wrong during the installation of this module?

**Comment by GalochkinKirov** [comment]
I had resolved it by updating gulp build.

**Comment by ivpusic** [comment]
@vdlindenmark could you compare build.gradle files?

**Comment by vdlindenmark** [comment]
@ivpusic 
You are using com.android.tools.build:gradle:2.2.3
My app use com.android.tools.build:gradle:1.3.1

Maybee that causes the issue, i will check that tonight.

**Comment by ivpusic** [comment]
@vdlindenmark that would be very helpful. thanks

**Comment by vdlindenmark** [comment]
Yeah it's fixed!
i had to use com.android.tools.build:gradle:2.2.3
and i had updated the gradle version to this: distributionUrl=https\://services.gradle.org/distributions/gradle-2.14.1-all.zip
