### ISSUE TITLE
Feature request: customize background color of navigation bar

### ISSUE THREAD

**Issue by joeferraro** [ivpusic/react-native-image-crop-picker#215]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker 0.10.5
- react-native v0.38.0

### Platform
Tell us to which platform this issue is related

- iOS
- Android

### Expected behaviour
It would be great if we could specify the color of the navigation bar for the image picker.

### Actual behaviour
Currently, it seems statically set.

### Steps to reproduce

1. Open photo picker

**Comment by ivpusic** [comment]
check relese https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.14.0.
