### ISSUE TITLE
Feature request: Choose path where images are stored

### ISSUE THREAD

**Issue by Zamponotiropita** [ivpusic/react-native-image-crop-picker#217]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.10.5
- react-native v0.40

### Platform
Tell us to which platform this issue is related

- iOS
- Android

### Expected behaviour

Choose path where images are stored (disk, temp, cameraRoll). That would be really great.

### Actual behaviour

Location where images are stored is hard-coded.

### Steps to reproduce

Look at path which is returned after cropping the image.

**Comment by ivpusic** [comment]
Thanks for suggestion. Currently I have no plans of supporting this. However, I would accept PR with such feature.
