### ISSUE TITLE
Avoid save to camera roll on Android

### ISSUE THREAD

**Issue by fuleshu** [ivpusic/react-native-image-crop-picker#221]
Hi,
everything works fine for me on Android.
But when I make a picture the picture is also save in the Android camera roll directory. I tested this on two different Android phones.  I think this is just the default action from the invoked system camera app.
Is there a way to avoid this?

Thanks!

**Comment by ivpusic** [comment]
currently not, but such feature would be cool if you have some time to send pull request.
