### ISSUE TITLE
App crashes when i try to use the image picker

### ISSUE THREAD

**Issue by kill4food** [ivpusic/react-native-image-crop-picker#223]
### Version
- react-native-image-crop-picker v0.12.1
- react-native v0.40

### Platform
- Android

### Expected behaviour
show image picker when i run 
    ImagePicker.openPicker({
      multiple: true
    }).then(images => {
      console.log(images);
    });

### Actual behaviour

the app crashes and shows the following output with red background:
undefined is not an object (evaluating '_reactNativeImageCropPicker2.default.openPicker')

### Steps to reproduce
1. as i explained

**Comment by ivpusic** [comment]
this means installation is not complete. could you please follow all installation steps from readme document?
