### ISSUE TITLE
Multiple images Android version OnClick handler

### ISSUE THREAD

**Issue by kill4food** [ivpusic/react-native-image-crop-picker#224]
When i pick multiple images in android in order to pick more than one picture the user must make a long press to select the first image and then normal presses to select more images.

This is problematic when a user doesn't know that and makes a short press then it finishes and selects only a single image.

Is it possible to prevent from finishing the selection when the user makes a short click on the first selection?

**Comment by ivpusic** [comment]
currently not, because built in gallery is used, and exact behaviour depends on phone and manufacturer and android version.
