### ISSUE TITLE
loadingLabelText  is no effective

### ISSUE THREAD

**Issue by CecilLee** [ivpusic/react-native-image-crop-picker#225]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.11.2
- react-native v0.39.2

### Platform
Tell us to which platform this issue is related

- iOS
- Android

### Expected behaviour
loadingLabelText: 'chinese language: 处理中...',

### Actual behaviour

loadingLabelText still is default value

### Steps to reproduce

1.

### Attachments

// stacktrace or any other useful debug info

**Comment by ivpusic** [comment]
because feature is just on master branch, not released to npm yet. Will do it know.

**Comment by ivpusic** [comment]
https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.12.2
