### ISSUE TITLE
multiple option does not work on android

### ISSUE THREAD

**Issue by bangd** [ivpusic/react-native-image-crop-picker#227]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.12.2
- react-native v0.4.0

### Platform
Tell us to which platform this issue is related

- Android

### Expected behaviour
multiple selection

### Actual behaviour
modal immediately closed after image selection

**Comment by bangd** [comment]
sorry, need to do long press for first image to select multiple

**Comment by sergiocloud** [comment]
@bangd I don't understand how had you salved this issue, if I do long press nothing happens

**Comment by anhphamt** [comment]
It's still an issue with long press, too. Please check it soon.

**Comment by tza17313** [comment]
long press  did works, but  it's inconvenient for user
