### ISSUE TITLE
[iOS]  Favourites album is not showing

### ISSUE THREAD

**Issue by superandrew213** [ivpusic/react-native-image-crop-picker#228]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker 0.11.2
- react-native 0.39.2

### Platform
Tell us to which platform this issue is related

- iOS

### Expected behaviour

Show favourites album

### Actual behaviour

Doesn't show favourites album

**Comment by ivpusic** [comment]
library is using qbimagepickercontroller which does not have mentioned option :/. Take a look here for available options https://github.com/questbeat/QBImagePicker/blob/49b7c6c30216b91f5c6ce6e685c35a506adf4bf3/QBImagePicker/QBImagePickerController.m#L31

**Comment by lucastonon** [comment]
Is there any other way to get this to work besides forking QBImagePicker?
@superandrew213 have you find a way?

**Comment by superandrew213** [comment]
@lucastonon I think I added this a while ago. Check `smartAlbums` option in readme.
