### ISSUE TITLE
Cannot read property 'openPicker' of undefined

### ISSUE THREAD

**Issue by mattBlackDesign** [ivpusic/react-native-image-crop-picker#23]
I have installed the library using 
`npm install react-native-image-crop-picker --save`
and then I ran `npm install` again for safe measure.

I then added the following line to the header of my file 
`import ImagePicker from 'react-native-image-crop-picker';`

I am using the following function to use the image picker
`openImagePicker() {
      ImagePicker.openPicker({
        width: 300,
        height: 400,
        cropping: true
      }).then(image => {
        console.log(image);
      });
    }`
I am getting the error
`Cannot read property 'openPicker' of undefined`

I realize it's an issue with ImagePicker, but I'm not sure what I'm importing incorrectly.

**Comment by ivpusic** [comment]
probably you are missing some step in installation process. As already many people have troubles with this, I created step by step iOS installation tutorial. https://github.com/ivpusic/react-native-image-crop-picker#ios-step-by-step-installation
