### ISSUE TITLE
To use CocoaPod,Then Archive My App It tell me: 'RSKImageCropper/RSKImageCropper.h' file not found

### ISSUE THREAD

**Issue by dailinyi** [ivpusic/react-native-image-crop-picker#232]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.12.1
- react-native v0.37.0

### Platform
Tell us to which platform this issue is related

- iOS

### Expected behaviour

Success Archive

### Actual behaviour

Have a issue :  'RSKImageCropper/RSKImageCropper.h' file not found

### Steps to reproduce

1.add pod file
```
# Uncomment the next line to define a global platform for your project
platform :ios, ‘8.0’

target 'together' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  #react-native-image-crop-picker
  pod 'RSKImageCropper' , '1.5.2'
  pod 'QBImagePickerController' , '3.4.0'
  
  # Pods for together

  target 'togetherTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

2.react-native link react-native-image-crop-picker
(because react-native-image-crop-picker is already in my project)

3. coding in my RN .js

4. in xcode : product -> scheme -> edit scheme 
   select archive to change "build configuaration" to release
   product -> archive 

### Attachments

// stacktrace or any other useful debug info
xxx/node_modules/react-native-image-crop-picker/ios/ImageCropPicker.h:15:9: 'RSKImageCropper/RSKImageCropper.h' file not found

![wx20170208-211441](https://cloud.githubusercontent.com/assets/5791355/22738792/de26d68c-ee43-11e6-87db-924ddefeb8b9.png)
![wx20170208-211509](https://cloud.githubusercontent.com/assets/5791355/22738805/e8274676-ee43-11e6-8487-2a9dd33e9b66.png)

**Comment by dailinyi** [comment]
I change `#import "RSKImageCropper/RSKImageCropper.h"` to `#import <RSKImageCropper/RSKImageCropper.h>` and clean ,build . but it have this issue always

Please tell me what can I do ? Thanks!

**Comment by ranpaco** [comment]
Same Problem here, but @dailinyi solution is not working for me, and some time I get `#import "RSKImageCropper/RSKImageCropper.h"` and others `#import "QBImagePicker/QBImagePicker.h"` file not found. This error is quite frustrating.

I using:

react-native-image-crop-picker@0.12.3
react-native@0.40.0

**Comment by dailinyi** [comment]
@ranpaco 
I copy all of the react-native-image-crop-picker source file to my project (include .m & .h)
And then cocoapod RSKImageCropper and QBImagePickerController to my project
unlink react-native-image-crop-picker library
link photos.framework library
It works!
I know this is not the best way, but is the most simple way to solve this question.

Please keep open this issue until it have perfect solution.Thank you~

**Comment by L-Jovi** [comment]
I always encounter this issue in many condition, eventually I figure out that when I change schema to `release` mode to archive, it works well.
don't understand the reason :(

**Comment by L-Jovi** [comment]
@ranpaco  how do you copy the react-native-image-crop-picker source file? do you check `copy if needed`

thanks for your time.

**Comment by dailinyi** [comment]
@L-Jovi  Yeah , I checked `Copy if needed` and `Create groups` .

**Comment by L-Jovi** [comment]
@dailinyi  thanks again, I follow your idea and it works well.

**Comment by anback** [comment]
I ended up in this thread after having this problem. I actually think its linked to #193 and the explanation there is probably the most correct one but the solution is cumbersome. I was very glad when i tried a simple "clean project" step before building and now my builds are passing.

**Comment by sondremare** [comment]
@ivpusic Hi! Any progress on this issue?

**Comment by danjersoft** [comment]
I re-ran `pod install` and that fixed it for me.

**Comment by austinkettner** [comment]
Still having this issue. Looking for solutions with the `Cocoapod` approach. Anyone have any luck?

**Comment by ywein** [comment]
It happens for me also from time to time. I'am using cocoapod approach.

**Comment by dailinyi** [comment]
Yeah ,Yesterday I update my project , run `npm install ` && `pod install` .It fixed.
Thanks everyone.

**Comment by zkrige** [comment]
I had cases where pod install and clear derived data didnt work for me. I solved this by editing the imageCropPicker scheme.

- Click "build"
- Click + bottom left
- Add "RSKImageCropper" as a dependancy
- Drag this above "imageCropPicker"
- uncheck "Parallelize builds"

![screen shot 2017-07-28 at 14 25 18](https://user-images.githubusercontent.com/968412/28717078-9e22225c-73a0-11e7-9fa6-4e356762d651.png)

**Comment by kyle-ssg** [comment]
I think this issue should be reopened, I'm seeing the exact same issue (and so are others from the looks of it).

**Comment by dailinyi** [comment]
OK , I've the problem sometimes too. I'll reopen the issue. 
Before fix ,try my way at 4 Floor which copy sourses into project  please.

**Comment by jinxac** [comment]
@dailinyi can u please tell which files do you copy in the project? After i copied I am getting error saying `RCTImageView.h` is not present.

**Comment by jinxac** [comment]
@zkrige i tried adding "RSKImageCropper" as a dependancy but this is not working for me

**Comment by jinxac** [comment]
However while building with `fastlane` on my local this works fine. I am not really sure how. When i do xcode archive it throws this error but with fastlane beta(on my local) it works fine. But i guess issue is not with `fastlane` because i tried integrating CI to the build process with `bitrise`. Now `bitrise` also runs `fastlane` beta only but i see this error there.

**Comment by zkrige** [comment]
This error is extremely random. I will do 10 `fastlane` builds in a row with no problem, but on the 11th one, suddenly I get the error.

The same with xcode builds - It will work fine for a number of builds in a row, and then randomly suddenly it throws the error.

**Comment by dailinyi** [comment]
@jinxac   I copy whole project of `react-native-image-crop-picker` . 
The path in `node_modules/react-native-image-crop-picker/ios/`.
BecauseI used cocoaPods. I need exclude `ImageCropPickerSDK folder`, `QBImagePicker folder` & `RSKImageCropper folder`.
eg:
![123](https://user-images.githubusercontent.com/5791355/29152100-054e3a9e-7db8-11e7-9d2e-327fafc9b47e.png)

**Comment by BetterFanKai** [comment]
This error is extremely random when I build or Archive,I use cocoapods,I resolve it by:
1.react-native unlink react-native-image-crop-picker
2.npm uninstall react-native-image-crop-picker —save
3.remove pod 'RSKImageCropper'   pod 'QBImagePickerController' in podfile and pod install
4.install react-native-image-crop-picker again by readMe
5.clean xcode and build

**Comment by eltonlauhk01** [comment]
if use xcodebuild, or build on CI server, it will still randomly fail, annoying 👎

**Comment by wildQueequeg** [comment]
Linking #428

**Comment by CCYQ1995** [comment]
ou need to add RSKImageCropper.framework and QBImagePicker.framework to Embedded Binaries. This problem can be solved

**Comment by wildQueequeg** [comment]
@CCYQ1995 This still does not solve the problem 100% of the time

**Comment by ivpusic** [comment]
should be fixed with https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.19.1. Please try it
