### ISSUE TITLE
Feature Request: Expose Compressor as a static method

### ISSUE THREAD

**Issue by wachunei** [ivpusic/react-native-image-crop-picker#233]
We're using built in compression system when selecting and taking pictures using this module, but besides it, we have another source of images. It would be nice to, disregarding which source was used to get the image, have the same compression applied to all of the them.

**Comment by ivpusic** [comment]
thanks for suggestion. Yes, something like this would be cool, but currently I have no plans of introducing such feature by myself, but I would gladly accept PR.
