### ISSUE TITLE
crash when use cropping on nexus6p 5.1.1。

### ISSUE THREAD

**Issue by MingYe-dz** [ivpusic/react-native-image-crop-picker#234]
There is error:

TypeError: expected dynamic type 'int64', but had type 'double'

getInt
ReadableNativeMap.java:-2

setConfiguration
PickerModule.java:106

openCamera
PickerModule.java:256

---------------
I used this component on my products. So if this Serious problem has be solved as soon as possible. I will be very thankful and grateful.

**Comment by ivpusic** [comment]
could you provide js snippet you are using when this is happening?

**Comment by MingYe-dz** [comment]
![image](https://cloud.githubusercontent.com/assets/19658375/22879121/7e35c22e-f217-11e6-8052-5ceab930c014.png)

**Comment by ivpusic** [comment]
can you check if result of `deviceWidth - 80` is int?

**Comment by MingYe-dz** [comment]
deviceWidth = Dimensions.get('window').width;
the result is int. only  nexus6p 5.1.1 has this problem.

**Comment by ivpusic** [comment]
could you try putting some fixed number like 500 for with and height and then try on nexus6p 5.1.1?

**Comment by MingYe-dz** [comment]
Yeah, my fault, the deviceWidth is double on nexus6p 5.1.1 . I close this issue.
