### ISSUE TITLE
Add a license file to the repo

### ISSUE THREAD

**Issue by varungupta85** [ivpusic/react-native-image-crop-picker#236]
Although the package.json specified the license as MIT but there is no license file in the repo and I am not able to get the exact license text to ship with my app. Mainly, there are some placeholders that need to be filled in the license such as the year and the copyright holders which I can't fill myself. It would be great if you could add a LICENSE file to the repo.

**Comment by ivpusic** [comment]
tnx for suggestion. added https://github.com/ivpusic/react-native-image-crop-picker/blob/master/LICENSE
