### ISSUE TITLE
Moving/scaling/cropping not working on iPad

### ISSUE THREAD

**Issue by Matzu89** [ivpusic/react-native-image-crop-picker#238]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.12.3
- react-native v0.41.2

### Podfile

```
target 'MyImageCroppingApp' do
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'
  
  # etcetera
end
```

### Platform

- iOS

### Expected behaviour

Moving and scaling on actual device (**iPad**) while making gestures on the screen.
It does work in the simulator.

### Actual behaviour

Nothing happens on actual device (**iPad**) while making gestures on the screen. I _can_ confirm that I'm done with making my gestures, which works as expected. 
It does work in the simulator.

### Steps to reproduce

1. `npm install react-native-image-crop-picker --save`

2. `react-native link react-native-image-crop-picker`

3. `pod install`

4. Run on iPad (broken) or Simulator (working)

**Comment by ivpusic** [comment]
I never tried it on ipad device as I don't have one. Did you try it on iphone device?

**Comment by Matzu89** [comment]
Fun fact: Haven't tried it on iPhone yet, as this application is iPad only. 

Strange thing is that it does work in the iPad simulator. Did you ever encounter similar issues with the iPhone?

**Comment by ivpusic** [comment]
nope, maybe you could check RSKImageCropper library, because this one is used under the hood for cropping. maybe issue is there

**Comment by ivpusic** [comment]
RSKImageCropper is not used anymore. please try latest version with TOCropViewController
