### ISSUE TITLE
smartAlbums not support SelfPortraits

### ISSUE THREAD

**Issue by CecilLee** [ivpusic/react-native-image-crop-picker#241]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.11.2
- react-native v0.39.2

### Platform
Tell us to which platform this issue is related

- iOS

### Expected behaviour

https://developer.apple.com/reference/photos/phassetcollectionsubtype

smartAlbums support SelfPortraits

### Actual behaviour

not support SelfPortraits

### Steps to reproduce

1.

2.

3.

### Attachments

// stacktrace or any other useful debug info

**Comment by CecilLee** [comment]
need 
SelfPortraits, Imported

**Comment by ivpusic** [comment]
unfortunately, currently this is not possible because of qbimagepicker library which is user under the hood. List of smart albums is coming from there.

**Comment by srameshr** [comment]
@ivpusic What are the different list album values?

**Comment by ivpusic** [comment]
any of `['UserLibrary', 'PhotoStream', 'Panoramas', 'Videos', 'Bursts']`

**Comment by srameshr** [comment]
@ivpusic What if I want ```SelfPortraits``` or ```CloudShared``` or any of the other values specified here: https://developer.apple.com/documentation/photos/phassetcollectionsubtype
