### ISSUE TITLE
Unable to run. Uses-sdk:minSdkVersion 16 cannot be smaller than version 18

### ISSUE THREAD

**Issue by berkayk** [ivpusic/react-native-image-crop-picker#25]
Hi, I am unable to build and run this on android simulator. It is giving me the error below.

Error: uses-sdk:minSdkVersion 16 cannot be smaller than version 18 declared in library [Ogre:react-native-image-crop-picker:unspecified] C:\.......\android\app\build\intermediates\exploded-aar\Ogre\react-native-image-crop-picker\unspecified\AndroidManifest.xml
        Suggestion: use tools:overrideLibrary="com.reactnative.imagepicker" to force usage
:app:processDebugManifest FAILED

C:\......\android\app\src\main\AndroidManifest.xml:15:5-17:41 Error:
        uses-sdk:minSdkVersion 16 cannot be smaller than version 18 declared in library [Ogre:react-native-image-crop-picker:unspecified] C:\......\android\app\build\intermediates\exploded-aar\...\react-native-image-crop-picker\unspecified\AndroidManifest.xml
        Suggestion: use tools:overrideLibrary="com.reactnative.imagepicker" to force usage
:app:processDebugManifest FAILED

How can I fix this? Thanks.

**Comment by ivpusic** [comment]
as error says, use minSdkVersion 18 in your build.gradle
