### ISSUE TITLE
react-native run-android  run error

### ISSUE THREAD

**Issue by jingxin2015** [ivpusic/react-native-image-crop-picker#250]
version: 0.12.4
RN version: 0.38

:app:compileDebugJavaWithJavac
C:\Test\MainApplication.java:7: ����: ������com.reactnative.ivpusic.imagepicker������
import com.reactnative.ivpusic.imagepicker.PickerPackage;
                                          ^
C:\Test\MainApplication.java:32: ����: �Ҳ�������
            new PickerPackage(),
                ^
  ����: �� PickerPackage
2 ������
 
FAILED

FAILURE: 
Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by ivpusic** [comment]
upgrade your project to latest version of rn, or use react-native-image-crop-picker version < 0.12

**Comment by andylidong** [comment]
Did you solve it
