### ISSUE TITLE
Compressed image is larger than original

### ISSUE THREAD

**Issue by cwRichardKim** [ivpusic/react-native-image-crop-picker#252]
### Version
Tell us which versions you are using:

- react-native-image-crop-picker v0.11.2
- react-native v0.37.0

### Platform
Tell us to which platform this issue is related

- iOS

### Expected behaviour

Compressed image is smaller, or at the very least the same size as the original

### Actual behaviour

original (66kb): 
![1488041806216](https://cloud.githubusercontent.com/assets/5778691/23333224/f113f170-fb55-11e6-921e-7e31b0862b8d.jpg)

just size compression (433kb): 
![1488043261799](https://cloud.githubusercontent.com/assets/5778691/23333226/02794c26-fb56-11e6-8fc2-696880f877ac.jpg)

size and image compression (92kb): 
![14711143_10154622892393064_3707145447315550417_o](https://cloud.githubusercontent.com/assets/5778691/23333240/302d3042-fb56-11e6-9abd-9ec9849be264.jpg)

### Steps to reproduce

```
ImagePicker.openPicker({
        width: 700,
        height: 700,
        cropping: true,
        compressImageMaxHeight: 700,
        compressImageMaxWidth: 700,
        compressImageQuality: 0.6, // <- removed this for 2nd photo)
      }).then(image => {
        this._uploadPhotoToFirebase(image, index);
      }).catch(error => {
        console.log(error);
      });
```

### Attachments

// stacktrace or any other useful debug info

**Comment by fubar** [comment]
A change to skip compression in this scenario (#554) will go out with the next release. If you want to retrieve the original image without modification I'd suggest omitting all compressImage* parameters.

**Comment by superandrew213** [comment]
@ivpusic this can be closed.

**Comment by ivpusic** [comment]
tnx @superandrew213

**Comment by ivpusic** [comment]
fixed by https://github.com/ivpusic/react-native-image-crop-picker/pull/736
