### ISSUE TITLE
Service exited due to Abort trap: 6

### ISSUE THREAD

**Issue by clovs** [ivpusic/react-native-image-crop-picker#253]
Hello guys,

After install react-native-image-crop-picker
The App work fine when I build it with Xcode.
But I got  an error when I "react-native run-ios" from a terminal.
The App try launch with "powered by react-native" and abort..

Feb 27 12:00:12 cloviss-MacBook-Pro com.apple.CoreSimulator.SimDevice.D16F00EE-4D42-4322-AF16-943C4390908E.launchd_sim[522] (UIKitApplication:org.reactjs.native.example.ReactPixit[0x7d01][1186]) <Notice>: Service exited due to Abort trap: 6
Feb 27 12:00:13 cloviss-MacBook-Pro CoreSimulatorBridge[566] <Warning>: Launch successful for 'org.reactjs.native.example.ReactPixit'

my   "dependencies": {
    "@shoutem/theme": "^0.8.10",
    "@shoutem/ui": "^0.10.9",
    "react": "15.4.2",
    "react-native": "0.41.2",
    "react-native-camera": "git+https://github.com/lwansbrough/react-native-camera.git",
    "react-native-fontawesome": "^4.7.0",
    "react-native-image-crop-picker": "^0.12.4",
    "react-native-router-flux": "^3.37.0"
  },

**Comment by vahuja13** [comment]
Same error, but it doesn't work for me even if I build with xcode.

**Comment by clovs** [comment]
I resolved this issue without:

- Drag and drop the ios/ImageCropPickerSDK folder to your xcode project.

Cause it was a problem with frameworks path.  
But You still have to:

- Click on project General tab :

- Under Deployment Info set Deployment Target to 8.0

- Under Embedded Binaries click + and add RSKImageCropper.framework and QBImagePicker.framework

And done

Hope it's work with you :-)

**Comment by vahuja13** [comment]
Indeed it did. Thanks!

**Comment by ryanhomer** [comment]
You should copy the frameworks to your app bundle by adding a new **Copy Files** phase with Destination **Frameworks**

http://stackoverflow.com/a/43899868/305383
