### ISSUE TITLE
Lexical or Preprocessor Issue

### ISSUE THREAD

**Issue by nshung** [ivpusic/react-native-image-crop-picker#254]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.12.4
- react-native v0.41.0

### Platform
Tell us to which platform this issue is related

- iOS

### Expected behaviour
Run without error

### Actual behaviour
Cannot run because of the error in the screenshot

### Steps to reproduce
This happened when I updated the Xcode to the latest beta version because my app needs to run on iOS 10. 

### Attachments
![screen shot 2017-02-28 at 03 50 22](https://cloud.githubusercontent.com/assets/7210851/23390593/71dcb4ca-fd6f-11e6-9082-c838cb45d16d.png)

// stacktrace or any other useful debug info
Check dependencies

warning: no rule to process file '/Users/user1/Desktop/project1/node_modules/react-native-image-crop-picker/ios/ImageCropPicker.h' of type sourcecode.c.h for architecture armv7
warning: no rule to process file '/Users/user1/Desktop/project1/node_modules/react-native-image-crop-picker/ios/UIImage-Resize/UIImage+Resize.h' of type sourcecode.c.h for architecture armv7
warning: no rule to process file '/Users/user1/Desktop/project1/node_modules/react-native-image-crop-picker/ios/ImageCropPicker.h' of type sourcecode.c.h for architecture arm64
warning: no rule to process file '/Users/user1/Desktop/project1/node_modules/react-native-image-crop-picker/ios/UIImage-Resize/UIImage+Resize.h' ofproject1type sourcecode.c.h for architecture arm64

**Comment by harishsn** [comment]
Same issue..

**Comment by nshung** [comment]
I fixed the issue with solution from here http://stackoverflow.com/questions/10925539/lexical-or-preprocessor-issue-file-not-found-occurs-while-archiving

**Comment by harishsn** [comment]
Thanks that worked !

**Comment by nathan-charles** [comment]
After updating my xCode to 8.3 today i'm now getting this same error. And the solution above did not work for me.

**Comment by harishsn** [comment]
Had similar issue again with xcode 8.3 beta 4. However with beta 5 no issues ! did u check with beta 5 ?

**Comment by cwRichardKim** [comment]
same issue here

**Comment by cwRichardKim** [comment]
no luck with beta 5, still getting the issue image attachments:
![image](https://cloud.githubusercontent.com/assets/5778691/24486218/000f20c4-14d7-11e7-8f16-0e6193a6b67a.png)
![image](https://cloud.githubusercontent.com/assets/5778691/24486225/0565c398-14d7-11e7-96f2-a3d039d7fc9d.png)

**Comment by eiosca** [comment]
Hi @cwRichardKim , did you try to get the last version? See https://github.com/ivpusic/react-native-image-crop-picker/issues/281

**Comment by cwRichardKim** [comment]
unfortunately i'm on .29
decided it was about time to upgrade so i'm going through that process right now

**Comment by eiosca** [comment]
@cwRichardKim Okay, good Luck!

**Comment by the-mace** [comment]
I'm on react native 0.38.0 and can't upgrade now, so some of the proposed solutions here don't work. For those in the similar state, perhaps this will help:

To get past this problem I did the following:

1) Get v1.6.1 of RSKImageCropper (https://github.com/ruslanskorb/RSKImageCropper/releases/tag/1.6.1)
2) Delete RSKImageCropper.framework from my project
3) Drop new RSKImageCropper.framework into the top of my project (copy files) 
4) Open node_modules/react-native-image-crop-picker/ios and replace RSKImageCropper folder with new one from download above (#1)
5) In Xcode, Add back in the embedded binary for RSKImageCropper
6) Clean and build.

This did it for me. My react-native-image-crop-picker is at 0.11.2 for now. I can't take RN >0.38.0 without some significant changes I'm not ready yet to make (don't get me started on the whole breaking changes bit...)

**Comment by litingjun2015** [comment]
thanks @the-mace , I'm on react native 0.39.2 and have similar issue. your instructions helps.
