### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by ragnorc** [ivpusic/react-native-image-crop-picker#255]
When will different languages or custom strings be supported?

**Comment by ivpusic** [comment]
some of the internal libraries are already supporting i18n, but currently, there is no full support. I cannot promise this feature in near future, but it is definitely needed. I would gladly accept PR if you have some time for this.

**Comment by ragnorc** [comment]
Okay, any basic idea on how this could be implemented?

**Comment by yeknava** [comment]
@ragnorc 
for iOS: #125
for android: add this line to your string.xml file:
``<string name="ucrop_label_edit_photo">edit profile photo</string>``

**Comment by yeknava** [comment]
@ragnorc 
for iOS: #125
for android: add this line to your string.xml file:
``<string name="ucrop_label_edit_photo">edit profile photo</string>``

**Comment by Bodasia** [comment]
https://github.com/KBIM-dev/react-native-image-crop-picker
add possible to set custom text on picker
