### ISSUE TITLE
ios 8.4 crash EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by litingjun2015** [ivpusic/react-native-image-crop-picker#258]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v3.10.8
- react-native v0.39.2

### Platform
Tell us to which platform this issue is related

- iOS

### Actual behaviour

Crash when start

### Steps to reproduce

1. start and crash..

### Attachments

![ios](https://cloud.githubusercontent.com/assets/13675353/23540665/a8f102e4-001d-11e7-944c-a977929d0063.jpg)

![ios crash](https://cloud.githubusercontent.com/assets/13675353/23540542/d7e71ab2-001c-11e7-8094-6aa458494077.png)

**Comment by ivpusic** [comment]
this is fixed in newer versions of the library

**Comment by litingjun2015** [comment]
v0.12.7 ？

**Comment by ivpusic** [comment]
yes for example, that version has fix included, but also some earlier. You can check release notes.

**Comment by litingjun2015** [comment]
thanks.
