### ISSUE TITLE
[Android] Can't import from SD card

### ISSUE THREAD

**Issue by superandrew213** [ivpusic/react-native-image-crop-picker#259]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.11.2
- react-native v0.39.2

### Platform
Tell us to which platform this issue is related

- Android

### Expected behaviour

Be able to import from SD card.

### Actual behaviour

You can browse SD card but no media is returned.

**Comment by ivpusic** [comment]
I would like to help here, but on all devices I have, this works :/. Would be very cool if you can dig deeper into this.

**Comment by superandrew213** [comment]
@ivpusic are you sure it's working? It's not even working on the sim for me.

**Comment by ivpusic** [comment]
oh, would be great if I could reproduce this on simulator. Which simulator are you using? What version?

**Comment by superandrew213** [comment]
<img width="494" alt="screen shot 2017-03-06 at 7 15 46 pm" src="https://cloud.githubusercontent.com/assets/13059204/23603548/67b8676e-02a1-11e7-9030-eefcc15e5248.png">

**Comment by ivpusic** [comment]
could you try new version https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.12.7.

**Comment by superandrew213** [comment]
Didn't work for me. Is it working for you?

**Comment by ivpusic** [comment]
hm, yes, works for me.

**Comment by superandrew213** [comment]
You testing with same sim settings?

**Comment by ivpusic** [comment]
same same

**Comment by superandrew213** [comment]
Type [here](https://github.com/ivpusic/react-native-image-crop-picker/commit/c483a3f2f095c42522c20c39e41ac1f486ee675d#diff-bb02fac60d336bc591a1f78314ce0a2eL25) equals 0A15-2C09

**Comment by ivpusic** [comment]
for me as well, but split[1] was correct path for me, so I returned `return Environment.getExternalStorageDirectory() + "/" + split[1];`, and it was valid file path which points to real file, and file was shown on react-native app in the end. I was googling a little bit about that, but didn't find anything useful so far (it was 5min googling).

For you `return Environment.getExternalStorageDirectory() + "/" + split[1];` created invalid path or?

**Comment by superandrew213** [comment]
It does give me a path but I also get this ```image-crop-picker: Promise rejected. Cannot resolve asset path.```

**Comment by ivpusic** [comment]
hm, that means path was null or empty, but as you said you get some path, and this error should not happen, even if path is not valid => it should not be null or empty.

**Comment by superandrew213** [comment]
Sorry my bad I was trying something else there. I'm getting this:
```
03-06 23:24:57.559  3731  3731 E BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /storage/emulated/0/Pictures/1487681662759.jpeg (No such file or directory)
03-06 23:24:57.559  3731  3731 E image-crop-picker: Promise rejected. Invalid image selected
```

**Comment by superandrew213** [comment]
I'm looking at this proposed solution:
https://github.com/iPaulPro/aFileChooser/issues/58

**Comment by superandrew213** [comment]
Just tested it a bit and it seems to be working. Will do some more tests. Feel free to add it or wait for my PR tomorrow. It's late here.

**Comment by ivpusic** [comment]
Awesome! I will also try it, and let you know if I got any issues. Looking forward to PR :).
