### ISSUE TITLE
Build failed issue (like #12)

### ISSUE THREAD

**Issue by xuansontrinh** [ivpusic/react-native-image-crop-picker#26]
I still have problem with `RCTBridgeModule.h not found` after following the instructions.
I am using React Native 0.29.
This is my pod file:

```
platform :ios, '9.3'

target 'NhapHoc' do

  # Pods for NhapHoc

  source 'https://github.com/CocoaPods/Specs.git'
  pod 'React', :subspecs => ['Core', 'RCTImage', 'RCTNetwork', 'RCTText', 'RCTWebSocket'], :path => '../node_modules/react-native'
  pod 'react-native-image-crop-picker', :path => '../node_modules/react-native-image-crop-picker/ios'

end
```

**Comment by ivpusic** [comment]
did you run pod install inside ios dir and added inherited flag described in installation tutorial?

**Comment by ivpusic** [comment]
https://github.com/ivpusic/react-native-image-crop-picker#ios-step-by-step-installation

**Comment by xuansontrinh** [comment]
I already did that, but this problem just came out of nowhere.

**Comment by xuansontrinh** [comment]
I created a brand new project with your instruction and it worked. I think maybe something is wrong with the building phases of my project. I will try to figure out and get back to you later. Temporarily, I will close this problem, thank you for your help.
