### ISSUE TITLE
I need to get uri from the response but not provided

### ISSUE THREAD

**Issue by r4ggj** [ivpusic/react-native-image-crop-picker#261]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker latest
- react-native latest

### Platform
Tell us to which platform this issue is related

- iOS
- Android

I need to get uri from the response but not provided.Can you please provide this function？

**Comment by ivpusic** [comment]
uri should be returned always when `openPicker` promise resolves. Can you provide more information? Some example code, describe more...Did you follow all installation steps, etc..

**Comment by r4ggj** [comment]
promise resolves as {path:"file://xxx/xxx.jpg",data:xxx,...}

but I want to get a uri, such as {uri:"content://xxx/1235",...}

I have look up your source code.no uri return.

**Comment by ivpusic** [comment]
yes, currently this is not supported.
