### ISSUE TITLE
vectorDrawables.useSupportLibrary in README

### ISSUE THREAD

**Issue by jjdp** [ivpusic/react-native-image-crop-picker#263]
this release removed `vectorDrawables.useSupportLibrary = true` but the README says otherwise, did the lib updated it back?

**Comment by ivpusic** [comment]
hmm, I didn't quite understand question 😄 . `vectorDrawables.useSupportLibrary = true` is required, as stated in readme file. Latest release didn't remove anything regarding `vectorDrawables.useSupportLibrary = true`.

**Comment by jjdp** [comment]
woops its this one https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.9.4

**Comment by ivpusic** [comment]
just follow readme file :).

**Comment by punksta** [comment]
@ivpusic  Hello. Why `vectorDrawables.useSupportLibrary = true` is required for the library?

**Comment by CatWithNineLives** [comment]
Hello @ivpusic , adding on to the previous question, do I still need to set ```vectorDrawables.useSupportLibrary = true``` in order to use this library  if the ```minSdkVersion ``` of the app I am working on is 21 , since [API Level 21 already supports ```VectorDrawable```](https://developer.android.com/guide/topics/graphics/vector-drawable-resources).
Thanks
