### ISSUE TITLE
Issue calling image picker from modal

### ISSUE THREAD

**Issue by bsiddiqui** [ivpusic/react-native-image-crop-picker#264]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.24.1
- react-native v0.39.0

### Platform
- iOS

### Expected behaviour
- opening image picker from modal works

### Actual behaviour
- opening image picker from modal errors
```
Warning: Attempt to present <UIAlertController: 0x7f8a16d32fc0> on 
<RCTModalHostViewController: 0x7f8a16c78460> whose view is not in the window hierarchy!
```

**Comment by ivpusic** [comment]
hm, I am opening picker from modal windows and it works without any problems for me. Could you please try using most recent version.

**Comment by sfratini** [comment]
I am actually having the same issue. It seems it only happens if I modify the state right before calling the picker. I am updating the state to hide the modal box. This does not work:

```
selectImage = () => {

    this.setState({imageSelectorVisible: false});

    ImagePicker.openPicker({
      width: 900,
      height: 1200,
      cropping: true,
      compressImageQuality: 0.8,
      includeBase64: true
    }).then(image => {
      this.setState({
        imagen: image,
      });
      console.log(image);
    });

}
```

If I remove this line, it works, but of course the modal is not hiding:

`    this.setState({modalImageSelectorVisible: false});
`

I solved it by updating the state after the promise but it seems like a hack. I am fine using like this but it would be nice to know why it is happening:

```
ImagePicker.openPicker({
      width: 900,
      height: 1200,
      cropping: true,
      compressImageQuality: 0.8,
      includeBase64: true
    }).then(image => {
      this.setState({
        imagen: image,
        imageSelectorVisible: false
      });
      console.log(image);
    }).catch((error) => {
        console.log(error);
        this.setState({imageSelectorVisible: false});
    });

```

**Comment by brainbow91** [comment]
@sfratini I agree with you. Same issue here

**Comment by ivpusic** [comment]
@sfratini if modifying state is causing issue for you, then you can try `this.setState({imageSelectorVisible: false}, () => {  /* call image picker here */ })`

**Comment by YeaonLee** [comment]
this like dismiss dialog,you need set timeout about 200ms
