### ISSUE TITLE
Is it support react-native <0.40

### ISSUE THREAD

**Issue by helongbin** [ivpusic/react-native-image-crop-picker#265]
### Version
Tell us which versions you are using: 
- react-native v0.33.0

### Platform
Tell us to which platform this issue is related

- iOS only

### Issue
<img width="992" alt="screen shot 2017-03-09 at 6 25 22 pm" src="https://cloud.githubusercontent.com/assets/16235205/23746135/d42f05d2-04f5-11e7-9469-98d71d39bb7e.png">

**Comment by helongbin** [comment]
'<React/RCTBridgeModule.h>' file not found

**Comment by ivpusic** [comment]
yes, version v0.11.2 supports it, but it is recommended to upgrade because there is no more official support for < 0.40
