### ISSUE TITLE
Crash when calling .openCamera()

### ISSUE THREAD

**Issue by PavSidhu** [ivpusic/react-native-image-crop-picker#267]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.12.6
- react-native v0.42.0

### Platform
Tell us to which platform this issue is related

- iOS - Yes
- Android - Unable to test

### Expected behaviour
When calling `ImagePicker.openCamera({width: 500, height: 500})`, the camera should open.

### Actual behaviour
The app simply crashes.

### Steps to reproduce
calling the following method in my React native component:
```
openCamera () {
    ImagePicker.openCamera({width: 500, height: 500})
    .then(image => console.log(image))
  }
```

**Comment by ivpusic** [comment]
I will need more information, like stacktrace. Did you follow all installation instructions? It could be that you are missing `NSCameraUsageDescription`.

**Comment by TuNguyenThanh** [comment]
If you want to use camera picker in your project, add following to AndroidManifest.xml
<uses-permission android:name="android.permission.CAMERA"/>

**Comment by TuNguyenThanh** [comment]
If you want to use camera picker in your project, add following to AndroidManifest.xml
`<uses-permission android:name="android.permission.CAMERA"/>`

**Comment by lprhodes** [comment]
I has this and it was indeed a missing NSCameraUsageDescription
