### ISSUE TITLE
Unable to import ImagePicker

### ISSUE THREAD

**Issue by kaushikdr** [ivpusic/react-native-image-crop-picker#268]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.12.8
- react-native v0.42.0

### Platform
Tell us to which platform this issue is related

- Android

### Expected behaviour
Methods of ImagePicker should work.

### Actual behaviour
Methods are not working since ImagePicker is undefined

### Steps to reproduce

1. Installed and did post installation steps for android.

2. Imported ImagePicker for a Component
`import ImagePicker from 'react-native-image-crop-picker';`

3. Used ImagePicker.openPicker on click of a TouchableOpacity.
 `pickMultiple() {
ImagePicker.openPicker({
  multiple: true
}).then(images => {
  console.log(images);
});
}`

**Comment by ivpusic** [comment]
this means installation is not complete. Please check installation steps once again, and make sure that every single step is done.

**Comment by kaushikdr** [comment]
Did this : 
`npm i react-native-image-crop-picker --save
react-native link react-native-image-crop-picker`

Installed and linked successfully.

Then added 
`vectorDrawables.useSupportLibrary = true`
in project->android->app->build.gradle inside defaultConfig{}

Is there anything else that I need to do?

**Comment by kaushikdr** [comment]
Rebuilding the package does the trick.
