### ISSUE TITLE
library not found for -lQBImagePickerController

### ISSUE THREAD

**Issue by kokororin** [ivpusic/react-native-image-crop-picker#27]
Like #7
pod install success with no warning
```
Update all pods
Updating local specs repositories

CocoaPods 1.1.0.beta.1 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.1.0.beta.1

Analyzing dependencies
Fetching podspec for `React` from `../node_modules/react-native`
Fetching podspec for `react-native-image-crop-picker` from `../node_modules/react-native-image-crop-picker/ios`
Downloading dependencies
Using QBImagePickerController (3.4.0)
Using RSKImageCropper (1.5.1)
Using React (0.28.0)
Using UIImage-Resize (1.0.1)
Using react-native-image-crop-picker (0.4.3)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 6 dependencies from the Podfile and 5 total
pods installed.

```
but build failed in XCode..
```

ld: warning: directory not found for option '-L/Users/Kotori/Library/Developer/Xcode/DerivedData/bosspower-estwxlnmygshocelqgoskkpxmitw/Build/Products/Debug-iphonesimulator/QBImagePickerController'
ld: warning: directory not found for option '-L/Users/Kotori/Library/Developer/Xcode/DerivedData/bosspower-estwxlnmygshocelqgoskkpxmitw/Build/Products/Debug-iphonesimulator/RSKImageCropper'
ld: warning: directory not found for option '-L/Users/Kotori/Library/Developer/Xcode/DerivedData/bosspower-estwxlnmygshocelqgoskkpxmitw/Build/Products/Debug-iphonesimulator/React'
ld: warning: directory not found for option '-L/Users/Kotori/Library/Developer/Xcode/DerivedData/bosspower-estwxlnmygshocelqgoskkpxmitw/Build/Products/Debug-iphonesimulator/UIImage-Resize'
ld: warning: directory not found for option '-L/Users/Kotori/Library/Developer/Xcode/DerivedData/bosspower-estwxlnmygshocelqgoskkpxmitw/Build/Products/Debug-iphonesimulator/react-native-image-crop-picker'
ld: library not found for -lQBImagePickerController
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

**Comment by ivpusic** [comment]
probably you are missing one step in installation. Follow step by step here https://github.com/ivpusic/react-native-image-crop-picker#ios-step-by-step-installation

**Comment by kokororin** [comment]
I followed the steps and created a new RN project, but it still occurred the same error...

**Comment by ivpusic** [comment]
I just created new project and did steps from here https://github.com/ivpusic/react-native-image-crop-picker#ios-step-by-step-installation and it worked. Will close this one as probably you are missing something in installation process.

**Comment by kokororin** [comment]
Open workspace file, not project file fixed for me.Thank you.

**Comment by suinia** [comment]
@kokororin  how to fix library not found for -lQBImagePickerController?
use react-native run-ios with error and open workspace file aslo

**Comment by kokororin** [comment]
@suinia Sorry, I haven't touch RN in a long time. (version now is 0.10.x while when I use, it is 0.4.x)

**Comment by suinia** [comment]
@kokororin 谢谢 Thanks

**Comment by tavriaforever** [comment]
@kokororin great! Thanks)

**Comment by JKonTiki** [comment]
opening workspace file worked here too :) 

anyone have any idea why that might be?

**Comment by soroushchehresa** [comment]
this issue is happening when don't take complitly step 2 of Post-install steps.
manual install not working and you can only use Cocoapods.
after install pod and take steps for resolve this error **open your-project.xcworkspace file with xcode and run project from here**.

NOTE: 
your-project.xcworkspace created after take step 2 complitly in ios folder of your project.

**Comment by halileohalilei** [comment]
This happened to me when I used a different iOS version (12.0) on my Podfile other than 8.0. It seems QBImagePicker is abandoned and no new versions have been released for it for over three years. The last iOS version it supports is 8.0, hence the error.

**Comment by cchamikara** [comment]
@halileohalilei  do we have a solution for this ?

**Comment by halileohalilei** [comment]
@cchamikara I seem to have got it working fine, but can't remember what the actual problem was back then. Here's the relevant part of my working Podfile if you want to have a look at it:

```
platform :ios, '9.0'

#
# https://github.com/CocoaPods/CocoaPods/issues/4370
#
install! 'cocoapods', :deterministic_uuids => false

target 'MyProject' do
  # # this is very important to have!
  rn_path = '../node_modules/react-native'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'

  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'RNCViewpager', :path => '../node_modules/@react-native-community/viewpager'

end
...
```
