### ISSUE TITLE
Crop image depending on orientation

### ISSUE THREAD

**Issue by gerardus1995** [ivpusic/react-native-image-crop-picker#279]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.12.8?
- react-native v0.40.0?

### Platform
Tell us to which platform this issue is related

- iOS
- Android

### Expected behaviour

Is there any way the cropping width and height depends on the orientation the user took the photo? I don't know how can i get the original orientation. Something like this:

    CropPicker.openCamera({
      width: (pic is vertical )? 300 : 500,
      height:  (pic is vertical )? 500 : 300,
      cropping: true,
      includeBase64: true
    }).then(image => {
      this.uploadPicture(image);
    });

**Comment by ivpusic** [comment]
currently this is not possible. You can try some exif libraries to get image orientation.
