### ISSUE TITLE
Android 4.4.4 can't open camera

### ISSUE THREAD

**Issue by arthasAndDk** [ivpusic/react-native-image-crop-picker#283]
### Version
Tell us which versions you are using: 
- react-native-image-crop-picker v0.10.5
- react-native v0.39.2

### Platform
Tell us to which platform this issue is related
- Android 4.4.4

### Detail
PickerModule.java

private File createImageFile() throws IOException {
        String imageFileName = "image-" + UUID.randomUUID().toString();
        File path = Environment.getExternalStoragePublicDirectory(
                Environment.DIRECTORY_PICTURES);
        File image = File.createTempFile(imageFileName, ".jpg", path);

        // Save a file: path for use with ACTION_VIEW intents
        mCurrentPhotoPath = "file:" + image.getAbsolutePath();

        return image;
}

run on Android 4.4.4

if Environment.DIRECTORY_PICTURES is not exist
File.createTempFile unable to create folder automatically

so you should create Environment.DIRECTORY_PICTURES by yourself

**Comment by andrevargas** [comment]
Hello, I'm having the same issue. The JS method `ImagePicker.openCamera` doesn't produce any effect on **Android 4.4**, and after debugging with AndroidStudio I've reached the same problem reported above. Some details about my case:

#### Version
* react-native-image-crop-picker v0.12.9
* react-native 0.40.0

#### Platform
* Android 4.4 (KitKat), API level 19

#### Details
As said by @arthasAndDk, if the directory pointed by `Environment.DIRECTORY_PICTURES` doesn't exist in the file system, the method `File.createTempFile()` throws an `IOException: open failed: ENOENT (No such file or directory)`. So, for testing purposes, my code looks like this now:

```java
private File createImageFile() throws IOException {

    String imageFileName = "image-" + UUID.randomUUID().toString();
    File path = Environment.getExternalStoragePublicDirectory(
        Environment.DIRECTORY_PICTURES);
    
    // Create the directory if it doesn't exist
    if (!path.exists() && !path.isDirectory()) {
        path.mkdirs();
    }

    File image = File.createTempFile(imageFileName, ".jpg", path);

    mCurrentPhotoPath = "file:" + image.getAbsolutePath();

    return image;

}
```
...And everything works fine! I'm opening a PR with these fixes.

By the way, thanks for this awesome library, and thank you @arthasAndDk for opening and explaining this issue! :octocat:

**Comment by ivpusic** [comment]
fixed in https://github.com/ivpusic/react-native-image-crop-picker/pull/292
