### ISSUE TITLE
Build failing on ios build after updating

### ISSUE THREAD

**Issue by redvulps** [ivpusic/react-native-image-crop-picker#284]
### Version
- react-native-image-crop-picker v0.12.9
- react-native v0.40.0

### Platform
Using XCode 8.3 with iOS Emulator 10.3, no cocoapods

After updating from **react-native-image-crop-picker@0.10.5** to **react-native-image-crop-picker0.12.9** (to fix modulemap issue with new xcode), made react-native link, and proper update binaries references(tried to update search paths and other things but no luck) I'm getting the following error:

```
ld: library not found for -limageCropPicker
```

Any suggestions how can I fix it?

**Comment by magrinj** [comment]
Before deinstalling `react-native-image-crop-picker` and running `react-native link` did you unlink it ?

**Comment by redvulps** [comment]
Nope, but did it now and it worked, simple as is, thanks :) guess you should put this as a note on readme/changelog
