### ISSUE TITLE
[iOS] Problem when choosing image

### ISSUE THREAD

**Issue by xuansontrinh** [ivpusic/react-native-image-crop-picker#29]
When I defined the width and height for the chosen image, the image holder seemed to go down and lost a part of its detail, which makes the image hard to crop. Image size I defined is width: 450, height: 750. I am using RN 0.30 and iOS 9.3, Xcode 7.3. 
I have attached an example image for you to take a look.
![img_0063](https://cloud.githubusercontent.com/assets/18229317/17162320/48ea7190-53df-11e6-85e4-006e44ff88bd.jpg)

Original photo:
![img_0051](https://cloud.githubusercontent.com/assets/18229317/17162617/b81b3a98-53e1-11e6-892b-5b35b156fe09.jpg)

**Comment by ivpusic** [comment]
Tnx for reporting this. Fixed in 0.5.1 by https://github.com/ivpusic/react-native-image-crop-picker/commit/c84c392fa24ff6d86d955f66237b134abc2a0889
