### ISSUE TITLE
 Can I use a cance event?

### ISSUE THREAD

**Issue by juxiaowei** [ivpusic/react-native-image-crop-picker#291]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.12.9
- react-native v0.42.3

### Platform
 iOS

 Can I use a cance  event？

**Comment by ivpusic** [comment]
what do you mean?

**Comment by ivpusic** [comment]
closing this as question is unclear

**Comment by joeferraro** [comment]
@ivpusic I think the question may relate to forcing the `ImagePicker` to close programmatically. Is this possible? e.g. `ImagePicker.closePicker()`

**Comment by ivpusic** [comment]
right now not

**Comment by joeferraro** [comment]
@ivpusic happy to submit a PR, is this something you think would be relatively straightforward?

**Comment by ivpusic** [comment]
I would not include such functionality for now

**Comment by isaachinman** [comment]
@ivpusic Why? It seems trivial to include the ability to programmatically close the picker/cropper, and there are genuine use cases where people need to do this.

**Comment by dhiraj1site** [comment]
@ivpusic This issue - https://github.com/ivpusic/react-native-image-crop-picker/issues/959 really needs this feature
