### ISSUE TITLE
Feature request: Take multiple photos from camera

### ISSUE THREAD

**Issue by DaniAkash** [ivpusic/react-native-image-crop-picker#293]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.12.2
- react-native v0.40

### Platform

- iOS
- Android

### Expected behaviour
An option to take multiple photos from camera instead of reopening the camera repeatedly for each image.

### Actual behaviour
Currently the camera returns a single photo taken from it.

Suggestions to implement this functionality are welcome. Thanks!

**Comment by ivpusic** [comment]
hi, thanks for proposal, but currently this is our of scope for this library. However you can fork it and implement this feature to meet your requirements.

**Comment by Hamawis** [comment]
is it implimented yet?

**Comment by hadare1** [comment]
also interested :)
