### ISSUE TITLE
ImageCropPicker.h' of type sourcecode.c.h for architecture armv7

### ISSUE THREAD

**Issue by MrVisitor** [ivpusic/react-native-image-crop-picker#295]
### Version

- react-native-image-crop-picker v0.?.?
- react-native v0.43.2
- xcode 8.3.1

### Platform

- iOS

### Attachments

<img width="1238" alt="2017-04-08 17 17 01" src="https://cloud.githubusercontent.com/assets/7935653/24829704/b44370ea-1c7f-11e7-9f94-14f7ba1612fe.png">

**Comment by ivpusic** [comment]
closing with https://github.com/ivpusic/react-native-image-crop-picker/pull/489
