### ISSUE TITLE
When I change the product framework and build in the device,the app shutdown when it start，and throw a dyld which 'Reason: image not found'

### ISSUE THREAD

**Issue by SegmentControl** [ivpusic/react-native-image-crop-picker#296]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker ^0.24.1
- react-native v0.39.2

### Platform
Tell us to which platform this issue is related

- iOS

### Actual behaviour
dyld: Library not loaded: @rpath/QBImagePicker.framework/QBImagePicker
  Referenced from: /var/containers/Bundle/Application/E55120AD-2E41-4018-B86B-626369487FE2/xxxxx.app/hifaner
  Reason: image not found

**Comment by ivpusic** [comment]
check post installation steps in readme. my recommendation is to use cocoapods, then you wont get these errors
