### ISSUE TITLE
When I remove pre-build framework and add product framework then run in the device ,the app shutdown and throw 'Reason: image not found'

### ISSUE THREAD

**Issue by SegmentControl** [ivpusic/react-native-image-crop-picker#297]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker ^0.24.1
- react-native v0.39.2

### Platform
Tell us to which platform this issue is related

- iOS

### Actual behaviour
dyld: Library not loaded: @rpath/QBImagePicker.framework/QBImagePicker
  Referenced from: /var/containers/Bundle/Application/E55120AD-2E41-4018-B86B-626369487FE2/hifaner.app/hifaner
  Reason: image not found

**Comment by puzpuz** [comment]
how did you solve this problem? I run into the same problem but because of RSImageCropper.framework
