### ISSUE TITLE
Can't drop ImageCropPickerSDK in my project

### ISSUE THREAD

**Issue by rocwangv** [ivpusic/react-native-image-crop-picker#299]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker :"^0.10.9",
-  "react-native": "0.43.3",

### Platform

- iOS
- MAC OS 10.12.4 
- XCODE Version 8.3.1

### Steps to reproduce

1. Follow the doc's step , I drag the ImageCropPickerSDK folder to my project , but when I drop it , something happened like `Couldn’t communicate with a helper application.`
I know the issue maybe not made by this module , but I really have no idea for now .
I tried this:
```
xcrun git config --global user.email your@email.com
xcrun git config --global user.name "your name"
```
 BUT it does't works!!

### Attachments

![qq20170412-182238](https://cloud.githubusercontent.com/assets/15099302/24953218/118d232e-1fad-11e7-8ba8-d3a547ba9241.png)

**Comment by ivpusic** [comment]
I cannot help you here. My general suggestion is to use cocoapods, then you dont have to drag-and-drop external libraries

**Comment by rocwangv** [comment]
@ivpusic Thx anyway
