### ISSUE TITLE
use rpnm to link and build in Xcode got error

### ISSUE THREAD

**Issue by ivanzhang** [ivpusic/react-native-image-crop-picker#3]
<ReactNative Project Root>/node_modules/react-native-image-crop-picker/ios/ImageCropPicker.h:12:9: 'RCTBridgeModule.h' file not found

also tried don't use rnpm link, just manually add as Libraries and add the libios.a into Build Phase>Link Binary with Libraries...

still got the build error:
'RCTBridgeModule.h' file not found

**Comment by rakesh0r** [comment]
+1

**Comment by ivpusic** [comment]
rnpm currently is not supported. PR to support this is welcome.

https://github.com/ivpusic/react-native-image-crop-picker#ios-1

**Comment by ivpusic** [comment]
rnpm supported now https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.7.0
