### ISSUE TITLE
[Android] Allow remote media

### ISSUE THREAD

**Issue by superandrew213** [ivpusic/react-native-image-crop-picker#305]
Can we allow remote media on Android? Or is there a reason for local only?

https://github.com/ivpusic/react-native-image-crop-picker/blob/073293426fc69c7778b840d7ad7090ce369bd4db/android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java#L323

**Comment by ivpusic** [comment]
if you have some time to test it, and if it works...we can merge it

**Comment by superandrew213** [comment]
@ivpusic if you have some time can you test my current progress with this:
https://github.com/superandrew213/react-native-image-crop-picker/tree/allow-remote-media

This doesn't seems to be as easy as I thought. Google Photos (GP) & Google Drive (GD) app don't automatically download media.

I'm working on GP first (would like to do GD too. Dropbox seems to be working out of the box).

Both single and multiple images/videos are working using GP. For testing go into GP and select "Free up space" in menu to clear local media. 

When you download a video, the screen goes black. For images the Google Photos progress bar shows.

**Comment by MyGuySi** [comment]
Is there way to limit it to local files? It would help if remote files weren't even shown in the UI
