### ISSUE TITLE
Add Podspec for direct Cocoapods support

### ISSUE THREAD

**Issue by johncblandii** [ivpusic/react-native-image-crop-picker#307]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker #ed07e3
- react-native v0.42.3

### Platform
Tell us to which platform this issue is related

- iOS

### Expected behaviour

Link easily

### Actual behaviour

Fails to build too often.

### Steps to reproduce

1. See #274 

2. See #278 

3. ...etc

### Reasoning

If I could simply point to `pod 'ReactNativeImageCropPicker', path: 'node_modules/react-native-image-crop-picker'` and stop having to do all of this "add xcodeproj", etc stuff, I feel it will help considerably in using this library.

**Comment by ivpusic** [comment]
+1. Feel free to submit PR. The main problem is that a lot of people using react-native does not have ios/cocoapods background. Your suggestion could help, but it won't solve issues with installation until people know what they are doing.
