### ISSUE TITLE
Installation documentation for Android

### ISSUE THREAD

**Issue by sherwinWatson** [ivpusic/react-native-image-crop-picker#309]
### Version

- react-native-image-crop-picker v0.13.0
- react-native v0.41.2

### Platform

- Android

### Expected behaviour

Android need this step

> 

> // file: MainApplication.java
> ...
> 
> import com.reactnative.picker.PickerPackage; // import package
> 
> public class MainApplication extends ReactApplication {
> ...
>    /**
>    * A list of packages used by the app. If the app uses additional views
>    * or modules besides the default ones, add more packages here.
>    */
>     @Override
>     protected List<ReactPackage> getPackages() {
>         return Arrays.<ReactPackage>asList(
>             new MainReactPackage(),
>             new PickerPackage() // Add package
>         );
>     }
> ...
> }
> 

It's not included in final version documentation

**Comment by ivpusic** [comment]
you don't have to use this if you run `react-native link <package-name>`. That step is required if you are doing manual installation/linking of package.

**Comment by jmcartlamy** [comment]
Sorry but it is necessary to add one more step on the documentation to install `react-native-image-crop-picker` for Android. 

Indeed, running the following command `react-native link <package-name>` don't modify the `MainApplication.java` file with `react-native@0.43.4`.

As said @sherwinWatson, we need to add few lines to our `MainApplication.java` for the package to work. For me, it was : 
```
import com.reactnative.ivpusic.imagepicker.PickerPackage;
```
And in the `getPackages()` method : 
``` 
new PickerPackage()
```

**Comment by jmcartlamy** [comment]
Sorry but it is preferable to add one more step on the documentation to install correctly `react-native-image-crop-picker` for Android in case of doubt.

Indeed, running the following command `react-native link <package>` don't modify the `MainApplication.java` file when our android package name have been renamed.

As said @sherwinWatson, we need to add few lines to our `MainApplication.java` for the package to work. For me, it was : 
```
import com.reactnative.ivpusic.imagepicker.PickerPackage;
```
And in the `getPackages()` method : 
``` 
new PickerPackage()
```

**Comment by tonystaa** [comment]
1 more step:
add following to file **android/app/build.gradle**

dependencies {
.....
**compile project(':react-native-image-crop-picker')**
.....
}

**Comment by ghsa** [comment]
Thank you!!!

**Comment by noelsp** [comment]
Thanks!
