### ISSUE TITLE
not work on android

### ISSUE THREAD

**Issue by Lepinr** [ivpusic/react-native-image-crop-picker#31]
System Version : 4.4.4 (19);

---------------------------------------------------------------------------------------------------
### 2. cannot crop image. if you try it, app will be dead and open "System Clocks";
---------------------------------------------------------------------------------------------------
Console Logs : 

> 07-29 06:54:14.864 25020-25020/com.alipay.app E/VdcInflateDelegate: Exception while inflating <vector>
>                                                                 org.xmlpull.v1.XmlPullParserException: Binary XML file line #1<vector> tag requires viewportWidth > 0
>                                                                     at android.support.graphics.drawable.VectorDrawableCompat.updateStateFromTypedArray(VectorDrawableCompat.java:535)
>                                                                     at android.support.graphics.drawable.VectorDrawableCompat.inflate(VectorDrawableCompat.java:472)
>                                                                     at android.support.graphics.drawable.VectorDrawableCompat.createFromXmlInner(VectorDrawableCompat.java:436)
>                                                                     at android.support.v7.widget.AppCompatDrawableManager$VdcInflateDelegate.createFromXmlInner(AppCompatDrawableManager.java:878)
>                                                                     at android.support.v7.widget.AppCompatDrawableManager.loadDrawableFromDelegates(AppCompatDrawableManager.java:355)
>                                                                     at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:196)
>                                                                     at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:191)
>                                                                     at android.support.v7.widget.AppCompatImageHelper.loadFromAttributes(AppCompatImageHelper.java:49)
>                                                                     at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:65)
>                                                                     at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:53)
>                                                                     at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:102)
>                                                                     at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:972)
>                                                                     at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:1030)
>                                                                     at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
>                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:684)
>                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
>                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
>                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
>                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
>                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
>                                                                     at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276)
>                                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:136)
>                                                                     at com.yalantis.ucrop.UCropActivity.onCreate(UCropActivity.java:102)
>                                                                     at android.app.Activity.performCreate(Activity.java:5303)
>                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1091)
>                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2165)
>                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2255)
>                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:142)
>                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1213)
>                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                                     at android.os.Looper.loop(Looper.java:136)
>                                                                     at android.app.ActivityThread.main(ActivityThread.java:5217)
>                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
>                                                                     at java.lang.reflect.Method.invoke(Method.java:515)
>                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818)
>                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634)
>                                                                     at dalvik.system.NativeStart.main(Native Method)
> 07-29 06:54:14.874 25020-25020/com.alipay.app W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x4185ae00)
> 07-29 06:54:14.874 25020-25020/com.alipay.app E/AndroidRuntime: FATAL EXCEPTION: main
>                                                             Process: com.alipay.app, PID: 25020
>                                                             java.lang.RuntimeException: Unable to start activity ComponentInfo{com.alipay.app/com.yalantis.ucrop.UCropActivity}: android.view.InflateException: Binary XML file line #35: Error inflating class ImageView
>                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2201)
>                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2255)
>                                                                 at android.app.ActivityThread.access$800(ActivityThread.java:142)
>                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1213)
>                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                                 at android.os.Looper.loop(Looper.java:136)
>                                                                 at android.app.ActivityThread.main(ActivityThread.java:5217)
>                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
>                                                                 at java.lang.reflect.Method.invoke(Method.java:515)
>                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818)
>                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634)
>                                                                 at dalvik.system.NativeStart.main(Native Method)
>                                                              Caused by: android.view.InflateException: Binary XML file line #35: Error inflating class ImageView
>                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713)
>                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
>                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
>                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
>                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
>                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
>                                                                 at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276)
>                                                                 at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:136)
>                                                                 at com.yalantis.ucrop.UCropActivity.onCreate(UCropActivity.java:102)
>                                                                 at android.app.Activity.performCreate(Activity.java:5303)
>                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1091)
>                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2165)
>                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2255) 
>                                                                 at android.app.ActivityThread.access$800(ActivityThread.java:142) 
>                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1213) 
>                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
>                                                                 at android.os.Looper.loop(Looper.java:136) 
>                                                                 at android.app.ActivityThread.main(ActivityThread.java:5217) 
>                                                                 at java.lang.reflect.Method.invokeNative(Native Method) 
>                                                                 at java.lang.reflect.Method.invoke(Method.java:515) 
>                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818) 
>                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634) 
>                                                                 at dalvik.system.NativeStart.main(Native Method) 
>                                                              Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ucrop_vector_ic_crop.xml from drawable resource ID #0x7f020066
>                                                                 at android.content.res.Resources.loadDrawable(Resources.java:2265)
>                                                                 at android.content.res.Resources.getDrawable(Resources.java:751)
>                                                                 at android.support.v7.widget.ResourcesWrapper.getDrawable(ResourcesWrapper.java:128)
>                                                                 at android.support.v7.widget.TintResources.getDrawable(TintResources.java:45)
>                                                                 at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:323)
>                                                                 at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:201)
>                                                                 at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:191)
>                                                                 at android.support.v7.widget.AppCompatImageHelper.loadFromAttributes(AppCompatImageHelper.java:49)
>                                                                 at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:65)
>                                                                 at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:53)
>                                                                 at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:102)
>                                                                 at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:972)
>                                                                 at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:1030)
>                                                                 at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
>                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:684)
>                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
>                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
>                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
>                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
>                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
>                                                                 at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276) 
>                                                                 at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:136) 
>                                                                 at com.yalantis.ucrop.UCropActivity.onCreate(UCropActivity.java:102) 
>                                                                 at android.app.Activity.performCreate(Activity.java:5303) 
>                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1091) 
>                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2165) 
>                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2255) 
>                                                                 at android.app.ActivityThread.access$800(ActivityThread.java:142) 
>                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1213) 
>                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
>                                                                 at android.os.Looper.loop(Looper.java:136) 
>                                                                 at android.app.ActivityThread.main(ActivityThread.java:5217) 
>                                                                 at java.lang.reflect.Method.invokeNative(Native Method) 
>                                                                 at java.lang.reflect.Method.invoke(Method.java:515) 
>                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818) 
>                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634) 
>                                                                 at dalvik.system.NativeStart.main(Native Method) 
>                                                              Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
>                                                                 at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
>                                                                 at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
>                                                                 at android.content.res.Resources.loadDrawable(Resources.java:2261)
>                                                                 at android.content.res.Resources.getDrawable(Resources.java:751) 
>                                                                 at android.support.v7.widget.ResourcesWrapper.getDrawable(ResourcesWrapper.java:128) 
>                                                                 at android.support.v7.widget.TintResources.getDrawable(TintResources.java:45) 
>                                                                 at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:323) 
>                                                                 at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:201) 
>                                                                 at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:191) 
>                                                                 at android.support.v7.widget.AppCompatImageHelper.loadFromAttributes(AppCompatImageHelper.java:49) 
>                                                                 at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:65) 
>                                                                 at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:53) 
>                                                                 at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:102) 
>                                                                 at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:972) 
>                                                                 at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:1030) 
>                                                                 at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44) 
>                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:684) 
>                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
>                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
>                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
>                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
>                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
>                                                                 at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276) 
>                                                                 at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:136) 
>                                                                 at com.yalantis.ucrop.UCropActivity.onCreate(UCropActivity.java:102) 
>                                                                 at android.app.Activity.performCreate(Activity.java:5303) 
>                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1091) 
>                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2165) 
>                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2255) 
>                                                                 at android.app.ActivityThread.access$800(ActivityThread.java:142) 
>                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1213) 
>                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
>                                                                 at android.os.Looper.loop(Looper.java:136) 
>                                                                 at android.app.ActivityThread.main(ActivityThread.java:5217) 
>                                                                 at java.lang.reflect.Method.invokeNative(Native Method) 
>                                                                 at java.lang.reflect.Method.invoke(Method.java:515) 
>                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818) 
>                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634) 
>                                                                 at dalvik.system.NativeStart.main(Native Method) 
> 

---------------------------------------------------------------------------------------------------
Sorry, I don't know how to do it.

**Comment by ivpusic** [comment]
what device you are using? I tested it on Samsung Galaxy S3, S6, Nexus 5 and there it works.

Can you give me more details about your app, about image you are trying to crop and similar.

**Comment by ivpusic** [comment]
any updates here?

I have some:

1. it seems that EXTRA_ALLOW_MULTIPLE flag is just telling gallery app that it SHOULD allow multiple select, so it doesn't mean that app WILL allow multiple select. On few new phones I tried it works, but apparently it doesn't work on all older phones
2. I cannot reproduce issue you mentioned when trying to crop image. I also released new version with bitmap  decoding improvement for android, so you can try it

**Comment by Lepinr** [comment]
@ivpusic 

Oh thank your reply! 
 it normal worked on Android 5/6 and higher versions.
 but it's a pity that it doesn't work on Android4.4 :), maybe you are used higher apis.

**Comment by ssomnoremac** [comment]
@ivpusic Why do keep closing this issue and it's duplicates. There is no solution posted unless I'm missing something. On Android 6, it immediately returns an array of 1 image as soon as one is selected.

**Comment by jeffreymendez1993** [comment]
@ivpusic  This does not work on the Nexus 6p or the galaxy nexus s5 also tested on simulator as well. Can you show a video or ss of it working on your phone so we can see it working first hand.

**Comment by ivpusic** [comment]
if you want to select multiple images, long press on image, and you will be in "multiple selection mode". tried it on many android 5 and 6 phones and it works. However feature depends on phone manufacturer.

**Comment by zxyah** [comment]
@ivpusic has other way support multiple images on android ?

**Comment by AndreiCalazans** [comment]
@ivpusic  is right, it works for android, but its different of IOS, you gotta press and hold to enable multi-selection mode.

Thanks @ivpusic for your information.

**Comment by minhphung210** [comment]
@ivpusic  i think you should writing in readme for people can read 👍
