### ISSUE TITLE
Photo album created from iTunes is not in the album list from openPicker.

### ISSUE THREAD

**Issue by wenbinf** [ivpusic/react-native-image-crop-picker#311]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.12.9
- react-native v0.43.3

### Platform

- iOS

### Expected behaviour

Sync a folder of photos from iTunes on Mac, then we should be able to see the newly created album on iPhone from openPicker() of react-native-image-crop-picker. 

### Actual behaviour

The newly created album doesn't show up.

### Steps to reproduce

1. Connect iPhone to Mac and use iTunes to sync a folder of photos.

2. See the newly created album in iOS's Photos app and other apps (e.g., try changing profile photo on Twitter app)

3. Open any app that uses react-native-image-crop-picker and uses openPicker() to inspect the list of albums. The newly created album doesn't show up here.

### Attachments

N/A

**Comment by ivpusic** [comment]
this is limitation of https://github.com/questbeat/QBImagePicker which this library is using

**Comment by wenbinf** [comment]
I applied this change and it fixed the problem: https://github.com/questbeat/QBImagePicker/pull/149/files
