### ISSUE TITLE
Android : ImagePicker.openPicker multiple: true can not select more than one Images

### ISSUE THREAD

**Issue by renhongguang** [ivpusic/react-native-image-crop-picker#312]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.1.3.0
- react-native v0.42.3

### Platform
Tell us to which platform this issue is related

- Android

**Comment by yuyongmao** [comment]
i met the same problem

**Comment by sergiocloud** [comment]
@renhongguang how did you resolve this problem?
