### ISSUE TITLE
Possible Unhandled Promise Rejection

### ISSUE THREAD

**Issue by combing520** [ivpusic/react-native-image-crop-picker#316]
I add this <uses-permission android:name="android.permission.CAMERA"/>
in the  AndroidManifest.xml  of Android

But  I got this error
" Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
Error: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference"  
 when I attempt to  do this "  ImagePicker.openCamera({
              width: 300,
              height: 400,
              cropping: true
          }).then(image => {
            //   console.log(image);
            alert(image);
          });"

**Comment by ivpusic** [comment]
can you please provide more information about issue

**Comment by ivpusic** [comment]
closing because missing information

**Comment by ramsestom** [comment]
You need to add a catch(error => {}) to your api call to fix this error (That occur when user cancel the camera action for example).

**Comment by drmas** [comment]
add this to your `AndroidManifest.xml file`
```
<provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="${applicationId}.provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths" />
        </provider>
```

and add this to your `android/app/main/res/xml/provider_paths.xml`
```
<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
    <external-path name="external_files" path="."/>
</paths>
```

**Comment by chuece** [comment]
@drmas I had "android.support.file_provider_paths" error when opening camera. Your code fixed it for mey, but why do we need it?
