### ISSUE TITLE
iOS crash

### ISSUE THREAD

**Issue by batosai** [ivpusic/react-native-image-crop-picker#317]
### Version

- react-native-image-crop-picker v0.13.0
- react-native v0.42.0

### Platform

- iOS

### Installation

Manual add imageCropPicker.xcodeproj and  libimageCropPicker.a

### Compilation problem

Hi,
After libimageCropPicker.a add, launch app device crash. By xcode, it works on simulator.
By terminal `react-native run-ios`, Simulator crash.

No problem for android.

Do you have an idea ?
Thanks

**Comment by ivpusic** [comment]
please ensure that you followed all post installation steps https://github.com/ivpusic/react-native-image-crop-picker#ios

**Comment by batosai** [comment]
Sorry and thanks

**Comment by ashusdn** [comment]
I have followed all steps as mentioned but after successfully build it runs the first time when running app from SDK but it goes to the background when I try to run again in the simulator. In the device, it not working properly. 

Can you please provide any solution regarding it.

**Comment by Dock1100** [comment]
I had same issue, solved by performing [https://github.com/ivpusic/react-native-image-crop-picker#step-2](second step from post-install)
