### ISSUE TITLE
Android Activity restarts without state/image result when 'Do not keep activites' is set.

### ISSUE THREAD

**Issue by stephenlaughton** [ivpusic/react-native-image-crop-picker#318]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.13.0
- react-native v0.44.0

### Platform
Tell us to which platform this issue is related

- Android

### Expected behaviour
After an image is selected, return to the activity which called image picker, where it left off.

### Actual behaviour
Restarting the activity which called image picker. It has a new rootTag as well.

### Steps to reproduce

1. ```npm install react-native-image-crop-picker```

2.```react-native link```

3. Run on simulator or device with Android 5.1.1, API 22

### Attachments

Has anyone else seen this? I am integrating this image picker into a pre-existing codebase, but I tested on a greenfield react-native init project and it does the same thing.

**Comment by ivpusic** [comment]
cannot reproduce such behavior. can you give me more information/steps how I can verify wrong behaviour?

**Comment by stephenlaughton** [comment]
@ivpusic to reproduce the android phone needs to have 'Do not keep activities' checked in developer settings and actually applies to all android versions. i forgot this is how we set all our test devices. i will edit the initial issue. the problem seems to be that as soon as the image picker is launched, the react-native activity is killed and loses all of its state. i am not sure if figuring out a general fix is in the scope of this repo.

if anyone has dealt with this before and has a solution i'd love to hear it!

**Comment by ivpusic** [comment]
...probably not in the scope of this repo.

**Comment by wkoutre** [comment]
@stephenlaughton Did you ever figure out a solution to this?
