### ISSUE TITLE
I want to custom title of pick an image

### ISSUE THREAD

**Issue by zhangyezeng** [ivpusic/react-native-image-crop-picker#320]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.13.0
- react-native v0.42.3

### Platform
Tell us to which platform this issue is related

- Android

### Expected behaviour
custom title of pick an image

### Actual behaviour
cannot custom,it seems in java hard code

### Attachments

// stacktrace or any other useful debug info

**Comment by ivpusic** [comment]
this would be a nice extension. however, currently, I don't have time to add it. feel free to submit PR with such feature.
