### ISSUE TITLE
temporary file path problem 

### ISSUE THREAD

**Issue by amitbravo** [ivpusic/react-native-image-crop-picker#322]
- react-native-image-crop-picker ^0.12.10
- react-native 0.43.3

Platform issue: 

- iOS
- Android

### Expected behaviour
Appending Files from camera, gallery and icloud where react-native-image-crop-picker distinguishably can not make difference between older selected files and new selected files due to every time file name change because of tmp file system. 

### Actual behaviour
I am creating an app where user can select files from multiple sources at one form e.g. icloud/drives, camera and from gallery and can upload whole bunch to the server, everytime I store file names into an array so everytime I can check whether a file already selected or not. 

As camera each time produces a new image, no problem with it, it will be always a new file, to access icloud I am using react-native-document-picker which return original path of the file , so again its easy to check whether file is already picked or not 

, but it does not work with react-native-image-crop-picker because it produces always new temporary files and because it returns path to temporary directory where file name changed everytime (even on device), is there any way I get can original file name or path while selecting a file from the gallery ?
otherwise, I have to create three separate array for each type of source one for camera, one for gallery and one for cloud files.

**Comment by ivpusic** [comment]
currently, this is not possible, but such a feature would be nice to have. If you have some time to implement PR for ios/android to return original filepath I would gladly accept it.

**Comment by RameshTigeen** [comment]
when use the file upload using the tempory path then the network request failed , in the ios without using the tempory file path then the network request get the success and if the user select the camaera feature then that also return the original path then the api gets success
