### ISSUE TITLE
Don't copy images to cache

### ISSUE THREAD

**Issue by gameboyVito** [ivpusic/react-native-image-crop-picker#324]
- react-native-image-crop-picker v0.13.0
- react-native v0.44.0

### Platform
- iOS

### Expected behaviour
I only need to select multiple images from camera roll and get their uri, without using the cropping feature. However, it seems like enabling or disabling the cropping, the selected images will always be copied to a cache folder. This is a bad user experience because when I need to select more than 50 images, I will need to wait for a long time, but what I need is only to get each image's uri, instead of editing them.

Therefore, I suggest you add a new constraint to disable copy feature when `multiple` prop is set to be true, since we do not want to copy anything. Copying just wastes tons of time.

### Actual behavior
After selecting plenty of images, a loading spinner was shown for a long while. I guess the is because all selected images were copying to a cache path. However, multiple selections didn't need to use cropping method, there's no need to perform any copying action.

### Steps to reproduce
```
const images = await ImagePicker.openPicker({
                multiple: true,
                maxFiles: 60,
                mediaType: 'photo',
                loadingLabelText: '',
                showsSelectedCount: false
   });
   this.setState({images});
```

**Comment by ivpusic** [comment]
reason for creating tmp files is because you would get "permission denied" if you try to read original files from react-native app. If you find a workaround for this, I would be very interested in implementing such a feature.

**Comment by gameboyVito** [comment]
Dear author, thx for your reply. I'm curious why you can copy images from camera roll to tmp files, but returning selected images' path will encounter "permission denied"?

**Comment by digital-flowers** [comment]
can you return the original image path as an extra attribute called originalImagePath ? we can use this to make sure selected images are unique

**Comment by redwind** [comment]
Hi @gameboyVito ,thanks for your library, in my case, i would like to re-upload feature but sometime  tmp removed so i app can't find last selected image. How could i get original image path ?

Thanks !

**Comment by stoneWeb** [comment]
I also need this requirement. I just want to get the data returned by CameraRoll without any file copy or compression. How should I do that? Can you provide a parameter? Because I just want to get the image information that the user chooses, not the data.

**Comment by SnaiNeR** [comment]
Same, just need original file path and nothing else
