### ISSUE TITLE
The image from the gallery doesn't keep the correct orientation

### ISSUE THREAD

**Issue by cfontana0** [ivpusic/react-native-image-crop-picker#327]
Hi! I'm using the library on iOS and the image from the gallery doesn't keep then orientation when I choose an image with the portrait orientation.

I'm not able to reproduce it on Android.

I'm using the following versions of the libraries:
```
    "react-native-image-crop-picker": "^0.12.8",
    "react-native": "0.39.2",
```

This is my implementation:
```
 ImagePicker.openPicker({
        width: 400,
        height: 400,
        cropping: false,
        includeBase64: true,
        maxFiles: 10,
        compressVideoPreset: 'MediumQuality',
        compressImageQuality: 0.5,
        multiple: true
      }).then(images => {
         ... 
      }).catch(e => {
        ....
      })
```

Any idea?

Thanks,
Carlos

**Comment by ivpusic** [comment]
try https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.13.1

**Comment by cfontana0** [comment]
Brillant! It works! :)
