### ISSUE TITLE
Image picker not working

### ISSUE THREAD

**Issue by saurabhkapur** [ivpusic/react-native-image-crop-picker#328]
### Version

- react-native-image-crop-picker v^0.13.0
- react-native v0.43.4

### Platform

- Android

### Actual behaviour

/node_modules/react-native-image-crop-picker/android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java:31: error: cannot find symbol
import com.facebook.react.modules.core.PermissionAwareActivity;
                                      ^
  symbol:   class PermissionAwareActivity
  location: package com.facebook.react.modules.core
/node_modules/react-native-image-crop-picker/android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java:32: error: cannot find symbol
import com.facebook.react.modules.core.PermissionListener;
                                      ^
  symbol:   class PermissionListener
  location: package com.facebook.react.modules.core
/node_modules/react-native-image-crop-picker/android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java:48: error: PickerModule is not abstract and does not override abstract method onActivityResult(int,int,Intent) in ActivityEventListener
class PickerModule extends ReactContextBaseJavaModule implements ActivityEventListener {
^
/node_modules/react-native-image-crop-picker/android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java:216: error: cannot find symbol
            ((PermissionAwareActivity) activity).requestPermissions(missingPermissions.toArray(new String[missingPermissions.size()]), 1, new PermissionListener() {
                                                                                                                                              ^
  symbol:   class PermissionListener
  location: class PickerModule
/node_modules/react-native-image-crop-picker/android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java:216: error: cannot find symbol
            ((PermissionAwareActivity) activity).requestPermissions(missingPermissions.toArray(new String[missingPermissions.size()]), 1, new PermissionListener() {
              ^
  symbol:   class PermissionAwareActivity
  location: class PickerModule
/node_modules/react-native-image-crop-picker/android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java:665: error: method does not override or implement a method from a supertype
    @Override
    ^
/node_modules/react-native-image-crop-picker/android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java:676: error: method does not override or implement a method from a supertype
    @Override
    ^
7 errors
:react-native-image-crop-picker:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-image-crop-picker:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by ivpusic** [comment]
this is installation issue. please follow all steps described in readme file
