### ISSUE TITLE
how can I select pdf , word and other document files ?

### ISSUE THREAD

**Issue by amitbravo** [ivpusic/react-native-image-crop-picker#329]
### Version

- "react-native-image-crop-picker": "^0.12.10"
- react-native v0.43.3

### Platform

- Android

### Expected behaviour

As I can see my document files such as word, pdf in filemanager folder at Android with react-native-image-crop-picker, how can I select them too ?

**Comment by ivpusic** [comment]
currently this is not possible

**Comment by amitbravo** [comment]
at Android, I see google drive option in menu at picker , I observe its not picking images from drive as well, though it seems copy from drive to device, it does not pick these images either . so I am wondering if either a way to disable menu/remove drive folder icons etc or it can pick those images too .

**Comment by SwirlClinic** [comment]
A

**Comment by danna88** [comment]
Have you solved your problem?
