### ISSUE TITLE
Build failed and pod failed

### ISSUE THREAD

**Issue by magrinj** [ivpusic/react-native-image-crop-picker#33]
Hello, 

I got this error when I try to pod install:

```
Analyzing dependencies
Fetching podspec for `react-native-image-crop-picker` from `../node_modules/react-native-image-crop-picker/ios`
[!] Unable to satisfy the following requirements:

- `react-native-image-crop-picker (from `../node_modules/react-native-image-crop-picker/ios`)` required by `Podfile`

It seems like you've changed the constraints of dependency `react-native-image-crop-picker` inside your development pod `react-native-image-crop-picker`.
You should run `pod update react-native-image-crop-picker` to apply changes you've made.
```

Here my PodFile:

```
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'APPNAME' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for APPNAME

  pod 'react-native-image-crop-picker', :path => '../node_modules/react-native-image-crop-picker/ios'

  pod 'Firebase/Messaging'

  target 'APPNAMETEST' do
    inherit! :search_paths
    # Pods for testing
  end

end

```

Edit: I use react-native 0.30

Fix:

If someone come here, check if your `platform` line is commented on your PodFile and uncomment it.

**Comment by ivpusic** [comment]
cannot reproduce this. Please ensure that you are following steps from here https://github.com/ivpusic/react-native-image-crop-picker#ios-step-by-step-installation

**Comment by magrinj** [comment]
I'm going to try on a fresh project like you advice

**Comment by magrinj** [comment]
Seems to work on a fresh project, I think I find the problem, if I enable the platform line I got another error:

```
Analyzing dependencies
Fetching podspec for `react-native-image-crop-picker` from `../node_modules/react-native-image-crop-picker/ios`
[!] Unable to satisfy the following requirements:

- `React (>= 0.26.1)` required by `react-native-image-crop-picker (0.5.4)`

None of your spec sources contain a spec satisfying the dependency: `React (>= 0.26.1)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

**Comment by magrinj** [comment]
Ok I find the problem, it's totally due to the comment of platform line.
Sorry for the inconvenience! And thanks for your help! 

If someone come here, check if your `platform` line is commented on your PodFile and uncomment it.

**Comment by magrinj** [comment]
I thought it was resolved, but when I compile my project, I got this error:

'RCTBridgeModule.h' file not found.

I just check I have the `$(inherit)` flags in `Other link flags`

**Comment by ivpusic** [comment]
did you open <project_name>.xcworkspace and tried to compile it from where?

**Comment by magrinj** [comment]
Yes, and I got this error

**Comment by magrinj** [comment]
Ok, I just find why, it's because I run `rnpm link` at the beginning when I install the module, so the module is import 2 times, and with the wrong flags, it's why this problem happen, by just unlink it that's working! Thanks a lot for your help and sorry again for the inconvenience

**Comment by ottoborden** [comment]
Thanks @magrinj !!

**Comment by magrinj** [comment]
You're welcome! :)

**Comment by tomazahlin** [comment]
@magrinj Hi! I also have problem with 'RCTBridgeModule.h' file not found. I used "rnpm link", because I always used that also with other modules and I don't want 2 different ways of installing things. I did not use the podfile. What do you suggest I should do?

**Comment by magrinj** [comment]
@tomazahlin Hi ! I understand your point of view, but you don't have the choice, this module is currently not working with `rnpm link`, you must use PodFile :/
But feel free to make a PR for that! :)

**Comment by L-Jovi** [comment]
@magrinj  hi, sorry to trouble, I also encounter the same issue, and I follow doc's install step as below.

1. install npm module and link

```
npm i react-native-image-crop-picker --save
react-native link react-native-image-crop-picker
```

2. add Podfile and install pod module

__my Podfile__

```
platform :ios, '8.0'

use_frameworks!

target 'TapDB' do
  pod 'SwiftyJSON', git: 'https://github.com/SwiftyJSON/SwiftyJSON.git', branch: 'swift2'
  pod 'Charts', git: 'https://github.com/danielgindi/Charts.git', branch: 'legacy/v2'
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '2.3'
    end
  end
end
```

I know we should compile prodution framework manually, but I use `pod install` so I think it should be fine now.

and my question is, should I unlink react-native-image-crop-picker after above step? alternatively, 

```
npm i react-native-image-crop-picker --save
#(don't execaute this line) react-native link react-native-image-crop-picker 
pod install
```

thanks for your time,

regards.

**Comment by magrinj** [comment]
@L-Jovi You miss to add `react-native` in your Podfile, try to add this line above `pod 'RSKImageCropper'` and run a `pod install` again in your console:

```
  pod 'React', :path => '../node_modules/react-native'
```

Tell me if it's working :) 

PS: With Podfile, il you try to compile from `Xcode` you need to open: `"PROJECT_NAME".xcworkspace` and not `"PROJECT_NAME".xcodeproj`

**Comment by L-Jovi** [comment]
@magrinj  thanks for your reply, it works by following your method,

thanks again :)

**Comment by magrinj** [comment]
@L-Jovi Your welcome :)

**Comment by L-Jovi** [comment]
@magrinj  sorry to trouble again, I get some warning after add `pod 'React', :path => '../node_modules/react-native'`

maybe it's harmless, but how should I prevent these warning message?

![image](https://cloud.githubusercontent.com/assets/7262199/22233347/b73c87da-e22a-11e6-8681-a4a6c78d4aff.png)


thanks for your time,

regards.

**Comment by magrinj** [comment]
@L-Jovi I find a solution long time ago, but I don't remember what it was, check this solution: 

http://stackoverflow.com/questions/35309385/how-do-you-hide-the-warnings-in-react-native-ios-simulator

**Comment by L-Jovi** [comment]
@magrinj  thanks, I'll try it :)
