### ISSUE TITLE
Cancelling a selected image should take the user back to image gallery instead of rejecting the promise

### ISSUE THREAD

**Issue by varungupta85** [ivpusic/react-native-image-crop-picker#330]
### Version
Tell us which versions you are using:
- react-native-image-crop-picker v0.12.8
- react-native v0.42.0

### Platform
- iOS
- Android

### Expected behaviour
If user open image gallery to pick an image and then cancels the selected image, the user should land back in the image gallery so that he/she can select a different image. 

### Actual behaviour
If user open image gallery to pick an image and then cancels the selected image, the user should land back in the image gallery so that he/she can select a different image. Currently, the promise returned by `openPicker` is rejected and the user is taken back to the app.

### Steps to reproduce

1. Open the image picker

2. Select an image

3. Press Cancel(iOS) or X(Android)

4. User is taken back to the app. User may want to choose a different photo instead but now he has to go through the steps again.

### Attachments

// stacktrace or any other useful debug info

**Comment by ivpusic** [comment]
currently, I have no plans of implementing such a behavior. For customizing UX I suggest that you fork this repo

**Comment by ivpusic** [comment]
introduced for ios in https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.14.1
