### ISSUE TITLE
Need a bit of help 

### ISSUE THREAD

**Issue by SanchiSinghal** [ivpusic/react-native-image-crop-picker#332]
### Version
Tell us which versions you are using:

- react-native-image-crop-picker v0: 0.12.10
- react-native v0:0.42.0

### Platform
Tell us to which platform this issue is related

- iOS
- Android - currently working on android only

### Expected behaviour

1. Need the images to get saved in local images library also.
2. So the other issue is i need to get the image clicked by camera need to show it user so user can add text or emoji on top of it (new js page for this). The image should go directly after cropping to the new page with image and a text input on top of it 

### Actual behaviour

1. showing path of cache
2. But the openCamera() internally uses intent which after cropping shows the screen from where the camera is being called and then navigate to the required screen(image with a text input on top)

 P.S The imagePicker.openCamera() is called on new js only. Just the button of camera is onprevious page.On click of it, it navigate to new.js where first imagePicker.openCamera() is being called and then the image is render.

**Comment by ivpusic** [comment]
currently, you cannot get it into images library because it is saved to tmp location. If you can find some workaround for this, I would accept PR.
