### ISSUE TITLE
"undefine is not an object" ImagePicker.openPicker({

### ISSUE THREAD

**Issue by veargithub** [ivpusic/react-native-image-crop-picker#337]
### Version
Tell us which versions you are using: 

"react-native-image-crop-picker": "^0.13.1"
- react-native v0.44.0

### Platform
Tell us to which platform this issue is related

- iOS

### Actual behaviour

"undefine is not an object" which points to the line "ImagePicker.openPicker({" in app.js I copied from library

and i can not find "ImageCropPicker.h" and "ImageCropPicker.m" in my project include pods dictionary which exports the module

what's wrong? 

### Steps to reproduce

npm install 

npm link

pod install

just follow the official steps

### Attachments

// stacktrace or any other useful debug info

**Comment by ivpusic** [comment]
installation failed. follow all installation steps again and check if there are any errors

**Comment by veargithub** [comment]
after a few days effort, i find the reason is link native library

my project can not link any of native libraries

so i copy the native source code from library to my project and then modify some import path

another question is it possible that it can goto "All Photos" page directly, skipping the "Photos" page?
