### ISSUE TITLE
Doesn't this library support multiple image picker in Android?

### ISSUE THREAD

**Issue by theebi** [ivpusic/react-native-image-crop-picker#338]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.?.?
- react-native v0.?.?

### Platform
Tell us to which platform this issue is related

- iOS
- Android

### Steps to reproduce

1.

2.

3.

### Attachments

// stacktrace or any other useful debug info

**Comment by ivpusic** [comment]
yes, but this depends on the android device.
