### ISSUE TITLE
undefined is not an object(evaluating '_reactNativeImageCropPicker2.default.openCamera') 

### ISSUE THREAD

**Issue by PatWu16** [ivpusic/react-native-image-crop-picker#339]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.?.?0.13.1
- react-native v0.?.?0.43.3

### Platform
Tell us to which platform this issue is related
ios
- iOS
- Android

### Actual behaviour

undefined is not an object(evaluating '_reactNativeImageCropPicker2.default.openCamera') 

### Steps to reproduce

1.

2.

3.

### Attachments

// stacktrace or any other useful debug info

that's why?
please help

**Comment by ivpusic** [comment]
installation failed. please follow all steps from readme.
