### ISSUE TITLE
Pod failed due to missing attributes

### ISSUE THREAD

**Issue by watert** [ivpusic/react-native-image-crop-picker#34]
```
[!] The `react-native-image-crop-picker` pod failed to validate due to 2 errors:
    - ERROR | attributes: Missing required attribute `homepage`.
    - ERROR | attributes: Missing required attribute `source`.
```

**Comment by ivpusic** [comment]
cannot reproduce. Both fields are included in podspec. https://github.com/ivpusic/react-native-image-crop-picker/blob/master/ios/react-native-image-crop-picker.podspec

Probably you are doing something wrong which trying to install it. Detailed instructions here https://github.com/ivpusic/react-native-image-crop-picker#ios-step-by-step-installation
