### ISSUE TITLE
int cannot be dereferenced

### ISSUE THREAD

**Issue by kiranlak** [ivpusic/react-native-image-crop-picker#341]
### Version
- react-native-image-crop-picker v0.13.1
- react-native v0.44.2

### Platform
- Android

There is a bug in `PickerModule.java` on line 550. You are trying to dereference an `int`, resulting in a `int cannot be dereferenced` compilation error.

I suggest a fix to compare an `int` colour value to a hex string would be to replace

```
int activeWidgetColor = Color.parseColor(cropperActiveWidgetColor);
//.....
if (activeWidgetColor.equals(DEFAULT_TINT))
```

with

```
int activeWidgetColor = Color.parseColor(cropperActiveWidgetColor);
//.....
if (String.format("#%06X", (0xFFFFFF & activeWidgetColor)).equals(DEFAULT_TINT))
```

**Comment by ivpusic** [comment]
fixed by https://github.com/ivpusic/react-native-image-crop-picker/pull/345
