### ISSUE TITLE
is it possible that it can goto "All Photos" page directly, skipping the "Photos" page?

### ISSUE THREAD

**Issue by veargithub** [ivpusic/react-native-image-crop-picker#342]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.?.?
- react-native v0.?.?

### Platform
Tell us to which platform this issue is related

- iOS

is it possible that it can goto "All Photos" page directly, skipping the "Photos" page?

**Comment by ivpusic** [comment]
not right now. this library depends on qbimagepicker, if possible there, will be possible also here.
