### ISSUE TITLE
Crash on Samsung Galaxy S8

### ISSUE THREAD

**Issue by DaniAkash** [ivpusic/react-native-image-crop-picker#343]
### Version

- react-native-image-crop-picker v0.13.1
- react-native v0.40

### Platform

- Android

### Expected behaviour

- Open Android's default Image picker
- Open Android's camera to take a new picture

### Actual behaviour

- Crashing on both scenarios when using Samsung Galaxy S8 running Android 7.0

### Steps to reproduce

Crash occurs whenever `ImagePicker.openCamera()` or `ImagePicker.openPicker()` methods are called. Works fine on other android devices.

### Attachments

![screenshot_20170606-150827](https://user-images.githubusercontent.com/6841445/26863691-d257f7ce-4b71-11e7-9310-38e3e832e85e.png)
![screenshot_20170606-150930](https://user-images.githubusercontent.com/6841445/26863692-d2590e52-4b71-11e7-9689-656993031df4.png)

**Comment by ivpusic** [comment]
can you show me your code example? to me this looks like you are passing wrong configuration into functions.

**Comment by DaniAkash** [comment]
i'm using the same code for both iOS and Android
For opening the image picker:
```js
            const {height, width} = Dimensions.get('window');
            noOfImages = 3; // will be between 1-5
            isMultiple = false;
            ImagePicker.openPicker({
                width,
                height,
                cropping: false,
                multiple: Platform.OS === 'android'
                            ?
                                noOfImages === 1 && !isMultiple
                                ?
                                    false
                                :
                                    true
                            :true,
                compressImageQuality: 0.3,
                mediaType: 'photo',
                PhotoStream: ['PhotoStream'],
                maxFiles: isMultiple?noOfImages*2:noOfImages,
            })
```

For opening camera:
```js
            const {height, width} = Dimensions.get('window');
            ImagePicker.openCamera({
                width,
                height,
                cropping: false,
                compressImageQuality: 0.3,
            })
```

**Comment by ivpusic** [comment]
`width, height,` is the problem. You have to pass integer, not double.

**Comment by DaniAkash** [comment]
Yup! works after changing it to parseInt(width) and parseInt(height). Thanks for the help!!
