### ISSUE TITLE
question: how to show a photo correctly

### ISSUE THREAD

**Issue by edwardfhsiao** [ivpusic/react-native-image-crop-picker#344]
### Version

- react-native-image-crop-picker v0.13.1
- react-native v0.44.2

### Platform

- iOS

### Expected behavior

Sorry to bother you, but how to show a photo correctly after choosing it? 
I guess it is \<Image\> tag right?
Everything works like charm except the error shows when require the image:

*Error: Unknown named module: '/Users/*****/Library/Developer/CoreSimulator/Devices/CC1CF2B6-289F-44D6-9186-86B96F299049/data/Containers/Data/Application/66E21296-E77B-4D76-89B5-631FDF4614F1/tmp/react-native-image-crop-picker/8F5F5C62-E1AB-4C8B-86F8-2E11F0E39B14.jpg'*
```js
...
    ImagePicker.openPicker({
      width: 300,
      height: 400,
      cropping: true
    })
      .then(image => {
        this.setState({ image: image });
      })
...
    render(){
      return(
        <Image source={require(this.state.image.path)} />;
      )
    }
```

Did I figure it wrong?

**Comment by ivpusic** [comment]
dont require it, provide object with {uri} to source instead
