### ISSUE TITLE
How to display the image after getting the response

### ISSUE THREAD

**Issue by tested01** [ivpusic/react-native-image-crop-picker#346]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.13.1
- react-native v0.43.3

### Platform
- iOS

### Expected behaviour

Display the image after getting the response

### Actual behaviour

Nothing display on the screen 
I have printed the response on the console. Path seems the absolute path of the image.
Am I right to use the path as the uri of Image component's parameter?

let path = image.path;
    return (<Image source={{uri: path}}></Image>);

**Comment by ivpusic** [comment]
here is the example of usage https://github.com/ivpusic/react-native-image-crop-picker/blob/master/example/app.js

**Comment by tested01** [comment]
Thanks for the help.
