### ISSUE TITLE
Can't build from Xcode

### ISSUE THREAD

**Issue by EnriqueDev** [ivpusic/react-native-image-crop-picker#355]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.13.1
- react-native v0.43

### Platform
- iOS

### Expected behaviour
After pod install the project should build.

### Actual behaviour
project won't build.

### Attachments

ld: warning: directory not found for option '-F/Users/enriquem/Library/Developer/Xcode/DerivedData/Wupplier-crqjfnkinpdhptdffxxaumoabdml/Build/Products/Debug-iphoneos/QBImagePickerController'
ld: warning: directory not found for option '-F/Users/enriquem/Library/Developer/Xcode/DerivedData/Wupplier-crqjfnkinpdhptdffxxaumoabdml/Build/Products/Debug-iphoneos/RSKImageCropper'
ld: framework not found QBImagePickerController
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ivpusic** [comment]
this is an installation issue. please follow all installation steps from the readme file. I recommend using cocoapods approach.

**Comment by sakin** [comment]
For anyone else finding this, this was mentioned in another issue:
https://github.com/ivpusic/react-native-image-crop-picker/issues/27

I followed all the instructions, however i had to open the `.xcworkspace` file instead of `.xcodeproj` in order to get the build to work properly
