### ISSUE TITLE
Scale image bigger than the crop window?

### ISSUE THREAD

**Issue by binoy14** [ivpusic/react-native-image-crop-picker#356]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.12.9
- react-native v0.44.0

### Platform
Tell us to which platform this issue is related

- iOS

First of all, thank you for the great library! I am wondering if there is a way to scale out an image if it's bigger than a crop window. For instance if I set the crop window to 375x375 and if the image picked is 1080x375 is there a way to zoom out so the full image can be shown?

**Comment by AunMSheikh** [comment]
If you are looking to get your hands dirty in the node_module folder there is a  folder react-native-image-crop-picker you will find the file ImageCropPicker.m in the ios folder. In that file is where all the views for cropping are created you can try changing the dimensions there and see if you get the desired results. I suspect the method imageCropViewControllerCustomMaskRect is probably where you'd want to change the dimensions. Good luck!

**Comment by ivpusic** [comment]
yes. will close this one as for now this is out of scope for the library.
