### ISSUE TITLE
Feature Request: Preview in Photo Library

### ISSUE THREAD

**Issue by livefire2015** [ivpusic/react-native-image-crop-picker#364]
### Version

- react-native-image-crop-picker v0.13.1
- react-native v0.44.0

### Platform

- iOS

### Feature Request: Preview in Photo Library

Can you support preview for photo library in the image picker? The picker in use is QBImagePickerController that does not support it.  Or, is there any way for me to swap it with another ImagePickerController?

### Attachments

https://github.com/AwesomeDennis/DNImagePicker/blob/master/Screenshots/Untitled.gif
(credit to DNImagePicker by AwesomeDennis)

**Comment by luco** [comment]
Would be nice to set a option for showing a custom component after selecting images, such as WhatsApp does with images, for preview and edit.

**Comment by ivpusic** [comment]
@livefire2015 currently this is not supported. @luco should not be hard to show something after you receive a response from picker (in .then).
