### ISSUE TITLE
How to get original file name?

### ISSUE THREAD

**Issue by Arunkumar-Precise** [ivpusic/react-native-image-crop-picker#365]
How to get original file name? I want to show preview in my application. and also save same file name.

**Comment by ivpusic** [comment]
currently this is not possible.

**Comment by alainib** [comment]
i hope this will be available, i need to keep exif data of image avec crop :(

**Comment by ivpusic** [comment]
check latest release and response object.

**Comment by alainib** [comment]
i'm using the 0.14.2  version  ( checked in node_modules/react-native-image-crop-picker/package.json )

my code : 


pickAndCrop(cropit, circular = false) {
    ImageCropPicker.openPicker({
      width: 300,
      height: 300,
      cropping: cropit,
      cropperCircleOverlay: circular,
      compressImageMaxWidth: 640,
      compressImageMaxHeight: 480,
      compressImageQuality: 0.7,
      compressVideoPreset: "MediumQuality"
    })
      .then(image => {
        console.log("received image", image);

        this.setState({
          cropImage: {
            uri: image.path,
            width: image.width,
            height: image.height,
            mime: image.mime
          },
          librairieImagesUri: [],
          shootedImagePath: false
        });

      })
      .catch(e => {
        console.log(e);
        Alert.alert(e.message ? e.message : e);
      });
  }


in the log i have only 

	received image Object {
		size: 20101, mime: "image/jpeg", height: 300, width: 300, 
		path: "file:///storage/emulated/0/Pictures:f6838c6e-cca1-4c12-9cf9-cbc867aef9b2.jpg"
	}

what i'm missinge please ?

**Comment by ivpusic** [comment]
currently this is ios only. are you using ios?

**Comment by alainib** [comment]
thanks for response, I'm testing on android and ios same times. 
I found another solution combining your package with react-native-camera-roll-picker. I hope it will be available on both soon.

	import CameraRollPicker from "react-native-camera-roll-picker";
	import ImageCropPicker from "react-native-image-crop-picker";

	<CameraRollPicker
		scrollRenderAheadDistance={500}
		initialListSize={1}
		pageSize={3}
		groupTypes="SavedPhotos"
		batchSize={5}
		maximum={1}            
		assetType="Photos"
		imagesPerRow={3}
		imageMargin={5}
		callback={this.getSelectedImage.bind(this)}
	/>


	getSelectedImage(images, current) {
		let imagesTmp = images.map(n => {
		  ImageCropPicker.openCropper({
			path: n.uri,
			width: 300,
			height: 400
		  }).then(image => {
			this.clnj("openCropper", image);
		  });

		  Exif.getExif(n.uri)
			.then(msg => this.clnj("selected images", msg))
			.catch(msg => console.log("ERROR: " + msg));
		  return n.uri;
		});

		this.setState({
		  librairieImagesUri: imagesTmp,
		  shootedImagePath: false,
		  cropImage: false
		});
		this.toggleModalLibrairieVisible();
	  }

**Comment by dennymactav** [comment]
here to get name file  imge=this.state.image 
    myjson =JSON.stringify(imge); convert to json

**Comment by basha777** [comment]
you can get using the path `let filename = path.substring(path.lastIndexOf('/') + 1, path.length())`

**Comment by Jamal-ReachFirst** [comment]
It must be reopened

**Comment by fragilebanana16** [comment]
always return a guid for media, postman works fine, so this is a client side issue

**Comment by Meesam2000** [comment]
I was having the similar issue while picking the videos from both ios and android. it is giving me the cached fileName instead of the original one. So creating a patch to this package gives me the original filename

[react-native-image-crop-picker+0.42.0.patch](https://github.com/user-attachments/files/19395392/react-native-image-crop-picker%2B0.42.0.patch)
