### ISSUE TITLE
Archiving fails on iOS

### ISSUE THREAD

**Issue by superandrew213** [ivpusic/react-native-image-crop-picker#37]
I get the following error:

```
ld: 251 duplicate symbols for architecture arm64
```

duplicates are related to:
```
'Core', 'RCTImage', 'RCTNetwork', 'RCTText', 'RCTWebSocket'
```
which are in the podfile.

**Comment by ivpusic** [comment]
probably you are loading react-native from pod file but you have it loaded already inside you project (check libraries folder). You have to remove one and have react-native loaded from one source. Detailed instructions here https://github.com/ivpusic/react-native-image-crop-picker#ios-step-by-step-installation

**Comment by superandrew213** [comment]
Those are the instructions I followed.

**Comment by ivpusic** [comment]
https://github.com/ivpusic/react-native-image-crop-picker/commit/ac066ad1ab70af317e4d01b9e125d711b4269aa0 this commit is adding instructions which will (probably) solve your issue. Let me know if it works for you

**Comment by superandrew213** [comment]
Thanks. Do you mean remove this from podfile?
```
pod 'React', :subspecs => ['Core', 'RCTImage', 'RCTNetwork', 'RCTText', 'RCTWebSocket'], :path => '../node_modules/react-native'
```

Then run pod install. I get this error:
```
[!] Unable to satisfy the following requirements:

- `React (>= 0.26.1)` required by `react-native-image-crop-picker (0.4.2)`
```

**Comment by ivpusic** [comment]
instead of removing line completely, can you please try with `pod 'React', :path => '../node_modules/react-native'`

**Comment by superandrew213** [comment]
Thanks, it's working.
