### ISSUE TITLE
Can you change the "Move and Scale" header label text on the cropper?

### ISSUE THREAD

**Issue by larryranches** [ivpusic/react-native-image-crop-picker#370]
Is there a prop where you can customize the label text of "Move and Scale" to something like "Pinch and Zoom"

### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.13.1
- react-native v0.45.0

### Platform
- iOS
- Android

**Comment by ivpusic** [comment]
currently not. PR welcome.

**Comment by Ouadie** [comment]
This issue shouldn't be closed

**Comment by ivpusic** [comment]
this is a feature request, not an issue :).

**Comment by Ouadie** [comment]
yep you can reopen the issue and add a 'Feature Request' label and I'll do the PR.

**Comment by ivpusic** [comment]
just send a pull request and reference this issue. Thanks a lot!

**Comment by alainib** [comment]
+1 for this feature. i did'nt find how to open a new pull request, when i click on the button "new pull request" i'm redirected  to "https://github.com/ivpusic/react-native-image-crop-picker/compare"

**Comment by Ouadie** [comment]
@ivpusic sorry for my late response, this request is no longer in our scope and we've finally used another component that satisfies our need. I'll try to fix it once I have some free time.

**Comment by uinz** [comment]
@Ouadie can you share what Component did you using ?

**Comment by Ouadie** [comment]
I'm not working on that project anymore, but the team are planning to use _uploadcare_ for uploading and cropping photo. 
You can ask @loiclouvet for more information about how to use _uploadcare_ with react native

**Comment by mafiusu** [comment]
any update on that feature request? Or can anyone tell me where the title is listed in the node module, I would it change there.

**Comment by ivpusic** [comment]
implemented here https://github.com/ivpusic/react-native-image-crop-picker/pull/601
