### ISSUE TITLE
Disable Zoom in cropper

### ISSUE THREAD

**Issue by leofab86** [ivpusic/react-native-image-crop-picker#375]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.14.1
- react-native v0.45.1

### Platform
Tell us to which platform this issue is related

- iOS
- Android

### Expected behaviour
Would like to disable zoom in the image cropper.

I am wondering if there is an easy way to disable zoom. I just want user to be able to pan. Even if it is not built into this package but someone knows how to edit the settings of the source packages like uCrop, I don't mind forking my own version of this package to make these changes.

**Comment by ivpusic** [comment]
currently this is not supported.

**Comment by TareqElMasri** [comment]
When this is going to be supported?

**Comment by nihp** [comment]
Any solution to disable the cropper in this package

**Comment by qaiser-wali** [comment]
Any solution to disable the cropper in this package
