### ISSUE TITLE
can't choose more photoes on android 6.0.1

### ISSUE THREAD

**Issue by xiaoshuangshuang** [ivpusic/react-native-image-crop-picker#376]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.14.1
- react-native v0.43.3

### Platform
Tell us to which platform this issue is related

- iOS
- Android

### Expected behaviour
`MyImagePicker.openPicker({
      multiple: true,
      mediaType:"photo",
      showCropGuidelines :true,
	}).then(images => {
            console.log(images);
	});`
I hope Every time  can choose many pictures , but Every time can only choose one picture on android 6.0.1
## android 6.0.1 like this:
![android 6 0 1](https://user-images.githubusercontent.com/21165885/28236413-b838fa78-6958-11e7-8f05-e44153079d70.jpg)
## android 7.0.1 like this:
![android 7 0 1](https://user-images.githubusercontent.com/21165885/28236435-3b506d38-6959-11e7-8c00-19b1540cc5fc.png)

### Actual behaviour
I have the problem too,that I can't select multiple images on android , but on iOS is OK(some android device like:HuaWei[6.0.1],XiaoMi[5.1.1],MeiZu[5.0.1]) have different choose way

### Steps to reproduce

1.

2.

3.

### Attachments

// stacktrace or any other useful debug info

**Comment by ivpusic** [comment]
yes, this is device specific. some vendors do not have this functionality implemented, some do.

**Comment by cainiaoplayer** [comment]
@ivpusic  Hello,there is something wrong with the image-picker,it can't work at some android phone like Meizu、Huawei, what should i do to resolve it? I think it Maybe work if i can only wake the file management of android phone , because the pictures of android phone can not choose image , after long press it will come back also.

**Comment by ivpusic** [comment]
as we are not using any custom gallery, user experience will depend on OS version and device manufacturer. As you can see on some devices behavior can be different.

**Comment by cainiaoplayer** [comment]
@ivpusic Thanks for your answer ! Can you give me some advise to cope with this problem. I have to resolve it brook no delay but i can't find any useful information about custom gallery, is there other open source plug-ins that i can use ?

**Comment by yoyo0427** [comment]
@xiaoshuangshuang Have you solved the problem？
