### ISSUE TITLE
Upload to server

### ISSUE THREAD

**Issue by chrise86** [ivpusic/react-native-image-crop-picker#38]
Apologies as I know this isn't an issue with the library, but I can't find a solution anywhere.

Base64 is just too slow, especially if selecting multiple images. How do I got about uploading files via paths returned using this library? I'm using Relay inside my app and GraphQL on the server. Has anyone done this?

I can't get Relay's `getFiles` to work :(

**Comment by ivpusic** [comment]
I am using FormData and upload works well

**Comment by chrise86** [comment]
Is that with Relay? Do you have an example you could share please?

**Comment by ivpusic** [comment]
```Javascript
var photo = {
    uri: uriFromCameraRoll,
    type: 'image/jpeg',
    name: 'photo.jpg',
};

var body = new FormData();
body.append('photo', photo);
body.append('title', 'A beautiful photo!');

xhr.open('POST', serverURL);
xhr.send(body);```

sorry never used Relay, so I don't know if this works with it, but this is how I am doing it in my project

**Comment by chrise86** [comment]
For anyone who is using Relay and struggling, this is what I did:

```jsx
getFiles() {
  let files = {};

  this.props.images.map((image, idx) => {
    let pathParts = image.path.split('/');
    files[`file_${idx}`] = {
      uri: image.path,
      type: image.mime,
      name: pathParts[pathParts.length - 1]
    }
  });

  return files;
}
```

The important thing is to pass an object with `uri`, `type` and `name`.

**Comment by gopchi** [comment]
@chrise86 Hi, do you have any experience with React Native image upload. We have a custom API endpoint to upload images and when doing it with Postman everything works. The problem though is when I get the image object from the crop-picker, it does not upload the image. How should I pass the data?

Here is some of the code:

```
 let file = {
      uri: imagePath,
      type: imageType,
      name: imageName,
      size: imageSize,
  }
```

    const body = new FormData();
    body.append('file', file);


And then I pass the body to the request. 
P.S. I know that maybe somehow off topic but I could not get it to work and search some advice. The weird thing is that when I upload it with postman it works, so I don't know what is wrong. My headers are set to multipart/form-data and I have my boundary set as well. 

Would appreciate some help. :)
Thanks!

**Comment by chrise86** [comment]
@gopchi unfortunately I've only used Relay in that situation, and did exactly as mentioned above. Have you tried submitting without the `size` property - that is the only difference I can see without looking further into it.

**Comment by jlariza** [comment]
@ivpusic Hi, I am trying to send the following object

```
var profilePicture ={
  uri: "file:///data/data/com.myapp/cache/react-native…p-picker/059d9987-f8d4-481f-9002-448dadff1a0c.jpg",
  type: "image/jpeg",
  name: "059d9987-f8d4-481f-9002-448dadff1a0c.jpg"
}
data.append('profilePicture', profilePicture);
```

My debugger returns this as the sent header
```
------WebKitFormBoundary7czBhNB7z1bmRbAa
Content-Disposition: form-data; name="profilePicture"

[object Object]
------WebKitFormBoundary7czBhNB7z1bmRbAa--
```

What am I missing? I have tried it with fetch and with XMLHttpRequest and it does not work.

 Thank you,

**Comment by swarupbam** [comment]
`let file = {
                        uri: response.path,
                        type: 'image/jpeg',
                        name: response.fileName
                    }`
where response is returned from ImageCropPicker.openPicker. 
not working for me.

**Comment by tiffanym19** [comment]
I'm causing trouble with this I did all your suggestion but it is not yet working. what should be the data that need to be pass in API in able to work

**Comment by tiffanym19** [comment]
> ` let file = { uri: response.path, type: 'image/jpeg', name: response.fileName } const data = new FormData(); data.append('file',file)`
> where response is returned from ImageCropPicker.openPicker.
> not working for me.

in me either, how did you solve this?

**Comment by xang555** [comment]
> > ` let file = { uri: response.path, type: 'image/jpeg', name: response.fileName } const data = new FormData(); data.append('file',file)`
> > where response is returned from ImageCropPicker.openPicker.
> > not working for me.
> 
> in me either, how did you solve this?

can you try this solution? this is work for me
```JavaScript
import { Platform } from 'react-native'
export async function uploadProfileImage(token, image){
    try {
        const upload_body = {
            uri: image['path'],
            type: image['mime'],
            name: Platform.OS === 'ios' ? image['filename']: `my_profile_${Date.now()}.${image['mime'] === 'image/jpeg' ? 'jpg':'png'}`,
        }
        
        let _data_body = new FormData()
        _data_body.append('my_key_the_same_server_code', upload_body)
        const response = await privApi(token).patch('/users/me/profiles', _data_body, {
            headers: {
                'Content-Type': 'multipart/form-data'
            }
        })
        
        const { data, status } = response

        if (status === 204) {
            return data
        }else {
            throw status
        }

    } catch (error) {
        throw error
    }
}

should help! 
```

**Comment by RZsam** [comment]
having same problem here.
everything work fine with postman...

**Comment by re-ali** [comment]
> > > ` let file = { uri: response.path, type: 'image/jpeg', name: response.fileName } const data = new FormData(); data.append('file',file)`
> > > where response is returned from ImageCropPicker.openPicker.
> > > not working for me.
> > 
> > 
> > in me either, how did you solve this?
> 
> can you try this solution? this is work for me
> 
> ```js
> import { Platform } from 'react-native'
> export async function uploadProfileImage(token, image){
>     try {
>         const upload_body = {
>             uri: image['path'],
>             type: image['mime'],
>             name: Platform.OS === 'ios' ? image['filename']: `my_profile_${Date.now()}.${image['mime'] === 'image/jpeg' ? 'jpg':'png'}`,
>         }
>         
>         let _data_body = new FormData()
>         _data_body.append('my_key_the_same_server_code', upload_body)
>         const response = await privApi(token).patch('/users/me/profiles', _data_body, {
>             headers: {
>                 'Content-Type': 'multipart/form-data'
>             }
>         })
>         
>         const { data, status } = response
> 
>         if (status === 204) {
>             return data
>         }else {
>             throw status
>         }
> 
>     } catch (error) {
>         throw error
>     }
> }
> 
> should help! 
> ```

Its Works for me , thanks in advance.

**Comment by muganwas** [comment]
> For anyone who is using Relay and struggling, this is what I did:
> 
> ```js-jsx
> getFiles() {
>   let files = {};
> 
>   this.props.images.map((image, idx) => {
>     let pathParts = image.path.split('/');
>     files[`file_${idx}`] = {
>       uri: image.path,
>       type: image.mime,
>       name: pathParts[pathParts.length - 1]
>     }
>   });
> 
>   return files;
> }
> ```
> 
> The important thing is to pass an object with `uri`, `type` and `name`.

This works well with iOS but I'm having trouble with android, the image doesn't seem to be uploadable yet I can display it within the app.

**Comment by Sapphire8888** [comment]
Help me!!!
I am going to record Video and upload it on the server using image-crop-picker.
But I don't know what to do.
I need to source code.
Please help me!!!

**Comment by kele-leanes** [comment]
> having same problem here.
> everything work fine with postman...

Me too, have you any solution?

**Comment by aliwaqar981** [comment]
For me it's working well on ios but getting network on android. I'm using axios for api call. Any advice?

**Comment by TroubleSeven** [comment]
> For me it's working well on ios but getting network on android. I'm using axios for api call. Any advice?

me too, have u solved this problem bro?

**Comment by ils-narayanaR** [comment]
> upload

Muganwas i am facing issue in android .. Can you please help me

**Comment by Cado21** [comment]
> ` let file = { uri: response.path, type: 'image/jpeg', name: response.fileName } const data = new FormData(); data.append('file',file)` where response is returned from ImageCropPicker.openPicker. not working for me.

same issue with the others, 
I tried by doing what you are suggesting and it does not work on ios or android, then I tried to do this instead:
```
const file = {
        uri: Platform.OS === 'ios' ? `file:///${image.path}` : image.path,
        type: image.mime,
        name: image.filename || image.path.split('/').pop(),
};
const fd = new FormData();   
fd.append("file", file);

....
post using Axios
```
and this works for iOS only, and for android, I have no idea why it's not working, please help! 🙏🏻🙏🏻🙏🏻

**Comment by ils-narayanaR** [comment]
Guys i found the solution for this issue . While uploading images from android devices to services filename was missing thats we are getting white or blank . Just use below code 

       const path = image.path;
          const type = image.mime;
          const fileName = image.filename;

             var form = new FormData();
              form.append("avatar", {
                uri: path,
                type: type,
                name: Platform.OS === "ios" ? fileName : `${Date.now()}.jpg`,
              });

**Comment by Omkarmaurya** [comment]
Hi guys I know I am bit late I was having same issue since 3 days i solved it by adding this line below

 imagePicker.CutomImagePicker().then(async (image) => {
      var data = new FormData();
      data.append('picture', {
        uri: image.path,
        type: image.mime,
        name: `${new Date().getTime()}-${image.filename}`, <-------------- Add name lie this
      });
    });

**Comment by OguzEkinci** [comment]
I learned something for this title:
if you remove cropping:true parameter. upload server is working truely
![image](https://user-images.githubusercontent.com/45782857/229483109-0b585e20-e301-435a-b59d-ac47bfc37d66.png)

**Comment by denisha25** [comment]
When i upload image then getting network error in the API response some time and some time working in only Android. In iOS working fine how to fix this issue?
my libraries version 
 "react-native": "0.73.4",
 "react-native-image-crop-picker": "^0.40.3",
 "axios": "^1.6.7",
<img width="759" alt="Screenshot 2024-03-11 at 9 21 24 AM" src="https://github.com/ivpusic/react-native-image-crop-picker/assets/160586484/ee6e6cba-2b83-4869-8a91-2be6cd1470da">
