### ISSUE TITLE
[iOS]When pick a width < height image and only set "compressImageMaxWidth",will cause a {0,0}size image.

### ISSUE THREAD

**Issue by Howard-Wang-Hao** [ivpusic/react-native-image-crop-picker#382]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.14.1
- react-native v0.46.4

### Platform
Tell us to which platform this issue is related

- iOS 8.0, Xcode 8.3.3

### Expected behaviour
When pick a width < height image and only set "compressImageMaxWidth",will cause a {0,0}size image.

### Steps to reproduce

1.  Use "openPicker" with options like: { compressImageMaxWidth: 800, includeBase64: true}

2. Pick a width < height image in iPhone photo library, will cause a {0,0}size image. 

3.Finally i found this bug, in the origin code in iOS Compression.m file line 38，there are two "maxWidth" 😶

4.I have fix this bug and pull a request, hope help you that  suffer the same problem. 
 Pull request link: https://github.com/ivpusic/react-native-image-crop-picker/pull/381 

### Attachments

// stacktrace or any other useful debug info

**Comment by ivpusic** [comment]
thanks a lot! PR merged
