### ISSUE TITLE
I selected a png image on iphone, but get a jpg image. How can i fixed it? Thank you.

### ISSUE THREAD

**Issue by ShenghuGong** [ivpusic/react-native-image-crop-picker#383]
I selected a png image on iphone, but get a jpg image. How can i fixed it? 
Thank you.

### Version
- react-native-image-crop-picker v0.14.0
- react-native v0.46.2

### Platform
- iOS

### Expected behaviour
I selected a png image on iphone, get a png image.

### Actual behaviour
 get a jpg image.

**Comment by ivpusic** [comment]
currently all images are returned as jpg https://github.com/ivpusic/react-native-image-crop-picker/blob/master/ios/Compression.m#L77
