### ISSUE TITLE
A problem occurred configuring project ':react-native-image-crop-picker'.

### ISSUE THREAD

**Issue by ananddayalan** [ivpusic/react-native-image-crop-picker#39]
I'm getting the following error  on building the project. I think I followed the link steps correctly, but still getting the error below.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> A problem occurred configuring project ':react-native-image-crop-picker'.

**Comment by ananddayalan** [comment]
Sorry, the problem was on my project, some tools were missing.

**Comment by Nishthagehlot-externlabs** [comment]
which tools?? getting same error
