### ISSUE TITLE
attempt to insert nil object from objects[1]

### ISSUE THREAD

**Issue by OisinOKeeffe** [ivpusic/react-native-image-crop-picker#393]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.14.2
- react-native v0.46.4

### Platform
Tell us to which platform this issue is related

- iOS

### Expected behaviour
Photo is taken -> image is cropped -> response used in app

### Actual behaviour
Photo is taken -> image is cropped -> app crashes

### Steps to reproduce

see above

### Attachments

-[ImageCropPicker createAttachmentResponse:withLocalIdentifier:withFilename:withWidth:withHeight:withMime:withSize:withData:]
NSInvalidArgumentException: *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]

**Comment by ivpusic** [comment]
can you post code example?

**Comment by zkrige** [comment]
seeing same crash

crash is here

```
return @{
             @"path": filePath,
             @"localIdentifier": localIdentifier,
             @"filename": filename,
             @"width": width,
             @"height": height,
             @"mime": mime,
             @"size": size,
             @"data": data,
             };
```

problem is because a dictionary is being created with nil items
![screen shot 2017-07-31 at 14 52 34](https://user-images.githubusercontent.com/968412/28778524-edebedb6-75ff-11e7-8798-cd120dcf5ca9.png)

**Comment by ivpusic** [comment]
@zkrige could you send PR?

**Comment by zkrige** [comment]
will do

**Comment by zkrige** [comment]
`self.croppingFile[@"localIdentifier"]` and `self.croppingFile[@"filename"]` are read, but never initialized. In fact `self.croppingFile` is nil if cropping == false

Is it safe to pass an empty string if those values are nil?

**Comment by zkrige** [comment]
#396

**Comment by ivpusic** [comment]
thanks a lot.

**Comment by zkrige** [comment]
will be curious to see if it fixes all instances of crash. I was specifically only addressing a certain instance. There might be other uses cases that still cause crash

**Comment by ivpusic** [comment]
probably better idea would be to add this null check inside `createAttachmentResponse`. This way we would have central handling for such cases. What do you think?

**Comment by zkrige** [comment]
yes that occured to me after I hastily did the PR. Let me do another PR

**Comment by zkrige** [comment]
updated with #397

**Comment by ivpusic** [comment]
@zkrige thanks. @OisinOKeeffe could you try version https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.14.4?

**Comment by ivpusic** [comment]
try the latest version. the issue should not appear anymore.
