### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by archieherbias** [ivpusic/react-native-image-crop-picker#399]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.?.?
    0.14.4
- react-native v0.?.?
    0.45.1

### Platform
Tell us to which platform this issue is related
- Android

### Expected behaviour
I want to customize the "open" button (can be seen on the attached file) on the picker when you select multiple images. I want it to have a background color. Is this possible? I tried changing the theme but it's not working.

### Steps to reproduce

1. Just open the image picker

### Attachments
![screenshot from 2017-08-02 09-43-07](https://user-images.githubusercontent.com/9944872/28854061-669ec20c-7767-11e7-8346-243d80017d33.png)

**Comment by ivpusic** [comment]
currently not
