### ISSUE TITLE
[Android] [react-native-navigation] cannot requestPermissions

### ISSUE THREAD

**Issue by lipingruan** [ivpusic/react-native-image-crop-picker#400]
### Version

- react-native-image-crop-picker v0.14.1
- react-native-navigation v1.1.142
- react-native v0.46.4

### Platform

- [ ] iOS
- [x] Android

### Expected behaviour

it will alert to request permission

### Actual behaviour

crash or no any response

### Attachments
<pre>
08-02 00:35:27.406 12873 12975 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
08-02 00:35:27.406 12873 12975 E AndroidRuntime: Process: com.helloworld, PID: 12873
08-02 00:35:27.406 12873 12975 E AndroidRuntime: java.lang.RuntimeException: Could not invoke ImageCropPicker.openPicker
08-02 00:35:27.406 12873 12975 E AndroidRuntime:  at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
08-02 00:35:27.406 12873 12975 E AndroidRuntime:  at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:166)
08-02 00:35:27.406 12873 12975 E AndroidRuntime:  at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
08-02 00:35:27.406 12873 12975 E AndroidRuntime:  at android.os.Handler.handleCallback(Handler.java:739)
08-02 00:35:27.406 12873 12975 E AndroidRuntime:  at android.os.Handler.dispatchMessage(Handler.java:95)
08-02 00:35:27.406 12873 12975 E AndroidRuntime:  at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
08-02 00:35:27.406 12873 12975 E AndroidRuntime:  at android.os.Looper.loop(Looper.java:135)
08-02 00:35:27.406 12873 12975 E AndroidRuntime:  at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
08-02 00:35:27.406 12873 12975 E AndroidRuntime:  at java.lang.Thread.run(Thread.java:818)
08-02 00:35:27.406 12873 12975 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
08-02 00:35:27.406 12873 12975 E AndroidRuntime:  at java.lang.reflect.Method.invoke(Native Method)
08-02 00:35:27.406 12873 12975 E AndroidRuntime:  at java.lang.reflect.Method.invoke(Method.java:372)
08-02 00:35:27.406 12873 12975 E AndroidRuntime:  at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:363)
08-02 00:35:27.406 12873 12975 E AndroidRuntime:  ... 8 more
08-02 00:35:27.406 12873 12975 E AndroidRuntime: Caused by: java.lang.NoSuchMethodError: No virtual method requestPermissions([Ljava/lang/String;I)V in class Lcom/reactnativenavigation/controllers/NavigationActivity; or its super classes (declaration of 'com.reactnativenavigation.controllers.NavigationActivity' appears in /data/app/com.helloworld-1/base.apk)
08-02 00:35:27.406 12873 12975 E AndroidRuntime:  at com.reactnativenavigation.controllers.NavigationActivity.requestPermissions(NavigationActivity.java:442)
08-02 00:35:27.406 12873 12975 E AndroidRuntime:  at com.reactnative.ivpusic.imagepicker.PickerModule.permissionsCheck(PickerModule.java:221)
08-02 00:35:27.406 12873 12975 E AndroidRuntime:  at com.reactnative.ivpusic.imagepicker.PickerModule.openPicker(PickerModule.java:349)
08-02 00:35:27.406 12873 12975 E AndroidRuntime:  ... 11 more
08-02 00:36:26.836  1445  1463 I am_crash: [13664,0,com.helloworld,8961604,java.lang.NoSuchMethodError,No virtual method requestPermissions([Ljava/lang/String;I)V in class Lcom/reactnativenavigation/controllers/NavigationActivity; or its super classes (declaration of 'com.reactnativenavigation.controllers.NavigationActivity' appears in /data/app/com.helloworld-1/base.apk),NavigationActivity.java,442]
08-02 00:36:26.836  1445  1463 I ActivityManager: handleApplicationCrash callvip.lifehome
08-02 00:36:26.836  1445  1463 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.startService:1738 com.android.server.am.ActivityManagerService.handleApplicationCrashInner:13916 com.android.server.am.ActivityManagerService.handleApplicationCrash:13786 android.app.ActivityManagerNative.onTransact:1412 com.android.server.am.ActivityManagerService.onTransact:2619 
08-02 00:36:26.846  1445  1463 W ActivityManager:   Force finishing activity 1 com.helloworld/com.reactnativenavigation.controllers.NavigationActivity
08-02 00:36:26.846  1445  1463 I am_finish_activity: [0,406147883,13312,com.helloworld/com.reactnativenavigation.controllers.NavigationActivity,crashed]
</pre>

**Comment by lipingruan** [comment]
@ivpusic @guyca

**Comment by ivpusic** [comment]
do you have some time to take a look into this?

**Comment by lipingruan** [comment]
```shell
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>

```

some permissions need write in Manifest.
