### ISSUE TITLE
How can I use a white background instead of a black one?

### ISSUE THREAD

**Issue by jamesone** [ivpusic/react-native-image-crop-picker#405]
### Version
Tell us which versions you are using: 

- "react-native-image-crop-picker": "^0.12.9"
- "react-native": "0.44.0"

### Platform
Tell us to which platform this issue is related

- iOS

### Expected behaviour

I'm wondering if we can change the background colour from BLACK to WHITE? At the moment when I crop an image, the resulting image will have BLACK surrounding it, can I make this white?

### Attachments

Here is an example of what the cropper does (note the black background): https://www.dropbox.com/s/c5c1rmiynploqmk/ScreenSnap%202017-08-03%20at%205.14.33%20pm.png?dl=0

**Comment by ivpusic** [comment]
currently this is not supported.

**Comment by bhrugu09** [comment]
is it now?
