### ISSUE TITLE
Issue about Multi-choice for Photos

### ISSUE THREAD

**Issue by wjw0520** [ivpusic/react-native-image-crop-picker#410]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.14.1
- react-native v0.40.0

### Platform
Tell us to which platform this issue is related

- Android

### Expected behaviour
Entering into the photo album, the user can click one photo to realize multi-choice.
 
### Actual behaviour
Entering into the photo album, the user has to press the photo for a while then can realize multi-choice through clicking one photo. How can I deal with it to achieve the expected behavior?

**Comment by ivpusic** [comment]
as we are not using custom gallery but system one, this depends on android version on the device. Currently we cannot fix this until there is custom gallery which supports all features we need. After that, we can switch and unify user experience.
