### ISSUE TITLE
Wrong language on picker

### ISSUE THREAD

**Issue by sofianegargouri** [ivpusic/react-native-image-crop-picker#411]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.13.1
- react-native v0.39

### Platform
Tell us to which platform this issue is related

- iOS

### Expected behaviour

Picker should be in device language

### Actual behaviour

Picker is in random language (italian on my simulator, german on my device)

### Steps to reproduce

No particular steps, just open the picker

**Comment by mag1492** [comment]
Same here both device and simulator.

**Comment by ivpusic** [comment]
yes. Currently, I have no plans of adding i18n by myself. If you have some time I would be happy to accept PR with this feature.

**Comment by Bodasia** [comment]
https://github.com/KBIM-dev/react-native-image-crop-picker
add possible to set custom text on picker
