### ISSUE TITLE
Set width and height dynamically based on selected image

### ISSUE THREAD

**Issue by WillyRamirez** [ivpusic/react-native-image-crop-picker#412]
Hi, I accept 3 ratios in my app. landscape, portrait and square. I would like to set the width and height of the cropper dynamically by detecting the size of the image that was chosen by the user. 
ie when the image width > height, i would like to set the width and height props to my respective ratio. 

Is there a hook for something like this?

**Comment by ivpusic** [comment]
currently not

**Comment by KamranKhankhail** [comment]
@ivpusic are you working on it?  is it possible now or in near future?

**Comment by KamranKhankhail** [comment]
@WillyRamirez you can try [this fork](https://github.com/mjaveed/react-native-image-crop-picker)
It will work your way. For android we've used another implementation than in original package, that provides more control on how to crop the image. Hope you'll enjoy.

**Comment by WillyRamirez** [comment]
@KamranKhankhail  thanks i will try it!

**Comment by WillyRamirez** [comment]
@KamranKhankhail Thanks again for sharing, quick question though. Are you sure this is what i need? Can i base the cropping size based on the orientation of the selected image? I don't see it in the documentation.

**Comment by WillyRamirez** [comment]
@ivpusic  would you accept a PR for this?

**Comment by ParhamZare** [comment]
remove 
![screenshot from 2018-05-28 09-35-49](https://user-images.githubusercontent.com/11447106/40598071-d40e8884-625a-11e8-936a-2de5ce78b7c3.jpg)
and uCrop detect automatic size image
