### ISSUE TITLE
Free Image Crop

### ISSUE THREAD

**Issue by SainiRohitSeasia** [ivpusic/react-native-image-crop-picker#416]
Can we do free image cropping. Means,Is cropping possible with any width or height like the latest cropping functionality.

**Comment by ivpusic** [comment]
currently not possible.

**Comment by mafiusu** [comment]
is this feature for that repo in the pipeline for iOS?

**Comment by ivpusic** [comment]
no

**Comment by Udbhav12** [comment]
@ivpusic Can we have free style cropping in iOS, like we have in Android? 

The default cropping behaviour of this library in  iOS is not very user friendly,The user should have an ability to apply custom rectangular area, just like that of Android
