### ISSUE TITLE
Android platform  cannot support multiple photos?

### ISSUE THREAD

**Issue by wenwen1995** [ivpusic/react-native-image-crop-picker#417]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.15.1
- react-native v0.44.2

### Platform
   Android (China HuaWei Honor 8)
- Android

### Expected behaviour and Actual behaviour
I want to go into the photos gallery to select multiple photos,and then to upload them ,but there are two problems occur.

(1) It goes into the phone root directory,not the gallery directory,like this...:
![qq 20170821163035](https://user-images.githubusercontent.com/12100065/29510363-1baa5df2-868e-11e7-9998-2201748af404.png)

So I don't how to solve this problem..

(2),when I want to select multiple photos,I write this code:
   `ImagePicker.openPicker({
          multiple: true
        }).then(images => {
          console.log(images);
        });`
but it can only select one photo,I searched it in website,someone say the croppicker plugin doesn't support it in android ??Is it true ? I hope to solve it.......

### Attachments

no debug info.

**Comment by ivpusic** [comment]
selecting multiple photos depends on device vendor. Try to long-press one photo...usually this will allow you to enter into "multi-selection" mode.

**Comment by Fox-3394** [comment]
@ivpusic Thank a lot, it worked for me.

**Comment by wenwen1995** [comment]
Oh，Thanks a lot @ivpusic ,but it cannot work well for me ...Even I tried to long-press one photo.It just likes in photo gallery title: already select xx(number), but I still cannot select multiple photos... Like this:

![img_20170821_165014](https://user-images.githubusercontent.com/12100065/29511203-0774ffba-8691-11e7-88b4-79bbe9514795.png)

My android app version is android 7.0.It's a high version. @Fox-3394 ,how can you solve the problem ?Can u tell me about your app some info?

**Comment by wenwen1995** [comment]
@ivpusic ,I'm so sorry to ask u the first problem again..Can you tell me some ways to solve the first problem or did u meet this situation when I want to choose photos,it goes into the root directory,the same question is in this link,[https://github.com/ivpusic/react-native-image-crop-picker/issues/357](url),
    A few days ago,I thought it might be a small bug,because in the code ,like this:
![2](https://user-images.githubusercontent.com/12100065/29511734-95074a76-8692-11e7-975c-bea562f1bbf8.png)
So when I set cropping false,and openPicker,it goes into the root directory...Is it right ?

**Comment by ivpusic** [comment]
actual behaviour depends on the phone manufacturer again, because built in gallery is used. From time to time I am looking for available custom galleries to unify user experience, but so far I didn't find any which meets all requirements.

**Comment by wenwen1995** [comment]
Okay, @ivpusic , thanks a lot !

**Comment by zhuxiaozhuworking** [comment]
@wenwen1995 您这个问题解决了吗 我也是在华为上遇到了同样的问题

**Comment by dekemega** [comment]
i tried other libraries like "react-native-file-picker" and it works just fine .. it is supported by the device but there is some problems in your implementation 
please give it another try
