### ISSUE TITLE
Cannot read property 'openPicker' of undefined

### ISSUE THREAD

**Issue by ottoborden** [ivpusic/react-native-image-crop-picker#42]
This project looks great and I'm really looking forward to using it. However I'm getting the error referenced in the title when trying to open the image picker in my app.

Here is the code:

```
import ImagePicker from 'react-native-image-crop-picker'

...

selectPhotoTapped() {
    console.log(ImagePicker)
    ImagePicker.openPicker({
      multiple: true
    }).then(images => {
      console.log(images);
    })
}

...

<TouchableOpacity onPress={this.selectPhotoTapped.bind(this)}>
  <View style={[styles.avatar, styles.avatarContainer, {marginBottom: 20}]}>
    { this.state.image === null ? <Text>Select a Photo</Text> :
      <Image style={styles.avatar} source={this.state.image} />
    }
  </View>
</TouchableOpacity>
```

And this is my Podfile:
```
# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'SclMktUi' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SclMktUi

  target 'SclMktUiTests' do
    inherit! :search_paths
    source 'https://github.com/CocoaPods/Specs.git'
    pod 'React', :path => '../node_modules/react-native'
    pod 'react-native-image-crop-picker', :path => '../node_modules/react-native-image-crop-picker/ios'
    # Pods for testing
  end

end
```

Per the iOS install instructions I added `$(inherited)` to the Other Linker Flags field:

![screen shot 2016-08-09 at 10 39 37 pm](https://cloud.githubusercontent.com/assets/3083164/17540179/32c3a6f4-5e82-11e6-9297-fce30b0483f5.png)

When I run the code and click my TouchableOpacity I get the RSOD and the console log of ImagePicker reports `undefined`. Not sure what I'm doing wrong here.

From checking out [https://github.com/ivpusic/react-native-image-crop-picker/issues/33] I found that I had to undo the `rnpm link` at which point the build succeeded but I'm stuck at this undefined error. Everything looks good to my ignorant eyes 😄 

Below is a screenshot of my Build Phases settings in Xcode. Any help would be greatly appreciated!

![screen shot 2016-08-09 at 10 25 53 pm](https://cloud.githubusercontent.com/assets/3083164/17539944/7b76f056-5e80-11e6-937a-575b4c914516.png)

**Comment by magrinj** [comment]
You do some mistakes in your Podfile, move your pod import from the target `SclMktUiTests` to `SclMktUi` and try to change your `platform :ios, '9.0'` to `platform :ios, '8.0'`. Note the version of the platform in the Podfile need to be the same, as the version in Xcode!

So wen you do this small change your Podfile gonna looks like:

```
# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'SclMktUi' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SclMktUi

  source 'https://github.com/CocoaPods/Specs.git'
  pod 'React', :path => '../node_modules/react-native'
  pod 'react-native-image-crop-picker', :path => '../node_modules/react-native-image-crop-picker/ios'

  target 'SclMktUiTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

After that do a `pod install` and try to rebuild your project :)

**Comment by ivpusic** [comment]
this means that installation is not completed. Scroll down to the bottom of readme, there is step by step installation tutorial

**Comment by ottoborden** [comment]
That got things working! Thanks a lot!

I am getting a new build error now but the app still actually runs in the simulator. I'm certain that ObjC and lc++ are in the Other Linker Flags setting. Not sure what's going on. FWIW I'm using RVM with Ruby 2.3 and I just installed it last night on OS X 10.11.3.

![screen shot 2016-08-10 at 6 23 10 am](https://cloud.githubusercontent.com/assets/3083164/17550439/03032250-5ec3-11e6-9b24-9a642a2b94f4.png)

**Comment by magrinj** [comment]
I'm not sure but the error is maybe because libReact.a is not linked to `SclMktUiTests` project in Xcode

**Comment by ottoborden** [comment]
Thanks for responding again. I looked into my settings and libReact.a is in fact linked to the SclMktUiTests Target. However I notice that even after `pod install` (as well as `rm -rf node_modules` and a clean build) that `libPods-SclMktUi.a` and `libPodsSclMktUiTests.a` are both red in Xcode.

![screen shot 2016-08-10 at 7 06 19 pm](https://cloud.githubusercontent.com/assets/3083164/17574288/e1691594-5f2d-11e6-9f7e-d08ff64bcc86.png)

Any one have any idea's? I'm brand new to CocoaPods and have no idea what I'm doing haha

**Comment by ivpusic** [comment]
any progress here?

**Comment by magrinj** [comment]
@ottoborden Your error is strange, try to remove the lines added in the pod file, then do a `pod install`, add again the lines in the pod fille, and redo a `pod install`

**Comment by tomazahlin** [comment]
I also got this error, but it was because I did not do the linking yet.

After I did the linking, I get this error:

RCTBridgeModule.h file not found

This comes from ImageCropPicker.h.

Any help?

**Comment by ottoborden** [comment]
So I finally did get it working. I ultimately had to put the `-lc++` flag in **Other linker flags** in both the Target AND Project for my Xcode settings.

@tomazahlin Have you tried `rnpm unlink react-native-image-crop-picker`? That is have you ensured you have not doubly linked the react-native-image-crop-picker project via both Xcode (manual install) as well a `rnpm link`?

**Comment by wootwoot1234** [comment]
I followed the instructions on the readme and still had errors.  I have to change the top of the podfile to:
```
platform :ios, '9.0'
```
for it to build.

**Comment by tomazahlin** [comment]
@ottoborden I did not link it twice, and I think I will use react-native-image-picker, it worked on previous project, but I might give this module a shot with the podfile later if needed.

**Comment by magrinj** [comment]
@wootwoot1234 Try to put this:

```
  platform :ios, '8.0'
```

@tomazahlin  You must use PodFile to link your project instead of `rnpm link`, because `rnpm` isn't support for the moment on this module, if someone know how to do it and want to make a PR :)

@ottoborden Strange for the flag, because normally it's added by Podfile, but it's good if that work for you! :)

**Comment by wootwoot1234** [comment]
@magrinj thanks but I was saying that changing it to ios 9.0 fixed my problem.  Does it have to do with what version of ios your testing on?

**Comment by magrinj** [comment]
@wootwoot1234 Oh ok! Yes, the version in the Podfile must be the same as the version in Xcode, and as I see this module work since the version 8

**Comment by wootwoot1234** [comment]
@ivpusic this problem isn't solved, why did you close this issue?  Don't you want your project to be more usable?  There are clearly a lot of people having issues with this.  At the very least, the docs need to be updated.  If possible I think this project needs to be converted to work with rnpm which is how all other modules are installed and much more user friendly.

This is a great project and you've done a great job but don't you want to see it grow/evolve?

I can understand you not having the time to fix these issues yourself but closing issues implies they have been solved.  Why don't you leave them open and categorize them as feature requests or bugs so that people who have the time are motivated to help you with the project.

**Comment by ivpusic** [comment]
@wootwoot1234 currently categorization of issues for me are real issues and "issues" with integrating the project with your setup. Most of the issues I received are from people which are not used to cocoa pods and are not used to native development. This module highly depends on native packages on both iOS and Android side, so I instruct people to check install instructions, and I close these "issues". If I don't do this, quickly I would have 50+ "issues" and these will hide real ones. 

Integration with RNPM is out of the box if you are not using external dependencies. In our case lib is using 2 on iOS side, so I already tried to quickly download them into the lib and link them. I run into issues when running on real device, and because of lack of my free time I stopped experimenting. If you have a time to play with this please do. I will be very happy to accept PR and stop receiving "issues" related to installing lib.

**Comment by wootwoot1234** [comment]
@ivpusic I don't understand your categorization of issues.  Are you saying this isn't a really issue?  I'm one of those people that have never used cocoa pods and even though I installed it in a new/empty project, the instructions didn't work for me (I'm clearly not the only one).  I had to make some 'guess and check' changes to get it to work (see my comments above).

This is your project so you do you but it seems to me that you wouldn't get 50+ issues if people saw threads like these open that they could comment on.  If someone opens a second thread about the same thing, point them to the original thread and close the duplicate issue.  This is just my opinion but as someone that contributes to a lot of projects closing issues makes me feel like you don't want/need a PR.

Look, I don't mean to start something.  You have an awesome project here and I'm just trying to help out.  I ended up going a different route and not using this module in my app but it's still one of the best image pickers out there and will keep it in mind for future projects.

I thought that might be a limitation of rnpm.  Why not just copy the code from the external libraries into a folder of this project?  It's not an ideal solution but wouldn't be difficult to maintain and would make the installation much much easier.

**Comment by wootwoot1234** [comment]
Looks like good minds think alike.  :)  https://github.com/ivpusic/react-native-image-crop-picker/issues/46#issuecomment-242430163

**Comment by ivpusic** [comment]
@wootwoot1234 I didn't want to be rude, just my point was that I don't have time to teach people how to use cocoa pods. I did the installation of this package already 100 times just to see if I can reproduce reported issues, but for me it always works. 

One thing is sure. We need RNPM support to avoid these issues and emotional discussions.

**Comment by ivpusic** [comment]
@wootwoot1234 @magrinj and all others, version 0.7.0 is bringing rnpm support and dropping cocoa pods support. Details here https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.7.0
