### ISSUE TITLE
[Android] On Release 0.16.0 App Crashes when Taking photo

### ISSUE THREAD

**Issue by ferminmoli** [ivpusic/react-native-image-crop-picker#425]
App closes when taking photos on Android.

This are my imageOptions:

this.imageOptions = {
            width: 300,
            height: 400,
            cropping: false,
            multiple: false,
            includeBase64: false,
            mediaType: 'photo', 
            compressImageQuality: 0.5
        };

**Comment by ivpusic** [comment]
can you provide some stacktrace or some other useful info?

**Comment by ferminmoli** [comment]
It's the same crash as in other issues that I uploaded.

**Comment by ivpusic** [comment]
then I will close this one in favor of https://github.com/ivpusic/react-native-image-crop-picker/issues/423.

**Comment by pbwei** [comment]
imageOptions={{
                  compressImageQuality: 0.85,
                  mediaType: 'photo',
                  cropping: true,
                  width:600,
                  height:600
                }}

this options is ok

**Comment by enso123456** [comment]
@pbwei  this is fixed the issue putting compressImageQuality.
