### ISSUE TITLE
ImagePicker.openCamera for video recording?

### ISSUE THREAD

**Issue by pongponglau** [ivpusic/react-native-image-crop-picker#426]
This is a very good library. Thank you very much.
I can run it on my Android device and can open the camera to take picture.

May i ask if i can open the camera to take video as well?

Thank you very much.

**Comment by ivpusic** [comment]
Currently not possible.

**Comment by quy1403** [comment]
hi @ivpusic,  now is It posssible ???
thanks u :D

**Comment by andrei0807** [comment]
Video Recording Now possible?
