### ISSUE TITLE
Support EXIF metadata? 

### ISSUE THREAD

**Issue by AlmogRnD** [ivpusic/react-native-image-crop-picker#427]
Are there any plans to support EXIF metadata, specific GPS and timestamp?

**Comment by ivpusic** [comment]
there are plans but currently no time. If you have a time to submit a PR would be awesome. The idea would be to return `exif: { ... }` in the response with all collected exif data from the image.

**Comment by AlmogRnD** [comment]
@ivpusic are you stripping away the meta data from the exif header, my backend just gets the data from the image but I'm not seeing it

**Comment by ivpusic** [comment]
I am creating temporary files for every file you select (on iOS), so exif could be lost in this step. https://github.com/ivpusic/react-native-image-crop-picker/blob/be03cead6b9edf9927595fd5f0f9707bbe8a7a81/ios/Compression.m#L77

**Comment by AlmogRnD** [comment]
Yeah, I believe that is what's happing, I also found another couple of bugs.
1. if I take a photo from the camera there source URL is empty but if I select images from the gallery it's not

As for exif data I have a workaround so no worries

**Comment by MobileAppVault** [comment]
@AlmogRnD what was your workaround to get the exif data?

**Comment by AlmogRnD** [comment]
@MobileAppVault I just the GPS and capture that info and send it as an object with the image

**Comment by jennyh-jy** [comment]
Hey @AlmogRnD, 

Are you able to elaborate? I'm trying to capture GPS data as well but unsure how to

**Comment by MobileAppVault** [comment]
thanks @AlmogRnD

**Comment by AlmogRnD** [comment]
@jennyh-jy I have the following function that gets the location and stores in the redux store which I than use when uploading - https://gist.github.com/AlmogRnD/ade9b80a128a3a2118148be421485905

**Comment by AlmogRnD** [comment]
@ivpusic Hi, my company would like to support this package, we really need the EXIF data for our mobile app. We wanted to offer some funding/donation to add this feature are you interested? If so when can you have it done? and how much feel free to send me an email at almog@constructioncloud.com.au
