### ISSUE TITLE
iphone debug error

### ISSUE THREAD

**Issue by banli17** [ivpusic/react-native-image-crop-picker#429]
### Version

- react-native-image-crop-picker v0.16
- react-native v0.44

### Platform

- iOS

### issue
```
dyld: Library not loaded: @rpath/RSKImageCropper.framework/RSKImageCropper
  Referenced from: /var/containers/Bundle/Application/67DAF0AE-BF88-4081-94A3-1BAB071F6523/创酷.app/创酷
  Reason: image not found
(lldb) 
```

i use xcode simulator can run , but i use my iphone can't。

![qq20170829-094443](https://user-images.githubusercontent.com/12556069/29800826-bb592e30-8c9e-11e7-84a5-f5a95af5e061.png)

and if i use pod，it has other error:
```

ld: warning: directory not found for option '-L/Users/banli/Library/Developer/Xcode/DerivedData/sucaiapp-fuirohhdudimnddmehtevfaqebxz/Build/Products/Debug-iphoneos/QBImagePickerController'

ld: warning: directory not found for option '-L/Users/banli/Library/Developer/Xcode/DerivedData/sucaiapp-fuirohhdudimnddmehtevfaqebxz/Build/Products/Debug-iphoneos/RSKImageCropper'

ld: library not found for -lQBImagePickerController
```

please help me ,thank you

**Comment by xzf158** [comment]
+1

**Comment by BraunreutherA** [comment]
Hi, I had the same problem - did you switch in xcode from <your_app>.xcodeproj to <your_app>.xcworkspace? You simply have to close xcode and open the workspace, then the pods should be included an the compiler should find them.

Hope this helps!

**Comment by JonsonHI** [comment]
+1  我也出现了这个问题不知道该怎么解决 前几天还好好的

**Comment by chen-wen** [comment]
I am sure it works well run in command line, but I have the same issue in Xcode

**Comment by wfly-git** [comment]
加入报错的framework并把报错的框架设置为可选择（optional）的？至少暂时没奔溃，能不能用还得试试

**Comment by jakewtaylor** [comment]
+1. Any solutions?

I'm using .xcworkspace not .xcodeproj, error still happens.

It could be because I've had to manually link the library and there's no instructions for how to do that, so if anyone has those, that would be helpful, too.

**Comment by banli17** [comment]
@jakewtaylor   update to 2.0 and restart，i'm ok

**Comment by soroushchehresa** [comment]
this issue is happening when don't take completely step 2 of Post-install steps.
manual install not working and you can only use Cocoapods.
after install pod and take steps for resolve this error **open your-project.xcworkspace file with xcode and run project from here**.

NOTE:
your-project.xcworkspace file created after take step 2 of Post-install steps completely in ios folder of your project.

**Comment by stlemon** [comment]
+1

**Comment by ivpusic** [comment]
RSKImageCropper is not used anymore. please try latest version with TOCropViewController
