### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by leoabacade** [ivpusic/react-native-image-crop-picker#43]
hi there, I just install the module on:

"react-native": "^0.28.0",
Nexus 6  5.1.1

below is what I am facing:

/node_modules/react-native-image-crop-picker/android/build/intermediates/exploded-aar/com.yalantis/ucrop/1.5.0/res/drawable/ucrop_vector_loader.xml: Error: Width (0) and height (0) cannot be <= 0
:react-native-image-crop-picker:mergeReleaseResources FAILED

* What went wrong:
Execution failed for task ':react-native-image-crop-picker:mergeReleaseResources'.

here is ucrop_vector_loader.xml

`<?xml version="1.0" encoding="utf-8" ?>
<vector xmlns:android="http://schemas.android.com/apk/res/android"
        android:width="@dimen/ucrop_progress_size"
        android:height="@dimen/ucrop_progress_size"
        android:viewportHeight="192"
        android:viewportWidth="192">

    <group
        android:name="circleGroup"
        android:pivotX="96.0"
        android:pivotY="96.0"
        android:rotation="0">

        <path
            android:name="circlePath"
            android:pathData="M96,5.56405C145.946,5.56405 186.436,46.0536 186.436,96C186.436,145.946 145.946,186.436 96,186.436C46.0536,186.436 5.56405,145.946 5.56405,96C5.56405,46.0536 46.0536,5.56405 96,5.56405Z"
            android:strokeAlpha="1"
            android:strokeColor="@color/ucrop_color_toolbar_widget"
            android:strokeWidth="13"
            android:trimPathEnd="0.7"/>

    </group>

</vector>`

any ideas to fix it?

**Comment by ivpusic** [comment]
did you follow all steps from here? https://github.com/ivpusic/react-native-image-crop-picker#android-1

You can try with `gradlew clean` but if you follow all steps you should be fine. I cannot reproduce this issue.

**Comment by leoabacade** [comment]
yes, I did follow the steps, excepts I

import com.reactnative.picker.PickerPackage;
and
return Arrays.<ReactPackage>asList(
            new PickerPackage() 
@ MainActivity.java
not @ MainApplication.java

(react-native": "^0.28.0)

**Comment by ivpusic** [comment]
for latest version RN0.30+ is required

**Comment by leoabacade** [comment]
ok, thanks. I will try it again later after my project is ready to use RN0.30+
