### ISSUE TITLE
undefined is not an objdect (evaluating 'c.default.openPicker') 

### ISSUE THREAD

**Issue by congdufs** [ivpusic/react-native-image-crop-picker#431]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.?.?
- react-native v0.?.?

### Platform
Tell us to which platform this issue is related

- iOS
- Android

### Steps to reproduce

1.

2.

3.

### Attachments

// stacktrace or any other useful debug info

**Comment by dgurns** [comment]
Getting same thing here on iOS (working fine on Android)

RN 0.44
react-native-image-crop-picker 0.16.0

![simulator screen shot sep 1 2017 1 12 07 pm](https://user-images.githubusercontent.com/1173791/29980292-33609f9c-8f17-11e7-99bd-d1b7c8b4b80a.png)

**Comment by ivpusic** [comment]
installation of library failed. Please read installation instructions again, follow each step and make sure each step succeeds.

**Comment by dgurns** [comment]
I did follow the steps exactly and used CocoaPods. It worked fine while running on my iPhone 6 via Xcode. However, on the Simulator it did not work. It failed right before the permissions step.. maybe it's something to do with that?

**Comment by anjalsaneen123** [comment]
@dgurns did you got what is the solution, i'm facing same error?

**Comment by Mandeep03** [comment]
Add this in you MainApplication.java, sometimes react-native link does not work perfectly.
<img width="532" alt="screen shot 2017-09-07 at 7 16 56 pm" src="https://user-images.githubusercontent.com/7822632/30166555-4cc19d8a-9401-11e7-98e9-8000f76b87cd.png">

**Comment by ropc** [comment]
I was having a similar issue on iOS. I also use other cocoapods dependencies so I made a podspec that works for me. Made a PR for it here: #454

**Comment by ivpusic** [comment]
@congdufs please try suggestion from @Mandeep03
