### ISSUE TITLE
Custom Loading Style

### ISSUE THREAD

**Issue by as123456py** [ivpusic/react-native-image-crop-picker#434]
### Version

- react-native-image-crop-picker v0.16.0
- react-native v0.44.3

### Platform
IOS&Android

hello,
I am using this package,thank you for your package. it is very cool
now ,there is one question.When I select one picture and upload ,I want to use my custom loading style ,but i can't hide default loading style.can you provide one prop to controll hide default loading style.

thank you.

**Comment by ivpusic** [comment]
currently this is not supported. feel free to submit a PR.
