### ISSUE TITLE
compile error, react-native 0.48.1

### ISSUE THREAD

**Issue by cbjs** [ivpusic/react-native-image-crop-picker#439]
<img width="736" alt="screen shot 2017-09-07 at 8 30 10 pm" src="https://user-images.githubusercontent.com/1215843/30163405-6f00cd9e-940b-11e7-95a1-c9b38e563720.png">

**Comment by aforty** [comment]
Temporary work-around is to change `imageCropPicker.h`

```
#if __has_include("RCTBridgeModule.h")
#import "RCTBridgeModule.h"
#import "RCTImageLoader.h"
#else
#import <React/RCTBridgeModule.h>
#import <React/RCTImageLoader.h>
#endif
```

to

```
#import <React/RCTBridgeModule.h>
#import <React/RCTImageLoader.h>
```

**Comment by mmerickel** [comment]
This was fixed in https://github.com/ivpusic/react-native-image-crop-picker/issues/436

**Comment by cbjs** [comment]
thanks~

**Comment by wayne1203** [comment]
Hi, How can I download the fixed version?

**Comment by ivpusic** [comment]
try https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.16.1
