### ISSUE TITLE
A Feature that does not do anything?

### ISSUE THREAD

**Issue by sandropoluan** [ivpusic/react-native-image-crop-picker#443]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.15.1
- react-native v0.44

### Platform
Tell us to which platform this issue is related

- Android

![img_20170912_110038](https://user-images.githubusercontent.com/11922251/30306382-67f275fa-97aa-11e7-8ea3-2d52cef800bb.jpg)
What is that for? that is not do anything.

**Comment by ivpusic** [comment]
under the hood library uses ucrop. You can refer to their docs for more details about features https://github.com/Yalantis/uCrop.
