### ISSUE TITLE
How do I set it up in Android Studio?

### ISSUE THREAD

**Issue by guilhermerech88** [ivpusic/react-native-image-crop-picker#444]
I'm developing a project with Android Studio, and excuse me if that's a dumb question... but how the heck do I include this package in my project?

"npm i react-native-image-crop-picker --save" What do you mean with that? 

All the other projects I've seen around here have something like "compile 'com."...

I'm kind of lost here.

**Comment by ivpusic** [comment]
react-native install react-native-image-crop-picker will install it and add "compile ..." things to build.gradle
