### ISSUE TITLE
android平台不支持图片多选?

### ISSUE THREAD

**Issue by super-ax** [ivpusic/react-native-image-crop-picker#446]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.?.?
- react-native v0.?.?

### Platform
Tell us to which platform this issue is related

- iOS
- Android

### Steps to reproduce

1.

2.

3.

### Attachments

// stacktrace or any other useful debug info

**Comment by mySteamIDisLiKang** [comment]
Version
react-native v0.49.1
react-native-image-crop-picker v0.17.2

Platform
Android

Issue
multiple property does not work

**Comment by ivpusic** [comment]
multiple selections depend on phone manufacturer. Some manufacturers do not support it. It also depends on OS version. Try to long press on the image and you should enter multi-selection mode if it is available on your phone.

**Comment by super-ax** [comment]
Ok, thanks, I'm trying




------------------ 原始邮件 ------------------
发件人: "Ivan Pusic";<notifications@github.com>;
发送时间: 2017年10月9日(星期一) 下午3:54
收件人: "ivpusic/react-native-image-crop-picker"<react-native-image-crop-picker@noreply.github.com>;
抄送: "傲宇凌风"<1020786594@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [ivpusic/react-native-image-crop-picker] android平台不支持图片多选? (#446)




multiple selections depend on phone manufacturer. Some manufacturers do not support it. It also depends on OS version. Try to long press on the image and you should enter multi-selection mode if it is available on your phone.
