### ISSUE TITLE
when compressImageQuality = 1, image size is bigger than original size

### ISSUE THREAD

**Issue by yiky84119** [ivpusic/react-native-image-crop-picker#449]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.16.1
- react-native v0.47.1

### Platform
Tell us to which platform this issue is related

- iOS

### Expected behaviour

default width and height, set compressImageQuality to 1, get compressed image's size is bigger than original size. should return default NSData when set the default option.

### Actual behaviour

default width and height, set compressImageQuality to 1, get compressed image's size is bigger than original size. Almost increased by 300%.

### Steps to reproduce

1.

2.

3.

### Attachments

// stacktrace or any other useful debug info

**Comment by ivpusic** [comment]
do you have some time to try to fix this and submit a PR?

**Comment by fubar** [comment]
A change to skip compression in this scenario (#554) will go out with the next release. If you want to retrieve the original image without modification I'd suggest omitting all compressImage* parameters.

**Comment by ivpusic** [comment]
fixed by https://github.com/ivpusic/react-native-image-crop-picker/pull/736
