### ISSUE TITLE
"RCTBridgeModule.h" not found

### ISSUE THREAD

**Issue by VctrySam** [ivpusic/react-native-image-crop-picker#45]
Does this work with the latest version of RN?
I've uninstalled and reinstalled this module and it's pods like 10 times.

**Comment by ivpusic** [comment]
yes, it should work. This is common issue people run into. You can read answers on other closed issues of this type, or you can scroll down to the end of readme file to see step by step instructions

**Comment by alexmngn** [comment]
I keep having the same issue on my project.
I've tried to install, uninstall, I've followed exactly the instruction at the bottom of the readme file, nothing works.
@VctrySam did you find a solution?

**Comment by juanluisgv1** [comment]
Hi! I have been the whole day with this issue.. which actually come from nowhere because I never had this problem before. Anyone found a solution?
