### ISSUE TITLE
Customize ImagePreview Buttons

### ISSUE THREAD

**Issue by AunMSheikh** [ivpusic/react-native-image-crop-picker#450]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.14.2
- react-native v0.45.1

### Platform
- Android

### Expected behaviour
Consistent values across the OS for the buttons

### Actual behaviour
Values vary from different devices and versions of OS, i.e S7 edge pair is {Retry, Ok}, and on Pixel running android 6.0 its a cross and a check mark
![screenshot_1505758423](https://user-images.githubusercontent.com/15763563/30557302-d9dd144c-9c7b-11e7-920a-400a9cbdc5c3.png)

### Attachments

// stacktrace or any other useful debug info

**Comment by ivpusic** [comment]
currently, this is out of scope. If you have some time to improve this, PR will be welcome
