### ISSUE TITLE
Manual installation?

### ISSUE THREAD

**Issue by elkinjosetm** [ivpusic/react-native-image-crop-picker#451]
react-native link doesn't work, how can I do manual installation for both Android and iOS?

**Comment by ivpusic** [comment]
unfortunately there are no docs for this. However process should be very similar how other libraries do it. You can find example for ios in react-native docs https://facebook.github.io/react-native/docs/linking-libraries-ios.html.

**Comment by SourceCipher** [comment]
Its been 2 years, where on earth is a full manual instantiation when linking fails which is always the case?? Which package do I import into the MainApplication??
