### ISSUE TITLE
Error to get images from 'http://'

### ISSUE THREAD

**Issue by niros001** [ivpusic/react-native-image-crop-picker#452]
I have images files at url start with 'http://' and 'https://'. while i try to get from 'https://' everything works good but when i try to get image from 'http://' i get that error: 'Error: Can't find the image at the specified path'
* The image exist if i put the path on the browser

**Comment by eduardojunio** [comment]
@niros001 iOS doesn't allow HTTP requests by default. You should disable ATS in your Info.plist

**Comment by ivpusic** [comment]
thanks @eduardojunio for support. @niros001 can you please try that.
