### ISSUE TITLE
cannot read property openPicker of undefined for android 

### ISSUE THREAD

**Issue by devanshsadhotra** [ivpusic/react-native-image-crop-picker#459]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.16.1
- react-native v0.46

### Platform
Tell us to which platform this issue is related
- Android

### Expected behaviour
Gallery would have got opened so that i could select multiple images

### Actual behaviour
cannot read property openPicker of undefined

### Steps to reproduce

1. install the plugin

2. follow the steps for setting up for android

3. press on the button u called this function

### Attachments
![screenshot_1506097781](https://user-images.githubusercontent.com/15092405/30754708-6bbf650a-9fe1-11e7-8cba-7d7b000fe8c2.png)

// stacktrace or any other useful debug info

**Comment by ivpusic** [comment]
this usually means that installation somewhere failed. Can you open your MainActivity.java class and check if image picker module is imported correctly? If not, that means `react-native link` step failed.

**Comment by pulkitkkr** [comment]
I'mFacing the same issue, though react-native link says already linked

**Comment by devanshsadhotra** [comment]
@pulkitkkr i resolved this issue , by following the code as done in https://github.com/ivpusic/react-native-image-crop-picker/tree/master/example/android . Please go through , build.gradle, settings.gradle , mainApplication.java and all other files , to make this plugin work as desired . 
hence i am closing this  issue

**Comment by ruk91** [comment]
After linking It worked perfectly. Thanks
