### ISSUE TITLE
why not support rnpm?

### ISSUE THREAD

**Issue by charlesluo2014** [ivpusic/react-native-image-crop-picker#46]
hi,this component,why not support rnpm?

**Comment by ivpusic** [comment]
feel free to submit PR.

**Comment by wootwoot1234** [comment]
That would be great but this uses pod to download a few libraries:

```
    pod 'QBImagePickerController', '3.4.0'
    pod 'RSKImageCropper', '1.5.1'
    pod 'UIImage-Resize', '~> 1.0'
```

is it possible to do that with npm/rnpm?

**Comment by ivpusic** [comment]
way to go would be to download these libraries, put them into this lib, and link them with it.

**Comment by ivpusic** [comment]
supported https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.7.0
