### ISSUE TITLE
Quick question on Android are you able to tell which gallery to open 

### ISSUE THREAD

**Issue by AlmogRnD** [ivpusic/react-native-image-crop-picker#463]
On Andriod is there a way to set the gallery that is open for example device?

**Comment by ivpusic** [comment]
Currently, this is not supported. As you can see here https://github.com/ivpusic/react-native-image-crop-picker/blob/master/android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java#L316, we will run intent, and anything which can respond to that intent will be offered to the user.
