### ISSUE TITLE
￼ macOS High Sierra is the last version of macOS that will run 32-bit apps without compromise. The Mac App Store will require all apps (including updates) to be exclusively 64-bit by June 2018.

### ISSUE THREAD

**Issue by 7caishi** [ivpusic/react-native-image-crop-picker#464]
What if you solve it?
Help Me !!!!

**Comment by vanyaland** [comment]
Hey @7caishi!
According to the Apple's [Converting Your App to a 64-Bit Binary](https://developer.apple.com/library/content/documentation/General/Conceptual/CocoaTouch64BitGuide/ConvertingYourAppto64-Bit/ConvertingYourAppto64-Bit.html) guide  I see that `imageCropPicker` is successfully supports both architectures.

#### Build Settings:
![screen shot 2017-09-30 at 10 22 14](https://user-images.githubusercontent.com/8586063/31043703-46b3f260-a5c9-11e7-9a42-e1126cd9b1da.png)

***Architectures***: Standard architectures (Apple recommended). Which means build both 32 and 64 Bit architectures.

***Valid Architectures*** : Specify the architectures you want to build:
armv7 and armv7s are for 32 bit devices.
arm64 is for 64 bit devices

***Build Active Architecture Only*** : This is specifies, whether, build all the valid architectures or build only for the target specified.

***Note***:
I'm successfully developing for iOS 8-11, which mean that support of the 64-Bit architecture is included.

So, all looks fine and there is no problem with the framework. I recommend you to take a look at your own project and follow this [steps](https://developer.apple.com/library/content/documentation/General/Conceptual/CocoaTouch64BitGuide/ConvertingYourAppto64-Bit/ConvertingYourAppto64-Bit.html).

**Comment by 7caishi** [comment]
@vanyaland Thank you for!!!
