### ISSUE TITLE
Quality is so bad

### ISSUE THREAD

**Issue by brkrtp** [ivpusic/react-native-image-crop-picker#465]
"react-native-image-crop-picker": "^0.16.1",
"react-native": "0.46.4",
- iOS
- Android
Cropped image quality is so bad. I try compressImageQuality:1 same result. On IOS simulator.
![simulator screen shot - iphone 6 - 2017-10-01 at 12 03 35](https://user-images.githubusercontent.com/18514716/31053203-ecd6f99e-a6a0-11e7-90a6-dd8ec1a61fbf.png)

**Comment by KamranKhankhail** [comment]
@brkrtp, @thebergamo you can try  [this fork](https://github.com/mjaveed/react-native-image-crop-picker)
here we have solved the issue of image quality. For android we've used another 'com.theartofdev.edmodo:android-image-cropper', that provides more control on how to crop the image. Hope you'll enjoy.

**Comment by thebergamo** [comment]
@KamranKhankhail will try it :D thanks

**Comment by jigaryadav** [comment]
i have modified the original package to upgrade the internal crop library so try [this fork](https://github.com/jigaryadav/react-native-image-crop-picker) 
i have an issue with cropping the image so I take a fork from @KamranKhankhail but there is no option to select cropped image so just resolved this issue

**Comment by ivpusic** [comment]
fixed here https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.21.2

**Comment by hermance** [comment]
I have the same problem of quality (with cropping, only Android) with your latest release @ivpusic

**Comment by saiprathapcse** [comment]
compressImageQuality:1,
        outMimeType:"image/png"

set above 2 properties to improve the quality.
