### ISSUE TITLE
iPhone X

### ISSUE THREAD

**Issue by florianeckerstorfer** [ivpusic/react-native-image-crop-picker#466]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.17.2
- react-native v0.48.1

### Platform
Tell us to which platform this issue is related

- iOS (only iPhone X)

### Expected behaviour

There is a spacing on top for the "notch" or an option to customise the padding on the sides.

### Actual behaviour

There is no spacing for the "notch" and the header is hidden behind it.

### Steps to reproduce

1. Open Image Picker on iPhone X

### Attachments

![iPhone X Notch](https://files.florian.ec/react-native-image-crop-picker-iphone-x-notch.png)

**Comment by ivpusic** [comment]
I have open issue in the library on which react-native-image-crop-picker depends on https://github.com/questbeat/QBImagePicker/issues/200

**Comment by superandrew213** [comment]
That's weird. I don't get this issue. @ivpusic are you getting this issue too?

<img width="373" alt="screen shot 2017-10-24 at 10 20 22 pm" src="https://user-images.githubusercontent.com/13059204/31942709-952770f4-b909-11e7-842d-cdc12915a526.png">

**Comment by ivpusic** [comment]
@superandrew213 I still didn't try it on iphone X
