### ISSUE TITLE
changing cropper text

### ISSUE THREAD

**Issue by erfanyousefifar** [ivpusic/react-native-image-crop-picker#468]
### Version
- react-native-image-crop-picker v0.17.2?.?
- react-native v0.48.4?.?

### Platform
- Android

Hello, I want to change the label in cropper ( Edit Photo ) to another string, how can I do that, thanks

**Comment by ivpusic** [comment]
currently not possible, but feel free to send a pull request

**Comment by khrizt** [comment]
If you define a string resource value in your android project with the name "ucrop_label_edit_photo" that's the text it will appear. I don't know how to do it in iOs, but I hope it works for you.
