### ISSUE TITLE
Android Kitkat or lower than v.5 will crash on v.0.14.0 or above

### ISSUE THREAD

**Issue by teyou** [ivpusic/react-native-image-crop-picker#469]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.14.0
- react-native v0.45.1

### Platform
Tell us to which platform this issue is related
- Android : 4.4 (Kitkat)

### Expected behaviour
app will run

### Actual behaviour

app crash immediately once started

### Steps to reproduce

1. upgrade from v.0.13.1 to v.0.14.0 or above

2. app will immediately crash on Android Kitkat version

### Attachments

// stacktrace or any other useful debug info
```
Fatal Exception: java.lang.NoClassDefFoundError: com.facebook.react.CoreModulesPackage$1
       at com.facebook.react.CoreModulesPackage.getNativeModules(CoreModulesPackage.java:98)
       at com.facebook.react.LazyReactPackage.createNativeModules(LazyReactPackage.java:73)
       at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106)
       at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1009)
       at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:933)
       at com.facebook.react.ReactInstanceManager.access$600(ReactInstanceManager.java:109)
       at com.facebook.react.ReactInstanceManager$4.run(ReactInstanceManager.java:746)
       at java.lang.Thread.run(Thread.java:841)
```

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by ivpusic** [comment]
I tried it to kitkat on samsung galaxy s3 and it works without problems. Do you have some time to debug it and try to send a pull request?

**Comment by jonathanmauer** [comment]
I have the same issue here, can you resolve this @teyou ?

**Comment by teyou** [comment]
@jonathanmauer currently i'm reverting to v0.13.1 as i don't have time yet to figure out the fix. 

@ivpusic I'm running on simulator (using Genymotion android emulator) and it's also crash

**Comment by jonathanmauer** [comment]
Ok, thank you! i will try on v0.13.1

**Comment by ivpusic** [comment]
hm, @teyou could you try it on example project provided by this repo? just to be sure that it is not about some misconfiguration in your project

**Comment by teyou** [comment]
tried the example from master branch. it was working 👍

**Comment by ivpusic** [comment]
great! could you compare your build.gradle to https://github.com/ivpusic/react-native-image-crop-picker/blob/master/example/android/build.gradle?

**Comment by jonathanmauer** [comment]
Hi @ivpusic i have the same problem and i compare this gradles files to my projects and they are pratically the same

\app\build.gradle
`def enableSeparateBuildPerCPUArchitecture = false

def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion 25
    buildToolsVersion '25.0.0'

    defaultConfig {
        applicationId "com.gonices"
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    compile project(':react-native-linear-gradient')
    compile project(':react-native-vector-icons')
    compile project(':react-native-maps')
    compile project(':react-native-fbsdk')
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:23.0.1'
    compile 'com.facebook.react:react-native:+'
    // From node_modules
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}`

\build.gradle
`buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}
`

**Comment by jonathanmauer** [comment]
i made the changes in my gradle(s) files to match exactly with this, and still crashes in android <= 5

**Comment by teyou** [comment]
turns out it was multidex issue.
solution: https://stackoverflow.com/a/36263927
