### ISSUE TITLE
Fit image picker to <View />?

### ISSUE THREAD

**Issue by wootwoot1234** [ivpusic/react-native-image-crop-picker#47]
Is it possible to have the image picker not be fullscreen?  For example, I have a modal in my app that I would like to have the picker inside of instead of taking over the whole screen.  It would give it more of an integrated feel.

**Comment by ivpusic** [comment]
Currently not.

**Comment by wootwoot1234** [comment]
Wouldn't this be a nice feature?  Would you be open to a PR?

**Comment by ivpusic** [comment]
if you can make it to support both iOS and Android, and without breaking existing API, then sure
