### ISSUE TITLE
Can't enter multi-selection mode in my Android device

### ISSUE THREAD

**Issue by mySteamIDisLiKang** [ivpusic/react-native-image-crop-picker#470]
### Version

-react-native v0.49.1
-react-native-image-crop-picker v0.17.2

### Platform

- Android7.0
-FRD-AL10 Honor8 (some other Chinese Phone also encounter this problem)

### Expected behaviour

Use long press on the image to enter multi-selection mode.

### Actual behaviour

I can pick single picture in both mode. 
And I can use long press  to enter multi-selection mode in file manager,  
but I can't use long press  to enter multi-selection mode in my app.

### Steps to reproduce

1.trigger the picker 

2. I can't  enter multi-selection mode when I long press a image , and I can pick a image using short press.

**Comment by superandrew213** [comment]
See https://github.com/ivpusic/react-native-image-crop-picker/issues/417
