### ISSUE TITLE
no value return

### ISSUE THREAD

**Issue by renso3x** [ivpusic/react-native-image-crop-picker#471]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.17.2
- react-native v"0.45.0",

### Platform
The issue is that it does not return a value when selecting photos. It doesn't prompt any permissions.

- iOS
- Android

### Expected behaviour
It should return the photos

### Actual behaviour
No return value when selecting photos.

### Steps to reproduce
Here is my code.

https://gist.github.com/renso3x/0e49eb0c933a8c0b887b5c33fd78afdf

**Comment by ivpusic** [comment]
you can check example project for additional information how to use it https://github.com/ivpusic/react-native-image-crop-picker/blob/master/example/app.js.

**Comment by renso3x** [comment]
Yes I have followed the example app. But it seems it's not returning the image itself. In a fresh install react-native it is working but in the existing app is not working. 
RN v0.45.0. Does it have a conflict with other module like sms, firestack, linear-gradient?

**Comment by ivpusic** [comment]
Probably not, but I cannot tell you that for sure. To me, this looks like this is your app specific issue, and therefore I cannot help you with that.

**Comment by jonathanmauer** [comment]
is it in conflict with linear-gradient?
