### ISSUE TITLE
remove particular image

### ISSUE THREAD

**Issue by ankitbisht143** [ivpusic/react-native-image-crop-picker#472]
After rendering images in UI, if user  wants to remove a particular image then how to achieve this.

**Comment by ivpusic** [comment]
just hide image component? if you want to remove temporary image file, then you can use .clean method which you can find in readme file

**Comment by ankitbisht143** [comment]
On hiding image component all images getting hidden.. I want to hide particular one

**Comment by ivpusic** [comment]
sorry but this sounds like an issue in your code

**Comment by ankitbisht143** [comment]
Can you please show me the cide for hiding one image

**Comment by ankitbisht143** [comment]
*code

**Comment by ankitbisht143** [comment]
I did not get my answer..

**Comment by Nagasai97** [comment]
deleteImage(uri) {
    const images = this.state.imageList;
    images.splice(
      images.findIndex((index) => index.filePath === uri),
      1,
    );
    this.setState({ newImages: images });
    log.info('deleted one image', this.state.imageList);
  }
