### ISSUE TITLE
image component not hiding!

### ISSUE THREAD

**Issue by ankitbisht143** [ivpusic/react-native-image-crop-picker#473]
renderAsset(image) {
    if (image.mime && image.mime.toLowerCase().indexOf('video/') !== -1) {
      return this.renderVideo(image);
    }
    return this.renderImage(image);
  }

  renderImage(image) {
    return(
      <View>
      <Image style={{width: 300, height: 300, resizeMode: 'contain'}} source={image} />
      <TouchableOpacity activeOpacity={1} onPress={() => ..... }>
        <Text> Cancel </Text>
      </TouchableOpacity>
      </View>
    );
  }

Can you please tell me how to hide a particular image from onPress action?

**Comment by ivpusic** [comment]
sorry, but this is question for stackoverflow.

**Comment by ankitbisht143** [comment]
i am using react native image crop picker
