### ISSUE TITLE
Cannot read property 'openPicker' of undefined ( if eject into 'ExpoKit' )

### ISSUE THREAD

**Issue by anyexinglu** [ivpusic/react-native-image-crop-picker#474]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.17.3
- react-native v0.48.4
- react v16.0.0-alpha.12
- expo v21.0.0

### Platform

- iOS

### Expected behaviour

Gallery would have got opened so that i could select multiple images

### Actual behaviour

cannot read property openPicker of undefined

### Steps to reproduce

1. `create-react-native-app myProject`

2. `cd myProject & npm run eject` and choose "ExpoKit"

3. Install & configure react-native-image-crop-picker following README

When executing step 2 `pod install`(https://github.com/ivpusic/react-native-image-crop-picker#step-2), have a problem: 

> [!] Unable to satisfy the following requirements: `ExpoKit/Core (from `http://github.com/expo/expo.git`, tag `ios/1.20.5`)` required by `Podfile`
Specs satisfying the `ExpoKit/Core (from `http://github.com/expo/expo.git`, tag `ios/1.20.5`)` dependency were found, but they required a higher minimum deployment target.

So I change the `platform :ios, '8.0'` into `platform :ios, '9.0'` in ios/Podfile and `pod install` in this step.

4. Then I encountered with the error: Cannot read property 'openPicker' of undefined

### Supplementary explanation
Since Expo requires iOS9.0+  (https://docs.expo.io/versions/latest/introduction/installation.html)

> Required Android and iOS versions: The minimum Android version Expo supports is Android 4.4 and _the minimum iOS version is iOS 9.0_.

![image](https://user-images.githubusercontent.com/8243326/31584918-85c235a6-b17d-11e7-8ac2-ae962102686d.png)

### My solution

Choosing "Regular React Native" when runing `npm run eject`, then following the README, everything works will.

So we can't use Expo with this react-native-image-crop-picker?

**Comment by ivpusic** [comment]
Yes, if expo requires ios 9.0 minimum, then, for now, it won't be able to work with this module. What I suggest to you is to fork this library and make a change on your branch.

**Comment by sotocodes** [comment]
I am having the same problem using android. What kind of change do I need to make @ivpusic ?
