### ISSUE TITLE
[Android] Control number of image multi-picker.

### ISSUE THREAD

**Issue by ducpt2** [ivpusic/react-native-image-crop-picker#476]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.17.3
- react-native v0.48.3

### Platform
Tell us to which platform this issue is related
- Android

### Expected behaviour
- Can control number of images picker (multi-image picker). Example: We can set number of image can pick is 5 like iOS.

### Actual behaviour
- No limit.

### Steps to reproduce

1. User multi-Image pick function.

2.

3.

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by ivpusic** [comment]
currently not possible

**Comment by aghamarshana-svmx** [comment]
Is this issue fixed ?

**Comment by christopher-18** [comment]
@ivpusic  @aghamarshana-svmx  Can we use this in android?
