### ISSUE TITLE
Use smartAlbums props for Android.

### ISSUE THREAD

**Issue by ducpt2** [ivpusic/react-native-image-crop-picker#477]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.17.3
- react-native v0.48.3

### Platform
Tell us to which platform this issue is related

- Android

### Expected behaviour
- Same behaviour iOS.

### Actual behaviour
- Android not has smartAlbums props.

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by ivpusic** [comment]
yes, this is ios only
