### ISSUE TITLE
define the output directory of cropped image

### ISSUE THREAD

**Issue by alainib** [ivpusic/react-native-image-crop-picker#478]
### Version
 "react": "16.0.0-alpha.12",
 "react-native": "^0.47.2",
 "react-native-image-crop-picker": "^0.17.2",

### Needs :  can we define the folder name for output cropped images ? 

I use this package to crop image from gallery and camera on IOS and ANDROID. It work very well thanks.
I need to put the cropped image in a given folder. is there a way with this package or i shoul use another one to juste move/copy the file to the folder i want in the callback ?

Thanks

    // open camera then crop the image
    openCameraCropper() {
        ImagePicker.openCamera({
            includeExif: true,
            cropping: true,
            width: 300,
            height: 400,
            compressImageMaxWidth: 900,
            compressImageMaxHeight: 900,
            compressImageQuality: 0.72
        }).then(image => {
            this.processDataImage(image);
        });
    }
    // open gallery then crop image
    openPickerCropper() {
        ImagePicker.openPicker({
            includeExif: true,
            cropping: true,
            width: 300,
            height: 400,
            compressImageMaxWidth: 900,
            compressImageMaxHeight: 900,
            compressImageQuality: 0.72
        }).then(image => {
            this.processDataImage(image);
        });
    }

**Comment by ivpusic** [comment]
currently not possible with this package
