### ISSUE TITLE
Cancell cropping of openCamera cann't return reject 

### ISSUE THREAD

**Issue by JjieChen** [ivpusic/react-native-image-crop-picker#479]
### Version

- react-native-image-crop-picker v0.17.3
- react-native v0.47

### Platform
- iOS

### Expected behaviour

openCamera and go to cropping page,when user click Cancell btn,it can  reject a Error"User cancelled image selection"

### Actual behaviour

openCamera and go to cropping page,when user click Cancell btn, it cann't return anything.

### Steps to reproduce

1.`ImagePicker.openCamera({
    width: 256,
    height: 256,
    cropping: true,})`

2.take a photo and go to the cropping page

3.in cropping page,click cancell btn,nothing will retrun

**Comment by Herb-Sun** [comment]
I have same issue

**Comment by Herb-Sun** [comment]
I update the version to 0.18.1, solute my issue, thx, we can close this issue

**Comment by JjieChen** [comment]
the version 0.18.1 ,still have thie issue

**Comment by HeiSiBaby** [comment]
0.20.3 依然存在

**Comment by ivpusic** [comment]
fixed with https://github.com/ivpusic/react-native-image-crop-picker/pull/954

**Comment by timbrandin** [comment]
0.35.0 have this issue, changed this line to this and it started working:
![image](https://user-images.githubusercontent.com/1715834/98214629-04e22280-1f47-11eb-87ee-769ff7315b70.png)
