### ISSUE TITLE
Cannot read property 'openCamera' of undefined

### ISSUE THREAD

**Issue by nzwnabdulwahid** [ivpusic/react-native-image-crop-picker#481]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.17.3
- react-native v0.42.0

### Platform
iOS 

### Expected behaviour
To open camera with Circle Crop

### Actual behaviour
Red Screen of Death stating "Cannot read property 'openCamera' of undefined"

### Steps to reproduce
I install the package according to README
1. Install Package
2. Link Package
3. Podfile setup.

### Attachments
![screen shot 2017-10-19 at 6 13 56 pm](https://user-images.githubusercontent.com/15116775/31766155-5f401cfc-b4f9-11e7-9de5-292c3601beb5.png)

**Comment by ivpusic** [comment]
this means linking of the library failed somehow. Try to link it again by following all instructions in readme file. Also check if you get any errors while running link command.

**Comment by roycclu** [comment]
I followed the manual instructions. Dropped in the folder.
Added pods accordingly. 
Then react-native link still failed silently. Nothing shows. 

`
➜  timecapsule git:(dev) ✗ react-native link react-native-image-crop-picker
Scanning 783 folders for symlinks in /Users/roycclu/Workspace/timecapsule/node_modules (9ms)
`

Can you please explain why? @ivpusic 
Thank you
