### ISSUE TITLE
[Andrioid] Cropped image not displaying at all on Android

### ISSUE THREAD

**Issue by TimonSotiropoulos** [ivpusic/react-native-image-crop-picker#485]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.17.2
- react-native v0.49.3

### Platform
Tell us to which platform this issue is related

- Android

### Expected behaviour
After cropping an image using the ImagePicker, the result.path location should be passed to an Image component as a uri and load in an Image component.

### Actual behaviour
The resulting image is just a white image, which appears like the file cannot be found at the correct path?

### Steps to reproduce

1. Crop image in Android

2. Pass image to Image component

### Attachments

```
    _updateProfileImage = () => {
        ImagePicker.openPicker({
            width: 300,
            height: 300,
            cropping: true,
        }).then(image => {
            const uri = (IS_IOS) ? image.sourceURL : image.path;
            this.setState({
                imageLink: {uri: uri}
            }, () => {
                this.props.updateProfileImage(image);
            });
        });
    }
```

Console Logs show the following data is from from the resulting image

<img width="951" alt="screen shot 2017-10-21 at 2 00 59 pm" src="https://user-images.githubusercontent.com/10914502/31847440-6aa1227e-b668-11e7-8345-6468e5783754.png">

Screen shot of the actual application with what is rendered after attempting to show the image.

![screenshot_1508554422](https://user-images.githubusercontent.com/10914502/31847386-49edcbe6-b667-11e7-9833-e21bf5ddeba4.png)

// stacktrace or any other useful debug info

Do I need to do something around requesting the correct permissions for this as a "Dangerous Permissions Request" for andrioid?

I'm very confused any help here would be great!

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by ivpusic** [comment]
can you show me how you are rendering image?

**Comment by ivpusic** [comment]
closing because there is no response from the author
