### ISSUE TITLE
Question: Open camera from picker?

### ISSUE THREAD

**Issue by compojoom** [ivpusic/react-native-image-crop-picker#486]
Is it somehow possible to open the camera from the picker? Use case being - user clicks on add image from multimedia, but then decides to take a picture.

**Comment by ivpusic** [comment]
currently not, you have to prepare UI on react-native side for this, and call `openCamera`.

**Comment by compojoom** [comment]
@ivpusic - you used the word "currently" :) Is this planned?
I've already used the openCamera and openPicker separately, but I get more and more the question - can't I switch from the picker to the camera and vice versa.

**Comment by ivpusic** [comment]
not in the near future

**Comment by Jancat** [comment]
The same desired feature.

**Comment by dev3288** [comment]
any alternative solution ?
