### ISSUE TITLE
"compile project(':react-native-image-crop-picker')" has to be added to app's build.gradle

### ISSUE THREAD

**Issue by XBLDev** [ivpusic/react-native-image-crop-picker#487]
Maybe add this to your readme? I think that line is important for the project to build but it's not included in the readme. I used this package like 6 months ago, and just spent the past hour trying to figure out why it keeps saying the packages doesn't exist.

**Comment by ivpusic** [comment]
this should be done by `react-native link react-native-image-crop-picker`.
