### ISSUE TITLE
Images with file:/// url is not being displayed on the device but works on simulator

### ISSUE THREAD

**Issue by srameshr** [ivpusic/react-native-image-crop-picker#491]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker : 0.18.1
- react-native: 0.48.4

### Platform
Tell us to which platform this issue is related

- iOS

### Expected behaviour
This is the url the plugin returns the following sourceURL from a simulator (iPhone 5 9.0, iPhone X 11.0):
```
file:///Users/sramesh/Library/Developer/CoreSimulator/Devices/BCF390E7-37B8-41B0-8309-47B177A8B501/data/Media/DCIM/100APPLE/IMG_0001.JPG

file:///Users/sramesh/Library/Developer/CoreSimulator/Devices/BCF390E7-37B8-41B0-8309-47B177A8B501/data/Media/DCIM/100APPLE/IMG_0018.GIF

``` 
When I load this into the ```Image``` tag it works and the image loads.

The same scenario with an actual device: iOS 10.3.3. iPhone 5s:

These are the sourceURL's returned from the device:
```
file:///var/mobile/Media/DCIM/100APPLE/IMG_0110.PNG
file:///var/mobile/Media/DCIM/100APPLE/IMG_0006.GIF
```
When I load these urls on my phone to the Image tag, it does not return anything. The ```onError``` callback of the ```Image``` tag fires. I don't know what the error is.

It works fine if I use the ```path``` instead of ```sourceURL```. But I want ```GIF``` images and the ```path``` does not give the actual ```GIF``` image.

### Actual behaviour
It should work same across simulator and device.

**Comment by ivpusic** [comment]
you should use path. Source url is original image location.

**Comment by srameshr** [comment]
@ivpusic Wait, how come it works on the simulator?
And path image does not return actual GIF files.

**Comment by srameshr** [comment]
@ivpusic Can you let me know how do I do this?

**Comment by ivpusic** [comment]
simulator has different permissions model. Because of that, I am creating temp files where the device has access to. I never tried with GIF images, but PR to support it would be welcome.

**Comment by srameshr** [comment]
I have no idea about Objective C or Java?
If I use the ```file:///``` url in simulator the ```GIF``` file plays but not with the path. Path returns ```.jpeg``` format even for GIF files.

**Comment by srameshr** [comment]
The ```file:///``` uri is working on the device with this plugin: https://github.com/react-community/react-native-image-picker but not with this.
But that plugin does not allow multiple images to be used. Damn!

**Comment by Blutude** [comment]
> you should use path. Source url is original image location.

What do you mean by path? I got the same issue. Using source uri works on emulator, it properly fetches the server for the media file, but when I try it on my actual iphone, it doesn't even fetch the server and uses a random cached photo.
I couldn't find any other way of fetching media files other than require('...') (but that is for local files) and source uri. I don't see what you mean by path.
