### ISSUE TITLE
How do I uninstall this plugin and also remove the pod files that were installed.

### ISSUE THREAD

**Issue by srameshr** [ivpusic/react-native-image-crop-picker#492]
I did run ```react-native unlink``` and did uninstalled the package manager. I also want to remove the dependent pod files.

**Comment by ivpusic** [comment]
question for stackoverflow

**Comment by srameshr** [comment]
@ivpusic If you know it, could you add it in the ```Readme``` file?

**Comment by srameshr** [comment]
I figured it out, just remove the lines where you mention the pod names in ```podfile``` and then run ```pod update```
