### ISSUE TITLE
Append multiple images!

### ISSUE THREAD

**Issue by ankitbisht143** [ivpusic/react-native-image-crop-picker#494]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.18.1
- react-native v0.49.5?

### Platform
Tell us to which platform this issue is related

- iOS
- Android

I am using react-native-image-crop-picker. All is good but i am struggling in one situtation where I want to append images one after another when selecting images from camera.

Currently when we select one image it is displaying and on selecting another image, the new image is overriding the previous one. I want to append them in scrollview.
How to achieve this?

**Comment by ivpusic** [comment]
hmm...this sounds like a react/react-native question. Store them in some kind of array and put array inside state. every time you get image from react-native-image-crop-picker append image to array. In the end render array of images in `render` method.
