### ISSUE TITLE
undefined is not an object (evaluating '_reactNativeImageCropPicker2.default.openPicker')

### ISSUE THREAD

**Issue by kealuya** [ivpusic/react-native-image-crop-picker#499]
### Version 
- react-native-image-crop-picker latest
- react-native 0.49.0

### Platform
- Android

react-native run-android after throw these error 
what can i do?? thanks.

undefined is not an object (evaluating '_reactNativeImageCropPicker2.default.openPicker')
<unknown>
    E:\reactnative_project\test1\MyApp\views\LoginPage.js:136:28
onComplete
    E:\reactnative_project\test1\MyApp\node_modules\react-native\Libraries\Animated\src\AnimatedImplementation.js:2172:31
<unknown>
    E:\reactnative_project\test1\MyApp\node_modules\react-native\Libraries\Animated\src\AnimatedImplementation.js:897:29
__debouncedOnEnd
    E:\reactnative_project\test1\MyApp\node_modules\react-native\Libraries\Animated\src\AnimatedImplementation.js:133:19
onUpdate
    E:\reactnative_project\test1\MyApp\node_modules\react-native\Libraries\Animated\src\AnimatedImplementation.js:341:28
callTimer
    E:\reactnative_project\test1\MyApp\node_modules\react-native\Libraries\Core\Timers\JSTimersExecution.js:98:17
callTimers
    E:\reactnative_project\test1\MyApp\node_modules\react-native\Libraries\Core\Timers\JSTimersExecution.js:138:34
__callFunction
    E:\reactnative_project\test1\MyApp\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:260:47
<unknown>
    E:\reactnative_project\test1\MyApp\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:101:26
__guard
    E:\reactnative_project\test1\MyApp\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:228:6
callFunctionReturnFlushedQueue
    E:\reactnative_project\test1\MyApp\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:100:17

**Comment by lucascavalheiro** [comment]
+1

**Comment by ivpusic** [comment]
installation failed. there are a number of similar issues, for example, https://github.com/ivpusic/react-native-image-crop-picker/issues/459
