### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by rakesh0r** [ivpusic/react-native-image-crop-picker#5]
after adding header search path RCTBridgeModule.h not found issue resolved but another new issue came 

Undefined symbols for architecture x86_64:
  "_RCTRegisterModule", referenced from:
      +[ImageCropPicker load] in ImageCropPicker.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ivpusic** [comment]
currently lib does not support rnpm. it is using cocoapods and gradle to manage external dependencies. PR is welcome to add support.

**Comment by anotherstarburst** [comment]
@ivpusic thanks for your contribution dude. Just to check, for existing projects where rnpm has been / is used we will not be able to use this lib right?

**Comment by ivpusic** [comment]
I am using rnpm with this lib in my project without any problems
