### ISSUE TITLE
[question/feature request] customizing photos modal

### ISSUE THREAD

**Issue by damathryx** [ivpusic/react-native-image-crop-picker#502]
Would like to ask for this feature if possible. I would like to contribute but I don’t have any experience in native. Making this issue is all I can do for now (sorry).
basically customizations like:
- navbar color
- header title
- left button / right button
- backgroundColor (?)
![23432174_1760947797257671_1438749100_o](https://user-images.githubusercontent.com/14576761/32491558-189a6c3c-c3f2-11e7-9c4c-03101e098aa2.jpg)

**Comment by ivpusic** [comment]
currently not supported and planned, but PR would be welcome
