### ISSUE TITLE
exif not working

### ISSUE THREAD

**Issue by anshu-goyal-lf** [ivpusic/react-native-image-crop-picker#506]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.16.1
- react-native v0.48.3

### Platform
Tell us to which platform this issue is related

- Android

### Expected behaviour

should give exif object in response

### Actual behaviour

not showing

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by ivpusic** [comment]
can you please provide more details? like image you are using? stacktrace?

**Comment by anshu-goyal-lf** [comment]
<img width="885" alt="screen shot 2017-11-14 at 18 54 22" src="https://user-images.githubusercontent.com/32696914/32782109-4aea968c-c96d-11e7-87bd-847cd5fdf9b6.png">
