### ISSUE TITLE
Can only select 1 photo when picking from Gallery on Android

### ISSUE THREAD

**Issue by superandrew213** [ivpusic/react-native-image-crop-picker#51]
You can pick multiple photos from the Photos folder but not Gallery.

**Comment by ivpusic** [comment]
read my comments here https://github.com/ivpusic/react-native-image-crop-picker/issues/31. Probably the same issue. Allow multiple on android is just telling app that it should support multiple selection, so it is not garantie that it will support it.

**Comment by superandrew213** [comment]
You said that it only doesn't work on older phones. I tested using Android 5 and 6 on Samsung S5 and it still doesn't allow it.

**Comment by ivpusic** [comment]
it depends on the phone. For eg. I tested it on samsung galaxy s6 and it works.
