### ISSUE TITLE
Run react-native link react-native-image-crop-picker failed when install

### ISSUE THREAD

**Issue by 9tong** [ivpusic/react-native-image-crop-picker#511]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.18.1
- react-native v0.47.2

### Platform
Tell us to which platform this issue is related

Android

### Expected behaviour

Run react-native link react-native-image-crop-picker failed
got 
project_path\react-native link react-native-image-crop-picker
Scanning 621 folders for symlinks in project_path\node_modules (9ms)
rnpm-install ERR! ERRPACKAGEJSON No package found. Are you sure this is a React Native project?

Non-whitespace before first tag.
Line: 0
Column: 1
Char: 

### Steps to reproduce

1.

2.

3.

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by ivpusic** [comment]
`rnpm-install ERR! ERRPACKAGEJSON No package found. Are you sure this is a React Native project?`

**Comment by 9tong** [comment]
@ivpusic thanks for reply,I executed command from project root  folder,and replace it with project_path for privacy here，I tried old version of react-native-image-crop-picker but it's not work.

**Comment by ivpusic** [comment]
problem is not `project_path`. From error message you got it seems that when you executed a command you were not in the project directory where package.json exists.

**Comment by 9tong** [comment]
sorry,there's something wrong with my project config,this's issue can be close now.
