### ISSUE TITLE
undefined is not an object('ReactNativeImageCropPicker')

### ISSUE THREAD

**Issue by himanshug16** [ivpusic/react-native-image-crop-picker#512]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker^0.18.1
- react-native v"0.49.3"

### Platform

- iOS

### Actual behaviour
It is working fine with android but throwing error in IOS. Did the pod installation process as described for IOS
![simulator screen shot 07-nov-2017 5 22 58 pm](https://user-images.githubusercontent.com/32382466/32946124-4103b6d4-cbbc-11e7-9fce-9c09881e7469.png)

### Steps to reproduce

1.

2.

3.

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by ivpusic** [comment]
ios linking failed probably. You can try to do linking again.

**Comment by himanshug16** [comment]
Did the linking and unlinking process several times but nothing changes. Also tried to add the files manually and by using cocoapods. No progess. Using this library for the first time. Any Support Provided to do it successfully will be Appreciated. Thanks

**Comment by ivpusic** [comment]
there is an example project with all things connected together without cocoapods. You can take a look into this one.

**Comment by yns01** [comment]
I'm currently facing the same issue. Tried the method with cocoa pods and manually, both without luck. However, if I run the app with XCode, it works fine.

**Comment by himanshug16** [comment]
this is my podfile:
target 'Example' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'
  # Pods for ValerB
end


*The library integration:
              import ImagePicker from 'react-native-image-crop-picker'

*File for the same:
                  PickfromCamera() {
      ImagePicker.openCamera({
      width: 300,
      height: 400,
      cropping: true
    }).then(image => {
      console.log(image);
    });
}

*Function Calling:
       <TouchableOpacity onPress={() =>this.PickSingleImage(ImagePicker)}>
                <Image source={additem} >
              </TouchableOpacity>

*IOS/InfoPlist File:
          key>NSCameraUsageDescription</key>
		<string>Your message to user when the camera is accessed for the first time</string>

	
	<key>NSPhotoLibraryUsageDescription</key>
	<string>Your message to user when the photo library is accessed for the first time</string>
.

Please verify the same and let me know if there is something wrong in it.

**Comment by himanshug16** [comment]
@yns01  Thanks.Adding folders to Xcode Worked. Thanks @ivpusic  for this awesome library.

**Comment by lwinkyawmyat** [comment]
### Versions
- react@16.0.0
- react-native@https://github.com/expo/react-native/archive/sdk-23.0.0.tar.gz
- react-native-image-crop-picker@^0.18.1

### Platforms
 - iOS

Hi @ivpusic ,
There isn't worked for me. This is a bug. Can you re-open this issue?
👍 👍 👍

**Comment by paul019** [comment]
@yns01 @ivpusic 

> Be sure to copy the folder at the root of the project in XCode.

Which folder do you mean?
