### ISSUE TITLE
suggest:  android multiple 

### ISSUE THREAD

**Issue by giantss** [ivpusic/react-native-image-crop-picker#514]
At present, many people reflect that android cannot be selected on many manufacturers. Can you please find a way to write a generic android multiple selector? Please

**Comment by ivpusic** [comment]
currently, I don't have a time for this. If anyone from the community is having some time to do this, PR would be very welcome.

**Comment by superandrew213** [comment]
@ivpusic can we have a TO DO list in the readme? I think 2 key features should be:

1. Multiple select for Android
2. Remote media for Android

**Comment by ivpusic** [comment]
@superandrew213 good idea. Could you add it to the readme file?
