### ISSUE TITLE
Selecting images from a custom local folder.

### ISSUE THREAD

**Issue by sri** [ivpusic/react-native-image-crop-picker#517]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker 0.18.1
- react-native v0.49.5

### Platform
Tell us to which platform this issue is related

- iOS

### Expected behaviour

I need to allow users to select images from custom, local folder created by the app. Is that possible with this library?

I tried to pass in the folder's path to the `smartAlbums` argument, but that didn't work.
Also, I tried to pass in a `userAlbums` arg with the folder, but that didn't work either
(got the reference for userAlbums from `QBAlbumsViewController.m`.

Apologies if this isn't the right way to ask such questions.
I'm new to this project and react-native.

Thanks!

**Comment by ivpusic** [comment]
currently this is not possible
