### ISSUE TITLE
Android 'Activity doesn't exist'

### ISSUE THREAD

**Issue by yulanfeiyang** [ivpusic/react-native-image-crop-picker#52]
In androind with the lastest version 0.70, occur this error: 'Activity doesn't exist'

**Comment by ivpusic** [comment]
can you please give me more details. Which android version you are using, which RN version, post stacktrace

**Comment by yulanfeiyang** [comment]
"react": "15.2.1", "react-native": "0.31.0",android: 5.1
when called openPicker or openCamera it catched an error:  'Activity doesn't exist', any thoughts?

**Comment by yulanfeiyang** [comment]
activity = getCurrentActivity();

        if (activity == null) {
            promise.reject(E_ACTIVITY_DOES_NOT_EXIST, "Activity doesn't exist");
            return;
        }

does there have some settings I lost?

**Comment by ivpusic** [comment]
nope, this is completely the same as before

**Comment by ksti** [comment]
I'm wondering how getCurrentActivity() works, since it seems not work well on my project neither.

**Comment by ivpusic** [comment]
@ksti you got exactly the same issue or?

**Comment by ksti** [comment]
Yes. And I tried to send 'this' like ''.addPackage(new PickerPackage(this))'', then I can get this as an Activity in PickerModule.java which under the node_modules folder , it works but not really so good.
In my project android activity get null by this code:  "activity = getCurrentActivity(); " . Any idea is appreciated!

**Comment by ivpusic** [comment]
@yulanfeiyang @ksti  please try this version https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.9.0. It might be relevant to this issue.

**Comment by ksti** [comment]
@ivpusic the issue is still there, we got activity null with "activity = getCurrentActivity(); "
Do you know why this happen? Thanks.

**Comment by ksti** [comment]
@ivpusic Tanks for your awesome working. We finally find the reason, we missed overriding the below methods(witch should be passed to ReactInstanceManager):
@Override
protected void onPause() {
    super.onPause();

    if (mReactInstanceManager != null) {
        mReactInstanceManager.onPause();
    }
}

@Override
protected void onResume() {
    super.onResume();

    if (mReactInstanceManager != null) {
        mReactInstanceManager.onResume(this, this);
    }
}

Thank you so much. Wish you not mind being bothered.

**Comment by ivpusic** [comment]
Great to hear you found a solution.
