### ISSUE TITLE
Multiple is not working

### ISSUE THREAD

**Issue by senthilbalajiganesan** [ivpusic/react-native-image-crop-picker#522]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.18.1
- react-native v0.50.3

### Platform
Tell us to which platform this issue is related

- iOS
- Android

### Expected behaviour
Multiple images while picking

### Actual behaviour
Cannot select more than one image, tick mark on long press is only not showing

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by ivpusic** [comment]
```ImagePicker.openPicker({
  multiple: true
}).then(images => {
  console.log(images);
});```
