### ISSUE TITLE
react-native-image-crop- picker 如何从相册直接获取视频，而不显示图片

### ISSUE THREAD

**Issue by wabgy** [ivpusic/react-native-image-crop-picker#524]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker ^0.17.2
- react-native 0.48.2

### Platform
Tell us to which platform this issue is related

- iOS
- Android

### Steps to reproduce

1.

2.

3.

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by ivpusic** [comment]
You can specify `mediaType`. Check readme for more instructions
