### ISSUE TITLE
Import ImagePicker get Undefined

### ISSUE THREAD

**Issue by lzmhhh123** [ivpusic/react-native-image-crop-picker#525]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.18.1
- react-native v0.49.5
- create-react-native-app v1.0.0

### Platform
Tell us to which platform this issue is related

- Android

### Expected behaviour

I'd like to use ImagePicker like the example. 

### Actual behaviour

The code like as follow:
`import ImagePicker from 'react-native-image-crop-picker';
console.log(ImagePicker);`
But the log returns a "Undefined"

**Comment by ivpusic** [comment]
installation failed. Can you please follow installation steps from readme and ensure all steps are completed and none of them returned error. Also you can check example project as an reference.
