### ISSUE TITLE
选择gif抛出Error: Cannot find image data

### ISSUE THREAD

**Issue by lhhhhhhhhh** [ivpusic/react-native-image-crop-picker#527]
Version
- react-native-image-crop-picker v0.18.1
- react-native v0.44.3
Platform
- iOS
- Android

**Comment by ivpusic** [comment]
Gifs are not currently supported. JPG/PNG and MP4 videos are.

**Comment by nwaughachukwuma** [comment]
@ivpusic I get this same error message when trying to select image from download path. Please is there a way to specify in the native side to solve this problem? Thanks as you reply

**Comment by zcgit** [comment]
@nwaughachukwuma I am facing the same problem. Did you solved it?

**Comment by ronakjain-2** [comment]
@ivpusic I am getting this error too. when trying to get image from my download folder.
uri: "content://com.android.providers.downloads.documents/document/3532"

**Comment by zcgit** [comment]
> @ivpusic I am getting this error too. when trying to get image from my download folder.
> uri: "content://com.android.providers.downloads.documents/document/3532"

maybe you need to replace 'com.github.yalantis:ucrop:2.2.2-native' to a newer version in build.gradle.
