### ISSUE TITLE
iOS Image Orientation is getting changed after converting to base 64 string

### ISSUE THREAD

**Issue by KevinTAN52** [ivpusic/react-native-image-crop-picker#528]
### Version

- react-native-image-crop-picker v0.16.1
- react-native v0.48.3

### Platform
- iOS
### Expected behaviour

Picking image with the good orientation

### Actual behaviour

iOS Image Orientation is getting changed after converting to base 64 string

### Steps to reproduce

1.import ImagePicker from 'react-native-image-crop-picker';

2. pickSingleBase64(cropit,) {
        ImagePicker.openPicker({
            compressImageQuality: 0.3,
            includeBase64: true,
        }).then(image => {
            console.log(`data:${image.mime};base64,`+ image.data)
            this.setState({
                image: `data:${image.mime};base64,`+ image.data,
            });
        }).catch(e => console.log(e));
    }
3. Use image in attachment 
4. Get image's base64 from console.log and use any website to decode base64 to image

### Attachments

Image with bad orientation when picking with module
![img_9242 4](https://user-images.githubusercontent.com/25990745/33434082-71e92e06-d5de-11e7-8fad-a20412c4c44e.jpeg)

**Comment by bockc** [comment]
@KevinTAN52 How did you fix it, I currently have the same problem ?
