### ISSUE TITLE
On upgrade getting error running on device

### ISSUE THREAD

**Issue by chuckyouliu** [ivpusic/react-native-image-crop-picker#53]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.7.0
- react-native v0.32.0

// stacktrace or any other useful debug info

I can run on simulator just fine, but when I try to run on my iPhone I get the following stacktrace error:

dyld: Library not loaded: @rpath/RSKImageCropper.framework/RSKImageCropper
  Referenced from: /var/containers/Bundle/Application/E8B8771F-2FB0-413A-B4AE-9592B6DF6888/AppName.app/AppName
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/E8B8771F-2FB0-413A-B4AE-9592B6DF6888/AppName.app/Frameworks/RSKImageCropper.framework/RSKImageCropper: mach-o, but wrong architecture

The app just hangs on the launch screen. I also noticed when trying to archive that it won't let me push the build to iTunes with a similar error message about not all architectures being supported with RSKImageCropper and QBImagePicker.

When adding the libraries in the Embedded Binaries section of the installation - I choose the ones from Libraries/imageCropPicker.xcodeproj/Frameworks. Is that correct?

**Comment by ivpusic** [comment]
<img width="618" alt="screen shot 2016-08-30 at 8 40 50 am" src="https://cloud.githubusercontent.com/assets/450140/18078752/8352e498-6e8d-11e6-8ff2-9509acb9fc8b.png">

Can you please check if these two are added to Embedded binaries, and if "Deployment Target" is set to 8.0. Also do full project clean and then build it. 

If you had cocoa-pods in place before, make sure to remove it as described in steps here https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.7.0

**Comment by ivpusic** [comment]
@chuckyouliu any updates here?

**Comment by chuckyouliu** [comment]
I added those libraries but had a deployment target of 9.3. Although I don't see why that would affect the architecture types of the libraries, I haven't had a chance to try 8.0 yet. Will do so tomorrow

**Comment by chuckyouliu** [comment]
Thanks for the help, the issue was I originally did a clean build with a selected simulator so the libraries that get built are only for whatever architecture the simulator's on. Starting with a clean build on Generic iOS device allowed me to use the libraries on my device.

**Comment by ivpusic** [comment]
check https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.8.0 release. It is relevant for this issue.
