### ISSUE TITLE
take a long time to callback

### ISSUE THREAD

**Issue by cq920702** [ivpusic/react-native-image-crop-picker#531]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.16.1
- react-native v0.47.2

### Platform
Tell us to which platform this issue is related
- iOS
### Expected behaviour
when i use multiple.After i choose photos,it can come back and return data very soon.

### Actual behaviour

when i use multiple.After i choose photos,it takes a very long time to come back and a long time to return the data.So it will takes a long time to show the photos.How can I get the return data quickly. 
  tks. 

### Steps to reproduce

1.

2.

3.

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by ivpusic** [comment]
if you are using base64 remove it. It will slow down retrieving data. Also if you are selecting very big photos, it will need some time to process it because temporary files are created under the hood.

**Comment by cq920702** [comment]
I'm not using base64 and photos are not very big.It just takes a very long time to return data.Almost 5 seconds or longer.We can't accept taking too much time to wait.Is there any better way to make it faster?Thanks very mush.

**Comment by ivpusic** [comment]
If the situation is as you are saying, it should be done almost instantly. You can check example project as a reference, or take a look into your code if something else is making it slow.
