### ISSUE TITLE
Android:Toolbar color is different from my app styles ,not found properties for setting toolbar colors

### ISSUE THREAD

**Issue by tvrc1990** [ivpusic/react-native-image-crop-picker#538]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.18.2
- react-native v0.47

### Platform
- Android

### Expected behaviour
Photo Album toolbar color matches my app

### Actual behaviour
Black before default
Not found properties for setting toolbar colors
I want the toolbar color to match my app color

### Steps to reproduce

ImagePicker1.openPicker({ multiple: true}).then(images => {
console.log(images);
});

(Running the above code displays a list of albums)

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by tvrc1990** [comment]
Color and style  sync with device

**Comment by prestonlanetz** [comment]
how did you solve this problem?
