### ISSUE TITLE
Installation instructions are incomplete

### ISSUE THREAD

**Issue by kuhbaar** [ivpusic/react-native-image-crop-picker#54]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.7.0
- react-native v0.31.0

### Expected behaviour

After running your recommended steps for installation the application should run.
>npm i react-native-image-crop-picker --save
>react-native link react-native-image-crop-picker

### Actual behaviour

After executing "react-native run-android" following error occurs:
>E:\(...)\MainApplication.java:8: error: package com.reactnative.ivpusic.imagepicker does not exist
>import com.reactnative.ivpusic.imagepicker.PickerPackage;
>                                          ^
>E:\(...)\MainApplication.java:31: error: cannot find symbol
>          new PickerPackage(),
>              ^
>  symbol: class PickerPackage
>2 errors

### Steps to reproduce

1. npm i react-native-image-crop-picker --save
2. react-native link react-native-image-crop-picker
3. react-native run-android

### Attachments

I noticed in your example project there are lines that are missing in mine, for example:
settings.gradle: 
>include ':react-native-image-crop-picker'
>project(':react-native-image-crop-picker').projectDir = new File(settingsDir, '../../android')"
app/build.gradle:
>dependencies {
>  (...)
>  compile project(':react-native-image-crop-picker')
>}

However it still fails with:
>A problem occurred configuring project ':app'.
>> Cannot evaluate module react-native-image-crop-picker : Configuration with name 'default' not >found."

Here is my MainApplication.java:
package com.stampowlapp;

import android.app.Application;
import android.util.Log;
import com.oblador.vectoricons.VectorIconsPackage;

import com.facebook.react.ReactApplication;
import com.reactnative.ivpusic.imagepicker.PickerPackage;
import com.facebook.react.ReactInstanceManager;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;

import com.imagepicker.ImagePickerPackage;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    protected boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          new PickerPackage(),
          new VectorIconsPackage(),
          new ImagePickerPackage() // <-- add this line
      );
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
      return mReactNativeHost;
  }
}

**Comment by ivpusic** [comment]
tried

```
npm i react-native-image-crop-picker --save
react-native link react-native-image-crop-picker
react-native run-android
```

on brand-new project and it works

**Comment by kuhbaar** [comment]
Does it includes the entries in settings.gradle and app/build.gradle?

**Comment by ivpusic** [comment]
yes, this is included

// settings.gradle
```project(':react-native-image-crop-picker').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-image-crop-picker/android')```

// app/build.gradle
```compile project(':react-native-image-crop-picker')```

**Comment by ivpusic** [comment]
@kuhbaar any updates here?

**Comment by kuhbaar** [comment]
I tried unlinking and removing the package and installing/linking again, but still no success.

Do you know which files I have to adapt to link it manually?

**Comment by myfoostrong** [comment]
Just attempted to install on an existing project with other linked libraries, confirm that the link install **does not fully install**.

As above, manually adding the lines:
// app/build.gradle
`compile project(':react-native-image-crop-picker')`

//settings.gradle
>>This one too! `include ':react-native-image-crop-picker'`
`project(':react-native-image-crop-picker').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-image-crop-picker/android')`

You should update the install instructions, or fix the linking. I don't know package managers well enough to help :(

**Comment by shopshow** [comment]
same issue here.
