### ISSUE TITLE
Could not resolve all dependencies for configuration ':react-native-image-crop-picker:_debugPublishCopy

### ISSUE THREAD

**Issue by kevin871223** [ivpusic/react-native-image-crop-picker#540]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.19.0
- react-native v0.?.?

### Platform
- Android

### Expected behaviour
androidstudio  sdk 23.01

*****.android\repositories.cfg could not be loaded.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-image-crop-picker'.
      > Could not resolve all dependencies for configuration ':react-native-image-crop-picker:_debugPublishCopy'.
         > Could not find com.github.yalantis:ucrop:2.2.1-native.
           Required by:
               chshlife:react-native-image-crop-picker:unspecified

**Comment by ivpusic** [comment]
check readme post install android steps.
