### ISSUE TITLE
 ld: warning: directory not found for option '-L/Users/infcn/Library/Developer/Xcode/DerivedData/fudao-bacfockisfovbogaixdqmfpqollg/Build/Intermediates/ArchiveIntermediates/fudao/BuildProductsPath/Release-iphoneos/QBImagePickerController' ld: warning: directory not found for option '-L/Users/infcn/Library/Developer/Xcode/DerivedData/fudao-bacfockisfovbogaixdqmfpqollg/Build/Intermediates/ArchiveIntermediates/fudao/BuildProductsPath/Release-iphoneos/RSKImageCropper' ld: library not found for -lQBImagePickerController clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by summmmer** [ivpusic/react-native-image-crop-picker#545]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.?.?
- react-native v0.?.?

### Platform
Tell us to which platform this issue is related

- iOS
- Android

### Steps to reproduce

1.

2.

3.

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by BaderSerhan** [comment]
i am having the same issue, what was its solution?
