### ISSUE TITLE
Missing dimen folder?

### ISSUE THREAD

**Issue by idajimenez** [ivpusic/react-native-image-crop-picker#55]
- react-native-image-crop-picker v0.7.0
- react-native v0.30.0

I am encountering this error.
`* What went wrong:
Execution failed for task ':react-native-image-crop-picker:mergeReleaseResources'.`

`../node_modules/react-native-image-crop-picker/android/build/intermediates/exploded-aar/com.yalantis/ucrop/2.1.2/res/drawable/ucrop_vector_loader.xml: Error: Width (0) and height (0) cannot be <= 0`

**Comment by damathryx** [comment]
i have the same problem

**Comment by ivpusic** [comment]
cannot reproduce on both dev and release mode. Can you please ensure that gradle pulled react-native-image-crop-picker v0.7.0 and it's dependencies

**Comment by damathryx** [comment]
I see the issue in ucrop repo
https://github.com/Yalantis/uCrop/issues/84
