### ISSUE TITLE
Can't upload to app store

### ISSUE THREAD

**Issue by misuna1997** [ivpusic/react-native-image-crop-picker#551]
"react-native": "0.43.0",
"react-native-image-crop-picker": "0.19.1"

Dear developer,

We have discovered one or more issues with your recent delivery for "MyApp". To process your delivery, the following issues must be corrected:

Invalid Binary Architecture - iOS 3.0 introduced support for multiple binary architectures. If your binary is built for multiple architectures, your Info.plist must have a MinimumOSVersion key with a value of at least 3.0. Additionally, if your app is intended to support earlier iPhone and iPod touch models, your app must contain at least an armv6 binary; "thin" armv7-only binaries will not be accepted unless the armv7 required device capability is also present in the Info.plist UIRequiredDeviceCapabilities key or the MinimumOSVersion key has a value of 4.3 or higher.

Specifically, we found the following unsupported architectures in your binary:

x86_64
i386

When running on simulator everything works fine

**Comment by pedrogyn** [comment]
What was the problem?

**Comment by misuna1997** [comment]
I installed react-native-image-crop-picker with CocoaPods and problem has gone.
