### ISSUE TITLE
how to limit numbers of img  when multi on android ?

### ISSUE THREAD

**Issue by OrangeFlavoredColdCoffee** [ivpusic/react-native-image-crop-picker#555]

**Comment by superandrew213** [comment]
See options https://github.com/ivpusic/react-native-image-crop-picker#request-object. Only available for iOS.

**Comment by OrangeFlavoredColdCoffee** [comment]
@superandrew213 thanks for reply, there is some problems when choose more than 10+ or  quality high image , is anyone has solution about this ? thank a lot

**Comment by ivpusic** [comment]
you could check this from javascript, eg. if user selected more than X assets do something
