### ISSUE TITLE
can't pick the video

### ISSUE THREAD

**Issue by B4UGUYS** [ivpusic/react-native-image-crop-picker#557]
can't pick the video 
plz, help me guys

**Comment by B4UGUYS** [comment]
Finally, it works.I have to change this method


    private static String getMimeType(String url) {
        String type = null;
        String extension = null;

        int i = url.lastIndexOf('.');
        if (i > 0) {
            extension = url.substring(i+1);
        }

        if (extension != null) {
            type = MimeTypeMap.getSingleton().getMimeTypeFromExtension(extension);
        }
        return type;
    }
It is causing error  coz it is not returning type .

**Comment by hardcodet** [comment]
Are you saying this was a bug in the library?

**Comment by B4UGUYS** [comment]
It works in android version 16. When I change to version 27, It does not.

**Comment by hardcodet** [comment]
FYI @ivpusic
