### ISSUE TITLE
Response object does not contain all properties

### ISSUE THREAD

**Issue by fazeelzama20** [ivpusic/react-native-image-crop-picker#558]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker "^0.19.1"
- react-native "0.50.3"

### Platform
Tell us to which platform this issue is related
- Android

### Expected behaviour
the response object of image should contain all properties like fileName. It only supports in iOS.
I have to use it in android also.

### Actual behaviour
It is showing only some of the properties, not all.
![screen shot 2018-01-02 at 1 44 46 pm](https://user-images.githubusercontent.com/28836058/34477857-3e19f73c-efc3-11e7-9ea4-fd2928937219.png)

**Comment by ivpusic** [comment]
some properties are ios only. You can send a pull request to add android compatibility for them
