### ISSUE TITLE
Remove  RSKImageCropper.framework and QBImagePicker.framework from Linked Frameworks and Libraries?

### ISSUE THREAD

**Issue by superandrew213** [ivpusic/react-native-image-crop-picker#56]
Should RSKImageCropper.framework and QBImagePicker.framework be in both "Embedded binaries" and "Linked frameworks with libraries"?

This was causing issues for me when running on device or archiving (Sim was working fine). I was getting this error:
```
dyld`dyld_fatal_error:
->  0x1200ad088 <+0>: brk    #0x3
```

 Removing the two frameworks from "Linked frameworks with libraries" solved it.

**Comment by Nicolas-Menettrier** [comment]
I had the same issue but after few reinstall i linked manually the library and after that all work fine, strange bug. (I doesn't remove RSKImageCropper and QBImagePicker from linked frameworks and librairies).
![librairies](https://cloud.githubusercontent.com/assets/17987207/18200221/14c13d80-7104-11e6-9bbd-33a3b176d943.png)

**Comment by ivpusic** [comment]
new version with pre-built frameworks is published. https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.8.0. They are built for Simulator and Device arch.

Check updated iOS instructions. You will have to drag ImageCropPickerSDK to your project, and then put these *.framework files to Embedded binaries (and of course remove old ones).
