### ISSUE TITLE
mediaType: 'any'  not working as expected after opening the camera for images only

### ISSUE THREAD

**Issue by sarahmarciano** [ivpusic/react-native-image-crop-picker#563]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v^0.19.0
- react-native v0.48.4

### Platform
Tell us to which platform this issue is related
- Android

### Expected behaviour
when calling openPicker with property mediaType: 'any' I expect to see both video and pictures

### Actual behaviour
so in my app I have two buttons which one of them is supposed to open the gallery for both pics and videos and one button for opening the camera

so when calling the gallery first, I can see both videos and pics but, if I open the camera and then I open the gallery -> I can see just the pictures and not the videos
### Steps to reproduce
here is my two functions which I call to open the gallery/camera
```
 openGallery() {
        const { onComplete } = this.props;
        ImageCropPicker.openPicker({
            width: 300,
            height: 300,
            includeBase64: true,
            mediaType: 'any'
        }).then(({ path, mime }) => onComplete(path, mime));
    }
   openCameraPics() {
        const { onComplete } = this.props;
        ImageCropPicker.openCamera({
            width: 300,
            height: 300,
            cropping: true,
            includeBase64: true
        }).then(({ path, mime }) => onComplete(path, mime));
        }).catch(() => null);
    }
```

BTW: is it supported to open the camera for both video recording and taking pictures?
cause this code isn't working for me:
`ImageCropPicker.openCamera({
           mediaType: 'any'
        })`

thank you very much!!
awesome library!
### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by ivpusic** [comment]
currently this is android limitation as stated in readme file. I suggest you to create some ui element to select if you are choosing images or videos

**Comment by sarahmarciano** [comment]
First, tnx for your quick reply
as I understood from the readme file the mediaType: 'any' is not supported on android just when setting the cropImage to true but here I did not set it to true.
and it's working for me until I call the second function of open camera
seems like the library is caching the mediaType somewhere
is there maybe a way to clear the cach after calling the open camera, or something alike?
tnx again

**Comment by ivpusic** [comment]
hmm, it should not be caching it. Behaviour of that property depends on android version, so I suggest to avoid it on android.

**Comment by sarahmarciano** [comment]
Ok, so finally what I did is setting `cropping: false` on the `ImageCropPicker.openPicker` function and that resolved my issue
Tnx again for you help
