### ISSUE TITLE
Could not resolve all dependencies for configuration ':react-native-image-crop-picker:_debugPublishCopy'.

### ISSUE THREAD

**Issue by smilelabi** [ivpusic/react-native-image-crop-picker#566]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.19.1
- react-native v0.51.0

### Platform
Tell us to which platform this issue is related

- Android

### Actual behaviour

FAILURE: Build failed with an exception.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-image-crop-picker'.
> Could not resolve all dependencies for configuration ':react-native-image-crop-picker:_debugPublishCopy'.
   > Could not find com.github.yalantis:ucrop:2.2.1-native.
     Required by:
         haitaichanglian:react-native-image-crop-picker:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 13.033 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by timhorwood** [comment]
I am also getting this issue.

I have a reference to maven already in my project/build.gradle which has been suggested as a solution to this issue previous.

`maven {
            url "$rootDir/../node_modules/react-native/android"
        }`

I tried another solution which was to include multiple maven references

`maven { url "https://jitpack.io" }
        maven {
            url "$rootDir/../node_modules/react-native/android"
        }`

but this caused another issue on build regarding PickerPackage not being found.

Thanks,

**Comment by ivpusic** [comment]
as stated in the readme file, to the project build.gradle add

```gradle
allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}
```

**Comment by kriswuwenxiang** [comment]
`allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}`
==》cut no ice
![image](https://user-images.githubusercontent.com/17079854/34811563-6d74e74c-f6dc-11e7-9797-82bf7dff496f.png)
![image](https://user-images.githubusercontent.com/17079854/34811580-7b0f60da-f6dc-11e7-8ba1-6f0d5318c382.png)

**Comment by krionoah69** [comment]
@kriswuwenxiang I cause another error u.u
![screen shot 2018-01-31 at 15 19 24](https://user-images.githubusercontent.com/16009215/35648088-26a047f8-069a-11e8-814c-48b49da4ab4d.png)
