### ISSUE TITLE
Cannot read property 'openCamera' of undefined

### ISSUE THREAD

**Issue by roycclu** [ivpusic/react-native-image-crop-picker#568]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.19.1
- react-native v0.46.0

### Platform
Tell us to which platform this issue is related

- iOS

### Expected behaviour

openCamera should work

### Actual behaviour

Red Screen of Death stating "Cannot read property 'openCamera' of undefined"

### Steps to reproduce

1. Go to intended page, and trigger ImagePicker.openCamera

2. Error occurs.

I went accordingly to the install steps twice. 
And here were the steps: 
1. Yarn added package
2. react-native link <package> failed silently like so:

`
➜ timecapsule git:(dev) ✗ react-native link react-native-image-crop-picker Scanning 783 folders for symlinks in /Users/roycclu/Workspace/timecapsule/node_modules (9ms)
`

3. Dragged and dropped the frameworks folder accordingly
4. Manually added pod and Podfile
5. Build succeeded
6. Still failed.

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by ivpusic** [comment]
linking failed. Could you please try to debug that?

**Comment by roycclu** [comment]
@ivpusic solved.

linking succeeded after I 
1. manually added the package on the android side
2. ran react-native link <package> again
3. linking was successful
