### ISSUE TITLE
Could it be possible to open getBase64StringFromFile to react-native?

### ISSUE THREAD

**Issue by henkkasoft** [ivpusic/react-native-image-crop-picker#569]
### Version
- react-native-image-crop-picker v0.16.0
- react-native v0.47.4

### Platform
- Android
- iOS

Thank you for a great component. 
Could it be possible to open getBase64StringFromFile to react-native?
I am using openPicker and openCamera methods in my app and using the base64 output of them. Now I would need to convert one other image from path: content://media/external/images/media to base64 and couldn't find solution for that.
I tried to use https://github.com/xfumihiro/react-native-image-to-base64
but that did not work and is not actively developed.

Because react-native-image-crop-picker already has working solution for converting image urls to base64, and there are no other working solution for that, could it be possible to open method even it is not really core purpose of this component?
Thank you.

**Comment by ivpusic** [comment]
currently not, but you can fork library and do it
