### ISSUE TITLE
ImagePicker.openPicker crashs the app when calling it more than once

### ISSUE THREAD

**Issue by wxsms** [ivpusic/react-native-image-crop-picker#570]
I think this might be related to #275, but since there's still no solutions (and it is for android, mine is ios), I'd like to open this issue.

Note: I do have finish the README file for many times, and follow all the install guides. My ios dependencies are installed by `pod`.

### Version

- react-native-image-crop-picker v0.19.1
- react-native v0.49.3

### Platform

- iOS 11.2

### Expected behaviour

After Picker close, it can be open again. (It DO work as expect in my Android devices)

### Actual behaviour

When I close the Picker, and call `ImagePicker.openPicker` on the 2nd time:

1. The Picker shows for a second, then disapper
2. After that, the app becomes unclickable, even I refresh it by Reload scripts
3. I have to kill it and restart the app to make it work again

### Steps to reproduce

```javascript
// in some button press event
    try {
      image = await ImagePicker.openPicker({});
    } catch (err) {
      console.log(err)
    }
```

### Attachments

There are no errors catch by RN code, so I don't have any error log. It just happens.

**Comment by wxsms** [comment]
Added GIF screenshot:

![jan-11-2018 19-23-31](https://user-images.githubusercontent.com/5960988/34823452-573829de-f705-11e7-82da-9625d402c736.gif)

The warning is `user canceled image selection` after I close the first picker.

**Comment by ivpusic** [comment]
you have to implement .catch block

**Comment by wxsms** [comment]
Thank you for replying. I have tried:

```javascript
ImagePicker.openPicker({})
  .then(img => ...)
  .catch(err => ...)
```

but it doesn't help. Same problem still.

BTW, my Xcode: Version 9.2 (9C40b).

**Comment by wxsms** [comment]
I just found the root cause. it was cause by the actionsheet lib. Sry for wasting your time :cry:

**Comment by wangweijia** [comment]
@wxsms How do you solve this problem?

**Comment by Swaroop-Bhupathiraju** [comment]
@wxsms How did you solve the problem? I have the same problem. I am using react-native-actionsheet and i am guessing you are using the same.

**Comment by wxsms** [comment]
@Swaroop-Bhupathiraju this problem is cause by custom actionsheet, but I have not solved it, I just switch it to the system default one.

**Comment by Swaroop-Bhupathiraju** [comment]
@wxsms thank you, hopefully i can find a solution, o.w. will use the default one

**Comment by p3ym4n** [comment]
I found a hacky way and that is to delay the ImagePicker.openGallery() or ImagePicker.openCamera() call about 100 ms.

**Comment by bintoll** [comment]
Same problem, was also able to fix with 100ms delay

**Comment by hkxicor** [comment]
@bintoll can you show code snippet

**Comment by bintoll** [comment]
@hkxicor easy
setTimeout(() => {
      ImagePicker.openCamera({
        width: 300,
        height: 300,
        cropping: true,
        includeBase64: true
      }).then((imageObj) => {
        const res = {
          uri: imageObj.path,
          data: imageObj.data
        }
        this.onGetImageResponse(res)
      })
      .catch((error) => {
        console.log('onTakePhotoPress error')
        console.log(error)
      })
    }, 100)

**Comment by hkxicor** [comment]
@bintoll problem is still their

**Comment by bintoll** [comment]
sorry, for me it solved, may be you have a crash in other part of code?

**Comment by hkxicor** [comment]
@bintoll now it's working ... thanks for solution

**Comment by ashima-narula** [comment]
@bintoll it works ,thanks :-)

**Comment by YASH-8102** [comment]
I coud not resolve it using set timeout on iOS the problem is still there can anyone please help me out with this

**Comment by YASH-8102** [comment]
issue #893 can help you :)
