### ISSUE TITLE
oh my god ,how to save it !!!

### ISSUE THREAD

**Issue by R10burning** [ivpusic/react-native-image-crop-picker#571]
Version

Tell us which versions you are using:

react-native-image-crop-picker v0.19.1
react-native v0.50.2
Platform

Tell us to which platform this issue is related

Android
this is the issue below,how to save it ?
F:\MHT\aaa\mht_app2\android\app\src\main\java\com\mhoutapp\MainApplication.java:5: 错误: 找不到符号
import com.facebook.react.ReactApplication;
^
符号: 类 ReactApplication
位置: 程序包 com.facebook.react
F:\MHT\aaa\mht_app2\android\app\src\main\java\com\mhoutapp\MainApplication.java:6: 错误: 程序包com.reactnative.ivpusic.imagepicker不存在
import com.reactnative.ivpusic.imagepicker.PickerPackage;
^
F:\MHT\aaa\mht_app2\android\app\src\main\java\com\mhoutapp\MainApplication.java:10: 错误: 找不到符号
import com.facebook.react.ReactNativeHost;
^
符号: 类 ReactNativeHost
位置: 程序包 com.facebook.react
F:\MHT\aaa\mht_app2\android\app\src\main\java\com\mhoutapp\MainApplication.java:20: 错误: 找不到符号
public class MainApplication extends Application implements ReactApplication {
^
符号: 类 ReactApplication
F:\MHT\aaa\mht_app2\android\app\src\main\java\com\mhoutapp\MainApplication.java:22: 错误: 找不到符号
private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
^
符号: 类 ReactNativeHost
位置: 类 MainApplication
F:\MHT\aaa\mht_app2\android\app\src\main\java\com\mhoutapp\MainApplication.java:48: 错误: 找不到符号
public ReactNativeHost getReactNativeHost() {
^
符号: 类 ReactNativeHost
位置: 类 MainApplication
F:\MHT\aaa\mht_app2\android\app\src\main\java\com\mhoutapp\MainActivity.java:5: 错误: MainActivity不是抽象的, 并且未覆盖ReactActivity中的抽象方法getPackages()
public class MainActivity extends ReactActivity {
^
F:\MHT\aaa\mht_app2\android\app\src\main\java\com\mhoutapp\MainApplication.java:22: 错误: 找不到符号
private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
^
符号: 类 ReactNativeHost
位置: 类 MainApplication
F:\MHT\aaa\mht_app2\android\app\src\main\java\com\mhoutapp\MainApplication.java:47: 错误: 方法不会覆盖或实现超类型的方法
@override
^
9 个错误

**Comment by ivpusic** [comment]
can you please explain what is the issue here?

**Comment by R10burning** [comment]
when react-native run-android compile code ,console throw this exception .
see top floor is my issue

**Comment by R10burning** [comment]
3q

**Comment by CrazyPython** [comment]
did you follow the steps at https://github.com/ivpusic/react-native-image-crop-picker#android ?
