### ISSUE TITLE
Could not resolve all dependencies for configuration ':react-native-image-crop-picker:_debugPublishCopy'.

### ISSUE THREAD

**Issue by kriswuwenxiang** [ivpusic/react-native-image-crop-picker#574]
Tell us which versions you are using:

- react-native-image-crop-picker v0.19.1
- react-native v0.51.0

Platform

- Android

What went wrong:
```
A problem occurred configuring project ':react-native-image-crop-picker'.
Could not resolve all dependencies for configuration ':react-native-image-crop-picker:_debugPublishCopy'.
Could not find com.github.yalantis:ucrop:2.2.1-native.
```
Try:
```
allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}
```
==》cut no ice
![image](https://user-images.githubusercontent.com/17079854/34811563-6d74e74c-f6dc-11e7-9797-82bf7dff496f.png)
![image](https://user-images.githubusercontent.com/17079854/34811580-7b0f60da-f6dc-11e7-8ba1-6f0d5318c382.png)
Thanks,
@ivpusic

**Comment by amberv0** [comment]
@ivpusic , and if you keep BOTH maven lines? Like this. It worked for me.

```
maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven { url "https://jitpack.io" }
```

**Comment by kriswuwenxiang** [comment]
@amberv0 
I tried it.
It doesn't work for me.

**Comment by rusliabdulgani** [comment]
can someone solve this problem? i have this problem also... please help

**Comment by umarzaman2010** [comment]
@amberv0 
I tried it.
it worked for me.
just install and link and do the changes as suggested by  @amberv0  and it worked, thanks.

**Comment by bashirk** [comment]
@amberv0 
Your solution worked for me. Thank you

**Comment by caik123** [comment]
@amberv0 
ths,it worked for me

**Comment by ivpusic** [comment]
closing this. readme file is also now updated with comment from @amberv0

**Comment by Digvijaykumar21** [comment]
* What went wrong:
A problem occurred configuring project ':react-native-image-picker'.
> Could not resolve all artifacts for configuration ':react-native-image-picker:classpath'.
   > Could not resolve com.android.tools.build:gradle:3.1.4.
     Required by:
         project :react-native-image-picker
      > Could not resolve com.android.tools.build:gradle:3.1.4.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.1.4/gradle-3.1.4.pom'.
            > Could not HEAD 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.1.4/gradle-3.1.4.pom'.
               > dl.google.com: Name or service not known
      > Could not resolve com.android.tools.build:gradle:3.1.4.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.1.4/gradle-3.1.4.pom'.
            > Could not HEAD 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.1.4/gradle-3.1.4.pom'.
               > jcenter.bintray.com: Name or service not known

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
