### ISSUE TITLE
Trying to open camera always returns rejected Promise with message "Required permission missing"

### ISSUE THREAD

**Issue by BisiPaul** [ivpusic/react-native-image-crop-picker#576]
Hey,

As my title says, I always get this error when trying to open the camera with ImagePicker.
I have the permission for the camera in AndroidManifest.
Even when I check my app inside settings it says that it needs the Camera permission and that it is granted.

Code that I used for ImagePicker: 
`const result = ImagePicker.openCamera({ 
        width: 300,
        height: 400,
        cropping: true
      }).then(image => {
        console.log(image);
});`

Code that I used for permission:
`async function requestCameraPermission() {
  try {
    const granted = await PermissionsAndroid.request(
      PermissionsAndroid.PERMISSIONS.CAMERA,
      {
        'title': 'Cool Photo App Camera Permission',
        'message': 'Cool Photo App needs access to your camera ' +
                   'so you can take awesome pictures.'
      }
    )
    if (granted === PermissionsAndroid.RESULTS.GRANTED) {
      console.log("You can use the camera")
    } else {
      console.log("Camera permission denied")
    }
  } catch (err) {
    console.warn(err)
  }
}`

It always logs into the console the "You can use the camera" message".

**Comment by ivpusic** [comment]
do you have some time to investigate this? I cannot reproduce it

**Comment by BisiPaul** [comment]
You can close the issue. It seems that I was missing the Storage permission, so yeah, my bad.

**Comment by benhartouz** [comment]
the same issue, I always get `Error : Required permission missing` even i added this to AndroidManifest.xml
 ` <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />`

**Comment by benhartouz** [comment]
I fixed this issue by adding this: 
`<uses-permission
        android:name="android.permission.WRITE_EXTERNAL_STORAGE"
        tools:remove="android:maxSdkVersion" />`

**Comment by Usamaliaquat123** [comment]
@benhartouz  not fixed

**Comment by benhartouz** [comment]
@Usamaliaquat123 its worked fine for me, just try to clean up your  AndroidManifest.xml file, and try again.
