### ISSUE TITLE
app crash down

### ISSUE THREAD

**Issue by kk412027247** [ivpusic/react-native-image-crop-picker#578]
### Version

"dependencies": {
    "native-base": "^2.3.6",
    "prop-types": "^15.6.0",
    "react": "16.0.0",
    "react-native": "0.51.0",
    "react-native-camera": "^0.12.0",
    "react-native-image-crop-picker": "^0.19.1",
    "react-navigation": "^1.0.0-beta.23",
    "react-redux": "^5.0.6",
    "realm": "^2.1.1",
    "redux": "^3.7.2",
    "redux-thunk": "^2.2.0"
  },

### Platform

- iOS

### Actual behaviour

I just run " yarn add react-native-image-crop-picker && react-native link ".
My project can not run anymore, event if i remove the package.
When I open my App  , the App just close  immediately.

By the way, the "react-native-camera"  and the "react-native-image-picker" package working well  before.

### Attachments

The App show this screen for a second,  then crash down.

<img width="375" alt="2018-01-15 1 18 58" src="https://user-images.githubusercontent.com/30715186/34918763-24c0c0f2-f993-11e7-9ed4-5d61214dc6ae.png">

**Comment by fanzhiri** [comment]
check the user report in console , you will find that there is a crash file in list named like XXX_2018-01-XX-XXXX_XXX.crash .
I found two lines in the file 
Dyld Error Message:
  Library not loaded: @rpath/QBImagePicker.framework/QBImagePicker
I still looking for the solution too .

**Comment by kk412027247** [comment]
@fanzhiri Thx.

**Comment by radik** [comment]
@kk412027247 any luck? Did you find a solution?

**Comment by HeeTing** [comment]
@kk412027247 你这个问题解决了么，我用Xcode可以跑起来，react-native run-ios 就崩
when i use react-native run-ios, the app will crash down

**Comment by joaom182** [comment]
Same here..

Steps to install:
`npm install react-native-image-crop-picker`
`react-native link react-native-image-crop-picker`
- Added to Podfile `pod 'RSKImageCropper'`and `pod 'QBImagePickerController'`
`pod install`

When i run with Xcode, all is ok.. but if i run with `react-native run-ios` app crash down when startup.

**Comment by kk412027247** [comment]
Thx. finally it work.

**Comment by kk412027247** [comment]
@HeeTing 解决了，之前是忘记了添加 RSKImageCropper QBImagePickerController 这两个依赖包。

**Comment by kk412027247** [comment]
@radik thx. after adding RSKImageCropper and RSKImageCropper, the project works well.

**Comment by kk412027247** [comment]
@HeeTing 模拟器是跑起来没问题，但是 在真机运行 relase 版本的时候，xcode报错依赖包丢失了，我原生的IOS搞不定。所以我出门左转用了react-native-image-picker这个包。（￣▽￣）～■□～（￣▽￣）

**Comment by hufans** [comment]
> @kk412027247 你这个问题解决了么，我用Xcode可以跑起来，react-native run-ios 就崩
> when i use react-native run-ios, the app will crash down

same here
