### ISSUE TITLE
Failed to verify bitcode in QBImagePicker.framework/QBImagePicker: error: Cannot extract bundle from /var/folders/k4/k1l9n9v96lxf4h14bqxt36pr0000gn/T/IDEDistributionOptionThinning.Hff/Payload/LyApp.app/ImageCropPickerSDK/QBImagePicker.framework/QBImagePicker (x86_64)

### ISSUE THREAD

**Issue by daodaowang** [ivpusic/react-native-image-crop-picker#579]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.19.1
- react-native v0.44.0

### Platform
Tell us to which platform this issue is related

- iOS

### Expected behaviour
archive succefully but >>..

### Actual behaviour
Failed to verify bitcode in QBImagePicker.framework/QBImagePicker:
error: Cannot extract bundle from /var/folders/k4/k1l9n9v96lxf4h14bqxt36pr0000gn/T/IDEDistributionOptionThinning.Hff/Payload/LyApp.app/ImageCropPickerSDK/QBImagePicker.framework/QBImagePicker (x86_64)

### Steps to reproduce

1.

2.

3.

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by daodaowang** [comment]
run simulator is ok,but archive failed;

**Comment by daodaowang** [comment]
the probem was solved , but i dont know how did it,ahahh

**Comment by adarshroy** [comment]
What is the solution?   Mine is the same issue:

```
Failed to verify bitcode in ogg.framework/ogg:
error: Bundle only contains bitcode-marker /var/folders/ww/6vrzrmr5719673rcd2dl2h0w0000gn/T/XcodeDistPipeline.Zop/Root/Payload
```

**Comment by ngtlin** [comment]
I have the same issue. Can someone post the solution?

**Comment by Arshiamidos** [comment]
#58

**Comment by telmen** [comment]
how? lol
