### ISSUE TITLE
Failed to verify bitcode in QBImagePicker.framework/QBImagePicker

### ISSUE THREAD

**Issue by rops** [ivpusic/react-native-image-crop-picker#58]
- react-native-image-crop-picker v0.8.0
- react-native v0.32.0

I'm getting this error when building from command line with xcodebuild:

```
Failed to verify bitcode in QBImagePicker.framework/QBImagePicker:
```

Woks fine from XCode. Has anyone experienced that?

**Comment by rops** [comment]
If I don't add the pre-built libraries included in this repo but add them as pods it works fine. 
So I guess the pre-built frameworks here have something wrong?

**Comment by ivpusic** [comment]
just tried it on my personal and on brand new test project. It works on both places. 

`xcodebuild clean build -scheme testProject`

did you provide some additional args or?

If you go to `yourProject/Libraries/imageCropPicker/Libraries` you can find frameworks. 

They are xcodeprojects with Aggregate target. If you run this target, script for building *.framework will run. You will get output into `node_modules/react-native-image-crop-picker/ios/ImageCropPickerSDK`. 

You can try playing with configuration of frameworks, build Aggregate target for each framework, copy built *.framework into your project, and see if you can solve this issue.

**Comment by rops** [comment]
Sorry my bad. Building works. I got the error while archiving. Do you get any error while archiving and exporting?

```
xcodebuild archive -scheme testProject -archivePath test.xarchive
xcodebuild -exportArchive -archivePath test.xarchive
```

**Comment by ivpusic** [comment]
maybe related to this https://github.com/ivpusic/react-native-image-crop-picker/issues/61?

**Comment by rops** [comment]
If I set `compileBitcode = false` in the exportOptionsPlist I don't get any error. Could it be that the pre-built libraries were built with bitcode support off?

**Comment by rops** [comment]
Actually both QBImagePicker and RSKImageCropper have `ENABLE_BITCODE=true`. If it was disabled, compilation would have failed

**Comment by ivpusic** [comment]
you don't have to use pre-built versions. They are for development purposes -> they include simulator and device ARCHs. You can compile them as you wish, and just include *.framework (from framework Products folder) to embedded binaries.

**Comment by ivpusic** [comment]
@rops https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.8.1 may help you. If you still have issue, you can try tip from this post http://vourkosa.github.io/ios/2016/04/14/How-to-build-an-iOS-library-with-Bitcode-support-and-keep-backwards-compatibility-with-XCode-6.html

**Comment by erdostom** [comment]
When I try compile the *.framework from the Products folder, I get the following error:

Info.plist of “Myapp.app/Frameworks/QBImagePicker.framework” specifies a simulator platform for the CFBundleSupportedPlatforms key

Will try the v0.8.1. next.

**Comment by ivpusic** [comment]
@erdostom will add section to notice about not using pre-built *.framework(s) for production build

**Comment by erdostom** [comment]
@ivpusic I was not able to get it working yet. The premade binaries work OK, but I can't build my own. I'm following the the discussion in #61, here's what I did:

1. Remove premade binaries from Embedded Binaries
2. Build for Generic Device
3. Received following error:

<img width="1184" alt="screen shot 2016-09-07 at 09 54 54" src="https://cloud.githubusercontent.com/assets/3744979/18314560/8e237bf8-74e1-11e6-835b-e09232a6be10.png">

**Comment by ivpusic** [comment]
Glad to hear that it works for you. First installation instruction was with cocoa pods. This "just worked" if you had cocoa-pods enabled project. Some people were complaining about cocoa-pods, having issues with project setup, complaining about no rnpm support, so I decided to step away from cocoa-pods. This introduced some issues like this, because library depends on two external frameworks which has to be somehow present on runtime.

Do you have some ideas how to make it more "user friendly" or?

**Comment by erdostom** [comment]
The easiest for me would be if rnpm linked the required frameworks, and that was the whole install process. If we have to embed binaries, it would be easiest if we could embed the same ones for both dev and prod.

**Comment by parkerdan** [comment]
I can't get rid of the "Unsupported Architecture" errors and everything thing else that comes with them.  I've read/tried all of this and issue #61, still unable to get anything to work.

The only way I can get an app with this package to iTunes Connect, is with Cocoa Pods.

I generated a Podfile and pulled in QBImagePickerController along with RSKImageCropper as the only two pods and everything is great.

**Comment by superandrew213** [comment]
Try removing & unlinking react-native-image-crop-picker and cocoa pods etc, everything.

Then:

1. npm i --save react-native-image-crop-picker
2. react-native link react-native-image-crop-picker
3. Add Embedded binaries

<img width="344" alt="f2e94b10-7394-11e6-9c56-c9a61642976a" src="https://cloud.githubusercontent.com/assets/13059204/18331836/34f5c364-75a5-11e6-8a12-36f9a3441e27.png">

**Comment by ivpusic** [comment]
@parkerdan stay with pods, as this is defenitely better way for this library to handle external dependencies. Will update readme for other people as well.

**Comment by parkerdan** [comment]
Any chance to throw in an option to resize multiple images?

**Comment by ivpusic** [comment]
@parkerdan I would say currently it is out of scope.

**Comment by parkerdan** [comment]
@ivpusic no worries.  I just accomplished this on my machine for iOS, about to try for android....although I've never "written" obj-c or java before, I have something working locally and the speed of the response is noticeably faster now.  I just added a resizeMultiple bool option and found a resizing function.   Great job on this package.

**Comment by ivpusic** [comment]
@parkerdan, I just added section about installing dependencies via cocoa-pods https://github.com/ivpusic/react-native-image-crop-picker#cocoapods-users

**Comment by ivpusic** [comment]
@rops, I will close this issue. Please check latest post-install instructions and try using latest lib version.

**Comment by ShuBuShao** [comment]
我遇到了这个问题 Failed to verify bitcode in QBImagePicker.framework/QBImagePicker
我通过 将项目的 build Settings -> Build Options -> Enable Bitcode 设置为no 解决了问题 , 打包成功

**Comment by roycclu** [comment]
@ShuBuShao 

Hi, having some problem here. But Build Settings -> Build Options -> Enable Bitcode 设置为no did not fix it. 

Any other suggestions?

**Comment by Y-JH** [comment]
我遇到了类似的问题，是接入顶象无感验证后出现的。报错：Failed to verify bitcode in DingxiangCaptchaSDK.framework/DingxiangCaptchaSDK: error: Cannot extract bundle
[解决了问题！](https://blog.csdn.net/junhuahouse/article/details/88953365)
