### ISSUE TITLE
[IOS] is there any chance i can openCamera and capture multiple time? (now just one time/ one image.)

### ISSUE THREAD

**Issue by ducpt2** [ivpusic/react-native-image-crop-picker#583]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.19.1
- react-native v0.48.3

### Platform
Tell us to which platform this issue is related
- iOS

### Expected behaviour
- openCamera can capture image mutilple time and i can open gallery on Camera Screen, when i press cancel button(want change name button to BACK), it return all image i capture.
- when capture image, image come to gallery, button show gallery show up right next to button capture (like android).

### Actual behaviour

- Capture one image and return one.

### Steps to reproduce

1.using openCamera

2. Capture image, show up screen OK or TryAgain.

3. Click OK return one image.

**Comment by ivpusic** [comment]
currently no
