### ISSUE TITLE
Dyld Error Message:   Library not loaded: @rpath/QBImagePicker.framework/QBImagePicker

### ISSUE THREAD

**Issue by fanzhiri** [ivpusic/react-native-image-crop-picker#584]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v^0.19.1
- react-native v0.52.0

### Platform
Tell us to which platform this issue is related

- iOS

### Expected behaviour

run well 

### Actual behaviour

crash down after run

### Steps to reproduce

1. react-native init Hello

2. yarn add react-native-image-crop-picker

3. react-native link

4.react-native run-ios

### Attachments log

I check the crash file

Time Awake Since Boot: 10000 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries
DYLD_FALLBACK_LIBRARY_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib
DYLD_ROOT_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot
DYLD_FALLBACK_FRAMEWORK_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks

Dyld Error Message:
  Library not loaded: @rpath/QBImagePicker.framework/QBImagePicker
xxxxxxxx
  Reason: image not found

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by ivpusic** [comment]
you are missing external libraries. Please follow https://github.com/ivpusic/react-native-image-crop-picker#post-install-steps
