### ISSUE TITLE
error: bundling failed: ambiguous resolution: module `/Users/**/index.js` tries to require `react-native`, but there are several files providing this module.

### ISSUE THREAD

**Issue by joaom182** [ivpusic/react-native-image-crop-picker#585]
### Version
react-native-image-crop-picker v0.19.1
react-native v0.52.0

### Platform
iOS

### Actual behaviour
On metro bundler
```
error: bundling failed: ambiguous resolution: module `/Users/**/index.js` tries to require `react-native`, but there are several files providing this module. You can delete or fix them: 

  * `/Users/**/ios/Pods/React/package.json`
  * `/Users/**/node_modules/react-native/package.json`
```

**Comment by amun1303** [comment]
The same to me

![image](https://user-images.githubusercontent.com/7189244/35189389-18e0926a-fe7c-11e7-900a-c300e1120470.png)

**Comment by ivpusic** [comment]
this is not issue related to this project

**Comment by mattop1709** [comment]
I am facing the same problem..

**Comment by rohan-jansen** [comment]
@joaom182 have you found a solution to your issue?

**Comment by Basavaraj-Tanikedar** [comment]
I have also facing same issue, please help me out this. Thanks

**Comment by liuwawa** [comment]
I have also facing same issue, please help me out this. Thanks

**Comment by joaom182** [comment]
This issue is related with .podfile, that's for some reason installs React as dependencies.
