### ISSUE TITLE
What is "Standardize multiple select" in the TO DO list?

### ISSUE THREAD

**Issue by palpatim** [ivpusic/react-native-image-crop-picker#586]
Regarding the TO DO list on the Readme: there are three items listed, one of which is "Standardize multiple select". I don't see an outstanding Issue for this, and I'm not sure how to interpret it. Does that mean the library doesn't handle multiple selection on all Android devices, or that its implementation needs reworking, or something else?

**Comment by ivpusic** [comment]
currently multiple select on android might not work on older devices as this feature is vendor specific. Better way would be to implement custom multiple selection which would work the same on all devices.
