### ISSUE TITLE
Change needed for gradle 3.0.1 compatibility

### ISSUE THREAD

**Issue by pacamara** [ivpusic/react-native-image-crop-picker#587]
### Version
- react-native-image-crop-picker v0.18.1 (but problem still exists in your latest version 0.19.1)
- react-native v0.51.0

### Platform
Android build of a downstream project on Ubuntu 16.04 LTS

### Expected behaviour
react-native-image-crop-picker uses gradle 3.0.1 compliant syntax and causes no build warning in downstream projects.

### Actual behaviour
A build warning in downstream projects is observed, due to react-native-image-crop-picker not using gradle 3.0.1 compliant syntax:
```
Configuration 'compile' in project ':react-native-image-crop-picker' is deprecated. Use 'implementation' instead.
```
Since `api` is recommended for library projects, suggest using that, rather than `implementation`.

### Steps to reproduce

1.Build downstream project https://github.com/status-im/status-react

2.Observe the above build warning.

### For further background
Please see issue https://github.com/status-im/status-react/issues/3037.

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by ivpusic** [comment]
can you send pr?

**Comment by pacamara** [comment]
@ivpusic Hi, we now realize doing this is a breaking change for new projects created with `react-native init`, unless [these manual changes](https://github.com/react-native-community/react-native-svg/issues/581#issuecomment-359201096) are made to the generated project. So we are going to wait for react-native to upgrade to gradle 3. Thanks!
