### ISSUE TITLE
Build failed, a problem occurred configuring project ':react-native-image-crop-picker'

### ISSUE THREAD

**Issue by tavriaforever** [ivpusic/react-native-image-crop-picker#588]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.19.1
- react-native v0.49.3

### Platform
Tell us to which platform this issue is related

- Android

### Expected behaviour

build success

### Actual behaviour

error while building

### Steps to reproduce

1. make install steps from README

2. run `react-native run-android`

### Attachments

// stacktrace or any other useful debug info

```
➜  ~/sites/atlantm/android git:(master) ✗ ./gradlew assembleRelease
Incremental java compilation is an incubating feature.
Checking the license for package Android SDK Build-Tools 27 in /Users/tavria/Library/Android/sdk/licenses
Warning: License for package Android SDK Build-Tools 27 not accepted.
Checking the license for package Android SDK Platform 27 in /Users/tavria/Library/Android/sdk/licenses
Warning: License for package Android SDK Platform 27 not accepted.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-image-crop-picker'.
      > You have not accepted the license agreements of the following SDK components:
        [Android SDK Build-Tools 27, Android SDK Platform 27].
        Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
        Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 10.771 secs
```

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by ivpusic** [comment]
please read error message, you will find answer there

**Comment by tavriaforever** [comment]
ok, I am ofcourse understood what error means, but react-native install tutorial says, that sdk version must be 23, not 27, if it compatible? @ivpusic

**Comment by tavriaforever** [comment]
So, I had a lot of errors after update sdk version, so I decided to return to 23 and choose 0.17.0
It is very strange change, because in README says https://github.com/ivpusic/react-native-image-crop-picker#android

Any suggestion?
