### ISSUE TITLE
something went wrong, can you help me

### ISSUE THREAD

**Issue by yangmc10086** [ivpusic/react-native-image-crop-picker#594]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.?.? download just now
- react-native v0.?.? 

### Platform
Tell us to which platform this issue is related
- Android

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-image-crop-picker'.
      > Could not resolve all dependencies for configuration ':react-native-image-crop-picker:_debugPublishCopy'.
         > Could not find com.github.yalantis:ucrop:2.2.1-native.
           Required by:
               crop_test:react-native-image-crop-picker:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by yangmc10086** [comment]
D:\test_myapp\AwesomeProject\node_modules\react-native-image-crop-picker\android\src\main\java\com\reactnative\ivpusic\imagepicker\PickerModule.java:31: 错误: 找不到符号
import com.facebook.react.modules.core.PermissionAwareActivity;
                                      ^
  符号:   类 PermissionAwareActivity
  位置: 程序包 com.facebook.react.modules.core
D:\test_myapp\AwesomeProject\node_modules\react-native-image-crop-picker\android\src\main\java\com\reactnative\ivpusic\imagepicker\PickerModule.java:32: 错误: 找不到符号
import com.facebook.react.modules.core.PermissionListener;
                                      ^
  符号:   类 PermissionListener
  位置: 程序包 com.facebook.react.modules.core
D:\test_myapp\AwesomeProject\node_modules\react-native-image-crop-picker\android\src\main\java\com\reactnative\ivpusic\imagepicker\PickerModule.java:49: 错误: PickerModule不是抽象的, 并且未覆盖ActivityEventListener中的抽象方法onActivityResult(int,int,Intent)
class PickerModule extends ReactContextBaseJavaModule implements ActivityEventListener {
^
D:\test_myapp\AwesomeProject\node_modules\react-native-image-crop-picker\android\src\main\java\com\reactnative\ivpusic\imagepicker\PickerModule.java:225: 错误: 找不到符号
            ((PermissionAwareActivity) activity).requestPermissions(missingPermissions.toArray(new String[missingPermissions.size()]), 1, new PermissionListener() {
                                                                                                                                              ^
  符号:   类 PermissionListener
  位置: 类 PickerModule
D:\test_myapp\AwesomeProject\node_modules\react-native-image-crop-picker\android\src\main\java\com\reactnative\ivpusic\imagepicker\PickerModule.java:225: 错误: 找不到符号
            ((PermissionAwareActivity) activity).requestPermissions(missingPermissions.toArray(new String[missingPermissions.size()]), 1, new PermissionListener() {
              ^
  符号:   类 PermissionAwareActivity
  位置: 类 PickerModule
D:\test_myapp\AwesomeProject\node_modules\react-native-image-crop-picker\android\src\main\java\com\reactnative\ivpusic\imagepicker\PickerModule.java:697: 错误: 方法不会覆盖或实现超类型的方法
    @Override
    ^
D:\test_myapp\AwesomeProject\node_modules\react-native-image-crop-picker\android\src\main\java\com\reactnative\ivpusic\imagepicker\PickerModule.java:708: 错误: 方法不会覆盖或实现超类型的方法
    @Override
    ^
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
7 个错误

**Comment by ivpusic** [comment]
please follow readme file, check android dependices section
