### ISSUE TITLE
can not select video from library IOS 11.

### ISSUE THREAD

**Issue by ccoeder** [ivpusic/react-native-image-crop-picker#595]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.16.1
- react-native v0.46.4

### Platform
Tell us to which platform this issue is related

- iOS

### Expected behaviour
Video selection from the library.

### Actual behaviour
When I select a video from the library, it says "processing assets..." and it stays there. nothing is happening and it does not give an error

### Steps to reproduce

1. Make the library video-selectable

2. Open app.

3. Choose video.

**Comment by ivpusic** [comment]
how big is video you are selecting? do you have some time to investigate this?

**Comment by ccoeder** [comment]
I have resolved this problem by downloading the npm packages again, I apologize.

**Comment by victormf123** [comment]
Hi Sirs, I'm having the same problem, even after I've downloaded npm packages, could you guys help me?

**Comment by ccoeder** [comment]
Hi @ victormf123, can you share the picker code?

**Comment by victormf123** [comment]
Hi @ccoeder good morning, here is the code:

`import React from "react";
import { AppRegistry, Alert, StyleSheet } from "react-native";
import { Container, Header, Left, Body, Title, Card, CardItem, Content, Right, Icon, Button, Text } from "native-base";
import { StackNavigator } from "react-navigation";
import ImagePicker from 'react-native-image-crop-picker';

export default class GerenciarVideosScreen extends React.Component {
  componentDidMount() {
    
  }
  render() {
    return (
      <Container>
        <Content padder style={styles.container}>
          
        </Content>
      </Container>
    );
  }
}
GerenciarVideosScreen.navigationOptions = ({ navigation }) => ({
  header: (
    <Header style={{ backgroundColor: '#fc5b07'}} titleStyle={{backgroundColor: 'transparent', color: '#fff'}}>
      <Left>
        <Button transparent onPress={() => navigation.navigate("DrawerOpen")}>
          <Icon name="menu"  style={{backgroundColor: 'transparent', color: '#fff'}}/>
        </Button>
      </Left>
      <Body>
        <Title style={{backgroundColor: 'transparent', color: '#fff'}}> Meus Videos </Title>
      </Body>
      <Right>
        <Button transparent
          onPress={() => {
              ImagePicker.openPicker({
                mediaType: "video",
              }).then((video) => {
                console.log('video', video);
              });
          } }  underlayColor="transparent">
          <Icon style={styles.icon} name="ios-add" />
        </Button>
      </Right>
    </Header>
  )
});
`

**Comment by L-Yeiser** [comment]
I am having the same issue. Have tried removing and reinstalling node_modules multiple times.

Device:
Iphone X

Package.json
```
"react-native": "^0.53.0",
"react-native-image-crop-picker":  "^0.20.0"
```

Code 
```
  selectImage() {
    ImagePicker.openPicker({
      multiple: true,
      mediaType: 'any',
    }).then((media: ImagePickerUpload[]) => {
      console.log(media);
      this.setState({
        ...this.state,
        media,
      });
    });
  }
```
