### ISSUE TITLE
can we write same functionality in single method  (for example  picking image from gallery or taking photo from camera)

### ISSUE THREAD

**Issue by atchuthsai468** [ivpusic/react-native-image-crop-picker#599]
can we write same functionality in single method for example  picking image from gallery or taking photo from camera
In this example  wrote two different methods(picking image from gallery or taking photo from camera)
pickSingleWithCamera(cropping) ->take photo from camera
pickSingle(cropit, circular = false) -> select image fromgallery
in react native image picker module single method is used

**Comment by ivpusic** [comment]
currently I have no plans to do it, but it should not be hard to implement something application-specific to handle this.
