### ISSUE TITLE
Possible Unhandled Promise Rejection Android 6.0

### ISSUE THREAD

**Issue by aspidvip** [ivpusic/react-native-image-crop-picker#603]
![error0](https://user-images.githubusercontent.com/22605655/35712615-9fff2eb4-080e-11e8-99c8-e42ec300bdb2.jpeg)
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.19.1
- react-native v0.49.5

### Platform
-Android

### Expected behaviour
`ImagePicker.openCamera({
         includeBase64: false,
        compressImageQuality: 0.5,
        mediaType: 'photo',
        }).then(image => {
        console.log(image);
        });`

### Steps to reproduce

1.

2.

3.

### Attachments

`D/EGL_emulation: eglMakeCurrent: 0xeaacd920: ver 2 0 (tinfo 0xed1dbd10)
D/EGL_emulation: eglMakeCurrent: 0xeaacd920: ver 2 0 (tinfo 0xed1dbd10)
D/EGL_emulation: eglMakeCurrent: 0xeaacd920: ver 2 0 (tinfo 0xed1dbd10)
D/EGL_emulation: eglMakeCurrent: 0xeaacd920: ver 2 0 (tinfo 0xed1dbd10)
D/EGL_emulation: eglMakeCurrent: 0xeaacd920: ver 2 0 (tinfo 0xed1dbd10)
D/EGL_emulation: eglMakeCurrent: 0xeaacd920: ver 2 0 (tinfo 0xed1dbd10)
D/EGL_emulation: eglMakeCurrent: 0xeaacd920: ver 2 0 (tinfo 0xed1dbd10)
I/art: Background partial concurrent mark sweep GC freed 52227(2MB) AllocSpace objects, 0(0B) LOS objects, 9% free, 38MB/42MB, paused 2.137ms total 110.076ms
D/EGL_emulation: eglMakeCurrent: 0xeaacd920: ver 2 0 (tinfo 0xed1dbd10)
D/EGL_emulation: eglMakeCurrent: 0xeaacd920: ver 2 0 (tinfo 0xed1dbd10)
E/Surface: getSlotFromBufferLocked: unknown buffer: 0xd929a500
D/EGL_emulation: eglMakeCurrent: 0xeaacd920: ver 2 0 (tinfo 0xed1dbd10)
D/EGL_emulation: eglMakeCurrent: 0xeaacd920: ver 2 0 (tinfo 0xed1dbd10)
E/Surface: getSlotFromBufferLocked: unknown buffer: 0xf40fc260
E/image-crop-picker: Promise rejected. User cancelled image selection
D/EGL_emulation: eglMakeCurrent: 0xeaacd920: ver 2 0 (tinfo 0xed1dbd10)
W/art: Suspending all threads took: 11.926ms
I/art: Background sticky concurrent mark sweep GC freed 91171(2MB) AllocSpace objects, 0(0B) LOS objects, 6% free, 44MB/47MB, paused 16.124ms total 156.045ms
W/ReactNativeJS: Possible Unhandled Promise Rejection (id: 0):
                 Error: User cancelled image selection
                 createErrorFromErrorData@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:5147:24
                 http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:5104:49
                 __invokeCallback@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:5457:21
                 http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:5250:31
                 __guard@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:5388:11
                 invokeCallbackAndReturnFlushedQueue@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:5249:20

`
![error222](https://user-images.githubusercontent.com/22605655/35712611-929b282c-080e-11e8-991e-750e6337964f.gif)

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by ivpusic** [comment]
you have to implement `.catch(() => { ... })`

**Comment by aspidvip** [comment]
thansk, is work!!!

**Comment by brmartins92** [comment]
> you have to implement `.catch(() => { ... })`

do you have some example ?

**Comment by KevinColemanInc** [comment]
@brmartins92 

```
ImagePicker.openCamera({
      width: 300,
      height: 300,
      cropping: true,
    }).then(image => {
      this.uploadImageBackground(image.path)
    }).catch((err) => { console.log("openCamera catch" + err.toString()) });
```

**Comment by AE0011** [comment]
@KevinColemanInc 
catch just avoid runtime error! the module still not working

**Comment by KevinColemanInc** [comment]
@AE0011 Yeah, I noticed that too. I still see it in my logs, but at least I don't have error notifications about it.

**Comment by eftikharEmad** [comment]
> you have to implement `.catch(() => { ... })`

it rescue the problem, but how to avoid it, I can't see any flag controls this functionality like `onCancle()` method example
