### ISSUE TITLE
how to change color and graphic layout and add my setting in ImagePicker.openCropper?

### ISSUE THREAD

**Issue by ali226281** [ivpusic/react-native-image-crop-picker#606]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.?.?
- react-native v0.?.?

### Platform
Tell us to which platform this issue is related

- iOS
- Android

### Steps to reproduce

1.

2.

3.

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by ivpusic** [comment]
you can check request object for customizing cropper https://github.com/ivpusic/react-native-image-crop-picker#request-object
