### ISSUE TITLE
Android multiple:true don't work

### ISSUE THREAD

**Issue by xuchao321** [ivpusic/react-native-image-crop-picker#607]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.?.?
- react-native v0.?.?

### Platform
Tell us to which platform this issue is related

- iOS
- Android

### Steps to reproduce

1.

2.

3.

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by xuchao321** [comment]
Android multiple: true

don't work

**Comment by ivpusic** [comment]
multiple selection depends on phone manufacturer and android version. If you have Android 5+ you will likely have this functionality. Just try long-pressing on image, and you will enter multiple-selection mode.

**Comment by xuchao321** [comment]
Just try long-pressing on image, and you will enter multiple-selection mode.  no response  thank you
