### ISSUE TITLE
Incomplete bit code when uploading to app store

### ISSUE THREAD

**Issue by superandrew213** [ivpusic/react-native-image-crop-picker#61]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.8.0
- react-native v0.32.0

### Steps to reproduce

1. Archive and upload to app store

### Attachments
<img width="870" alt="screen shot 2016-09-05 at 6 51 09 pm" src="https://cloud.githubusercontent.com/assets/13059204/18242518/18f4cef6-739a-11e6-95ce-948b695e143d.png">

**Comment by superandrew213** [comment]
Getting this now after cleaning, restarting, reinstalling, etc

<img width="877" alt="screen shot 2016-09-05 at 7 05 05 pm" src="https://cloud.githubusercontent.com/assets/13059204/18242944/097cd02a-739c-11e6-9c1a-c31bdd24ff4d.png">

**Comment by ivpusic** [comment]
you are getting this error because pre-built frameworks are built for simulator and device ARCHs. This is good for development because you don't have to worry about supported arch when building and running on different platforms. 

Before uploading to appstore, you have to strip away simulator platforms, and then use stripped versions of frameworks instead of current ones.

You can also remove current pre-built libraries for embedded binaries, and add the ones from `Libraries/imageCropPicker/Libraries/XXX/Product/XXX.framework` which will be there after you build project for specific platform.

**Comment by Mentioum** [comment]
@ivpusic could you give a step by step for this process as I'm having real trouble getting rid of this error.  It's definitely due to a misunderstanding of mine of how xcode works.

**Comment by ivpusic** [comment]
then probably latter will be easier for you. 

go to project General tab, scroll down to Embedded binaries. You will see that there are two pre-built frameworks. You can remove them, build project for Device => this will produce Frameworks built for Device platform. Click + under Embedded binaries, and now you can add these two frameworks.

<img width="344" alt="screen shot 2016-09-05 at 6 15 54 pm" src="https://cloud.githubusercontent.com/assets/450140/18253439/f2e94b10-7394-11e6-9c56-c9a61642976a.png">

Later probably you will want to switch back to pre-built frameworks because it is easier during development.

**Comment by superandrew213** [comment]
@ivpusic I'm still getting the same error if I do that.

**Comment by superandrew213** [comment]
This is what I did:

1. Completely remove react-native-image-crop-picker
2. Install and link react-native-image-crop-picker
3. Build for "Generic iOS Device"
4. Add the two frameworks from the libraries folder to  "Embedded Binaries"
5. Archive and upload

Before upload starts I get the same error in the first screenshot

**Comment by ivpusic** [comment]
can you go to Project -> Build Settings -> Enable Bitcode. Is it yes or no?

**Comment by superandrew213** [comment]
Yes, it's enabled.

**Comment by ivpusic** [comment]
hm, then would be cool if you can investigate what is happening. Maybe try flags/options from this link http://stackoverflow.com/questions/34959767/whats-the-difference-between-fembed-bitcode-and-bitcode-generation-mode. Probably for some reason bitcode is not included in built frameworks, and as you said your app has it, which is causing this incompatibility.

You can experiment by editing build options of each framework, build it and then link it with your app. Please keep me posted about progress here.

**Comment by superandrew213** [comment]
Have you been able to upload to itunesconnect yet?

**Comment by ivpusic** [comment]
nope, my personal project is still in development, so I didnt try upload yet.

**Comment by superandrew213** [comment]
Adding ```-fembed-bitcode ``` flag to frameworks fixes it.

**Comment by ivpusic** [comment]
great. will release new version with this fix.

**Comment by ivpusic** [comment]
@superandrew213 released in 0.8.1 https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.8.1

**Comment by superandrew213** [comment]
Great! thanks

**Comment by parkerdan** [comment]
@superandrew213, Have you released anything with this package?  This package works great on the simulator, but I put something on TestFlight and memory usage explodes when selecting photos with this...

**Comment by ivpusic** [comment]
@parkerdan what "memory usage explodes" means in your context? How much memory usage is increased? In my testings when running on device memory usage is ok. "Exploding" comes if I send base64 image data over the RN bridge, which is something you should generally avoid with react-native.

**Comment by parkerdan** [comment]
I love your work on being able to select multiple photos, and everything is great until the app is on the phone via TestFlight.  

My app is 80mb according to iOS Settings->General->Storage->Manage Storage.  My app got to 160mb after selecting a few photos with your package.  When I changed to react-native-image-picker, and added the same photos to the app, the memory was at 85mb.

**Comment by ivpusic** [comment]
@parkerdan did you use `includeBase64` for transferring image data?

**Comment by parkerdan** [comment]
Yes, i"m including base64.

**Comment by parkerdan** [comment]
@ivpusic, but I also get base64 from the other package without the memory increase....

**Comment by ivpusic** [comment]
sorry, I thought you were talking about RAM usage, but you are talking about disk usage? in that case reason why memory increases is because files are written to tmp location which is cleaned up automatically at some point. Maybe would be a good idea to export some cleanup function, so users can call it once they don't need file(s) anymore.

**Comment by parkerdan** [comment]
I would love a clean-up function.  Any idea how to go about that?

**Comment by ivpusic** [comment]
@parkerdan here you go https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.8.2

**Comment by superandrew213** [comment]
@parkerdan I delete images in temp folder as soon as I am done with them. You can use react-native-fs for that ```RNFS.unlink(path)```. 

@ivpusic it would be better to let react-native-fs handle that

**Comment by parkerdan** [comment]
@superandrew213, Thanks for the tip

**Comment by ivpusic** [comment]
@superandrew213 let't keep this option as well, because many people doesn't use fs package

**Comment by playing** [comment]
@ivpusic when add framework into  Embedded Binaries, you can use `add other` and add file in node_modules/react-native-crop-picker/ios/imageCropPickerSDK/xxx.framework, so you dont need to remove and add framework every time.

**Comment by sharingjingang050241** [comment]
@ivpusic hi,I have a question.When I click +  add RSKImageCropper.framework and QBImagePicker.framework under Embedded Binaries ,These were not add to Embedded Binaries.So,what should I do .Thanks

**Comment by ivpusic** [comment]
they should. Build your project first and then do steps you mentioned.

**Comment by sharingjingang050241** [comment]
thank u

**Comment by tavriaforever** [comment]
Hi! I tried to do everything that I found in this issue) But it`s not helped me. 

First of all I want to understand what means in README instruction
> If you are using pre-built frameworks from ios/ImageCropPickerSDK, then before deploying app to production you should strip off simulator ARCHs from these

What I should do?

Variant 2 
> or you can add frameworks from Libraries/imageCropPicker/Libraries/_framework_name_.xcodeproj/Products/_framework_name_.framework

okay, I read it many times. What I did:

![actxqvjuyc](https://user-images.githubusercontent.com/975906/29277309-f3132b40-8119-11e7-86c8-9d324356ed1a.gif)

How to upload archive
![2017-08-14_17-48-27](https://user-images.githubusercontent.com/975906/29276938-e251eb3a-8118-11e7-8fa2-214cf31d5951.png)

![monosnap 2017-08-14 17-50-55](https://user-images.githubusercontent.com/975906/29277039-2ce98180-8119-11e7-893f-fae7c204c9f5.png)

**Comment by ivpusic** [comment]
my best advice is to use cocoapods to manage QBImagePicker and RSKImageCropper dependencies. I uploaded app many times without any problems by using cocoapods.

**Comment by tavriaforever** [comment]
Unfortunately I couldn`t use cocoapods, because It conflict with libraries that I used, so after it I decided to install it manually. I feel the decision exist, but what wrong(

**Comment by tavriaforever** [comment]
ok, I will try

Podfile 
```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'palmy_mobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for palmy_mobile
  pod 'react-native-image-crop-picker', :path => '../node_modules/react-native-image-crop-picker'

end
```

run `pod install`

get an error 
```
➜  ~/sites/palmy_mobile/ios git:(dev) ✗ pod install
Analyzing dependencies
Fetching podspec for `react-native-image-crop-picker` from `../node_modules/react-native-image-crop-picker`
[!] No podspec found for `react-native-image-crop-picker` in `../node_modules/react-native-image-crop-picker`

[!] Automatically assigning platform ios with version 8.0 on target palmy_mobile because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
```

**Comment by hanishsharma** [comment]
@tavriaforever You have to create podspec  manually by using the  command to create podsec file.  You have to place this file in the root of this library. Then you can copy the code of this file from the git and paste it in this file, then run pod install again. It will work.

**Comment by Godlovekarl** [comment]
Can't support Chinese !🙃

**Comment by ShuBuShao** [comment]
我遇到了这个问题 Failed to verify bitcode in QBImagePicker.framework/QBImagePicker
我通过 将项目的 build Settings -> Build Options -> Enable Bitcode 设置为no 解决了问题 , 打包成功

**Comment by renso3x** [comment]
I highly recommend to use the pods it will lessen your config.

**Comment by roycclu** [comment]
hello, 
I used cocoapods, and did according to the instruction. Remove pre-built from embedded binaries, and then added them in from Libraries/imageCropPicker/Libraries/<package>/Products/<package>
But still get the following error: 
`
" UserInfo={NSLocalizedDescription=Failed to verify bitcode in QBImagePicker.framework/QBImagePicker:
error: Cannot extract bundle from /var/folders/wf/wxwbrgls6fg49tyhp_dx35cc0000gn/T/XcodeDistPipeline.HKc/Root/Payload/timecapsule.app/ImageCropPickerSDK/QBImagePicker.framework/QBImagePicker (x86_64)
`
Any idea how to solve this?

**Comment by roycclu** [comment]
@ShuBuShao 

Also tried toggling the Enable Bitcode to Yes, and then to No. 
Still getting this error:

`
Failed to verify bitcode in QBImagePicker.framework/QBImagePicker
`

Any other suggestions?

**Comment by bubuzzz** [comment]
I also have this issue with the latest version. Have no idea how to resolve it until I  **manually delete all the binary files, clean, clean build folder and archive project again**. Finally it worked.

**Comment by canastro** [comment]
I already have everything working properly on my dev environment. Now I want to upload it to testflight. I have a circle ci that will be triggered on push to master that will build the ipa and push it to testflight.

In order to not have to change my project manually every time I want to push to master (and trigger circle ci), I need to be able to delete these files before I start to build the IPA. 

> If you are using pre-built frameworks from ios/ImageCropPickerSDK, then before deploying app to production you should strip off simulator ARCHs from these,

This is not very clear for me. Which are the files I need to delete?

**Comment by codetay** [comment]
My problem was solved after i deleted the folder installed by the **Post-install steps 2**

**Comment by mayankbaiswar-CSE** [comment]
@canastro did you happen to solve "CFBundleIdentifier Collision"? I'm getting that too!

**Comment by mdio** [comment]
@mayankbaiswar-CSE I tried what @codetay suggested (removing the manually added reference to ImageCropPickerSDK in Xcode) and this solved the collision problem for me.

Also I took the script from https://github.com/oney/react-native-webrtc/blob/master/tools/ios_arch.js that @canastro mentioned and converted it into helper functions for [fastlane](https://fastlane.tools/).

```ruby
DEPENDENCIES_TO_STRIP = ['RSKImageCropper', 'QBImagePicker']

def strip_simulator_archs()
  archs_to_keep = ['armv7', 'armv7s', 'arm64']

  DEPENDENCIES_TO_STRIP.each { |dependency|
    Dir.chdir("../node_modules/react-native-image-crop-picker/ios/ImageCropPickerSDK/#{dependency}.framework") do
      sh("cp #{dependency} /tmp/#{dependency}")

      archs_to_keep.each { |arch|
        sh("lipo -extract #{arch} #{dependency} -o #{dependency}-#{arch}")
      }
      createParameters = archs_to_keep.reduce('') { |total, arch| "#{total} #{dependency}-#{arch}" }
      sh("lipo -o #{dependency} -create#{createParameters}")
      sh("rm #{dependency}-*")
    end
  }
end

def restore_simulator_archs()
  DEPENDENCIES_TO_STRIP.each { |dependency|
    Dir.chdir("../node_modules/react-native-image-crop-picker/ios/ImageCropPickerSDK/#{dependency}.framework") do
      sh("mv /tmp/#{dependency} #{dependency}")
    end
  }
end
```

In our release lane, `strip_simulator_archs` is called before and `restore_simulator_archs` after `gym`.
That way you don't have to fiddle around to have both a working simulator build and one for TestFlight.

**Comment by umut885** [comment]
> Adding `-fembed-bitcode` flag to frameworks fixes it.

excuse me, where exactly i do have to put this flag? Could provide a detailed instruction?

**Comment by mieszko4** [comment]
I am a bit confused about `Production build` step for non-pod installation.

I followed all steps for non-pod including post-install (adding `RSKImageCropper.framework` and `QBImagePicker.framework` manually) and I run it in simulator - all worked well.
Then I archived the apk and sent it to testflight, installed it from testflight - that also all worked well.

I am using `xcode 10`, `RN 0.57`, deployment target `9.0`,  `iOS 12.1.2` and no pods.
I use `react-native-crop-picker@0.21.3` to take a picture and to select from library then I send its base64 to my server.

Is striping away simulator platforms still a required step?

**Comment by douglasjunior** [comment]
I also can't use cocoapods, so here is the setup process that woked for me.

1. Install the `react-native-image-crop-picker`
1. `react-native link react-native-image-crop-picker`
1. Select `Generic iOS Device` as a target
1. Menu `Product -> Clean` and then `Product -> Build`.
1. Go to the folder `/Users/<user>/Library/Developer/Xcode/DerivedData/<app-name>/Build/Products/Debug-iphoneos`.
1. Copy the `QBImagePicker.framework` and `RSKImageCropper.framework` to your `project/ios` folder and drag and drop both as *Embedded binaries*.
1. Archive and Upload 🎉

**Comment by paolospag** [comment]
@douglasjunior @mieszko4 
So, having followed the installation step without Cocapoads (manual installation), can I avoid the production step?

With ```QBImagePicker.framework``` and ```RSKImageCropper.framework``` in ```Embedded Binaries``` and with Debug scheme my app works well, but I'm uploading it on TestFlight and I would like to understand if I have to do production step or not.

**Comment by douglasjunior** [comment]
Following my steps you are ready for development and production.

**Comment by douglasjunior** [comment]
After **step 4** the compiled `frameworks` are generated on `step 5` folder. You need to copy them to your `<project>/ios` folder, and then link both as **Embedded binaries**.

**Comment by mieszko4** [comment]
That's the point - I did not embed binaries from derived folder (i.e. I did not do steps 5 and 6).
I just followed the initial instructions on `README.md` and it worked for me both on simulator and testflight and I am just confused why. I will recheck this.

**Comment by mieszko4** [comment]
Please mind I am not an expert in iOS stuff.
I rechecked this and I did:
* `rm -fr /Users/mieszko4/Library/Developer/Xcode/DerivedData`
* `rm -fr ./node_modules`
* `npm ci`
* I opened the project (I have no cocoapod) in xcode, I set target as `Generic iOS Device`
* I cleaned the project
* I went to `General` tab and under `Embeded Binaries` I pressed `+` and I chose `RSKImageCropper.framework` and `QBImagePicker.framework` (they were automatically expanded and located under `Libraries/imageCropPicker/Libraries/_framework_name_.xcodeproj/Products/_framework_name_.framework`)

After adding them I've noticed that their paths are taken from `DerivedData` folder, i.e. `/Users/mieszko4/Library/Developer/Xcode/DerivedData/NAMEOFPROJECT-gyhgygejsxewwjakamghtszkqurn/Build/Products/Debug-iphoneos/QBImagePicker.framework`. This path points to no file though.

I archived the app and sent to the store - no problem.
I installed the app on Testflight and it is all good.

After that I changed target to `iPhone XR`, I built it and run on simulator - again it is all good.

**This is why I am confused why there is additional step for production only as it seems that the post-install ios Step 2 automatically does what needs to be done for production.**

**Comment by paolospag** [comment]
@mieszko4 oh sure, I'm little bit confused.
I probably didn't do all your steps, but having installed everything manually (without Cocoapods), I fully followed all the steps explained in the section **Post-install steps** (https://github.com/ivpusic/react-native-image-crop-picker#post-install-steps) for iOS and it works fine, both debug and release. I also tried with TestFlight.

I also find ```RSKImageCropper.framework``` and ```QBImagePicker.framework``` under ```Libraries/imageCropPicker/Libraries/_framework_name_.xcodeproj/Products/_framework_name_.framework``` (automatically located here).

I have this situation in Xcode:
![imagecroppicker-xcode](https://user-images.githubusercontent.com/35046292/52481055-bfe05f00-2bad-11e9-9b0c-7107f5463d1e.jpg)

So, why does it work anyway?
Is **Production build** (https://github.com/ivpusic/react-native-image-crop-picker#production-build) still necessary? @ivpusic

**Comment by douglasjunior** [comment]
@paolospag you need to **copy and paste** the compiled frameworks to your `<project>/ios`, and then link the frameworks from `<project>/ios` to **Embbeded binaries**.

**Comment by liuyunzyj** [comment]
@douglasjunior  Why is mine still not working? Is there any missing steps?
![image](https://user-images.githubusercontent.com/40293335/61840820-0f4cea00-aec5-11e9-925c-6549d870f679.png)
![image](https://user-images.githubusercontent.com/40293335/61840937-7cf91600-aec5-11e9-86c4-4cbe9bf0d3b0.png)
![image](https://user-images.githubusercontent.com/40293335/61840978-a023c580-aec5-11e9-83fb-1c770401e745.png)

**Comment by liuyunzyj** [comment]
@danilobuerger 
![image](https://user-images.githubusercontent.com/40293335/61841926-f8a89200-aec8-11e9-8f03-9815df0dc1c0.png)

![image](https://user-images.githubusercontent.com/40293335/61841966-183fba80-aec9-11e9-9829-59e7cda7d149.png)

**Comment by sivasankarchimata** [comment]
Can i use react-native-image-crop-picker with  expo ,

**Comment by balwinder4264** [comment]
img is file 
const { stream, filename } = await img;

stream is undefined but showing filename. 
Anybody know how to get stream from image

FrontEnd :ReactNative
Backend :Nodejs Apollo Boost
