### ISSUE TITLE
linker error after every cloning my project

### ISSUE THREAD

**Issue by bodaghialib4** [ivpusic/react-native-image-crop-picker#612]
Version:

- react-native-image-crop-picker v0.19.1
- react-native v0.51.0

 Platform:
- iOS

after installing according to:
https://github.com/ivpusic/react-native-image-crop-picker/blob/master/README.md

every time I clone my project and doing:
npm install

I got below error (for "react-native run-ios"):

```
ld: library not found for -limageCropPicker
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

and after reinstall image-crop-picker it work correctly.

What is the mistake?
Is it necessary to install  image-crop-picker every time I clone my project?

**Comment by ivpusic** [comment]
if you followed installation steps you should not see that. It looks like a linking a library failed for some reason. I suggest that when you run `react-native link` check console logs for any errors.

**Comment by bodaghialib4** [comment]
I linked manually and it worked.
thanks.
