### ISSUE TITLE
Crop Border Square

### ISSUE THREAD

**Issue by faketon** [ivpusic/react-native-image-crop-picker#614]
- react-native-image-crop-picker v0.19.2
- react-native v0.50.0

- OS android

I want to show only circle overlay.
How to remove border this squre ?

![screenshot_1518594164](https://user-images.githubusercontent.com/7258598/36192734-73cd7086-1195-11e8-9e90-ee73c6842b20.png)

**Comment by faketon** [comment]
i found setShowCropFrame in uCrop. 
can you add this option ?

**Comment by ivpusic** [comment]
do you have some time to submit a pull request for this feature?

**Comment by NikolaRavic** [comment]
Hey @ivpusic, can you add setFreeStyleCropEnabled, I saw it in uCrop and tried it in local. It worked. I think it is a very nice feature to have, to be able to crop custom rectangle area. I can submit pull request if you think that it will not break something maybe?

**Comment by ivpusic** [comment]
`setFreeStyleCropEnabled` is now merged. @faketon currently I don't have plans to introduce it, but I would accept PR from you.
