### ISSUE TITLE
Not working on XCode 9.0

### ISSUE THREAD

**Issue by Rahulgupta-cdnsol** [ivpusic/react-native-image-crop-picker#615]
### Version
Tell us which versions you are using: 

- Latest version

### Platform
Tell us to which platform this issue is related

- iOS

### Expected behavior
It should work with XCode 9.0.

### Actual behavior
When I compile my code on XCode 9.0 it gives following errors : 
<unknown>:0: error: module 'RSKImageCropper_Image' in AST file '/Users/rahulgupta/Library/Developer/Xcode/DerivedData/ModuleCache/2EULDJZJZX2KQ/RSKImageCropper_Image-2NQ69W8TZTQ8S.pcm' (imported by AST file '/Users/rahulgupta/Library/Developer/Xcode/DerivedData/Build/Intermediates/PrecompiledHeaders/PhotoSpring-Bridging-Header-swift_2QOWEZD7Q1FAT-clang_2EULDJZJZX2KQ.pch') is not defined in any loaded module map file; maybe you need to load '/Users/rahulgupta/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphoneos/RSKImageCropper/RSKImageCropper.framework/Modules/module.modulemap'?
<unknown>:0: note: imported by '/Users/rahulgupta/Library/Developer/Xcode/DerivedData/Build/Intermediates/PrecompiledHeaders/PhotoSpring-Bridging-Header-swift_2QOWEZD7Q1FAT-clang_2EULDJZJZX2KQ.pch'
<unknown>:0: error: clang importer creation failed

Please let me know what changes need to do.

Thanks,
Rahul

**Comment by ivpusic** [comment]
sorry, but I cannot reproduce the error. Could you please follow each step from readme file and make sure all of them pass?

**Comment by ivpusic** [comment]
new version is released https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.20.0. Please follow installation instructions
