### ISSUE TITLE
react-native link not working !!! builds fails But run

### ISSUE THREAD

**Issue by Arshiamidos** [ivpusic/react-native-image-crop-picker#616]
### Version
Xcode 9.0

- react-native-image-crop-picker v0.26.7
- react-native-cli: 2.0.1
- react-native: 0.53.0

### Platform
- iOS
### Expected behaviour
build must be success

### Actual behaviour
RSKImageCropper,QBImagePicker not found folder, when i build;
build fails but it will be run on simulator 
Cannot read property 'match' of undefined 'error' in 'react-native link'

### Steps to reproduce

1.access for camera granted
2.copy sdk to my_project /ios
3.pods installation compelet
4.add frameworks to binary

**Comment by ivpusic** [comment]
hmm, it looks like installation somehow failed. Could you please try to repeat installation steps and check for any errors during that?

**Comment by Arshiamidos** [comment]
i added NSCameraUsageDescription and NSMicrophoneUsageDescription
also pod init and paste this text and install 
`platform :ios, '9.0'

target 'final' do
    pod 'RSKImageCropper'
    pod 'QBImagePickerController'
end`
after install and add dependencies (said above)
its says famous error message in react native termial that `the dependency has error match`
after i searched in xcode i found out that it's has a problem with linker -o with this 2 librarys
i use xcode 9.0 also my simulator is 9.3 
may it has problem with version ?

**Comment by Arshiamidos** [comment]
ld: warning: directory not found for option '-L/Users/macuser/Library/Developer/Xcode/DerivedData/final-gupqqmxbakvbendislxrmkqwkixn/Build/Products/Debug-iphonesimulator/QBImagePickerController'
ld: library not found for -lQBImagePickerController
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Arshiamidos** [comment]
builds fails but any change on js will affect on simulator !!
so when i want add maps on my RN  i must reinit my project and add this reinstall crop-image !!

**Comment by soroushchehresa** [comment]
this issue is happening when don't take completely step 2 of Post-install steps.
manual install not working and you can only use Cocoapods.
after install pod and take steps for resolve this error **open your-project.xcworkspace file with xcode and run project from here**.

NOTE:
your-project.xcworkspace file created after take step 2 of Post-install steps completely in ios folder of your project.

**Comment by ivpusic** [comment]
new version released and updated installation instructions https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.20.0

**Comment by imspikey** [comment]
I get this error when deploying to device after following manual installation 
 
"framework not found RSKImageCropper"

**Comment by Arshiamidos** [comment]
maybe you installed **manually** and cocopods(**pods**) together

**Comment by s349856186** [comment]
@Arshiamidos  if installed **manually** and cocopods(**pods**) together，and get framework not found  lQBImagePickerController, how to fix it? Thanks

**Comment by Arshiamidos** [comment]
i suggest to reinstall fresh again.  
it's better to clean your cocopods with remove pod files/folder and lnstall again from instruction.
