### ISSUE TITLE
Cannot upload images in IOS Simulator

### ISSUE THREAD

**Issue by suryaadtmaja** [ivpusic/react-native-image-crop-picker#622]
### Version
![screen shot 2018-02-23 at 15 06 10](https://user-images.githubusercontent.com/7471695/36584315-c8345eb0-18ab-11e8-899b-db39e0b7a901.png)

- react-native-image-crop-picker ^0.19.3
- react-native 0.48.4

### Platform
Tell us to which platform this issue is related

- iOS

### Expected behaviour
i'm expecting it can be uploaded images from Camera Roll

### Actual behaviour
it always sends can't connect to the server, please check your internet connection, 
there's no problem with my internet connection, but every time I'm trying to upload images from camera roll in ios simulator, it's always an error, idk why, in android it's working fine.

**Comment by suryaadtmaja** [comment]
i'm sorry screenshot is in indonesia language, it's mean can't connect to the server, please check your internet connection.

**Comment by ivpusic** [comment]
this may be related to other code in your app. This module does not even try to use internet connection.
