### ISSUE TITLE
Cropping Page open twice, onActivityResult way execute twice

### ISSUE THREAD

**Issue by ljmkimqx** [ivpusic/react-native-image-crop-picker#623]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.19.3
- react-native v0.48.4
- Android 7.0

### Platform
Tell us to which platform this issue is related

- Android

### Expected behaviour

open cropping page once, and click cancel don‘t crash ( iOS no problem)

### Actual behaviour

open cropping page twice, and click cancel will crash

### Steps to reproduce

1. execute the code:   ImagePicker.openPicker(options).then(callback).catch((error) => { console.log('issues', error); });

2. the cropping page opened cropping page twice when I selecting a image. 

3. app will crash when I click Android back button.

I find:
react-native-image-crop-picker/src/main/java/com.reactnative.ivpusic.imagepicker/PickerModule
the 'onActivityResult' way will execute twice when I selecting a image

code:
![2018-02-24 1 34 38](https://user-images.githubusercontent.com/30502832/36626098-85f0b7c6-1967-11e8-9b78-8013488abbe7.png)

log:
<img width="866" alt="2018-02-24 1 30 23" src="https://user-images.githubusercontent.com/30502832/36626104-8e5cc062-1967-11e8-8d7a-cc196deeaa22.png">

### Attachments

![androidsure](https://user-images.githubusercontent.com/30502832/36626021-d0dd0390-1965-11e8-8c7c-96921956b3d0.gif)

crash code:
![2018-02-24 1 37 13](https://user-images.githubusercontent.com/30502832/36626130-e46cfa58-1967-11e8-8de9-bff3744c0e97.png)

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by tourze** [comment]
same problem + 1

**Comment by ljmkimqx** [comment]
has anybody can help?

**Comment by ljmkimqx** [comment]
a super man help me resolved it.

**Comment by ljmkimqx** [comment]
it is my error.I had resolved it.
check android 'MainActivity' file, 
way:
public void onActivityResult(int requestCode, int resultCode, Intent data){
        super.onActivityResult(requestCode, resultCode, data);
        // avoid repeated calls onActivityResult
        // getReactInstanceManager().onActivityResult(this, requestCode, resultCode, data);  // the problem source
    }

**Comment by anastasia-son** [comment]
> it is my error.I had resolved it. check android 'MainActivity' file, way: public void onActivityResult(int requestCode, int resultCode, Intent data){ super.onActivityResult(requestCode, resultCode, data); // avoid repeated calls onActivityResult // getReactInstanceManager().onActivityResult(this, requestCode, resultCode, data); // the problem source }

thanks, I had the same issue and same problem
