### ISSUE TITLE
Use of undeclared identifier 'PHAssetCollectionSubtypeSmartAlbumDepthEffect'

### ISSUE THREAD

**Issue by wikieswan** [ivpusic/react-native-image-crop-picker#624]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.19.1
- react-native v0.50

### Platform
Tell us to which platform this issue is related

- iOS

### Expected behaviour
BUILD FAILED！

### Actual behaviour

`/node_modules/react-native-image-crop-picker/ios/ImageCropPicker.m:296:66: Use of undeclared identifier 'PHAssetCollectionSubtypeSmartAlbumDepthEffect'; did you mean 'PHAssetCollectionSubtypeSmartAlbumGeneric'?`

### Steps to reproduce

1. run `react-native run-ios` but failed

error msg:

    /Users/wan-mac/www/syzs/repos/syzs_app/node_modules/react-native-image-crop-picker/ios/ImageCropPicker.m:296:66: error: use of undeclared identifier 'PHAssetCollectionSubtypeSmartAlbumDepthEffect'; did you mean 'PHAssetCollectionSubtypeSmartAlbumGeneric'?
                                                  @"DepthEffect" : @(PHAssetCollectionSubtypeSmartAlbumDepthEffect),
                                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                     PHAssetCollectionSubtypeSmartAlbumGeneric
    In module 'QBImagePicker' imported from /Users/wan-mac/www/syzs/repos/syzs_app/node_modules/react-native-image-crop-picker/ios/ImageCropPicker.h:25:
    In module 'Photos' imported from /Users/wan-mac/www/syzs/repos/syzs_app/ios/build/Build/Products/Debug-iphonesimulator/QBImagePicker.framework/Headers/QBImagePickerController.h:10:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.1.sdk/System/Library/Frameworks/Photos.framework/Headers/PhotosTypes.h:78:5: note: 'PHAssetCollectionSubtypeSmartAlbumGeneric' declared here
        PHAssetCollectionSubtypeSmartAlbumGeneric    = 200,
        ^
    /Users/wan-mac/www/syzs/repos/syzs_app/node_modules/react-native-image-crop-picker/ios/ImageCropPicker.m:297:65: error: use of undeclared identifier 'PHAssetCollectionSubtypeSmartAlbumLivePhotos'; did you mean 'PHAssetCollectionSubtypeSmartAlbumVideos'?
                                                  @"LivePhotos" : @(PHAssetCollectionSubtypeSmartAlbumLivePhotos),
                                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                    PHAssetCollectionSubtypeSmartAlbumVideos
    In module 'QBImagePicker' imported from /Users/wan-mac/www/syzs/repos/syzs_app/node_modules/react-native-image-crop-picker/ios/ImageCropPicker.h:25:
    In module 'Photos' imported from /Users/wan-mac/www/syzs/repos/syzs_app/ios/build/Build/Products/Debug-iphonesimulator/QBImagePicker.framework/Headers/QBImagePickerController.h:10:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.1.sdk/System/Library/Frameworks/Photos.framework/Headers/PhotosTypes.h:80:5: note: 'PHAssetCollectionSubtypeSmartAlbumVideos' declared here
        PHAssetCollectionSubtypeSmartAlbumVideos     = 202,
        ^
    /Users/wan-mac/www/syzs/repos/syzs_app/node_modules/react-native-image-crop-picker/ios/ImageCropPicker.m:298:63: error: use of undeclared identifier 'PHAssetCollectionSubtypeSmartAlbumAnimated'
                                                  @"Animated" : @(PHAssetCollectionSubtypeSmartAlbumAnimated),
                                                                  ^
    /Users/wan-mac/www/syzs/repos/syzs_app/node_modules/react-native-image-crop-picker/ios/ImageCropPicker.m:299:67: error: use of undeclared identifier 'PHAssetCollectionSubtypeSmartAlbumLongExposures';
     did you mean 'PHAssetCollectionSubtypeSmartAlbumTimelapses'?
                                                  @"LongExposure" : @(PHAssetCollectionSubtypeSmartAlbumLongExposures),
                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                      PHAssetCollectionSubtypeSmartAlbumTimelapses
    In module 'QBImagePicker' imported from /Users/wan-mac/www/syzs/repos/syzs_app/node_modules/react-native-image-crop-picker/ios/ImageCropPicker.h:25:
    In module 'Photos' imported from /Users/wan-mac/www/syzs/repos/syzs_app/ios/build/Build/Products/Debug-iphonesimulator/QBImagePicker.framework/Headers/QBImagePickerController.h:10:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.1.sdk/System/Library/Frameworks/Photos.framework/Headers/PhotosTypes.h:82:5: note: 'PHAssetCollectionSubtypeSmartAlbumTimelapses' declared here
        PHAssetCollectionSubtypeSmartAlbumTimelapses = 204,
        ^
    /Users/wan-mac/www/syzs/repos/syzs_app/node_modules/react-native-image-crop-picker/ios/ImageCropPicker.m:302:32: warning: unused variable 'album' [-Wunused-variable]
                    for (NSString* album in [self.options objectForKey:@"smartAlbums"]) {
                                   ^
    1 warning and 4 errors generated.

    ** BUILD FAILED **

![65 pic_hd](https://user-images.githubusercontent.com/7147483/36629946-c5d5bdce-1998-11e8-89ed-ce3ef659345f.jpg)

I need some help, Thanks!

**Comment by ivpusic** [comment]
which ios version you are targeting?

**Comment by wikieswan** [comment]
@ivpusic  ios 8

**Comment by rf1804** [comment]
same issue

**Comment by s349856186** [comment]
same issue

**Comment by pranav-pandey** [comment]
+1, using v0.19.3

**Comment by gaoxiaosong1113** [comment]
hi，这里报错的问题应该是几个参数未定义

**Comment by mairi17** [comment]
Same issue, target iOS 10, also v0.19.3

**Comment by luqmanrom** [comment]
I had the same issues. Solved it by upgrading my XCode from version 8.3.2 to version 9.2

**Comment by rf1804** [comment]
Just update Xcode to version 9.2 it will resolve this error
after that if u get RCTBridge and RCTBridgeModule error in libraries expand ImageCropPicker.xcodeproj and in all the file find import of respective Bridge and BridgeModule and just replace it with #import <React/RCTBridge.h> and #import <React/RCTBridgeModule.h>

**Comment by alzalabany** [comment]
@rf1804 i cannot upgrade xcode, is there any solution for thiss on xcode 8 ?

**Comment by rf1804** [comment]
@alzalabany i didn't found any other solution, i found a solution to upgrade xcode to 9.2 so i did that and it worked

**Comment by codingplayboy** [comment]
killed this error through downgrade this plugin to version 0.18.2.
