### ISSUE TITLE
Unable to deploy app to Testflight

### ISSUE THREAD

**Issue by joaom182** [ivpusic/react-native-image-crop-picker#626]
### Version
Tell us which versions you are using:

- react-native-image-crop-picker v0.19.1
- react-native v0.52.0

### Platform
Tell us to which platform this issue is related

- iOS

### Expected behaviour
1. Install lib and install with cocoa pods
2. Submit the app to Testflight, you are done just as the README instructs.

### Actual behaviour
The app is submited to testflight, but iTunes throws the error:
*Invalid Bundle* - One or more dynamic libraries that are referenced by your app are not present in the dylib search path. 
When i remove completely `react-native-image-crop-picker` iTunes validate the build.

I'm using Podfile, when i run app with XCode, app runs normaly, but when i run with `react-native run-ios` app crash on startup. So I manualy add `RSKImageCropper.framework` and `QBImagePickerController.framework` to Embedded Binaries, and run again with `react-native run-ios` app runs normaly, but when i try publish to Testflight, throws the same error of issue `https://github.com/ivpusic/react-native-image-crop-picker/issues/61`

**Comment by ivpusic** [comment]
please try latest version. I updated installation instructions https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.20.0

**Comment by mehrapratham** [comment]
I am getting same error. please help me
