### ISSUE TITLE
set Flash mode to On or Off

### ISSUE THREAD

**Issue by a3diti** [ivpusic/react-native-image-crop-picker#628]
I think its possible to implement the flash mode from openCamera options, after reviewing code on:
[https://github.com/react-native-community/react-native-camera/blob/master/ios/RN/RNCamera.m#L127](https://github.com/react-native-community/react-native-camera/blob/master/ios/RN/RNCamera.m#L127)

Can anyone contribute from this source code?

**Comment by ivpusic** [comment]
currently out of scope, but I would accept PR
