### ISSUE TITLE
ld: framework not found QBImagePickerController

### ISSUE THREAD

**Issue by AlmogRnD** [ivpusic/react-native-image-crop-picker#629]
I'm getting the following build error when I compile my project/app in xcode 

ld: framework not found QBImagePickerController

- "react-native-image-crop-picker": "^0.18.2",
- "react-native": "^0.53.3",

### Platform
iOS

**Comment by ivpusic** [comment]
probably linking with external dependencies failed. Make sure that react-native link runs without errors, and that you add required pods. https://github.com/ivpusic/react-native-image-crop-picker#install-package

**Comment by AlmogRnD** [comment]
@ivpusic why did you close this, I have pods installed correctly and I run react-native link and I'm still getting this error 
<img width="819" alt="screen shot 2018-03-05 at 8 57 47 am" src="https://user-images.githubusercontent.com/169507/36951084-50379940-2053-11e8-8376-cf8f5b2af007.png">

And I ran pod install

**Comment by EricCarrGH** [comment]
I've seen this happen when you open the xcodeproj file instead of the workspace. Make sure you are opening the project.cxworkspace file.
