### ISSUE TITLE
When is the [Android] Standardize multiple select complete?

### ISSUE THREAD

**Issue by wfxphoebus** [ivpusic/react-native-image-crop-picker#630]
Can you give me a plan?

**Comment by ivpusic** [comment]
currently multiple selection does not work on some android devices because stock multi-select option is used (if available at all). On most of devices after Android 5+ works without problems.

**Comment by miguelespinoza** [comment]
Looks like this was closed a while back, @ivpusic is there a fallback solution for these versions of Android?
If less than Android 5 are we falling back to single-select support?
