### ISSUE TITLE
When I click to select a picture, how do I call the album directly, just like react-native-image-picker calls the photo album and file selection directly.

### ISSUE THREAD

**Issue by mvpdream** [ivpusic/react-native-image-crop-picker#631]
When I click to select a picture, how do I call the album directly, just like react-native-image-picker calls the photo album and file selection directly.
![tim 20180304193403](https://user-images.githubusercontent.com/16203724/36945071-76949324-1fe3-11e8-81cc-5199ad07bc3c.png)
![tim 20180304193445](https://user-images.githubusercontent.com/16203724/36945072-76cc926a-1fe3-11e8-853c-faf72018db84.png)
![tim 20180304193456](https://user-images.githubusercontent.com/16203724/36945073-77027bc8-1fe3-11e8-82cc-e62d3c27aaee.png)

**Comment by ivpusic** [comment]
currently this is not supported

**Comment by ChristopherGillis** [comment]
https://github.com/ivpusic/react-native-image-crop-picker/issues/1081
