### ISSUE TITLE
up to appStore Error : ERROR ITMS-90087 QBImagePicker.framework contains unsupported architectures '[x86_64, i386]'

### ISSUE THREAD

**Issue by cantianshu** [ivpusic/react-native-image-crop-picker#632]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v"^0.19.0",
- react-native v"0.50.4",

### Platform
Tell us to which platform this issue is related

- iOS

### Steps to reproduce

1.
ERROR ITMS-90087: "Unsupported Architectures. The executable for aaa.app/Frameworks/QBImagePicker.framework contains unsupported architectures '[x86_64, i386]'."
		ERROR ITMS-90087: "Unsupported Architectures. The executable for aaa.app/Frameworks/RSKImageCropper.framework contains unsupported architectures '[x86_64, i386]'."

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by ivpusic** [comment]
are you using cocoapods?

**Comment by ivpusic** [comment]
please use cocoapods. I also updated installation instructions and added support for podspec https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.20.0

**Comment by gyyxiaogao** [comment]
<img width="688" alt="e10ae505deb014bcb894059119d11fcb" src="https://user-images.githubusercontent.com/16957066/41447423-c976169a-7087-11e8-9f33-a05f26a8971b.png">
I don't use cocoapods
