### ISSUE TITLE
formdata not being recieved at node .

### ISSUE THREAD

**Issue by kiranbabu189** [ivpusic/react-native-image-crop-picker#634]
This is how I'm appending a file to formdata ,
`formdata.append("profileImage", { uri: image.path, name: 'image.jpg', type: 'image/jpeg'})`

my request using fetch : 
```
fetch(url", {
                body: formdata,
                method: "POST",
                headers: {
                    'Content-Type': 'multipart/form-data; '
                }
            })

```
but at my endpoint im getting undefined when i read req.body

**Comment by abdul-elah-js** [comment]
how did you solve this ?

**Comment by EugeValeiras** [comment]
How did you resolved it??? @kiranbabu189
