### ISSUE TITLE
'RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by Zidail** [ivpusic/react-native-image-crop-picker#637]
### Version
- react-native-image-crop-picker v0.20.0
- react-native v0.51.0

### Platform

- iOS

### Expected behaviour

Links properly with no files missing.

### Actual behaviour

Gives a `Lexical or Preprocessor Issue` with `'RCTBridgeModule.h' file not found`.

### Steps to reproduce

1. Follow instructions in the current readme using Cocoapods.

Additional Notes: 
 * React is added via npm rather than pods.
 * Did not use `react-native link`
 * Already using XCWorkspace as I already have other pods in use.
 * Only added `pod "RNImageCropPicker", path: "../node_modules/react-native-image-crop-picker"
` to `Podfile`. (`:path => ` is equivalent to `path:`).

### Attachments

![Error](https://user-images.githubusercontent.com/9337042/37024517-0f568686-2164-11e8-8a15-9068fee564f2.png)

**Comment by ivpusic** [comment]
you have to add

```
  rn_path = '../node_modules/react-native'

  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]
```

later you exclude it from the build anyway with

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
```

**Comment by Zidail** [comment]
AH! Thank you for answering me so quickly, @ivpusic 
Everything works now.
