### ISSUE TITLE
Whats happend with image-crop-picker ?( Why it became fails an build( ios ) and upload to appStore ?

### ISSUE THREAD

**Issue by mastersam92** [ivpusic/react-native-image-crop-picker#638]
### Version
- react-native-image-crop-picker v0.19.0, v0.20.0
- react-native v0.54.0

### Platform
- iOS

### Expected behaviour

Building & archieving normally. Without some errors on appStore uploading( such as unsupported architecture etc )

### Actual behaviour

Any errors, that unable to be corrected 

### Steps to reproduce

1. Install & link

2. Try Archieve & upload to AppStore

3. Enjoy the list of the strange errors

**Comment by mastersam92** [comment]
Solved( problem with architecture etc. It took about 1 day for solve ) with next steps:
( for prod )

1. Delete QBImagePicker.framework & RSKImageCropper.framework from project( in XCode ) with "move to trash"

2. Check  & Del( if exists ) this 2 fw from dir (project)/ios

3. Check  & Del( if exists ) this 2 fw from dir (project)/ios/ios/ImageCropPickerSDK

4. Check  & Del( if exists ) this 2 fw from dir (project)/node_modules/react-native-image-crop-picker/ios/ImageCropPickerSDK


( in XCode ) 
5. (menu)Product -> Clean

6. Check  & Del( if exists ) this 2 fw from General -> Embedded Binaries

6. Set Generic iOS Device ( for prod:) )

7. (menu)Product -> Build

8. Now, add fresh frameworks to project: 
 ( in left panel, that shows project tree. Go to & drag fresh framework to General -> Embedded Binaries )
 8. 1. Libraries / imageCropPicker.xcodeproj / Libraries / QBImagePicker.xcodeproj / Products / QBImagePicker.framework
 8.2 Libraries / imageCropPicker.xcodeproj / Libraries / RSKImageCropper.xcodeproj / Products / RSKImageCropper.framework


It's strange, that it took so many time and that this wasn't compiled good( on iOS ) from the first time.. In previous project( few month ago ), there was no problems with version 0.19.0.. 

But, in any case, great thank for you project & please a little bit more npm/yarn, which are much more convenient and versatile than Cocoapods for dev on Android+iOS.

**Comment by ivpusic** [comment]
glad to hear it works now for you. However, I recommend using cocoapods. Then you don't have any of these issues.
