### ISSUE TITLE
Got warning when upload then press hardware back button

### ISSUE THREAD

**Issue by wzy535** [ivpusic/react-native-image-crop-picker#64]
### Version

- react-native-image-crop-picker v0.7.0
- react-native v0.31.0

### Actual behaviour
when I click upload button ,then I cancelled to select photo.
And I got warning bellow:

### Steps to reproduce

1.click upload button
2.don't select photos 
3.click hardware back button

Thanks in advance!
### Attachments
<image src="http://www.saitio.com/images/QQ20160908142613.png" />

**Comment by ivpusic** [comment]
put .catch to your openPicker call
