### ISSUE TITLE
iPhone hangs on processing assets when uploading vidoes

### ISSUE THREAD

**Issue by L-Yeiser** [ivpusic/react-native-image-crop-picker#642]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker ^0.20.0
- react-native 0.53.0

### Platform
Tell us to which platform this issue is related

- iOS
- Android

### Actual behaviour
Uploading a video on an iphoneX hangs on processing assets. Works on the IOS simulator and on android devices.

### Steps to reproduce

1. Open image picker.

2. Select a video from the camera roll.

3. Process hangs.

No errors are logged.

code: 
```
 selectImage() {
    ImagePicker.openPicker({
      multiple: true,
      mediaType: 'any',
    }).then((media: ImagePickerUpload[]) => {
      console.log(media);
      this.setState({
        ...this.state,
        media,
      });
    });
  }
```

**Comment by L-Yeiser** [comment]
As a follow up. I do not have this issue with an iphone 6 nor an iphone 7.

**Comment by ivpusic** [comment]
do you have some time to investigate what is happening here?

**Comment by L-Yeiser** [comment]
I am under a pretty strict deadline at the moment and am pretty new to react-native so do not have the time or resources to really dig in. If I find time this weeks I will see what I can come up with.

**Comment by L-Yeiser** [comment]
Our team has sunk a bit of time into this and come up empty handed. Other then knowing it is an IOS 11+ issue. We thought it had to do with an `invalid response for blob type` error but that was fixed with `RN 0.55` but that is not the case. For now we are using `react-native-image-picker` when a user is running IOS 11 + but it would be awesome to get this library working with newer IOS.

**Comment by L-Yeiser** [comment]
This issue was resolved when we upgraded to
`react-native 0.55.0`
`react-native--image-crop-picker 0.20.3`

**Comment by chrisbobbe** [comment]
I can confirm that I **only** have this issue when I set `multiple: true` **and** I try to select multiple videos.

**Comment by liuyunzyj** [comment]
Has anyone come across this problem?
![image](https://user-images.githubusercontent.com/40293335/61839310-afa01000-aebf-11e9-8041-05c5960b4e9b.png)
![image](https://user-images.githubusercontent.com/40293335/61839337-c21a4980-aebf-11e9-9fd3-eb8b643bad86.png)

**Comment by Bashamd455** [comment]
Hi @chrisbobbe, Even I am facing the same issue i.e., iPhoneX taking forever to process a video when selecting from the camera roll.
**versions I am using in the application:**
react-native-image-crop-picker ^0.21.1
react-native 0.56.0
