### ISSUE TITLE
Not working in react native expo

### ISSUE THREAD

**Issue by Mubashir1044** [ivpusic/react-native-image-crop-picker#643]
### Version
Tell us which versions you are using: 

"axios": "^0.18.0",
    "expo": "^25.0.0",
    "react": "16.2.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz",
"react-native-image-crop-picker":"0.20.0"
### Platform

 Expected behaviour
Pick multiple images

 Actual behaviour
showing error which is:
 Undefined is not an object (Eveluating '_react_NativeImageCropPicker2.default.openPicker

**Comment by ivpusic** [comment]
expo is not supported https://github.com/ivpusic/react-native-image-crop-picker/issues/627

**Comment by arnoldbird** [comment]
How could expo not be supported?  Expo is react native.

**Comment by paul019** [comment]
@ivpusic @arnoldbird Is Expo Kit supported?

**Comment by Dolla123** [comment]
hello I have using **react-native-image-cropper** in my project and I have installed **gl-react-native** also. but  **react-native-image-cropper** this is not working in expo. Is there has any alternative?
