### ISSUE TITLE
Custom metadata with images

### ISSUE THREAD

**Issue by amitbravo** [ivpusic/react-native-image-crop-picker#644]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.19.1
- react-native v0.53.3

### Platform
Tell us to which platform this issue is related

- iOS
- Android

### Expected behaviour
I am building a group communication system using firebase as backend. I use react-native-image-crop-picker to select images. images are sent to server and then cloud function is executed to create different thumbnail sizes for multiple files , after thumbnail generation , thumbnail url is created which should be keep in database at specific locations ( updating in the timeline of users who are participating that chat).   I can not tell the function where to update so I have to send some userid and path locations into the filename e.g. 8958178179@8998998@..... .jpg , can I send many userID with somekind of custom metadata where we can access and process it in cloud function ? I am using Sharp as a thumbnail generator in cloud function https://www.npmjs.com/package/sharp .

**Comment by ivpusic** [comment]
sounds like a something what is not supported, unfortunately
