### ISSUE TITLE
Error when trying to get image from Google Drive

### ISSUE THREAD

**Issue by theohdv** [ivpusic/react-native-image-crop-picker#645]
### Version

- react-native-image-crop-picker v0.20.0
- react-native v0.54.1

### Platform

- Android 7.0
- Real device

### Expected behaviour

Should return file path after selection.

### Actual behaviour

With the file picker, when I try to get a image from my google drive, an exception is thrown: "Error: Cannot resolve asset path."

### Steps to reproduce

1. Open android image picker

2. Open the left menu, click on drive and select an image.

### Attachments

<img width="541" alt="screen shot 2018-03-13 at 19 09 09" src="https://user-images.githubusercontent.com/26060802/37361081-4e03c4a0-26f2-11e8-88b8-a9f8f8161fdf.png">

### EDIT (14-03-18):
I've investigated and found that path is always null for cloud file (Android). I'm actually working on a PR.

**Comment by theohdv** [comment]
Create PR #650

**Comment by theohdv** [comment]
Maintaining a [fork](git@github.com:theohdv/react-native-image-crop-picker.git) with this feature and iCloud support.

**Comment by isaachinman** [comment]
@theohdv Is there any update on this, to your knowledge? Why hasn't this been merged?

I just hit this issue with my QA team. How has there only been a single person to discover/work on this bug, for a lib with over 2k stars...? Seems very strange.

**Comment by theohdv** [comment]
Fix with #650
