### ISSUE TITLE
Thumbnail generation

### ISSUE THREAD

**Issue by amitbravo** [ivpusic/react-native-image-crop-picker#646]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.19.1
- react-native v0.53.3

### Platform
Tell us to which platform this issue is related

- iOS
- Android

### Expected behaviour

I am using react-native-image-crop-picker for image selection and then I upload it on firebase storage , then I allow cloud function to trigger and generate a thumbnail for the image , I am using npm sharp for thumbnail generation but it takes very very long time , around 10 seconds and as my app is real time chat system , it does not feel good. I was convinced that thumbnail generation at mobile app puts negative impact on App performance thats why I used cloud function to take care of thumbnail but I want to replace it with something better option , can react-native-image-crop-picker provides some kind of thumbnail generation , is there any trick to use it ? I am thinking something like if one image is selected by react-native-image-crop-picker , it creates two instances one for thumbnail and another for main file ? did anyone use anything like that ?

### Steps to reproduce

1.

2.

3.

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by ivpusic** [comment]
currently this is out of scope, but 10 seconds for thumbnail generation sounds very wrong. I suggest that you revisit your code for thumbnail generation, and also check if there are some issues with the library you are using regarding the performance.

**Comment by superandrew213** [comment]
10 seconds is pretty long for sharp to resize your image. Are you including upload time?

You can easily generate thumbnails using `react-native-image-resizer` if you want to generate thumbnails locally.

**Comment by amitbravo** [comment]
@superandrew213 no I am not including upload time. Actually 8 minutes last time I checked. 8-10 seconds take time to execute function. I am sorry I am asking this out of scope here. thanks anyway for react-native-image-resizer suggestion though.
