### ISSUE TITLE
openCropper------>crash 

### ISSUE THREAD

**Issue by nextdooroldwang** [ivpusic/react-native-image-crop-picker#648]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker "^0.19.3"
- react-native "0.53.0"

### Platform
Tell us to which platform this issue is related

- Android

### Expected behaviour

![i 8 2pq9e81azxozu8 f96k](https://user-images.githubusercontent.com/18671240/37451654-20dad26c-286d-11e8-8e35-dba2c0b5a039.jpg)

### Steps to reproduce

1.openCropper

2.crash

**Comment by ivpusic** [comment]
do you have some time to investigate?
