### ISSUE TITLE
Error : cleanSingle is not a function

### ISSUE THREAD

**Issue by Nicolas-Menettrier** [ivpusic/react-native-image-crop-picker#65]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.8.0
- react-native v0.30.0

### Expected behaviour
Delete one image, the other method like openPicker work.

EDIT : clean don't work too.

### Actual behaviour
I have : _reactNativeImageCropPicker2.default.cleanSingle is not a function
![cleansingle](https://cloud.githubusercontent.com/assets/17987207/18351372/373e60ce-75da-11e6-8d28-9f2cf5c26c1b.jpg)

![deletephoto](https://cloud.githubusercontent.com/assets/17987207/18351439/7980e182-75da-11e6-85c9-ec9f797eb82c.jpg)

**Comment by ivpusic** [comment]
upgrade to https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.8.2
