### ISSUE TITLE
how to remove the permission asking pop-up?

### ISSUE THREAD

**Issue by harikrishnanssomdev** [ivpusic/react-native-image-crop-picker#661]
- react-native-image-crop-picker 0.19.3
- react-native 0.54.0
hi guys this is not an issue but i wanna get some help, actually i want to turn off permission asking pop-up  when using react-native-image-crop-picker which i think does not give a native feel. So is there any way for removing the permission(while opening picker) asking pop-pup?

**Comment by ivpusic** [comment]
this is default OS behavior. The user has to grant permission in order to see/take the photos.
