### ISSUE TITLE
directory not found for option

### ISSUE THREAD

**Issue by doukegithub** [ivpusic/react-native-image-crop-picker#665]
- react-native-image-crop-picker v0.20.0
- react-native v0.53.3

- iOS

Showing Recent Issues
ld: warning: directory not found for option '-L/Users/doukekeji/Library/Developer/Xcode/DerivedData/urologist-edhmotuwalzphlcxrahcgfhquggt/Build/Products/Debug-iphoneos/React'

**Comment by doukegithub** [comment]
I solved

**Comment by linhnh123** [comment]
@doukegithub I have the same error, how to solve ?
