### ISSUE TITLE
Add a getImage method

### ISSUE THREAD

**Issue by isaachinman** [ivpusic/react-native-image-crop-picker#671]
Hello again!

I am wondering what the owners/contributors think about adding a static method to simply read files from disk, eg `ImagePicker.getImage` or similar.

This library actually provides a lot of valuable information like bytes, image dimensions, and exif data. I have set up share receiving in my application, and have to use `react-native-fetch-blob` and a few other utils just to gather the same data.

I'm imagining that this method would return exactly the same sort of response that `openPicker` does.

**Comment by ivpusic** [comment]
sounds good. Are you interested in sending a pull request with such a feature?

**Comment by isaachinman** [comment]
Hi @ivpusic, I'm very new to this codebase so I wouldn't know where to start. If you can point me in the right direction, and if this doesn't require in-depth platform-specific knowledge, I would very gladly handle it.

**Comment by ivpusic** [comment]
sure. For ios the main file is https://github.com/ivpusic/react-native-image-crop-picker/blob/master/ios/src/ImageCropPicker.m, and for the android https://github.com/ivpusic/react-native-image-crop-picker/blob/master/android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java.

**Comment by ivpusic** [comment]
will close this issue for now. Please open a PR if you have some progress here.
