### ISSUE TITLE
select file will occor "Invalid image selected"

### ISSUE THREAD

**Issue by LuvSnow** [ivpusic/react-native-image-crop-picker#673]
### Version

- react-native-image-crop-picker v0.20.1
- react-native v0.54.2

### Platform

- Android

### Actual behaviour

When I select a file, such as xxx.txt, it will callback an error like 

    Error: Invalid image selected
        at createErrorFromErrorData
        at MessageQueue.__invokeCallback
        at MessageQueue.__guardSafe 
        at MessageQueue.invokeCallbackAndReturnFlushedQueue

Here is code

    selectFile() {
        ImagePicker.openPicker({
            cropping: false
        }).then(data => {
            console.log(data);
        }).catch(err => {
            console.log(err);
        });
    }

maybe I run it at simulator is the reason?

PS: I am chinese student, but my english is not so good, so....

**Comment by zhenghow93** [comment]
@LuvSnow 你好。不晓得你是否已经解决了这个问题，我也遇到了类似的问题... 如果你有了解决方案，麻烦你分享以下。谢谢你。

**Comment by AibiTi** [comment]
@zhenghow93

fuck you.

Stupid, this is `image-crop-picker`, which supports the selection of images or video files, and others report errors.
