### ISSUE TITLE
IOS Export archive failed 

### ISSUE THREAD

**Issue by ngtlin** [ivpusic/react-native-image-crop-picker#674]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.19.3
- react-native v0.50.4

### Platform
- iOS

### Expected behaviour

Output IPA

### Actual behaviour
XCode export archive failed. 
The log reveals following: 
 description = "Failed to verify bitcode in QBImagePicker.framework/QBImagePicker:\nerror: Cannot extract bundle from /var/folders/v8/czpspl811t1cwg38shzwt25r0000gn/T/IDEDistributionOptionThinning.9Hv/Payload/bonbon.app/ImageCropPickerSDK/QBImagePicker.framework/QBImagePicker (x86_64)\n\n";
            info =             {
            };
            level = ERROR;
            type = "malformed-payload";
        },
                {
            code = 0;
            description = "Failed to verify bitcode in RSKImageCropper.framework/RSKImageCropper:\nerror: Cannot extract bundle from /var/folders/v8/czpspl811t1cwg38shzwt25r0000gn/T/IDEDistributionOptionThinning.9Hv/Payload/bonbon.app/ImageCropPickerSDK/RSKImageCropper.framework/RSKImageCropper (x86_64)\n\n";
            info =             {
            };
            level = ERROR;
            type = "malformed-payload";
        }

### Steps to reproduce

1.

2.

3.

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by ivpusic** [comment]
RSKImageCropper is not used anymore. please try latest version with TOCropViewController
