### ISSUE TITLE
ImagePicker  is undefined

### ISSUE THREAD

**Issue by KumikoYYC** [ivpusic/react-native-image-crop-picker#676]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker  ^0.20.1
- react-native v0.55.2

### Platform
Tell us to which platform this issue is related
- Android

### Actual behaviour

import ImagePicker , but ImagePicker is undefined

### Steps to reproduce

1. import ImagePicker from 'react-native-image-crop-picker';

2. console.log(ImagePicker);

3. ImagePicker is undefined

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by MarkOSullivan94** [comment]
I was experiencing the same issue. Make sure you have correctly imported the package and then make sure to include `new PickerPackage()` in your `List<ReactPackage> getPackages()` method in your App class.

**Comment by ivpusic** [comment]
@KumikoYYC this looks like an installation issue. Please try the suggestion from @MarkOSullivan94, and carefully read all installation instructions from the readme file.
