### ISSUE TITLE
Linker command failed with exit code 1

### ISSUE THREAD

**Issue by jemise111** [ivpusic/react-native-image-crop-picker#691]
Having some trouble installing using the Cocoapod steps.

I'm getting "clang: error: linker command failed with exit code 1 (use -v to see invocation)"

I've tried what you suggested here: #633 
I also have not used the `react-native link` command at all.

Not sure what the problem is, I have other libraries installed using Cocoapods and they are linking fine. Any help would be much appreciated!

### Version
- react-native-image-crop-picker v0.20.1
- react-native v0.51.0

### Platform
- iOS

**Comment by jemise111** [comment]
Oops nevermind! Issue with an unrelated pod..

**Comment by ZeroCool00** [comment]
i also have a same problem.. but when i remove this library from pod and from xcode.. error solved..
how to use this library without having this error.
