### ISSUE TITLE
How to resolve QBImagePickerController dependency ?

### ISSUE THREAD

**Issue by rengasahusoft** [ivpusic/react-native-image-crop-picker#7]
> Unable to find a specification for `QBImagePickerController (= 3.4.0)` depended upon by `react-native-image-crop-picker

**Comment by ivpusic** [comment]
follow discussion here https://github.com/ivpusic/react-native-image-crop-picker/issues/6#issuecomment-222650760

does it work now?

**Comment by rengasahusoft** [comment]
No 

what i have done is added  podspec file in 
 > picker/node_modules/react-native-image-crop-picker/ios/react-native-image-crop-picker.podspec
it doesn't work

when i gave pod search QBImagePickerController it show as below

> Aerolitec-QBImagePickerController (1.0.0)
   A clone of QBImagePickerController (v2.2.2) with multiple selection support.
   pod 'Aerolitec-QBImagePickerController', '~> 1.0.0'
   - Homepage: https://github.com/Aerolitec/QBImagePickerController
   - Source:   https://github.com/Aerolitec/QBImagePickerController.git
   - Versions: 1.0.0 [master repo]

**Comment by rengasahusoft** [comment]
Dependency got installed  somehow  - network issue i think,,
but 
import ImagePicker from 'react-native-image-crop-picker';

ImagePicker is undefined and nativemodules doesn't have this ImageCropPicker

**Comment by ivpusic** [comment]
you should follow instructions from here https://github.com/ivpusic/react-native-image-crop-picker/issues/6#issuecomment-222647477

when you run pod install make sure there is not warnings => if you are getting inherited flag warning you should fix it

**Comment by rengasahusoft** [comment]
Perfectly Working after resolving the inherited flag warning

Thanks
