### ISSUE TITLE
Does it support compress photo ??

### ISSUE THREAD

**Issue by RocWangv** [ivpusic/react-native-image-crop-picker#70]
Hi !  Nice library !!!
Does it support compress photo ?

**Comment by rahulnakate7** [comment]
I am also facing same issue, not able to reduce the size of image,if anyone knows how to reduce the size of image please let me know

**Comment by ivpusic** [comment]
nope at the moment

**Comment by ivpusic** [comment]
on ios side, there is `UIImageJPEGRepresentation` which could be used for compression. Right now the quality level is set to 1 (best). On android side something like this is missing. 

If you have time to implement feature like this, definitely +1 from my side
