### ISSUE TITLE
how to show guideline in crop screen ios

### ISSUE THREAD

**Issue by taeyzzz** [ivpusic/react-native-image-crop-picker#701]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker : "0.20.1"
- react-native : 0.55.4

### Problem
it's good for android. there  is grid guide line for cropping image, but in ios there is no grid guide line for cropping .
So, How to show grid cropping guide line in IOS platform

Thank you.

these are screen capture

<img width="387" alt="screen shot 2561-05-17 at 11 51 52 am" src="https://user-images.githubusercontent.com/32537120/40157469-7010e082-59c9-11e8-8eea-57462323065f.png">
<img width="386" alt="screen shot 2561-05-17 at 11 51 44 am" src="https://user-images.githubusercontent.com/32537120/40157471-72c02ffe-59c9-11e8-8257-fb81d006489e.png">

**Comment by ivpusic** [comment]
this is not possible currently in ios

**Comment by taeyzzz** [comment]
Can you explain why is it impossible?

**Comment by ivpusic** [comment]
cropping guidelines are present in the android because cropping library which is used there is ucrop. On ios, we use a different library which does not support guidelines.
