### ISSUE TITLE
Feature Request - Convert Live Photos to Stills

### ISSUE THREAD

**Issue by SonnyBrooks** [ivpusic/react-native-image-crop-picker#707]
### Version

- react-native-image-crop-picker v0.19.3
- react-native v0.53.3

### Platform

- iOS

### Expected behaviour

When live photos are selected, they are converted to a still format such as `jpg` or `png`.

### Actual behaviour

When live photos are selected, they are `mp4`. 

### Steps to reproduce

1. Select live photo. Check file type, it will be `mp4`.

### Use Case
APIs that my app works with only accepts still image formats. Unfortunately, Live Photos are of type `mp4`. That'd be awesome if `react-native-image-crop-picker` could handle the conversions on its own.

**Comment by migue1s** [comment]
Addressed in #791. This PR adds a "forceJPG" flag which will convert Live -> Still photos

**Comment by SonnyBrooks** [comment]
Closed with #791
