### ISSUE TITLE
Android Build Failed

### ISSUE THREAD

**Issue by ChinaTang** [ivpusic/react-native-image-crop-picker#713]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker ^0.20.3
- react-native 0.50.3

### Platform
Tell us to which platform this issue is related
- Android

rootProject.name = 'FinancialManager'
include ':react-native-image-crop-picker'
project(':react-native-image-crop-picker').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-image-crop-picker/android')
include ':react-native-fs'
project(':react-native-fs').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-fs/android')
include ':react-native-spinkit'
project(':react-native-spinkit').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-spinkit/android')
include ':react-native-device-info'
project(':react-native-device-info').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-device-info/android')

include ':app'

Error:Could not find com.android.support:appcompat-v7:27.1.0.
Required by:
    FinancialManager:app:unspecified
    FinancialManager:app:unspecified > com.facebook.react:react-native:0.54.0

Please install the Android Support Repository from the Android SDK Manager.
<a href="openAndroidSdkManager">Open Android SDK Manager</a>

**Comment by BachirKhiati** [comment]
It clearly says:
Error:Could not find com.android.support:appcompat-v7:27.1.0.
try to add this to your project build Gradle:
 
allprojects {  
    repositories {  
        jcenter()  
        maven {  
            url "https://maven.google.com"  
        }  
    }  
}

**Comment by ivpusic** [comment]
you are missing repos in build.gradle. Please follow instructions from here https://github.com/ivpusic/react-native-image-crop-picker#android-1

**Comment by ChinaTang** [comment]
Use Android SDK >= 26 (android/app/build.gradle)
android {
    compileSdkVersion 27
    buildToolsVersion "27.0.3"
    ...
    
    defaultConfig {
      ...
      targetSdkVersion 27
      ...
    }
    ...
}
Can we change the compileSdkVersion of our project?

this is my gradle version
apply plugin: "com.android.application"
apply plugin: 'com.neenbedankt.android-apt'
import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
    entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"




/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

android {
    signingConfigs {
        debug {
            keyAlias 'indu'
            keyPassword 'indu8888'
            storeFile file('../induRelease.jks')
            storePassword 'indu8888'
        }
    }
    compileSdkVersion 27
    buildToolsVersion "27.0.3"
    defaultConfig {
        applicationId "com.indu"
        minSdkVersion 16
        targetSdkVersion 27
        versionCode 1
        versionName "1.0.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }

        vectorDrawables.useSupportLibrary = true
        multiDexEnabled true

        manifestPlaceholders = [qqappid: "tencent1106792195"]

    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "armeabi"
        }
    }
    /*signingConfigs {
        debug {
            storeFile file('induRelease')
            storePassword "indu8888"
            keyAlias "indu"
            keyPassword "indu8888"
        }
    }*/
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    packagingOptions {
        exclude 'META-INF/rxjava.properties'
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a": 1, "x86": 2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
    dexOptions {
        javaMaxHeapSize "4g"
    }
    /*----------------------------------渠道包配置------------------------------------*/
    productFlavors {
        yd001{}
        yd002{}
        yd003{}
        yd004{}
        yd005{}
        yd006{}
        yd007{}
        yd008{}
        yd009{}
        yd010{}
        yd011{}
        yd012{}
        yd013{}
        yd014{}
        yd015{}
        yd016{}
        yd017{}
        yd018{}
        yd019{}
        yd020{}

        in001{}
        in002{}
        in003{}
        in004{}
        in005{}
        in006{}
        in007{}
        in008{}
        in009{}
        in010{}
        in011{}
        in012{}
        in013{}
        in014{}
        in015{}
        in016{}
        in017{}
        in018{}
        in019{}
        in020{}
        official{}


    }
    productFlavors.all { flavor ->
        flavor.manifestPlaceholders = [UMENG_CHANNEL_VALUE: name]
    }
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            def outputFile = output.outputFile
            if (outputFile != null && outputFile.name.endsWith('.apk')) {
                def fileName = outputFile.name.replace(".apk", "-${defaultConfig.versionName}.apk")
                output.outputFile = new File(outputFile.parent, fileName)
            }
        }
    }
    /*----------------------------------渠道包配置------------------------------------*/
}

dependencies {
    compile project(':react-native-spinkit')
    compile project(':react-native-fs')
    compile project(':react-native-image-crop-picker')
    compile project(':react-native-device-info')
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:23.0.1'
    compile 'com.facebook.react:react-native:+'

    // From node_modules

    /*===========================第三方依赖==========================*/
    compile 'com.github.hotchemi:permissionsdispatcher:3.0.1'

    //apt 'com.github.hotchemi:permissionsdispatcher-processor:2.1.3'
    apt "com.github.hotchemi:permissionsdispatcher-processor:3.0.1"

    //http

    //Retrofit
    compile 'com.squareup.retrofit2:retrofit:2.3.0'
    compile 'com.squareup.retrofit2:adapter-rxjava:2.0.2'

    //GSON
    compile 'com.squareup.retrofit2:converter-gson:2.0.2'

    //请求日志
    compile 'com.squareup.okhttp3:logging-interceptor:3.8.1'
    compile 'com.squareup.okhttp3:okhttp:3.8.1'

    //RXjava
    compile 'io.reactivex:rxandroid:1.2.0'

    //Rxjava专门针对anroid封装的RxAndroid

    //compile 'io.reactivex:rxjava:1.1.5'

    //七鱼
    compile 'com.qiyukf.unicorn:unicorn:+'

    //图片加载框架
    compile 'com.squareup.picasso:picasso:2.5.2'

    //bugly
    compile 'com.tencent.bugly:crashreport:latest.release'

    //其中latest.release指代最新Bugly SDK版本号，也可以指定明确的版本号，例如2.1.9
    compile 'com.tencent.bugly:nativecrashreport:latest.release'

    //其中latest.release指代最新Bugly NDK版本号，也可以指定明确的版本号，例如3.0

    /*---------------------------------友盟 推送------------------------------------------*/

    //PushSDK必须依赖基础组件库，所以需要加入对应依赖
    compile 'com.umeng.sdk:common:1.5.0'

    //PushSDK必须依赖utdid库，所以需要加入对应依赖
    compile 'com.umeng.sdk:utdid:1.1.5.3'

    //PushSDK
    compile 'com.umeng.sdk:push:4.1.0'

    /*---------------------------------友盟------------------------------------------*/

    /*---------------------------------友盟分享------------------------------------------*/

    /*---------------------------------友盟------------------------------------------*/
    compile project(':react-native-vector-icons')
    compile files('src/libs/open_sdk_r5990_lite.jar')
    compile files('src/libs/umeng-common-1.5.1.jar')
    compile files('src/libs/umeng-debug-1.0.0.jar')
    compile files('src/libs/umeng-share-core-6.9.1.jar')
    compile files('src/libs/umeng-share-QQ-full-6.9.1.jar')
    compile files('src/libs/umeng-share-wechat-full-6.9.1.jar')
    compile files('src/libs/umeng-sharetool-6.9.1.jar')
    compile files('src/libs/wechat-sdk-android-without-mta-5.1.4.jar')
    compile files('src/libs/umeng-share-QQ-simplify-6.9.1.jar')
    compile files('src/libs/umeng-share-wechat-simplify-6.9.1.jar')
    compile files('src/libs/umeng-shareboard-widget-6.9.1.jar')
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}
