### ISSUE TITLE
Error processing request body: Error Domain=NSCocoaErrorDomain Code=257

### ISSUE THREAD

**Issue by ricardomalagon** [ivpusic/react-native-image-crop-picker#714]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.19.1?
- react-native v0.52?

### Platform
Tell us to which platform this issue is related

- iOS

**This is only for videos so my insue is if i put the video.path to upload the error disappear but have a bad bad quality but i i put the video.sourceURL show this error and the sourceURL have the best quality.**

i have this code:

![captura de pantalla 2018-05-25 a la s 10 41 24 a m](https://user-images.githubusercontent.com/19271573/40550480-3308fc84-6008-11e8-8144-c436a274c68f.png)

and give me this error

![img_0555](https://user-images.githubusercontent.com/19271573/40550751-071a8f1a-6009-11e8-9c29-9b82bd5e8e12.PNG)

**Comment by ivpusic** [comment]
you can use compressVideoPreset option to set better quality anf then use video.path for upload

**Comment by ivpusic** [comment]
it will still go through some compression...sourceURL you cannot use to upload files
