### ISSUE TITLE
Feature Request - Convert HEIC/HEIF to Compatible formats

### ISSUE THREAD

**Issue by SonnyBrooks** [ivpusic/react-native-image-crop-picker#720]
### Version

- react-native-image-crop-picker v0.19.3
- react-native v0.53.3

### Platform

- iOS 11

### Expected behaviour

When taking/selecting photos with iOS device, get the JPG/PNG version of the photo instead.

### Actual behaviour

Photo is taken/selected and is of file type HEIC/HEIF

### Steps to reproduce

1. Take photo running iOS 11+

2. Check file type

**Comment by robertvorthman** [comment]
Try setting `forceJpg:true`, then when you get the image response back, use the `path` property instead of `sourceURL` to get the jpg.  `sourceURL` will be the original HEIC.

**Comment by SonnyBrooks** [comment]
Thank you!

**Comment by ajfick** [comment]
Is there any known solution for this when using the base64 data from the image?
