### ISSUE TITLE
Multiple pictures can be selected under the document

### ISSUE THREAD

**Issue by xiaoxiaoyongPersonal** [ivpusic/react-native-image-crop-picker#721]
### Version
- react-native-image-crop-picker v0.20.0
- react-native v0.55.4?
### Platform
- Android
### Expected behaviour
Multiple pictures can be selected under the album

### Actual behaviour
You can't choose a number of pictures in the album, but
Multiple pictures can be selected under the document

**Comment by ivpusic** [comment]
currently, this is behavior which is vendor/android version dependent, because built-in gallery view is used.
