### ISSUE TITLE
Display image preview in component

### ISSUE THREAD

**Issue by mxdi9i7** [ivpusic/react-native-image-crop-picker#727]
### Version
Tell us which versions you are using: 

^0.20.3

### Platform
Tell us to which platform this issue is related

N/A

### Expected behaviour

Display image preview after user selects image from image picker

### Actual behaviour

Not displaying image by passing the image.path value into Image component

### Attachments
```
handleOpenImagePicker() {
    ImagePicker.openPicker({
      width: 300,
      height: 300,
      cropping: true
    }).then(async photo => {
      await this.setState({
        photo: {
          uri: photo.path,
          mime: photo.mime
        }
      })
      console.log(this.state)
    });
  }

...other code

<Image style={styles.image} source={
              {uri: publicAssets.avatars + (this.state.photo ? 
                this.state.photo.uri : 'default.png')}
            } />

```

![image](https://user-images.githubusercontent.com/13799221/41329555-6e93ed8e-6e9c-11e8-953d-b7ac8bd32437.png)

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by mxdi9i7** [comment]
Solved the issue, I was attaching my CDN's prefix to local image path upon selecting. closing the issue

**Comment by Martian2Lee** [comment]
@mxdi9i7 May I ask how to get `CDN's prefix`?

**Comment by mxdi9i7** [comment]
@Martian2Lee What I did was I appended my amazon S3's url address to all my images upon selecting, the CDN's prefix is referencing the aws S3 link.
