### ISSUE TITLE
Multiple selection method

### ISSUE THREAD

**Issue by netdown** [ivpusic/react-native-image-crop-picker#742]
Hi,
Would it be possible to change the way the multiple selection works, so long-touch would not be needed to select more images? Currently, if I touch a single image, it gets selected and the dialog is closed. I would like to be able to select multiple images by tapping, then closing with the done button.

I looked inside the source, but couldn't find the related code. Is this behaviour inside the createChooser native method?

**Comment by ivpusic** [comment]
currently this is device/android version/vendor specific. Cannot promise when this is going to be changed.
