### ISSUE TITLE
how to select more in android?

### ISSUE THREAD

**Issue by WaitInRaining** [ivpusic/react-native-image-crop-picker#752]
I have set multiple as true in ImagePicker.openPicker, but it is not visiable in android.what should i do?

**Comment by Mikunj** [comment]
On Android, you have to long press a selection for it to convert to multi-select.

**Comment by AbhijithRobosoft** [comment]
On Android long press an image then on top right hand side you can see "Open" tap on that should be good to go.

**Comment by ivpusic** [comment]
@WaitInRaining try suggestions from @Mikunj and @AbhijithRobosoft

**Comment by geisterfurz007** [comment]
Also make sure to not have any other attributes in the options object. I included `cropping: true` and `mediaType: 'photo'` and removing both allowed me to use the multiple selection.
