### ISSUE TITLE
the image picker interface is different from readme

### ISSUE THREAD

**Issue by soul-power** [ivpusic/react-native-image-crop-picker#756]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker ^0.20.3
- react-native 0.55.4

### Platform
Tell us to which platform this issue is related

- Android

### Actual behaviour

![_20180707233641](https://user-images.githubusercontent.com/30051610/42412429-d82df4c8-823e-11e8-9b32-9901cf698525.jpg)

### Steps to reproduce

1.

2.

3.

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by ivpusic** [comment]
currently we use stock android gallery, which means that interface depends on android version and device manufacturer
