### ISSUE TITLE
How to save the cropped image to CameraRoll on iOS?

### ISSUE THREAD

**Issue by leiz-me** [ivpusic/react-native-image-crop-picker#759]
Currently this package works pretty well and many thanks to @ivpusic.
I am building an app with this package that allowing people share some life photos. And I want to save the cropped photo to camera roll. 

How can I do this? Any sample or suggestion?
I have one clue that maybe I should use react native module CameraRoll to get this done. 
Any help?

Thank you.

**Comment by leiz-me** [comment]
Just use CameraRoll and link it to the project then save image.path and it's done.

**Comment by emalazt2014** [comment]
how do you do this? so that it can be viewed in the gallery or roll camera of ios and android, thank you very much

**Comment by zi6xuan** [comment]
@emalazt2014 about this  https://facebook.github.io/react-native/docs/cameraroll
