### ISSUE TITLE
how can i set limit to the number of selection of images?

### ISSUE THREAD

**Issue by AbhijithRobosoft** [ivpusic/react-native-image-crop-picker#761]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.20.3
- react-native v0.55.4

### Platform

Both
- iOS
- Android

Someone please help

**Comment by aiynmm** [comment]
Use `maxFiles` prop !

**Comment by ivpusic** [comment]
on ios use maxFiles, on android it is not yet supported.

**Comment by AbhijithRobosoft** [comment]
doesn't seem to be working.

**Comment by jacquesdev** [comment]
Hello @ivpusic 

Is this limited in Android or, just not yet implemented in the plugin?

**Comment by christopher-18** [comment]
@ivpusic  Any new update on this?
