### ISSUE TITLE
New logo/icon

### ISSUE THREAD

**Issue by mansya** [ivpusic/react-native-image-crop-picker#764]
Hi, I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, you have no logo on this project. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by ivpusic** [comment]
thanks a lot for interest in doing something like that. You are very welcome to propose logo/icon.

**Comment by mansya** [comment]
I have Design logo for this project. what do you think ? do you like it ?
![react native image crop picker](https://user-images.githubusercontent.com/33461607/42813542-9319dee2-89eb-11e8-8770-8971737f7c7b.png)

**Comment by ivpusic** [comment]
yes, looks good!

**Comment by mansya** [comment]
I've changed the file in readme to svg. You can check it.
