### ISSUE TITLE
pickMultiple() is undefined

### ISSUE THREAD

**Issue by AbhijithRobosoft** [ivpusic/react-native-image-crop-picker#767]
### Version
- react-native-image-crop-picker v0.20.3
- react-native v0.55.4

### Platform
- iOS not working.
-Android working as expected in emulator as well.

### Expected behaviour
Should Open the gallery

### Actual behaviour
crashing. Error: pickMultiple() is undefined

**Comment by ivpusic** [comment]
`pickMultiple` does not exists in this library. Check readme for usage
