### ISSUE TITLE
Failed to find Build Tools

### ISSUE THREAD

**Issue by teodors** [ivpusic/react-native-image-crop-picker#77]
Just added this packaged, tried to run it, but got an error. I don't know what are these "Build Tools". Could it have something to do with extra SDK packages?

Running:
- react-native-image-crop-picker v0.9.4 (latest)
- react-native v0.33
- Windows 10

Error:
>A problem occurred configuring project ':app'.
>\> A problem occurred configuring project ':react-native-image-crop-picker'.
>\> failed to find Build Tools revision 23.0.3

**Comment by ivpusic** [comment]
similar question http://stackoverflow.com/questions/36683726/failed-to-find-build-tools-revision-23-0-1

please ensure that you have proper android setup

**Comment by teodors** [comment]
Yeap, I practically figured it out by the time I posted, but my network connection died. Sorry. Thank you anyway!

**Comment by nickkapoor** [comment]
I am having the same issue.  Was wondering what @teodors did to resolve it?  Thanks all.
