### ISSUE TITLE
Inconsistent error codes

### ISSUE THREAD

**Issue by MyGuySi** [ivpusic/react-native-image-crop-picker#770]
I've got some questions about the error codes that are used because I've just had to fix a "bug" in our app that was due to a different error code for missing permissions.

```javascript
ImagePicker.openCamera({...})
.then(...)
.catch(error => {
  if (error === "E_PERMISSION_MISSING") {
    // Do stuff...
  }
});


ImagePicker.openPicker({...})
.then(...)
.catch(error => {
  if (error === "E_PERMISSION_MISSING") {
    // Do stuff...
  }
});
```

Here's the methods I originally had and as you can see, I assumed that `E_PERMISSION_MISSING` was the code to use to check that the user hadn't previously denied a permission. It turns out that the correct code to use for `openCamera()` is `E_PICKER_NO_CAMERA_PERMISSION`.

Are the error codes documented anywhere? I checked the README and searched issues and couldn't find that information out without having to debug it by logging the error codes. That's easy enough to do but it seems like the kind of thing that should be documented somewhere.

Apologies if it is documented, I just haven't been able to find it yet...

**Comment by ivpusic** [comment]
currently it is not documented. do you have some time to send a PR to make this consistent?

**Comment by MyGuySi** [comment]
@ivpusic I'll have a shot at it when I get some spare time 👍

**Comment by ishigamii** [comment]
Hi, I am actually wondering about this too any news since that time ?

**Comment by ishigamii** [comment]
Seems they both now give `E_PERMISSION_MISSING `

**Comment by MyGuySi** [comment]
I'm no longer working with React Native and given @ishigamii 's comment I'm going to close. Feel free to re-open if it's still an issue.

**Comment by ishigamii** [comment]
finally you were right it is `E_PICKER_NO_CAMERA_PERMISSION` on iOS while it seems to still be working with `E_PERMISSION_MISSING ` on Android
