### ISSUE TITLE
程序包com.reactnative.ivpusic.imagepicker不存在

### ISSUE THREAD

**Issue by learn4** [ivpusic/react-native-image-crop-picker#779]
![image](https://user-images.githubusercontent.com/40156494/43240541-a1e0e03a-90c9-11e8-800f-ae21d1376196.png)

version：
![image](https://user-images.githubusercontent.com/40156494/43240571-c8f5337e-90c9-11e8-8666-7948dc7692ac.png)

**Comment by cyunWeb** [comment]
解决了吗？
