### ISSUE TITLE
Rotation feature of Image crop picker for iOS

### ISSUE THREAD

**Issue by milosristic124** [ivpusic/react-native-image-crop-picker#787]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.20.0
- react-native v0.51.0

### Platform
Tell us to which platform this issue is related

- iOS

### Expected behaviour
When I choose or take a photo, the photo editor screen appears.
On Android, rotation and cropping options are featured.
I expected it works same on iOS.

### Actual behaviour
But on iOS, only cropping feature works but not rotation.

### Steps to reproduce
Is there any way to add rotation feature to iOS?

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by compojoom** [comment]
I would love this as well, but the feature is a clone of https://github.com/ivpusic/react-native-image-crop-picker/issues/206 and @ivpusic said that he doesn't plan to add this.

**Comment by kholiavko-roman** [comment]
@milosristic124 are you found a solution for rotation image on iOS ?

**Comment by milosristic124** [comment]
> @milosristic124 are you found a solution for rotation image on iOS ?

@kholiavko-roman , I created my own library to rotate image after picking image.

**Comment by kholiavko-roman** [comment]
@milosristic124 is it public ? Can I try it ?
