### ISSUE TITLE
Images from camera shifts forward in array of images.

### ISSUE THREAD

**Issue by rendomnet** [ivpusic/react-native-image-crop-picker#789]
Im using image-crop-picker to create array of images. 
And when I add first image from camera and second image from gallery. 
Then after I send this array using formData to my server.  Somehow my second image from gallery became first and my first image from camera became second.

If I sent 2 images from gallery then they are not shifting.
If I send 2 images from camera they WILL shift.

When I check my array before converting to formData. Images are in right order.

this is code of converting to formData
```
      } else if (Array.isArray(val) && val.length > 0) {
        for (let item of val) {
          // Array Images
          if (item.hasOwnProperty("mime")) {
            console.log("image");
            const img = {
              uri: item.path,
              type: item.mime,
              name: item.path
                .split("\\")
                .pop()
                .split("/")
                .pop()
            };
            fd.append(key, img);
```

iOS and android

**Comment by superandrew213** [comment]
@rendomnet is this happening on iOS and Android?

**Comment by rendomnet** [comment]
iOS and android

**Comment by rendomnet** [comment]
I found error inside my server function. Which was creating new uploaded array by using push. And because of this images which loaded first was placed first in the result array.
