### ISSUE TITLE
Select multiple images at once and crop them in a row without the cropper closing after each image?

### ISSUE THREAD

**Issue by SASoto** [ivpusic/react-native-image-crop-picker#800]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.20.3
- react-native v0.56.0

### Platform
Tell us to which platform this issue is related

- iOS
- Android

### Expected behaviour
I want to select a set of images using ImagePicker.openPicker, save the image paths to an array that is saved in state, and then loop through the array, cropping one photo at a time without the cropper closing between each image.

### Actual behaviour
I am using a loop of Promises to do this currently, but unfortunately, it seems that after the cropper resolves, it has to close before the next image can be cropped. This causes whatever screen that the user was on before opening the cropper to become visible for a split second, before the cropper is opened again with the following image in the array.

### Steps to reproduce

1. Save an array of image paths in state.

2. Call this function which loops through the a set of Promises equal to the number of image paths saved in state:
```
handleMultipleImageCropping() {
    let {imagesArr} = this.state;
    let that = this;
    
    var temp = that.state.imagesArr;
    
        (function loop(i) {
           if (i < imagesArr.length) new Promise((resolve, reject) => {
                ImagePicker.openCropper({
                  path: imagesArr[i],
                  width: 500,
                  height: 500,
                  //waitAnimationEnd: true,
                  compressImageQuality: 1,                  
                  cropperToolbarTitle: 'Crop image area'
                }).catch(reject => loop.bind(null, i+1))
                .then(image => {
                  
                  if(image.path) {
                    
                    temp[i] = {uri: image.path};
                    that.setState({imagesArr: temp});
                  }                  
                  resolve();
                  
                }).catch(() => console.log('erorr with image cropper after then'))
                
            }).catch(() => console.log('erorr with looped promise for image cropper'))
            .then(loop.bind(null, i,));
        })(0);
  }
```

3. Notice that after the cropper is opened and you successfully crop an image, the cropper is closed, the screen you were on is shown for a brief second, and then the cropper is opened again due to you still being in the Promises loop.

### Attachments
Let me know if you'd like to see an example (in the form of a gif) of what I am talking about.

**Comment by ivpusic** [comment]
unfortunetly something like this is currently not supported and not planned in a near future
