### ISSUE TITLE
Open image-crop-picker once component mounts

### ISSUE THREAD

**Issue by mopilo** [ivpusic/react-native-image-crop-picker#806]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v26.10.?.?
- react-native v56.0.?.?

### Platform
Tell us to which platform this issue is related

- Android

### Expected behaviour

Open image-crop-picker once the component  mounts

### Actual behaviour

I have to click a button to open image-crop-picker

### Steps to reproduce

My first screen is to show the image crop picker, how can i achieve it, rather than clicking a button to show it??

**Comment by ivpusic** [comment]
on componentDidMount call openPicker method

**Comment by mopilo** [comment]
then how would my render() look like??

**Comment by ivpusic** [comment]
in render method you don't have to do anything regarding image picker.
