### ISSUE TITLE
ReferenceError Can't find variable crypto (Build Release IOS)

### ISSUE THREAD

**Issue by pqminh** [ivpusic/react-native-image-crop-picker#810]
### Version
- react-native-image-crop-picker v0.21.1
"react": "16.0.0-alpha.12",
"react-native": "^0.47.2",

### Platform
- iOS
### Expected behaviour

Multi Picker image from library.

### Actual behaviour

![image from ios](https://user-images.githubusercontent.com/13993984/44893458-72fe7f80-ad15-11e8-8036-34ce1b395246.png)

### Steps to reproduce

1. 

const options = {
      width: 300,
      height: 400,
      multiple: true,
      cropperChooseText: 'Chọn',
      cropperCancelText: 'Huỷ',
      loadingLabelText: 'Đang xử lý...',
      maxFiles: 10,
      mediaType: 'any',
      cropperToolbarTitle: 'Sửa hình ảnh'
    };
     ImageCropPicker.openPicker(options).then(response => {}).catch(err => console.log(err))
Catch error: ReferenceError Can't find variable crypto 

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by pqminh** [comment]
My bad.

**Comment by jamesnyika** [comment]
> My bad.

Aw man.. at least say what you did wrong... no one learns if you do not tell us your mistake

**Comment by RazaShehryar** [comment]
What was the actual error? @pqminh

**Comment by bnmounir** [comment]
https://github.com/expo/expo/issues/7507

**Comment by Doenja** [comment]
I had the same issue and it turned out I didn't read the nano-id docs thoroughly. You need to install the react-native-get-random-values package and import it before you import nanoid. See the documentation for the exact steps:

https://www.npmjs.com/package/nanoid#react-native

**Comment by pqminh** [comment]
> > My bad.
> 
> Aw man.. at least say what you did wrong... no one learns if you do not tell us your mistake

Ya sorry but I don't remember this error. Have nice day!
