### ISSUE TITLE
How to rename fields

### ISSUE THREAD

**Issue by userbq201** [ivpusic/react-native-image-crop-picker#813]
How to rename fields on ios
gallery (default Cancel, Photos)
camera (Cancel)
preview photo (retake, use photo)

**Comment by ishigamii** [comment]
@userbq201 I just made a PR explaining how to do that. It has been merged so you will find it in the description now 👍 

- Open your Xcode project
- Go to your project settings by opening the project name on the Navigation (left side)
- Select your project in the project list
- Should be into the Info tab and add in Localizations the language your app was missing throughout the +
- Rebuild and you should now have your app camera and gallery with the classic ios text in the language you added.
