### ISSUE TITLE
Failed to resolve: com.github.yalantis:ucrop:2.2.2-native

### ISSUE THREAD

**Issue by Ann1995** [ivpusic/react-native-image-crop-picker#835]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.21.2
- react-native v0.56.0

### Platform
Tell us to which platform this issue is related
- Android

### Expected behaviour
build android without error 

### Actual behaviour

FAILURE: Build failed with an exception.
* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not resolve com.github.yalantis:ucrop:2.2.2-native.
  Required by:
      project :app > project :react-native-image-crop-picker
   > Could not resolve com.github.yalantis:ucrop:2.2.2-native.
      > Could not get resource 'https://jcenter.bintray.com/com/github/yalantis/ucrop/2.2.2-native/ucrop-2.2.2-native.pom'.
         > Could not HEAD 'https://jcenter.bintray.com/com/github/yalantis/ucrop/2.2.2-native/ucrop-2.2.2-native.pom'.
            > java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
   > Could not resolve com.github.yalantis:ucrop:2.2.2-native.
      > Could not get resource 'https://maven.google.com/com/github/yalantis/ucrop/2.2.2-native/ucrop-2.2.2-native.pom'.
         > Could not HEAD 'https://maven.google.com/com/github/yalantis/ucrop/2.2.2-native/ucrop-2.2.2-native.pom'.
            > java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

### Steps to reproduce
1. My android -> build.gradle
```
buildscript {
    repositories {
        jcenter()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }
}

ext {
    buildToolsVersion = "26.0.2"
    minSdkVersion = 16
    compileSdkVersion = 26
    targetSdkVersion = 26
    supportLibVersion = "26.1.0"
}
```
2. react-native run-android

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by sondremare** [comment]
@Ann1995 If you read at the "Post-install" steps on the readme. You need to add this to your build.gradle
     
maven { url "https://jitpack.io" }

**Comment by lastidea** [comment]
i still don't known how to do

**Comment by gamingumar** [comment]
what i was doing wrong is putting both of these
```
maven { url 'https://maven.google.com' }
maven { url "https://jitpack.io" }
```
in buildscript instead of allprojects

**Comment by sayed6201** [comment]
i added  maven { url "https://jitpack.io" } in allproject repo.. it solved the problem
allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://jitpack.io" }
    }
}

**Comment by hunzalashakeel1996** [comment]
i did add maven { url "https://jitpack.io" } but still getting same error `Could not determine artifacts for com.github.yalantis:ucrop:2.2.2-native: Skipped due to earlier error`. any help. `react-native-cli: 2.0.1,
react-native: 0.60.5, "react-native-image-crop-picker": "^0.25.2",`

**Comment by Kowaio** [comment]
Hi,
I've updated RN with last stable version 0.61 and I'm currently having this problem.

I've got correctly set maven url in allProjects > repositories like so.
Any idea ?

```
allprojects {
  repositories {
    maven { url 'https://maven.google.com' }
    maven { url "https://jitpack.io" }
    mavenLocal()
    google()
    jcenter()
    maven {
      // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
      url "$rootDir/../node_modules/react-native/android"
    }
    maven {
      // Android JSC is installed from npm
      url("$rootDir/../node_modules/jsc-android/dist")
    }
    maven {
      url 'https://maven.fabric.io/public'
    }
  }
}
```

and console is : 

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.github.yalantis:ucrop:2.2.2-native.
     Required by:
         project :app > project :react-native-image-crop-picker
      > Skipped due to earlier error
```

If anyone having clue it could be great! Thanks!

**Comment by hunzalashakeel1996** [comment]
@Kowaio put your  mavenLocal() google() jcenter() before all mavens, it solved for me.
like this
`allprojects {
  repositories {
    mavenLocal()
    google()
    jcenter()
    maven { url 'https://maven.google.com' }
    maven { url "https://jitpack.io" }
     maven {
      // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
      url "$rootDir/../node_modules/react-native/android"
    }
    maven {
      // Android JSC is installed from npm
      url("$rootDir/../node_modules/jsc-android/dist")
    }
    maven {
      url 'https://maven.fabric.io/public'
    }
  }
}`

**Comment by Kowaio** [comment]
Still the same unfortunately :(

Do you think it could be caused from another gradle settings ?

```
buildscript {
  ext {
    buildToolsVersion = "28.0.3"
    minSdkVersion = 21
    compileSdkVersion = 28
    targetSdkVersion = 28
    supportLibVersion = "28.0.0"
    googlePlayServicesVersion = "16.+"
    castFrameworkVersion = rootProject.ext.googlePlayServicesVersion
  }
  repositories {
    google()
    jcenter()
    maven {
      url 'https://maven.google.com/'
      name 'Google'
    }
    maven { url 'https://maven.fabric.io/public' }
    maven { url 'https://plugins.gradle.org/m2/' } // Gradle Plugin Portal
  }
  dependencies {
    classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.1, 0.99.99]'
    classpath 'com.android.tools.build:gradle:3.4.2'
    classpath 'com.google.gms:google-services:4.2.0'
    classpath 'io.fabric.tools:gradle:1.25.4'
    classpath 'com.google.firebase:perf-plugin:1.2.1'

    // NOTE: Do not place your application dependencies here; they belong
    // in the individual module build.gradle files
  }
}

allprojects {
  repositories {
    mavenLocal()
    google()
    jcenter()
    maven { url 'https://maven.google.com' }
    maven { url "https://jitpack.io" }
    maven {
      // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
      url "$rootDir/../node_modules/react-native/android"
    }
    maven {
      // Android JSC is installed from npm
      url("$rootDir/../node_modules/jsc-android/dist")
    }
    maven {
      url 'https://maven.fabric.io/public'
    }
  }
}

subprojects {
  afterEvaluate { subproject ->
    if ((subproject.hasProperty('android'))) {
      android {
        compileSdkVersion rootProject.ext.compileSdkVersion
        buildToolsVersion rootProject.ext.buildToolsVersion
      }
    }
  }
}

wrapper {
    gradleVersion = '5.1.1'
    distributionUrl = distributionUrl.replace("bin", "all")
}
```

Thanks for your help!

**Comment by hunzalashakeel1996** [comment]
@Kowaio i don't think. If it helps i paste my build.gradle 
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "29.0.2"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"

        // googlePlayServicesVersion = "16.1.0"
        firebaseVersion = "17.3.4"

        // firebaseVersion = "+" // default: "+"
        googlePlayServicesVersion = "+"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.4.1")

        classpath 'com.google.gms:google-services:+'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven { url 'https://maven.google.com' }
         maven {
            // Used by react-native-image-crop-picker for certain dependencies
            url("https://jitpack.io")
        }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        
    }
}

```

**Comment by Kowaio** [comment]
Well, for some reason putting the minSdk to 16 instead of 21 and arranging maven like this, did the trick. Also I added "www." just in case, well. ¯\_(ツ)_/¯ 

```
allprojects {
  repositories {
    google()
    jcenter()
    maven { url 'https://www.jitpack.io' }
    mavenLocal()
    maven {
      // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
      url("$rootDir/../node_modules/react-native/android")
    }
    maven {
      // Android JSC is installed from npm
      url("$rootDir/../node_modules/jsc-android/dist")
    }
  }
}
```

Thanks for your help!

**Comment by myckhel** [comment]
adding www to maven { url 'https://www.jitpack.io' } solved for me too after hours of frustration

**Comment by webdevbdh** [comment]
> adding www to maven { url 'https://www.jitpack.io' } solved for me too after hours of frustration

Are you using RN 0.59?

because in my case it is not solving my problem but creating another problem
> Task :@react-native-community_viewpager:compileDebugJavaWithJavac FAILED

**Comment by myckhel** [comment]
Im using react native 0.61

**Comment by MOwais** [comment]
I'm facing the same issue with RN 0.61.5. Ive linked the lib and added `maven { url "https://jitpack.io" }` to build.gradle but no luck

**Comment by marcshilling** [comment]
Just in case anyone else runs into the same problem I had...this was the error that surfaced for me when jitpack.io was experiencing downtime. If you've tried everything else and still nothing, check that you can reach https://jitpack.io. Once they came back up, my build started working again.

**Comment by supto09** [comment]
I had to use   `maven { url 'https://jitpack.io' }` . adding www before jitpack was causing the trouble

**Comment by prisar** [comment]
yes removing `www` worked

**Comment by Uzef1997** [comment]
Turning off the vpn worked for me
