### ISSUE TITLE
new version: video selection problem

### ISSUE THREAD

**Issue by keshamtravels** [ivpusic/react-native-image-crop-picker#838]
i am using the latest version from npm released 4 days ago . In earlier version ther was no problem with video selection but now video selection closes the app  just when we select a video

**Comment by ivpusic** [comment]
hm, could you try to provide more info?

**Comment by keshamtravels** [comment]
I am able to select the video from the gallery but as soon as i proceed to next screen where the video selected is played it shows there is no file at that path , i guess the thing is it is providing the path of saved video but video is not saved on that path thats why its returning null. In earlier version there was no such problem

**Comment by keshamtravels** [comment]
file:///data/user/0/com.worldtripy/cache/react-native-image-crop-picker/VID-20180921-WA0005.mp4

it is providing the path of saved video as above but there is no video at that path, i have searched it also in phone's memory at the specified path

**Comment by keshamtravels** [comment]
Please help me fast , my project is going to release soon

**Comment by ivpusic** [comment]
so version `v0.21.1` does not have this problem?

**Comment by keshamtravels** [comment]
Sorry @ivpusic  , you have done a great work , there was a mistake in another package that i was using the crop the video to which the video path was passed , thanks for paying attention and investing your time here , It would be great if you include video cropping facility in this project for android. Now closing this issue

**Comment by ivpusic** [comment]
could you tell me which package are you currently using for video cropping?

**Comment by keshamtravels** [comment]
i am using react-native video processing for cropping videos, suggest me if you know some better one.

**Comment by mursang** [comment]
@keshamtravels how did you manage to choose videos with this library and to crop videos with react-native-video-processing? I have exactly the same issue.

**Comment by shen-lan** [comment]
Hi  ,did you resolved it ?
