### ISSUE TITLE
Always 'processing assets' when choose video not in local device

### ISSUE THREAD

**Issue by JiangYulin** [ivpusic/react-native-image-crop-picker#839]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.20.3
- react-native v0.57.1

### Platform
- iOS

### Expected behaviour
procesing then done

### Actual behaviour
always show "processing assets"

### Steps to reproduce

1. choose video (not in filesystem)

2. then "processing assets"

**Comment by chrisbobbe** [comment]
A pull request to fix this issue was merged a month ago, and at the time @ivpusic said the fix would be released in the next version. I believe the fix was included in version 0.21.2 released five days ago -- have you tried running `npm update` to get this version?

**Comment by EvanMaFYH** [comment]
i use the version of 0.21.3 , but i still have the problem,any idea

**Comment by bbturtle** [comment]
> i use the version of 0.21.3 , but i still have the problem,any idea

You can try deleting the line minFiles: 0 in your code. The Done button is disabled when not selected. Working for me
