### ISSUE TITLE
File name contains Chinese crash. when i selected image

### ISSUE THREAD

**Issue by RoarRain** [ivpusic/react-native-image-crop-picker#841]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.16.1
- react-native v0.48.0

### Platform
- Android

Error：
java.lang.IllegalArgumentException: Unexpected char 0x5c71 at 34 in content-disposition value: form-data; name="file"; filename="山东-compressed.jpg"

**Comment by xlyren** [comment]
Encode the name
```bash
  let formData = new FormData();
        let arr = image.path.split('/');
        let name = arr[arr.length-1];
        let file = {uri: image.path, type: 'multipart/form-data', name:encodeURIComponent(name) };
        formData.append("file", file);
````

**Comment by RoarRain** [comment]
thx!
