### ISSUE TITLE
After the react-native-image-crop-picker is npm --save, the Terminal executes the react-native run-ios crash

### ISSUE THREAD

**Issue by xuxichen** [ivpusic/react-native-image-crop-picker#842]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.21.2
- react-native v0.49.3

### Platform
Tell us to which platform this issue is related

- iOS

### Expected behaviour
In Terminal react-native run-ios  and Xcode run don't have any difference 
 
### Actual behaviour
In Terminal：
1. when I "react-native init MyApp --version 0.49.3"
2. "react-native run-ios", There were no errors before this
3. But when I executes "npm i react-native-image-crop-picker --save"  and "react-native link react-native-image-crop-picker" in Terminal
4. after i executes  "react-native run-ios" the iphoneSimulator is always crash.
5. But I use Xcode run the project is don't have errors.

### Steps to reproduce

In Terminal：

1. when I "react-native init MyApp --version 0.49.3"

2. "react-native run-ios", There were no errors before this

3. But when I executes "npm i react-native-image-crop-picker --save"  and "react-native link react-native-image-crop-picker" in Terminal

4. after i executes  "react-native run-ios" the iphoneSimulator is always crash.

5. But I use Xcode run the project is don't have errors.

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by hcliff** [comment]
same problem

**Comment by ivpusic** [comment]
cannot reproduce this issue. please make sure that you followed installation steps from readme
