### ISSUE TITLE
[iOS] Images are not resized to given width and height prop after cropping

### ISSUE THREAD

**Issue by Lowisoft** [ivpusic/react-native-image-crop-picker#843]
Hi, I noticed that after the update 0.21.2, cropped images are not resized to the given height and width props (**only iOS**). The images keep their height and width and therefore most of the images are too big to upload to a server. 

After further investigation, I realized that the following change (in _ios/src/ImageCropPicker.m_) caused this issue:

https://github.com/ivpusic/react-native-image-crop-picker/pull/825/files#diff-ae20f589f1a9014f341c1ab93989eab1

The changes were made to avoid cropping the image twice, but as far as I can tell it causes this new bug. Undoing these changes solves the issue, but it would be great if this issue could be fixed in the main project. 

(another completely different issue that I noticed: https://github.com/ivpusic/react-native-image-crop-picker/issues/844)

### Version
- react-native-image-crop-picker v0.21.2
- react-native v0.55.4

### Platform
- iOS

### Expected behaviour

The width and height of the returned images is the same as the given width and height props.

### Actual behaviour

Images are not resized to given height and width prop.

### Steps to reproduce

1. Indicate a width and height prop

2. Choose an image or take a photo in iOS

3. Crop the image (or not) and finish your edit

4. Look at the returned image width and height

**Comment by leomercier** [comment]
Having this problem too. How did you fix? Modifying the ```ios/src/ImageCropPicker.m ```

Adding back 

```    
// we have correct rect, but not correct dimensions
// so resize image
    CGSize resizedImageSize = CGSizeMake([[[self options] objectForKey:@"width"] intValue], [[[self options] objectForKey:@"height"] intValue]);
    UIImage *resizedImage = [croppedImage resizedImageToFitInSize:resizedImageSize scaleIfSmaller:YES];
    ImageResult *imageResult = [self.compression compressImage:resizedImage withOptions:self.options];```

**Comment by Lowisoft** [comment]
Yes this was also my approach.

**Comment by Lowisoft** [comment]
Unfortunately not as I am using .data to get base64 of the image.

**Comment by Salinn** [comment]
As someone who was seeing this as well when I switched from image.sourceUrl to image.path it fixed me and probably could be closed.

**Comment by aminosman** [comment]
Can confirm the issue and that the cause is the suggested PR #825

**Comment by KevinColemanInc** [comment]
@leomercier / Everyone else

I found that you have to set the `compressImageMax...` values for iOS to correctly return the resized image.

Sample code:
```
ImagePicker.openCamera({
      width: 500,
      height: 500,
      compressImageMaxWidth: 500,
      compressImageMaxHeight: 500,
      cropping: true,
    }).then(image => {
      this.uploadImageBackground(image.path)
    }).catch((err) => { console.log("openCamera catch" + err.toString()) });
```

**Comment by rawadrifai** [comment]
Late to the party here.. was there a fix for this?
All I'm trying to do is open an image picker, select a photo, croppable and can be made light to save.
