### ISSUE TITLE
[iOS] Cancelling cropper after camera is not throwing an error

### ISSUE THREAD

**Issue by Lowisoft** [ivpusic/react-native-image-crop-picker#844]
Hi, I noticed that cancelling the cropper after taking a photo with the camera does not throw an error (**on iOS**). So, the function returns neither an error nor an image. I think this implementation has been forgotten in v0.17.0 (https://github.com/ivpusic/react-native-image-crop-picker/issues/367).

Changing line 811 of _ios/src/ImageCropPicker.m_ solves this issue, but as I am not very familiar with the code there might be a better solution to this problem:

`if (self.currentSelectionMode == CROPPING || self.currentSelectionMode == CAMERA) {`

(another completely different issue that I noticed: https://github.com/ivpusic/react-native-image-crop-picker/issues/843)
 
### Version

- react-native-image-crop-picker v0.21.2
- react-native v0.55.4

### Platform
- iOS

### Expected behaviour

Picker is throwing an error when cancelling the cropper after taking a photo with the camera.

### Actual behaviour

Neither error nor image are returned.

### Steps to reproduce

1. Open camera and take a photo.

2. Cancel the cropper.

3. No error is returned.

**Comment by dkfl1995** [comment]
GUYSS!!
We need to push this fix to release!!!
Please do this, to prevent a lot of unnecessary fork for a just one line

**Comment by Lowisoft** [comment]
Yes, I totally agree, but as I said before, I am not very familiar with the code and I have never made a pull request before. Furthermore, I think that not many people experience this issue, as this is a very particular usage of the picker. 
Feel free to propose a pull request if you want to. I think a fix could be easily implemented in a new version. As for now, I simply added my suggested solution to the file of my project.

**Comment by ivpusic** [comment]
fixed here https://github.com/ivpusic/react-native-image-crop-picker/pull/954

**Comment by timbrandin** [comment]
This is broken in 0.35.0, changed this line and it started working:
![image](https://user-images.githubusercontent.com/1715834/98214940-702bf480-1f47-11eb-9725-b9ebe44eca8b.png)
