### ISSUE TITLE
Problem with Code Push and upgrading version to v0.21.2

### ISSUE THREAD

**Issue by mahdibarati** [ivpusic/react-native-image-crop-picker#849]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.?.? v0.21.2
- react-native v0.?.? 0.55.2

### Platform
Tell us to which platform this issue is related
- Android

### Expected behaviour
when code push update, the app changed to newer version

### Actual behaviour
cropping change not upgraded

### Steps to reproduce

change version to v0.21.2 cause this problems

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by ivpusic** [comment]
code-push will update javascript code. this is native library, and if you upgrade it, you need to rebuild whole application and send it to google play instead of code-push
