### ISSUE TITLE
The picture is too big, upload too slow?

### ISSUE THREAD

**Issue by iamdurui** [ivpusic/react-native-image-crop-picker#85]
### Version
Tell us which versions you are using: 

- react-native v0.3.3

### Platform
Tell us to which platform this issue is related

- iOS and  Android

Hello, I have a problem now, because one of my pictures to 2 m, when I upload a few pictures very slowly,can you give me Suggestions and solutions?And I choose more pictures at most three,Thank you very much!

**Comment by ivpusic** [comment]
images on ios are converted to jpg (so image size should be ok already), but on android you are getting original ones. Currently on android side there is no feature to compress image. Maybe you could try to find some module to do image compression before upload. 

For max files, this feature is only available on iOS. On android there is no such feature currently.

**Comment by iamdurui** [comment]
@ivpusic Thanks,I must to  modify your code on Android。

**Comment by ceeesrt** [comment]
any solution for this ? im having same problem, on IOS the image uploads very fast to server but on android takes an eternity.

**Comment by fedecaccia** [comment]
same problem on android, any recommended method?
