### ISSUE TITLE
[iOS] cropRect contains wrong value

### ISSUE THREAD

**Issue by howg0924** [ivpusic/react-native-image-crop-picker#850]
### Version

- react-native-image-crop-picker v0.21.2
- react-native v0.55.4

### Platform
Tell us to which platform this issue is related

- iOS

### Expected behaviour

After crop, cropRect contains correct information.

### Actual behaviour

cropRect.width/height are wrong. Sometimes they are even larger than the width/height of the origainl image. cropRect.x and cropRect.y are also incorrect.

This only happened on iOS. The values are correct on Android.

### Steps to reproduce

1. Just crop some image and print the result:

```JavaScript
ImagePicker.openCropper({
  path: imagePath,
  width: 100,
  height: 100
}).then(result => {
  console.log(result);
});
```

2. You will see something like this:

```
{ cropRect: { width: 400, x: 0, height: 400, y: 314 },
  localIdentifier: '...',
  exif: null,
  width: 139,
  mime: 'image/jpeg',
  height: 139,
  data: null,
  modificationDate: null,
  path: '...',
  size: 8787,
  sourceURL: '...',
  creationDate: '1405312098' }
```

The values in result.cropRect are incorrect.

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by paintedbicycle** [comment]
Is this the same as https://github.com/ivpusic/react-native-image-crop-picker/issues/843 ?

Also can anyone confirm this only started after updating your phone to iOS 12? I didn't update my app to 0.21.2 as that other issue mentions, but I seem to now be having this issue in my app.

**Comment by howg0924** [comment]
I think it's not related to #843. After further investigation, I found it seems caused by bug introduced in newer version of the dependency library RSKImageCropper. Current version of RSKImageCropper is 2.2.1, and if I ask pod to use version 2.0.1 by adding this line to Podfile:

pod 'RSKImageCropper', '2.0.1'

then it works correctly.

**Comment by howg0924** [comment]
When using RSKImageCropper 2.2.1, I also encountered other weird problem. When I zoom in the image and crop, sometimes the resulting cropped image will bounce back with no zoom in. 

This problem also disappeared when I use 2.0.1.

**Comment by d3vhound** [comment]
@howg0924 updating the version in podfile does not fix the incorrect croprect values for me. This seems like a breaking issue. Currently sending files with sizes I can't control doesn't seem ideal.

**Comment by BaderSerhan** [comment]
+1
I am facing the same problem. When I want to choose a landscape image (without cropping) I am always getting a zoomed in and cropped image. The values in cropRect are larger than the Dimensions of my screen!

**Comment by guruparan** [comment]
Any update on this ? i also have the same issue

**Comment by StiffFy** [comment]
i use react-native-image-picker to replace this lib

**Comment by yasir-netlinks** [comment]
Hi there, is this similar to the problem I am having, and its only in ios. I cropped doesn't appear the correct one, I crop certain place in the image but it appear to be another area!! Can someone help, thanx

**Comment by brandonpearcy** [comment]
+1 having this issue as well.

FWIW, I was able to work around this issue simply by downgrading the problematic dependency. I don't know if there are other bugs that I'm introducing by downgrading, but it's more important to me to have a working zoom+crop on iOS right now.

` 
pod 'RSKImageCropper', '~> 2.0.1'
`

**Comment by jpalumickas** [comment]
We still have the same problem, after cropping images are zoomed in. Downgraded to `2.0.1` solved a problem for us.

**Comment by dori871992** [comment]
Confirm that downgrading the RSKImageCropper version to 2.0.1 will resolve the issue.

**Comment by ymc-thzi** [comment]
Thanks. Also confirming that downgrading the RSKImageCropper version to 2.0.1 will resolve the issue.

**Comment by ivpusic** [comment]
RSKImageCropper is not used anymore. please try latest version with TOCropViewController
