### ISSUE TITLE
Localizing camera control texts

### ISSUE THREAD

**Issue by edreyyo** [ivpusic/react-native-image-crop-picker#852]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.21.2
- react-native v0.56.0

### Platform
Tell us to which platform this issue is related

- iOS

I see it's possible to provide strings to localize the image cropper texts (`cropperToolbarTitle`, `cropperChooseText` and `cropperCancelText`). Is it possible to do the same with the camera controls? Please see attached image below.

### Attachments
![img](https://user-images.githubusercontent.com/6125211/47155137-6beef900-d2e4-11e8-97c4-b2642a88a08a.jpg)

**Comment by edreyyo** [comment]
Okay, it turns out these controls will take on the platform default language as long as the language is set in the Xcode project. Closing issue.

**Comment by jamal-rahimzadegan** [comment]
what for android?
