### ISSUE TITLE
Scale/Shrink/Zoomout larger images to desired width and height

### ISSUE THREAD

**Issue by SohailYaseen** [ivpusic/react-native-image-crop-picker#856]
Version
Tell us which versions you are using:

react-native-image-crop-picker v0.20.1
react-native v0.51.0
Platform
Tell us to which platform this issue is related

Android
Expected behaviour
If image dimensions are greater then output dimension, there should be option to scale down or zoom out the image to output dimensions.

Actual behaviour
Larger image does not scale or zoom out to selected crop width and height.

Steps to reproduce
Select image whose dimensions are grater than crop/target dimension.

Zoom out, shrink or scale down the image

Does not scale down to target dimension

Solution
How can i achieve the desired output????

**Comment by ishigamii** [comment]
can you close one of your issue as you did add twice the same 
thanks

**Comment by ivpusic** [comment]
fixed in 0.22.0
