### ISSUE TITLE
Scale/Shrink/Zoomout larger images to desired width and height

### ISSUE THREAD

**Issue by SohailYaseen** [ivpusic/react-native-image-crop-picker#857]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.20.1
- react-native v0.51.0

### Platform
Tell us to which platform this issue is related

- iOS
- Android

### Expected behaviour
If image dimensions are greater then output dimension, there should be option to scale down or zoom out the image to output dimensions.

### Actual behaviour
Larger image does not scale or zoom out to selected crop width and height.

### Solution
How can i achieve the desired output.????

**Comment by StiffFy** [comment]
i also have this problem. The output image size is not scaled in ios. but Android is the right. Are u solve it?

**Comment by ivpusic** [comment]
fixed in 0.22.0
