### ISSUE TITLE
Is there a way to specify an album name (other then the smartAlbum that is specific to iOS) ?

### ISSUE THREAD

**Issue by HadrienPierart** [ivpusic/react-native-image-crop-picker#864]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.21.3
- react-native v16.6.0

### Platform
- iOS
- Android

These days, we see many apps having their own folder / directory to store the various media they use / receive. Whatsapp for instance has a directory with its own name to store all the attached media that transit through message.
react-native-image-crop-picker seems to store images directly in the default image location. Is there a way to change this behaviour / specify a location ?

Thanks for the great library / module BTW !

**Comment by ivpusic** [comment]
the library only supports albums supported by https://github.com/questbeat/QBImagePicker, so currently not possible to add additional ones
