### ISSUE TITLE
android图片没有回调

### ISSUE THREAD

**Issue by jasoniOS35** [ivpusic/react-native-image-crop-picker#865]
- react-native-image-crop-picker v0.21.2
- react-native v0.55.4
- Android

1.            ImagePicker.openPicker({
              multiple: true,
              maxFiles: 9
            }).then(images => {
// 没有任何东西
              console.log(images);
            });

**Comment by pttyy** [comment]
multiple=false  console.log(image.path);
multiple=true 遍历 images for (let image of images) { console.log(image.path);}

**Comment by ivpusic** [comment]
please provide more info
