### ISSUE TITLE
It would be nice to update readme for android manual install 

### ISSUE THREAD

**Issue by ktomi42** [ivpusic/react-native-image-crop-picker#866]
Could you please update README for Android manual install:

- Following should be added to android/app/src/main/java/com/showtime_client/MainApplication.java
...
import com.reactnative.ivpusic.imagepicker.PickerPackage;
...
    protected List<ReactPackage> getPackages() {
       return Arrays.<ReactPackage>asList(
           ...
           new PickerPackage(),
           ...
     );
...

Thank you

**Comment by ishigamii** [comment]
You can make a PR @ktomi42 it's easy to do 👍
