### ISSUE TITLE
Customize crop view

### ISSUE THREAD

**Issue by serzmerz** [ivpusic/react-native-image-crop-picker#877]
I want to customize crop view, for example, border-radius support is it possible to introduce, I can help with a solution.
### Attachments
I mean something like this.
![photo_2018-11-09_23-48-07](https://user-images.githubusercontent.com/24809641/48290005-0ffa3900-e47a-11e8-8eb8-981391767490.jpg)

// stacktrace or any other useful debug info

**Comment by ivpusic** [comment]
check https://github.com/ivpusic/react-native-image-crop-picker#request-object for currently possible customizations. this one is not possible
