### ISSUE TITLE
OriginalWidth & OriginalHeight relative to the CropRect

### ISSUE THREAD

**Issue by rusuly** [ivpusic/react-native-image-crop-picker#878]
Hello Ivan,

I implement server-side cropping with possibility to upload an image and pass crop rectangle to the server so user can open original image in popup and edit its thumbnail from web and mobile.

The problem I encountered is that the `openCropper`'s callback never provides me with info about original `Width` and `Height` relative to the `cropRect` so I don't know the exact rectangle that I need to crop on backend(I could calculate it if I had original size which cropRect is relative to).
Instead, I see:
```
image.width = 200
image.height = 200
image.cropRect.width = 200
image.cropRect.height = 200

```
I found the [Issue 127](https://github.com/ivpusic/react-native-image-crop-picker/issues/127) but it's old.
My question: Are there any plans to implement the additional info about original size relative to cropRect?

**Comment by ivpusic** [comment]
currently no

**Comment by givik** [comment]
any good news related to this issue?
