### ISSUE TITLE
Crashes with iOS 10

### ISSUE THREAD

**Issue by camnuckols** [ivpusic/react-native-image-crop-picker#88]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker (latest)
- react-native (latest)

### Platform
Tell us to which platform this issue is related

- iOS

### Expected behaviour

Expected the app to behave properly.

### Actual behaviour

The app crashes and will not open.

### Steps to reproduce

1. ```npm i react-native-image-crop-picker --save
         react-native link react-native-react-image-crop-picker```
(These behave as expect and without errors)

2. In the podfile, I add the appropriate headers per the documentation. I did try it without the iOS 8.0 snippet as well, but it still does the same thing.

3. Launch the app. No errors, but app crashes and will not open where it worked perfectly beforehand.

**Comment by ivpusic** [comment]
For iOS 10+, Add the NSPhotoLibraryUsageDescription and NSCameraUsageDescription keys to your Info.plist with strings describing why your app needs these permissions. More https://forums.developer.apple.com/thread/49951

**Comment by Mythrim** [comment]
I am also facing the same issue as described above. But I tried adding the NSPhotoLibraryUsageDescription and NSCameraUsageDescription keys to my Info.plist with strings describing why the app needs these permissions. But still the app get crashed only in ios. Please help me with that.

**Comment by Mythrim** [comment]
Please try these stuffs it solved my issue https://github.com/ivpusic/react-native-image-crop-picker/issues/508.

**Comment by gyyxiaogao** [comment]
@Mythrim Hi,  I have the same problem, I don't have any effect, what is isOpen?

**Comment by Mythrim** [comment]
@gyyxiaogao Basically isOpen is a variable used in this package to set the state of modal.
(If isOpen is true this is means modal should open else if isOpen is false modal should be closed).
