### ISSUE TITLE
 images in ios cant be used again

### ISSUE THREAD

**Issue by daniel031699** [ivpusic/react-native-image-crop-picker#881]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.21.3
- react-native v0.55.4

### Platform
Tell us to which platform this issue is related

- iOS

### Expected behaviour
** images in ios cant be used again**

### Actual behaviour
**when i first time install the application ,i can use the imagepicker  normally ,but i cant use when i second use the imagepicker ,the page is lock and i cant operate**

### Steps to reproduce
**1、i debug the application on real machine by xcode

2、i use the picker to select image from photo album，its normal

3、when image is callback， i repeat the first setp，and then the page is lock**

### Attachments
**strangest of all i cant find anytiing error or logs in chorme and xcode**

**Comment by nicomontanari98** [comment]
I have the same issue with picker and camera

**Comment by daniel031699** [comment]
> I have the same issue with the picker and the camera

i have deal this problem。you can deal with this https://github.com/ivpusic/react-native-image-crop-picker/issues/508
