### ISSUE TITLE
Android 能不能不是长按选择，而且多选的张数能不能确定下

### ISSUE THREAD

**Issue by lchang70163** [ivpusic/react-native-image-crop-picker#882]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.?.?
- react-native v0.?.?

### Platform
Tell us to which platform this issue is related

- iOS
- Android

### Steps to reproduce

1.

2.

3.

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by crazySadSoul** [comment]
i have the save problem, how do you fixed this? can you share it to me?

or anyone can help?????   waiting on line!!!!
