### ISSUE TITLE
How to capture multiple images?

### ISSUE THREAD

**Issue by jaspervanbrian** [ivpusic/react-native-image-crop-picker#888]
Hello, I want to upload multiple images taken from the camera. I know how to upload multiple images/videos from gallery. My use case is this:

After taking a photo from opening the camera, I will push it to the attachments array like this:
```javascript
                                ImagePicker.openCamera({
                                      width: 300,
                                      height: 400,
                                })
                                .then(image => {
                                    let newAttachments = this.state.attachments
                                    newAttachments.push(image)
                                    console.log(this.state.attachments)
                                    this.setState({ attachments: newAttachments })
                                }).catch(error => {
                                    console.log(error);
                                })
```

and after that, if the user wants to capture another image, I will push it again. But sadly, that doesn't work. I think it clears the cache after that. How to solve this?

**Comment by jifromz09** [comment]
@jaspervanbrian - Did you find any solution/workaround for this?

**Comment by ivpusic** [comment]
currently not possible with this package

**Comment by valdman40** [comment]
> currently not possible with this package

is it possible now?

**Comment by tanveersalmangkn** [comment]
You should do something about this I saw this a lot of developers need this functionality (multiple captures) like in social media apps.
