### ISSUE TITLE
Question: Can I crop rectangular image to smaller square area

### ISSUE THREAD

**Issue by zinoviev** [ivpusic/react-native-image-crop-picker#890]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.21.3

Hi, what I'm trying to achieve: Our app need square images with defined border size. The user can pick photo and crop it to the desired square with zooming and scrolling - all good. But for some photo, users want to zoom out to keep image ratio and make color background for missing space. Something like this

Original:

<img width="390" alt="2018-11-28 21 20 34" src="https://user-images.githubusercontent.com/848985/49172984-82608980-f353-11e8-89e1-1fa68b0871f3.png">

Cropped:

<img width="377" alt="2018-11-28 21 12 34" src="https://user-images.githubusercontent.com/848985/49172719-d7e86680-f352-11e8-90bf-b04de83024e3.png">

**Comment by hermance** [comment]
I have the same need, and with this option, the "black borders" are not taken in consideration.
The empty space is ignored in the result (after cropping, there is no black bands).

**Comment by zinoviev** [comment]
@bwillem @hermance  Well, `avoidEmptySpaceAroundImage` was the thing I need. To put colored background I just write native module. So this issue can be closed from my perspective. Probably `avoidEmptySpaceAroundImage` can have better doc description for future users

**Comment by bwillem** [comment]
@zinoviev when I pass avoidEmptySpaceAroundImage i still get the image snapping back to the full frame. Am I missing something?

**Comment by bwillem** [comment]
```
ImagePicker.openPicker({ avoidEmptySpaceAroundImage: false })
```
does nothing

**Comment by zinoviev** [comment]
@bwillem I'm on iOS, don't know if it works for android. If it doesn't work on ios for you - try to upgrade lib version, I think they expose this option not so long ago and clean node modules/caches.

**Comment by bwillem** [comment]
can't get it to work. what RN version are u on?

**Comment by zinoviev** [comment]
@bwillem RN 0.57.8, react-native-image-crop-picker - "^0.21.3"

**Comment by bwillem** [comment]
am now on rn 0.57.8 and image-crop-picker 0.22.0
this is the behaviour i get with the exact same params as above
http://www.giphy.com/gifs/CakU3nHNvBceoy5mbX

**Comment by bwillem** [comment]
What do you mean by "To put colored background I just write native module."
Am I missing a step?
Thanks

**Comment by zinoviev** [comment]
@bwillem For default flowers picture it works same for me. Your picture is already fitted by width, it's inside requested bounding box, so you don't need to crop it any means. I don't think this lib able to zoom less to one of dimensions. In our case we have photos large than 1000px for height and we need to fit them inside smaller square box and this is what `avoidEmptySpaceAroundImage` do, so I think our needs slightly different
