### ISSUE TITLE
installation 

### ISSUE THREAD

**Issue by fatemehmemar123** [ivpusic/react-native-image-crop-picker#892]
hi ,after install get the this error :
Could not resolve all files for configuration ':react-native-image-crop-picker:debugCompileClasspath'.
> Could not find support-annotations.jar (com.android.support:support-annotations:27.1.0).
  Searched in the following locations:
      https://dl.google.com/dl/android/maven2/com/android/support/support-annotations/27.1.0/support-annotations-27.1.0.jar

**Comment by ivpusic** [comment]
cannot reproduce this issue. please make sure that you followed installation steps from readme
