### ISSUE TITLE
Image Uri bug in IOS

### ISSUE THREAD

**Issue by rengasahusoft** [ivpusic/react-native-image-crop-picker#9]
HI 
In ios simulator,  image is displayed without any issue but in ios phone the image is not displayed 

we have tried this module -  https://github.com/marcshilling/react-native-image-picker

image picked from library showing in both emulator and ios phone

image uri of same image fetched using your lib differs from their module

I hope that is the problem.

**Comment by ivpusic** [comment]
thanks for reporting this issue. Fixed in https://github.com/ivpusic/react-native-image-crop-picker/commit/a542e32145755d9367f329d6681ff776f75ca07d. Fix available in version 0.3.0
