### ISSUE TITLE
Code signing "QBImagePicker.framework" failed

### ISSUE THREAD

**Issue by EgidioCaprino** [ivpusic/react-native-image-crop-picker#902]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.21.3
- react-native v0.58.0-rc.1

### Platform
Tell us to which platform this issue is related

- iOS

### Expected behaviour
The app is built for release.

### Actual behaviour
The app fails to build for release.

### Attachments
![image](https://user-images.githubusercontent.com/5156120/50166878-2e105000-02e8-11e9-8604-f78ef510d4df.png)

**Comment by kartavyaparekh96** [comment]
same problem

**Comment by prasad456** [comment]
@kartavyaparekh96 @EgidioCaprino 
Guys, have you cleared the issue?

**Comment by kartavyaparekh96** [comment]
@prasad456 I have install pod and solved that.

**Comment by congy15** [comment]
I'm follow the step by step [https://github.com/ivpusic/react-native-image-crop-picker#manual](this) but still problem same you, how to clear it?
I'm using
React Native 0.59.9
react-native-image-crop-picker 0.24.1
