### ISSUE TITLE
List of error code(s)

### ISSUE THREAD

**Issue by paolospag** [ivpusic/react-native-image-crop-picker#903]
Hi,
I'm using this awesome package to get profile photo and get cropped image in a multilanguage app.
I want to show a message/alert to the user when error occured and I need to translate every error types returned by ```catch``` method when ```ImagePicker.openPicker``` is called.

Is it possible to have a complete list of error code(s)?

### Version
- react-native-image-crop-picker v0.21.3
- react-native v0.57.8

### Platform
Both iOS and Android

### Steps to reproduce
Calling this method: 
```
...
getAndCropImage = () => {
    ImagePicker.openPicker({
      width: 300,
      height: 400,
      cropping: true
    }).then(image => {
      console.log(image);
    }).catch(err => console.log(err.code));
}
...
```

**Comment by koo27** [comment]
You can find your answer on this old closed issue:
https://github.com/ivpusic/react-native-image-crop-picker/issues/884#issuecomment-440379335

> check https://github.com/ivpusic/react-native-image-crop-picker/blob/master/ios/src/ImageCropPicker.m#L10, top of file, defines with ERROR prefixes

**Comment by paolospag** [comment]
Thank you so much @koo27 this is very helpful!
