### ISSUE TITLE
Resulting Image width/height is always greater than compressImageMaxWidth/Height in Android

### ISSUE THREAD

**Issue by shubham1164** [ivpusic/react-native-image-crop-picker#908]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.21.3
- react-native v0.57.4

### Platform
Tell us to which platform this issue is related
- Android

### Expected behaviour
The result image height/width must be equal to or less than compressImageMaxWidth and compressImageMaxHeight

### Actual behaviour
Resulting Image width/height is always greater than compressImageMaxWidth and compressImageMaxHeight. Although the width and height both are reduced by random numbers but not accurately according to the compressImageMaxWidth and compressImageMaxHeight

### Steps to reproduce
Use the below code to fetch Image from gallery:
1. Without compression
ImagePicker.openPicker({
      multiple: true
    }).then(image => {
      // image[0]  => size: 69140, height: 1012, width: 924, mime: image/jpeg
    }).catch(e => {
      console.warn("e: ", e.message);
    })

2. with compressions param
ImagePicker.openPicker({
      multiple: true,
      compressImageMaxWidth: 180,
      compressImageMaxHeight: 180,
    }).then(image => {
      // image[0]  => size: 45532, height: 253, width: 232, mime: image/jpeg
    }).catch(e => {
      console.warn("e: ", e.message);
    })

**Comment by shubham1164** [comment]
I have done code changes by myself. B)

**Comment by leighman** [comment]
What changes did you need to make?

**Comment by shubham1164** [comment]
For compression, I used the react-native-image-resizer and for picking image/video from android/ios gallery, I used the react-native-image-crop-picker

**Comment by shubham1164** [comment]
I have found that this issue occurs only in Android, its working fine in IOS. Although, react-native-image-resizer solves the issue but it will be good if you can solve the issue with this library so that I don't need to use another library (react-native-image-resizer) just for output compression and size issue

**Comment by rat-moonshine** [comment]
Yes, this issue is legit. I actually excited being found that resizing feature is provided by this API itself. So I need not to use another API to resize the image (although, the workingness of the said API didn't fit my needs).

Can you please fix this size issue (?) Thanks!

**Comment by shubham1164** [comment]
Sorry, I am busy tight on schedule, but yes you can use react-native-image-resizer for compression and resizing. It works on both android and IOS. You can use both react-native-image-crop-picker and react-native-image-resizer

**Comment by bonesyblue** [comment]
I've created a PR with a fix for this issue, feel free to check it out and leave feedback 👍

**Comment by leelandclay** [comment]
Just ran into this problem. It's a shame the maintainer wants to take 9+ months to approve/merge a PR :/
