### ISSUE TITLE
Don't Use This Package If Not Using CocoaPods For iOS

### ISSUE THREAD

**Issue by DISKONEKTeD** [ivpusic/react-native-image-crop-picker#909]
Do yourself a favor: don't use this package if you're not using cocoapods on iOS (though, I even saw issues with that).

It's a disservice to claim it works without it because it doesn't. It only works in the development phase. You're under the assumption that if you follow the instructions that it will work, but it won't. It's heavily documented many people can't get it to run in production. Search.

It works great otherwise, but I've completely wasted my time with it, unfortunately.

It's due to the prebuilt stuff that are included that are considered obsolete architecture under the eyes of Apple. They are included supposedly for simulator support, but it makes dealing with the package a headache on iOS otherwise if you want to use your app in an actual production environment.

I recommend just sticking to the original, even if limited: https://github.com/react-native-community/react-native-image-picker

cheers.

**Comment by superandrew213** [comment]
I have been using this package for over a year without cocoapods (and with cocoapods at the begining, since it was the only option).

I don't have any issue building and running it on sim and production.

**Comment by krewllobster** [comment]
The installation instructions could certainly use some work and specificity for ios installation. I messed it up first because I couldn't find the framework files that the docs reference. However, the second time I looked, I found them, and was able to add them, then go and link the library in build phases and it worked fine.
