### ISSUE TITLE
Failed to find Build Tools revision 23.0.3

### ISSUE THREAD

**Issue by RatFou** [ivpusic/react-native-image-crop-picker#91]
### Version

Tell us which versions you are using: 
- react-native-image-crop-picker v0.9.7
- react-native v0.34
### Platform

Tell us to which platform this issue is related
- Android
### Expected behaviour

Run my app in Emulator
### Actual behaviour

Error when I run react-native run-android
### Steps to reproduce

1.npm i react-native-image-crop-picker --save
2.react-native link react-native-image-crop-picker
3.react-native run-android
### Attachments

A problem occurred configuring project ':app'.
A problem occurred configuring project ':react-native-image-crop-picker'. 
failed to find Build Tools revision 23.0.3

// stacktrace or any other useful debug info
- I already have installed Build Tools revision 23.0.3
  https://drive.google.com/open?id=0B2-fvDtYwHQyT3N2bENLVDVvNGc
- I did why you said on https://github.com/ivpusic/react-native-image-crop-picker/commit/6d59b8408aec74ddcd50e9139879355ff517329b

I don't understand what I'm doing wrong, could you please help me?

**Comment by kviswanath** [comment]
I had a very similar problem, in my case adb for pushing the app to the emulator was picked up from /usr/bin and the build for the app was using the sdk/platform-tools from my home directory. 

There was a mismatch in the adb and platform tools version being used for build and deploy. Adding the following in my .bashrc file solved the issue. 

$ANDROID_HOME=<path to android home>
$PATH=$ANDROID_HOME/platform-tools:$PATH

The above configuration ensure the adb and platform tools from the ANDROID_HOME are picked up.

Hope this helps.

**Comment by ivpusic** [comment]
@RatFou did above comment help you?

**Comment by RatFou** [comment]
@ivpusic I will check in few days, thanks

**Comment by tpt22133** [comment]
Please, update your version java to 8. It will better more than version 7.

**Comment by ivpusic** [comment]
@RatFou please reopen if this is still actual

**Comment by nickkapoor** [comment]
I am having this issue.  Builds ok on the ios. But on android I am getting stalled.  PLease help
