### ISSUE TITLE
App store rejecting app for lack of camera permission description but works during testing

### ISSUE THREAD

**Issue by jigajames** [ivpusic/react-native-image-crop-picker#913]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.21.3
- react-native v0.57.7

### Platform
- iOS

I'm trying to get my app approved by apple and they are rejecting saying i am missing a camera permission description.

![them_cam](https://user-images.githubusercontent.com/6396407/51150498-83b52980-18a1-11e9-9289-135ae9cb9203.jpg)

But when I am testing on the simulator and on the device I am seeing the correct description.

![me_cam](https://user-images.githubusercontent.com/6396407/51150515-9596cc80-18a1-11e9-9236-2d103708cb10.jpg)

and here is the description from my Info.plist

`
<key>NSCameraUsageDescription</key>
<string>to allow you to take rental related photos and/or scan rental documents</string>
`

and to show the picker I am doing:

`
ImagePicker.openPicker({
      mediaType: 'photo',
      includeExif: false,
      multiple: true
    }).then(images => {
      this.handleImages(images);
    }).catch((e) => console.log(e));
`
Has anyone run into this issue? Thanks in advance!

**Comment by skizzo** [comment]
You need to add a different type of usage description, since you want to show the ImagePicker and not the Camera. In your `Info.plist`, add:
```
<key>NSPhotoLibraryAddUsageDescription</key>
<string>Please allow usage of your photo library.</string>
```
Cheers
