### ISSUE TITLE
Cropper not called on ios

### ISSUE THREAD

**Issue by danielzzz** [ivpusic/react-native-image-crop-picker#916]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.21.1
- react-native v0.57.8

### Platform
Tell us to which platform this issue is related

- iOS

### Expected behaviour
cropper should appear after selecting a photo

### Actual behaviour
nothing happens

I am getting 
2019-01-18 12:12:07.767580+0100 myApp[301:14326] CroppingFile {
}
Main Thread Checker: UI API called on a background thread: -[UIScrollView zoomScale]

in xcode

thanks, cheers, dan

**Comment by yusunglee2074** [comment]
+1

**Comment by danielzzz** [comment]
it worked when installed with cocoapods

**Comment by ishigamii** [comment]
@danielzzz can you close it as you did find out the reason of your problem

**Comment by danielzzz** [comment]
ok, thx
