### ISSUE TITLE
On android plateform, the maxFiles/minFiles params cannot use.

### ISSUE THREAD

**Issue by UncleWang8898** [ivpusic/react-native-image-crop-picker#919]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.21.3
- react-native v0.57.5

### Platform
Tell us to which platform this issue is related

- iOS
- Android

### Expected behaviour
1.On android plateform, the maxFiles/minFiles params cannot use.
2.On some android plateform(Huawei device), the multiple param cannot use, and on the device only choose one picture once.

### Steps to reproduce

1.

2.

3.

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by ivpusic** [comment]
this is known limitation, dut to built in android gallery

**Comment by ivpusic** [comment]
multi select depends on device manufacturer and android version. on some devices does not work, unfortunately.
