### ISSUE TITLE
allowEmptySpaceAroundImage flag does nothing

### ISSUE THREAD

**Issue by bwillem** [ivpusic/react-native-image-crop-picker#921]
### Version
Tell us which versions you are using:

- react-native-image-crop-picker v0.22.0
- react-native v0.55.4

### Platform
Tell us to which platform this issue is related

- iOS
- Android

### Expected behaviour
`allowEmptySpaceAroundImage: false` should allow cropper to crop below 100%, allowing empty space around the image.

### Actual behaviour
`allowEmptySpaceAroundImage` flag does nothing

### Steps to reproduce

1. Place flag in your image picker params, along with `cropping: true`

2. See that when you crop smaller, image snaps back to 100%.

### Attachements
This commit introduces the option but the options doesn't seem to be wired up.

https://github.com/ivpusic/react-native-image-crop-picker/commit/05662bef75e12d2b4625276571d4b61ba73b0e38

**Comment by ivpusic** [comment]
option is called `avoidEmptySpaceAroundImage`, not `allowEmptySpaceAroundImage`

**Comment by bwillem** [comment]
That was a typo in the comment, sorry. I was using the right name in the code. Still can't doesn't do anything. Am I doing it wrong?
`ImagePicker.openPicker({ avoidEmptySpaceAroundImage: false })`

**Comment by ivpusic** [comment]
yes, looks fine. could you try to debug it if correct value is added to this line after opening picker https://github.com/ivpusic/react-native-image-crop-picker/blob/e5622719c2fae614780160de26d4972168404ddf/ios/src/ImageCropPicker.m#L407

**Comment by bwillem** [comment]
no, it's not being set properly. it does work as expected when I set that value manually

**Comment by ivpusic** [comment]
do you have some time do try to figure out why it is not set?

**Comment by danilobuerger** [comment]
I can only reproduce this on Android. Is this flag even intended for Android?

**Comment by danilobuerger** [comment]
@ivpusic If this is wanted for android, I could create a PR. But I am worried about when it would get merged, seeing the amount of opened and unanswered PRs.

**Comment by bwillem** [comment]
Can't get it to work. Can't get anything to log from ImageCropPicker.m. Very stuck

**Comment by bwillem** [comment]
RN 0.57.8
r-n-i-c-p 0.22.0
with flag set to false i get this behaviour
http://www.giphy.com/gifs/CakU3nHNvBceoy5mbX

**Comment by bwillem** [comment]
i was misunderstanding the functionality. What I need is to be able to pinch the image to become smaller than the bounding box, adding white space around it. That's not what avoidEmptySpaceAroundImage does.

**Comment by CristopherJonas** [comment]
> i was misunderstanding the functionality. What I need is to be able to pinch the image to become smaller than the bounding box, adding white space around it. That's not what avoidEmptySpaceAroundImage does.

And how did you solve your problem @bwillem ?? I need the same functionality.

**Comment by bwillem** [comment]
@CristopherJonas it's not possible to create negative space both vertically and horizontally with this plugin. avoidEmptySapceAroundImage is sort of equivalent to resizeMode: contain.

**Comment by Adigezalov** [comment]
Tell me please. Is the problem solved? If so, how?

**Comment by MinhHieu6796** [comment]
I want to move crop bounding box like android but it cant via ios, what the props i need ?

**Comment by CDBridger** [comment]
Even with the flag set to false, the image still acts like cover instead of contain for me (on iOS)

**Comment by danilobuerger** [comment]
`avoidEmptySpaceAroundImage` is unused since the switch to `TOCropViewController`.

**Comment by CDBridger** [comment]
So there is now way to zoom out to mimic contain behaviour?

**Comment by amanfcp** [comment]
> @CristopherJonas it's not possible to create negative space both vertically and horizontally with this plugin. avoidEmptySapceAroundImage is sort of equivalent to resizeMode: contain.

How can we achieve this? Is there any library?
