### ISSUE TITLE
openCamera mediaType:"any" not working as expected (enables only pictures) 

### ISSUE THREAD

**Issue by koo27** [ivpusic/react-native-image-crop-picker#923]
### Version

- react-native-image-crop-picker v0.22.0
- react-native v0.57.5

### Platform

- iOS
- Android

### Expected behaviour
mediaType: "any" should enable switching between photo and video mode.

### Actual behaviour
when calling openCamera with mediaType: "any" or leaving the default one (i.e. without writing mediaType property at all) enables only the camera for taking a picture and not video.
If I set mediaType: "video" or "photo" it works fine respectively.
I'm not sure about this, but it seems that it happened after setting up the permissions for iOS.

### Steps to reproduce

```
ImagePicker.openCamera({
            mediaType: "any",
        }).then(image => {
[...]
```

It lets you only take picture.
I tested also on a physical android device (honor 8) and it has the same behaviour.

I also tried this workaround (https://github.com/ivpusic/react-native-image-crop-picker/issues/563#issuecomment-355932239) and set `cropping:false` but it doesn't work either.

**Comment by L-Yeiser** [comment]
a relic of the previous release passing `mediaType: 'mixed'` works on iOs.

**Comment by ivpusic** [comment]
this is not yet suported

**Comment by milobluebell** [comment]
when will support it?

**Comment by dev3288** [comment]
any solution for this ?

**Comment by phatmann** [comment]
Supposedly Android does not support it.

**Comment by BooYeu** [comment]
when will support it? @ivpusic  We really really need this function~~thank you very much~~~!!!!

**Comment by jackimatin** [comment]
any solution?

**Comment by catapop84** [comment]
I'm in a similar situation. Any solution to this? Basically a way for user to switch between taking photo or recording a video.
