### ISSUE TITLE
Can't use on real android devices and some emulator devices with API level > 23

### ISSUE THREAD

**Issue by nwaughachukwuma** [ivpusic/react-native-image-crop-picker#925]
Hi Team,

Am not able to get crop-picker to work on real android devices, and most emulators with API level > 23. Please what could be the issue, and what is the potential fix?

Thanks

**Comment by ishigamii** [comment]
what error do you have ?? what version do you use help people to help you

**Comment by nwaughachukwuma** [comment]
Thanks @ishigamii, but I have resolved the issue. The problem is that I had set maxSDKVersion to 23 on write external storage permission in androidmanifest.xml The solution was to set it to 28. Thanks again

**Comment by ishigamii** [comment]
@nwaughachukwuma glad to hear and tanks for giving the answer now can you close the issue if it is solved and same for your other issues if they are solved
