### ISSUE TITLE
how to make alert come for the second time in coding wise if i won't allow user to access the photos for the first time 

### ISSUE THREAD

**Issue by saikiranoptisol** [ivpusic/react-native-image-crop-picker#926]
If on click of button in ios it is showing your app wants to access your photos. if i clickon wont allow for the first time in IOS it's cant coming again. i know i need to go to settings and enable there but i dont want like that. On click of dont allow for the first time the user must be able to get acess alert for the second time how this can be achieved

**Comment by dyaacov** [comment]
Did you find a solution?

**Comment by saikiranoptisol** [comment]
The only you can do is check error message based on that using 'Linking' in reactnative navigate to App settings
