### ISSUE TITLE
Wrong cropped image rect when openCropper is called with width and height props on iOs

### ISSUE THREAD

**Issue by zupodaniel** [ivpusic/react-native-image-crop-picker#929]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.22.0
- react-native v0.55.4

### Platform
Tell us to which platform this issue is related

- iOS

### Expected behaviour

Cropped image when openCropper is called with width and height must respect the cropRect and size.

### Actual behaviour

In despite of the chosen position of the cropper editor my cropRect has Y always in 0 and the image generated is not cropped at all. Without the width and height props the image is cropped like seen in editor. I played with the compressImageMaxWidth and compressImageMaxHeight but no success at all.

My podfile is looking for the pod inside the current version of the plugin: 

pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'

### Steps to reproduce

call ImagePicker.openCropper with any image (can be with default images from simulator), width and height configured (I use 1200x1200) and crop a region in the right bottom side of the image. The image generated will not be the same crop seen during the simulation.

**Comment by ivpusic** [comment]
do you have some time to investigate?

**Comment by zupodaniel** [comment]
I believe it's a problem with the new versions of RSKImageCropper, after version 2.0.0 it doesn't work with react-native-image-crop-picker.

So, I've tested regression with all versions in RSKImageCropper release timeline and ended up forcing version on my podfile right after the declaration of your plugin.

`pod 'RSKImageCropper', '2.0.0'`

**Comment by yasir-netlinks** [comment]
@zupodaniel hey, I believe I am having the same problem, where the image I crop , doesn't appear to be the correct area cropped. I am trying to install `pod 'RSKImageCropper', '2.0.0'`, but I get this error
<img width="895" alt="screen shot 2019-03-03 at 1 48 33 pm" src="https://user-images.githubusercontent.com/26054956/53693225-10b53300-3dbb-11e9-827e-145b7caefeae.png">

**Comment by yasir-netlinks** [comment]
After running `pod update RSKImageCropper` I am still not getting the desired outcome!!!

**Comment by ivpusic** [comment]
RSKImageCropper is not used anymore. please try latest version with TOCropViewController
