### ISSUE TITLE
Styling the crop modal

### ISSUE THREAD

**Issue by ramneekhanda** [ivpusic/react-native-image-crop-picker#93]
Can we change the navbar color, font etc for the crop modal?

Awesome work btw!

**Comment by ivpusic** [comment]
Currently, this is not possible. Lib depends on uCrop and RSKImageCropper, so to allow this we should check if these libs support changing options you mentioned, and them take passed options from user and proxy them to mentioned libs (eg navbarColor: 'blue', etc...).
