### ISSUE TITLE
react-native 0.58.4 app crashes on launch

### ISSUE THREAD

**Issue by alvin-toffler** [ivpusic/react-native-image-crop-picker#934]
### Version
- react-native-image-crop-picker 0.22.0
- react-native 0.58.4

### Platform
- iOS

### Expected behaviour
App runs without crashing.

### Actual behaviour
App loads splash screen and crashes. App is still visible in list of open apps.

### Steps to reproduce

```
react-native init reactNativeImageCropPickerTest
cd reactNativeImageCropPickerTest
npm i react-native-image-crop-picker --save
react-native link react-native-image-crop-picker
react-native run-ios --simulator="iPhone XS"
```

I don't want to use Cocoapods. Thank you!

**Comment by rawadrifai** [comment]
was there a solution to this?

**Comment by evaldsurtans** [comment]
In my case embedding frameworks of dependencies helped

<img width="607" alt="AiBit_xcodeproj" src="https://user-images.githubusercontent.com/1777062/62394797-eee0f780-b576-11e9-8b48-8c4ca50a5b01.png">
