### ISSUE TITLE
Launch image gallery directly

### ISSUE THREAD

**Issue by tigo0** [ivpusic/react-native-image-crop-picker#935]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.22.0
- react-native v0.57.8

### Platform
- Android

### Expected behaviour
Is it possible to open the image gallery directly? Similar to https://github.com/react-native-community/react-native-image-picker `launchImageGallery` function.

### Actual behaviour
When I execute `openPicker` it opens up the file browser from where I can navigate to the gallery.

### Steps to reproduce
Just run openPicker on Android

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by ivpusic** [comment]
behaviour (on android) is vendor and OS version dependent, so currently we cannot provide a consistent way of doing this on android among different android versions and vendors. the reason is because we use built-in api/gallery

**Comment by robert589** [comment]
Hi, could we open the issue look for a way to solve this?

**Comment by victormattosvm** [comment]
Hi. I know this topic is old, but I updated it here: [#1156 ](1156)
