### ISSUE TITLE
Not selecting images in selection sequence

### ISSUE THREAD

**Issue by mayupat13** [ivpusic/react-native-image-crop-picker#938]
### Version

- react-native-image-crop-picker ^0.21.2
- react-native 0.57.1

### Platform
- Android (may be both not tried on IOS)

### Expected behaviour
It should display images in sequence as per user selects images.

### Actual behaviour
When I am selecting the images from mobile in some sequence they are displaying in random sequence. but not displaying on my selection sequence.

### Attachments

Adding mobile screenshots for more info. 
This is Image selection sequence 
![img_20190215_015745](https://user-images.githubusercontent.com/22270616/52816936-5ccc5c00-30c8-11e9-985b-dadf52408e94.jpg)

This is and image displaying sequence

![img_20190215_020022](https://user-images.githubusercontent.com/22270616/52816958-6e156880-30c8-11e9-84ec-b325d49c81f9.jpg)

**Comment by ivpusic** [comment]
this is something what we currently can't control. it is up to your app to show them in a way you want

**Comment by mayupat13** [comment]
So, you mean I have to do to something which i am missing currently to rearrange the sequence?

**Comment by ivpusic** [comment]
nope, I mean library cannot control order of the selected items

**Comment by adamkosmala** [comment]
is it still not possible to have such control over selected images?
