### ISSUE TITLE
pickSingleWithCamera showing an error in xcode and not opening the camera

### ISSUE THREAD

**Issue by team-collaboration** [ivpusic/react-native-image-crop-picker#939]
### Version
0.57.8

- react-native-image-crop-picker v0.22.0
- react-native v0.57.8?

### Platform
- iOS

### Expected behaviour
Should Open the camera

### Actual behaviour
My phone just hanged

When using pickSingleWithCamera function my iphone getting hanged. and on xcode its showing me the error.

Any one can help me please regarding this issue.

`libsystem_kernel.dylib`__abort_with_payload:
    0x18c627df0 <+0>:  mov    x16, #0x209
    0x18c627df4 <+4>:  svc    #0x80
->  0x18c627df8 <+8>:  b.lo   0x18c627e10               ; <+32>.        **Thread 2: signal SIGABRT**
    0x18c627dfc <+12>: stp    x29, x30, [sp, #-0x10]!
    0x18c627e00 <+16>: mov    x29, sp
    0x18c627e04 <+20>: bl     0x18c61e800               ; cerror_nocancel
    0x18c627e08 <+24>: mov    sp, x29
    0x18c627e0c <+28>: ldp    x29, x30, [sp], #0x10
    0x18c627e10 <+32>: ret    
`

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by limaAniceto** [comment]
Can you double-check you've done all the Post-Install steps?
```
In Xcode open Info.plist and add string key NSPhotoLibraryUsageDescription with value that describes why you need access to user photos. More info here https://forums.developer.apple.com/thread/62229. Depending on what features you use, you also may need NSCameraUsageDescription and NSMicrophoneUsageDescription keys.
```
If you don't add the permissions you'll get a SIGABRT error
