### ISSUE TITLE
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.

### ISSUE THREAD

**Issue by harleenarora** [ivpusic/react-native-image-crop-picker#943]
Hi,

I am install new package version but this warning is not gone. Please tell me how to solve this. If I have change custom, but reinstall the npm, this warning is again occur.
Here version is "react-native-image-crop-picker": "^0.22.0"

**Comment by LonelyCpp** [comment]
in the `build.gradle` file, replace 
`compile project(':react-native-image-crop-picker')` 
with 
`implementation project(':react-native-image-crop-picker')`

**Comment by ryanhomer** [comment]
I believe similar changes need to be made in this project's `build.gradle` too.

    dependencies {
        compile 'com.facebook.react:react-native:+'
        compile 'com.github.yalantis:ucrop:2.2.2-native'
    }

My own `build.gradle` uses all `implementation` but I still get the warning for this project.

**Comment by ivpusic** [comment]
fixed in 0.23.1
