### ISSUE TITLE
Rectangle Overlay

### ISSUE THREAD

**Issue by Saad-Bashar** [ivpusic/react-native-image-crop-picker#945]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker -  Latest
"react-native": "0.57.8",

### Platform
Tell us to which platform this issue is related

- iOS
- Android

Is it possible to create a rectangle overlay when users open the camera? Inside camera view.

### Attachments
Something like the following: 

![overlay](https://user-images.githubusercontent.com/13269141/53540713-9afa5e80-3b51-11e9-8e26-b53127b36d34.jpg)

**Comment by ivpusic** [comment]
currently not possible
