### ISSUE TITLE
[Android possible solution] Cannot read property 'openPicker' of undefined

### ISSUE THREAD

**Issue by jelmarose** [ivpusic/react-native-image-crop-picker#946]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.23.0
- react-native v0.57.0

### Platform

- Android

### Expected behaviour

Image Picker opens

### Actual behaviour

Error pops up ``Cannot read property 'openPicker' of undefined``

### Steps to reproduce

1. ``yarn add react-native-image-crop-picker``

2. ``react-native link react-native-image-crop-picker``

3. Call Image Picker from a button

### Solution

Sometimes ``react-native link`` fails. The error usually appears as pink/purple error message on the terminal when you run react-native link. In my case, the reason was that I changed the package name of the app and it's trying to append new code on a non-existent MainApplication.java file.

For manual solution, add the following on your ``MainApplication.java``

``import com.reactnative.ivpusic.imagepicker.PickerPackage;``

```@java
@Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new PickerPackage(), // <== add this
            ....
```

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by ivpusic** [comment]
unfortunately, I cannot help here, this is probably a limitation of current react-native link command.

**Comment by 904492381** [comment]
> unfortunately, I cannot help here, this is probably a limitation of current react-native [link](http://track.uc.cn/lct?appid=2725715d66c1&turl=http://m.sm.cn/s?q=link&from=wm261556&uks=%E5%85%A8%E9%83%A8_link&cls=0&clt=0&rf=github.com&kid=7;uc_param_str=dnntnwvepffrgibijbprsvpidsdichei) command.

If I use react-native>=0.60，can i resolve it？ My version is 0.57

**Comment by snairsumith** [comment]
Any Updates ?
