### ISSUE TITLE
Long press on Android multiselect is :(

### ISSUE THREAD

**Issue by dbarner1** [ivpusic/react-native-image-crop-picker#948]
Hi folks,

I see this is on the to do list: ` Android: Standardize multiple select`

Is there an expectation on where it sits in priority? 

For context, our users would <3 to see multi select work without having to long press photos.  Most users don't understand they need to long press. :/

Mad respect for this repo, @ivpusic 

Thanks!
Dave

**Comment by ivpusic** [comment]
there is no plan in a near future for this. few times I was looking for (stable) pickers which support all features we have right now, but without luck so far. When there is android picker like that, we can plan implementation.

**Comment by rizwan92** [comment]
I also need this functionality when this functionality will be implemented soi can use?

**Comment by gabgagnon** [comment]
Hi, I also need this functionality. I know it is not the normal behaviour for Android but it is more intuitive and prevent someone to select only one item and quit directly.

**Comment by dbarner1** [comment]
@gabgagnon I’d suggest building out your own native experience with RN’s camera roll for this. 

It takes a bit more time, but then you can own the entire ux. See here for a good starter: https://link.medium.com/Vvm2DciG3U

And fwiw, I still use this lib in conjunction. ...Designing google drive support, with folders on folders on folders is...for another day :)
