### ISSUE TITLE
The order of the photos turned upside down in the photo list is returned

### ISSUE THREAD

**Issue by 000xuandu** [ivpusic/react-native-image-crop-picker#953]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.21.3
- react-native v0.55.4

Looks like the order of the images in the library list is not correct with the order in which the photos are selected in the photo gallery.

Someone please give me a useful solution.

**Comment by ivpusic** [comment]
order of photos is not guaranteed.

**Comment by ssinss** [comment]
Check this. https://github.com/questbeat/QBImagePicker/issues/185#issuecomment-283101841

**Comment by arpitjacob** [comment]
can we merge this fix that @ssinss has pointed out.
