### ISSUE TITLE
don't compile with react native 0.59.0

### ISSUE THREAD

**Issue by alainib** [ivpusic/react-native-image-crop-picker#956]
### Version

- react-native-image-crop-picker v0.23.0
- react-native v0.59.0

### Platform
- iOS (not tested yet on Android)

### Expected behaviour

I updated react-native from 0.58.6 to 0.59.0

now i have build error with the following error : 

     'YGValue.h'  file not found

<img width="839" alt="yg" src="https://user-images.githubusercontent.com/7910081/54280649-3c44d400-4598-11e9-91d0-81c82f46eb69.png">

### Actual behaviour

Build error

Any fix ? thanks

**Comment by stajics** [comment]
Try running "pod update" before building the app

**Comment by chuntley** [comment]
> Try running "pod update" before building the app

👍 fixed it for me, thank you.

**Comment by ivpusic** [comment]
just tried it on example project, and looks good on 0.59. reference commit for example project upgrade https://github.com/ivpusic/react-native-image-crop-picker/commit/23ffafa2c4c568b9fe43afe831a96d0f0c77701f.

**Comment by lincolnbf** [comment]
"pod update yoga" worked for me
