### ISSUE TITLE
Failed to select image from album，On Android 9

### ISSUE THREAD

**Issue by ShuChangSC** [ivpusic/react-native-image-crop-picker#958]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.23.0
- react-native v0.55.4

### Platform
Tell us to which platform this issue is related

- Android

### Expected behaviour

Select image from album to succeed

### Actual behaviour
Failed to select image from album，On Android 9

### Steps to reproduce
Error Reporter:
Error: /storage/emulated/0/Pictures/64d1d29f-c9d4-40f8-ad27-88e9cd7a9607.jpg (No such file or directory)

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by boaz-lachman** [comment]
Hi,

Why was this issue closed? Was it resolved?

I'm also facing this issue in react-native 0.56 on an android pie (9) phone

**Comment by CrnogoracIvan** [comment]
Also in Android 8 and RN 0.59.

**Comment by kayzenkayzen** [comment]
I have some issue in multiple android devices, in my case only when select image, not using the camera. How to fix it?

**Comment by liuwei-github** [comment]
Hi, brother, has this problem been solved ?
