### ISSUE TITLE
build fail with issues Apple Mach-o Linker (Id) Error

### ISSUE THREAD

**Issue by chuyihuang** [ivpusic/react-native-image-crop-picker#96]
### Version
Tell us which versions you are using: 

in my package.json: 

    "react": "15.3.2",
    "react-native": "0.34.1",
    "react-native-image-crop-picker": "^0.9.7"

### Platform
IOS(10) with XCODE 8

### Actual behaviour
follow the installation instruction step by step but got the following errors: 
![errors](https://cloud.githubusercontent.com/assets/881008/19065430/13fd329a-8a46-11e6-908f-fbe139b9b506.png)

I got these errors during the process of building app in .xcworkspace
I also follow the steps of issue #89: 
unlink and link again but no luck...

### Steps to reproduce

I created a brand new project to test react-native-image-crop-picker with the podfile: 

```
platform :ios, '8.0'

target 'ipicker' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ipicker
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'

  target 'ipickerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

```
any idea??

**Comment by ivpusic** [comment]
just tried it and works. Please double check what you did for installation.

Podfile I used

```
platform :ios, '8.0'

target 'ipicker' do
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'
end
```

**Comment by chuyihuang** [comment]
thank you, no more Apple Mach-o Linker (Id) Error after removing 

`
    target 'ipickerTests' do
      inherit! :search_paths
      # Pods for testing
    end
`

**Comment by musicode** [comment]
My RN version is 0.48.3, I have the same issue.

![image](https://user-images.githubusercontent.com/2732303/30326696-eac1991a-97fb-11e7-947e-a8c17d05b869.png)

Podfile I used

```
platform :ios, '8.0'

target 'App' do

    pod 'RSKImageCropper'
    pod 'QBImagePickerController'

end
```

**Comment by mschipperheyn** [comment]
I have the same issue. These library references are also visible in Xcode under Build Settings/Library Search Paths. According to what I read on SO, these paths should be removed by they are inferred based on `$(inherited)`

**Comment by mschipperheyn** [comment]
Anyone? This issue should be reopened! 

I think one way forward is to `react-native unlink react-native-image-crop-picker` and then relink it. 
Unlinking lead to the following error in my case, suggesting something is wrong

`It seems something went wrong while unlinking. Error: searchPaths.filter is not a function`

**Comment by mschipperheyn** [comment]
@ivpusic @musicode FINALLY resolved this. You need to add the generated `Pods.xcodeproj` to the `Libraries` folder for your project. Why this doesn't happen automatically on `react-native link` is beyond me.

**Comment by FunkyGeorge** [comment]
@mschipperheyn Thank you! This is what solved that error for me.  For anyone else, this fixed the issue but I also had another issue that was caused by me not linking the module first.  So the combination of those made the package work for me.

**Comment by amberkatyal** [comment]
How to fix this issue? Slider.xcodeproj in appDelegate file RCTRootView.h file not found so I changed it to "React/RCTRootView.h" Now this apple mach-o linker error im getting 151 of them...

**Comment by fabriziobertoglio1987** [comment]
https://stackoverflow.com/questions/39545880/apple-mach-o-linker-ditto-error-xcode-8

**Comment by fabriziobertoglio1987** [comment]
https://stackoverflow.com/questions/5329001/apple-mach-o-linker-error-when-compiling-for-device
