### ISSUE TITLE
Not compatible with new react native version

### ISSUE THREAD

**Issue by kunal886496** [ivpusic/react-native-image-crop-picker#965]
### Version

- react-native-image-crop-picker- Latest
- react-native v0.58.4

### Platform

- Android

It gives the error for react native gesture handler.

I had to downgrade the version to 0.21.2.

Please review this.

**Comment by naoey** [comment]
Unsure if related, but I'm also having trouble getting this library to work with RN 59. I'm seeing a "Malformed calls from JS" error:
<img width="472" alt="image" src="https://user-images.githubusercontent.com/3889501/54662287-921efc00-4b03-11e9-8f98-ba14c1d5fe80.png">

**Comment by ivpusic** [comment]
just tried it on example project, and looks good on 0.59. reference commit for example project upgrade https://github.com/ivpusic/react-native-image-crop-picker/commit/23ffafa2c4c568b9fe43afe831a96d0f0c77701f.
