### ISSUE TITLE
NPMJS not updated

### ISSUE THREAD

**Issue by cyphereza** [ivpusic/react-native-image-crop-picker#970]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.23.x
- react-native v0.59.1

### Platform
Tell us to which platform this issue is related

- iOS
- Android

### Expected behaviour

yarn or npm install would install 0.23.1

### Actual behaviour

I am prompted to choose which version, 0.23.0 being latest.

### Steps to reproduce

1. yarn or npm install

### Attachments

<img width="1375" alt="Screenshot 2019-03-23 at 7 33 00 PM" src="https://user-images.githubusercontent.com/31456191/54865581-7f762280-4da2-11e9-94f5-3d4b2f67e77d.png">

**Comment by ivpusic** [comment]
updated now
