### ISSUE TITLE
Cropping issue in Android 6 when photo from camera

### ISSUE THREAD

**Issue by minmedia** [ivpusic/react-native-image-crop-picker#98]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.8.3
- react-native v0.31

### Platform
Tell us to which platform this issue is related

- Android

### Expected behaviour

Take photo from camera with cropping.

### Actual behaviour

In Android 6 it showed cannot find image data.
In Android 4.4.4 no this issue.

If I without cropping. I can got photo from camera and showed it in Android 6

### Steps to reproduce

1. take a photo from camera

2. cropping

**Comment by ivpusic** [comment]
Can you please attach stacktrace output from Android studio when this error happens? Thanks

**Comment by minmedia** [comment]
Thank you for your reply.
Ok, I will attach it next week

**Comment by mywaystar** [comment]
Same issue here on Android 6

**Comment by minmedia** [comment]
Hello @ivpusic 
stacktrace output:
`10-10 19:01:10.910 4031-4039/com.minmedia.showroom W/NativeMemoryChunk: finalize: Chunk 4db9b0e still active. Underlying address = ffffffffac38e9b0
10-10 19:01:19.357 4031-4031/com.minmedia.showroom I/HwSecImmHelper: mSecurityInputMethodService is null
10-10 19:01:19.426 4031-4031/com.minmedia.showroom E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /storage/emulated/0/Pictures/image-3c13f882-1681-4a29-be34-f9066ddaef22.jpg: open failed: EACCES (Permission denied)
10-10 19:01:19.427 4031-4031/com.minmedia.showroom W/System.err: java.io.FileNotFoundException: /storage/emulated/0/Pictures/image-3c13f882-1681-4a29-be34-f9066ddaef22.jpg: open failed: EACCES (Permission denied)
10-10 19:01:19.430 4031-4031/com.minmedia.showroom W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:459)
10-10 19:01:19.430 4031-4031/com.minmedia.showroom W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:76)
10-10 19:01:19.430 4031-4031/com.minmedia.showroom W/System.err:     at com.reactnative.ivpusic.imagepicker.PickerModule.getBase64StringFromFile(PickerModule.java:234)
10-10 19:01:19.430 4031-4031/com.minmedia.showroom W/System.err:     at com.reactnative.ivpusic.imagepicker.PickerModule.getImage(PickerModule.java:323)
10-10 19:01:19.431 4031-4031/com.minmedia.showroom W/System.err:     at com.reactnative.ivpusic.imagepicker.PickerModule.cameraPickerResult(PickerModule.java:408)
10-10 19:01:19.431 4031-4031/com.minmedia.showroom W/System.err:     at com.reactnative.ivpusic.imagepicker.PickerModule.onActivityResult(PickerModule.java:438)
10-10 19:01:19.431 4031-4031/com.minmedia.showroom W/System.err:     at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:210)
10-10 19:01:19.431 4031-4031/com.minmedia.showroom W/System.err:     at com.facebook.react.XReactInstanceManagerImpl.onActivityResult(XReactInstanceManagerImpl.java:595)
10-10 19:01:19.431 4031-4031/com.minmedia.showroom W/System.err:     at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:147)
10-10 19:01:19.431 4031-4031/com.minmedia.showroom W/System.err:     at android.app.Activity.dispatchActivityResult(Activity.java:6597)
10-10 19:01:19.431 4031-4031/com.minmedia.showroom W/System.err:     at android.app.ActivityThread.deliverResults(ActivityThread.java:3726)
10-10 19:01:19.431 4031-4031/com.minmedia.showroom W/System.err:     at android.app.ActivityThread.handleSendResult(ActivityThread.java:3773)
10-10 19:01:19.431 4031-4031/com.minmedia.showroom W/System.err:     at android.app.ActivityThread.access$1400(ActivityThread.java:165)
10-10 19:01:19.431 4031-4031/com.minmedia.showroom W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1418)
10-10 19:01:19.431 4031-4031/com.minmedia.showroom W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
10-10 19:01:19.431 4031-4031/com.minmedia.showroom W/System.err:     at android.os.Looper.loop(Looper.java:150)
10-10 19:01:19.431 4031-4031/com.minmedia.showroom W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5546)
10-10 19:01:19.431 4031-4031/com.minmedia.showroom W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
10-10 19:01:19.431 4031-4031/com.minmedia.showroom W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
10-10 19:01:19.431 4031-4031/com.minmedia.showroom W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
10-10 19:01:19.431 4031-4031/com.minmedia.showroom W/System.err: Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
10-10 19:01:19.432 4031-4031/com.minmedia.showroom W/System.err:     at libcore.io.Posix.open(Native Method)
10-10 19:01:19.432 4031-4031/com.minmedia.showroom W/System.err:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
10-10 19:01:19.432 4031-4031/com.minmedia.showroom W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:445)
10-10 19:01:19.432 4031-4031/com.minmedia.showroom W/System.err: 	... 19 more
10-10 19:01:19.441 4031-4662/com.minmedia.showroom I/ReactNativeJS: 'received image', 'file:///storage/emulated/0/Pictures/image-3c13f882-1681-4a29-be34-f9066ddaef22.jpg'
10-10 19:01:19.494 4031-4031/com.minmedia.showroom I/HwSecImmHelper: mSecurityInputMethodService is null
10-10 19:01:19.674 4031-4663/com.minmedia.showroom I/System.out: /data/user/0/com.minmedia.showroom/cache/react-native-image-crop-picker
10-10 19:01:19.682 4031-4662/com.minmedia.showroom I/ReactNativeJS: removed all tmp images from tmp directory
10-10 19:01:19.689 4031-6794/com.minmedia.showroom I/System: core_booster, getBoosterConfig = false
10-10 19:01:21.720 4031-6830/com.minmedia.showroom I/System: core_booster, getBoosterConfig = false
10-10 19:01:23.759 4031-6864/com.minmedia.showroom I/System: core_booster, getBoosterConfig = false
10-10 19:01:25.800 4031-6896/com.minmedia.showroom I/System: core_booster, getBoosterConfig = false`

**Comment by ivpusic** [comment]
http://www.captechconsulting.com/blogs/runtime-permissions-best-practices-and-how-to-gracefully-handle-permission-removal it is this issue. @minmedia do you have a time to add a support for Android 6?

**Comment by minmedia** [comment]
oh....
I am trying on this.
https://facebook.github.io/react-native/docs/permissionsandroid.html

**Comment by minmedia** [comment]
I were tried it.
But I got same issue.

10-11 01:13:15.212 17587-17587/com.minmedia.showroom V/ActivityThread: Finishing stop of ActivityRecord{c064633 token=android.os.BinderProxy@6819df0 {com.minmedia.showroom/com.minmedia.showroom.MainActivity}}: show=false win=com.android.internal.policy.PhoneWindow@99f99fb
10-11 01:13:15.213 17587-17587/com.minmedia.showroom V/PhoneWindow: DecorView setVisiblity: visibility = 4 ,Parent =ViewRoot{e6d2223 com.minmedia.showroom/com.minmedia.showroom.MainActivity,ident = 5}, this =com.android.internal.policy.PhoneWindow$DecorView{d1e4afa I.E...... R......D 0,0-1080,1920}
10-11 01:13:15.213 17587-17587/com.minmedia.showroom D/ActivityThread: ACT-STOP_ACTIVITY_HIDE handled : 0 / android.os.BinderProxy@6819df0
10-11 01:13:18.238 17587-17600/com.minmedia.showroom I/ActivityThreadEui: scheduleResumeActivity com.minmedia.showroom.MainActivity
10-11 01:13:18.251 17587-17587/com.minmedia.showroom I/System.out: /data/user/0/com.minmedia.showroom/cache/react-native-image-crop-picker
10-11 01:13:18.255 17587-17599/com.minmedia.showroom I/ActivityThreadEui: schedulePauseActivity com.minmedia.showroom.MainActivity finished=false userLeaving=true configChanges=0 dontReport=false
10-11 01:13:18.257 17587-17587/com.minmedia.showroom D/ActivityThread: SEND_RESULT handled : 0 / ResultData{token=android.os.BinderProxy@6819df0 results[ResultInfo{who=null, request=2, result=-1, data=null}]}
10-11 01:13:18.257 17587-17587/com.minmedia.showroom V/ActivityThread: Performing resume of ActivityRecord{c064633 token=android.os.BinderProxy@6819df0 {com.minmedia.showroom/com.minmedia.showroom.MainActivity}}
10-11 01:13:18.283 17587-17587/com.minmedia.showroom D/ActivityThread: ACT-AM_ON_RESUME_CALLED ActivityRecord{c064633 token=android.os.BinderProxy@6819df0 {com.minmedia.showroom/com.minmedia.showroom.MainActivity}}
10-11 01:13:18.283 17587-17587/com.minmedia.showroom V/ActivityThread: Resume ActivityRecord{c064633 token=android.os.BinderProxy@6819df0 {com.minmedia.showroom/com.minmedia.showroom.MainActivity}} started activity: false, hideForNow: false, finished: false
10-11 01:13:18.284 17587-17587/com.minmedia.showroom D/ActivityThreadEui: check reason flags for activity window =com.minmedia.showroom.MainActivity reasonFlags=0
10-11 01:13:18.284 17587-17587/com.minmedia.showroom V/ActivityThread: Resuming ActivityRecord{c064633 token=android.os.BinderProxy@6819df0 {com.minmedia.showroom/com.minmedia.showroom.MainActivity}} with isForward=false
10-11 01:13:18.284 17587-17587/com.minmedia.showroom V/PhoneWindow: DecorView setVisiblity: visibility = 0 ,Parent =ViewRoot{e6d2223 com.minmedia.showroom/com.minmedia.showroom.MainActivity,ident = 5}, this =com.android.internal.policy.PhoneWindow$DecorView{d1e4afa V.E...... R.....ID 0,0-1080,1920}
10-11 01:13:18.284 17587-17587/com.minmedia.showroom V/ActivityThread: Scheduling idle handler for ActivityRecord{c064633 token=android.os.BinderProxy@6819df0 {com.minmedia.showroom/com.minmedia.showroom.MainActivity}}
10-11 01:13:18.284 17587-17587/com.minmedia.showroom D/ActivityThread: ACT-RESUME_ACTIVITY handled : 0 / android.os.BinderProxy@6819df0
10-11 01:13:18.308 17587-17587/com.minmedia.showroom D/ActivityThread: ACT-AM_ON_PAUSE_CALLED ActivityRecord{c064633 token=android.os.BinderProxy@6819df0 {com.minmedia.showroom/com.minmedia.showroom.MainActivity}}
10-11 01:13:18.312 17587-17587/com.minmedia.showroom D/ActivityThread: ACT-PAUSE_ACTIVITY handled : 1 / android.os.BinderProxy@6819df0
10-11 01:13:18.317 17587-17607/com.minmedia.showroom D/OpenGLRenderer: CanvasContext() 0xee107000 initialize window=0xd998db08, title=com.minmedia.showroom/com.minmedia.showroom.MainActivity
10-11 01:13:18.317 17587-17587/com.minmedia.showroom D/Surface: Surface::allocateBuffers(this=0xd998db00)
10-11 01:13:18.317 17587-17607/com.minmedia.showroom D/Surface: Surface::connect(this=0xd998db00,api=1)
10-11 01:13:18.317 17587-17607/com.minmedia.showroom W/libEGL: [ANDROID_RECORDABLE] format: 1
10-11 01:13:18.322 17587-17587/com.minmedia.showroom V/ActivityThread: Handling launch of ActivityRecord{a04ec5b token=android.os.BinderProxy@d7e8cf8 {com.minmedia.showroom/com.yalantis.ucrop.UCropActivity}} startsNotResumed=false
10-11 01:13:18.323 17587-17587/com.minmedia.showroom V/ActivityThread: ActivityRecord{a04ec5b token=android.os.BinderProxy@d7e8cf8 {com.minmedia.showroom/com.yalantis.ucrop.UCropActivity}}: app=com.minmedia.showroom.MainApplication@385bac3, appName=com.minmedia.showroom, pkg=com.minmedia.showroom, comp={com.minmedia.showroom/com.yalantis.ucrop.UCropActivity}, dir=/data/app/com.minmedia.showroom-2/base.apk
10-11 01:13:18.323 17587-17607/com.minmedia.showroom D/IMGSRV: gralloc_register_buffer:1370: hnd=0xd9404040 ID=137860 fd=36 ref=1
10-11 01:13:18.359 17587-17598/com.minmedia.showroom I/art: Background sticky concurrent mark sweep GC freed 52702(2MB) AllocSpace objects, 0(0B) LOS objects, 9% free, 35MB/39MB, paused 5.361ms total 25.349ms
10-11 01:13:18.360 17587-17596/com.minmedia.showroom I/System: FinalizerDaemon: finalize objects = 457
10-11 01:13:18.373 17587-17587/com.minmedia.showroom V/IMGSRV: IMGeglDestroyContext:4669: eglDestroyContext [+]
10-11 01:13:18.375 17587-17587/com.minmedia.showroom V/IMGSRV: IMGeglDestroyContext:4738: eglDestroyContext [-]
10-11 01:13:18.375 17587-17587/com.minmedia.showroom D/BitmapLoadUtils: maxBitmapSize: 2202
10-11 01:13:18.376 17587-17606/com.minmedia.showroom D/BitmapWorkerTask: Uri scheme: file
10-11 01:13:18.376 17587-17606/com.minmedia.showroom D/skia: --- SkImageDecoder::Factory returned null
10-11 01:13:18.377 17587-17587/com.minmedia.showroom V/ActivityThread: Performing resume of ActivityRecord{a04ec5b token=android.os.BinderProxy@d7e8cf8 {com.minmedia.showroom/com.yalantis.ucrop.UCropActivity}}
10-11 01:13:18.377 17587-17587/com.minmedia.showroom D/ActivityThread: ACT-AM_ON_RESUME_CALLED ActivityRecord{a04ec5b token=android.os.BinderProxy@d7e8cf8 {com.minmedia.showroom/com.yalantis.ucrop.UCropActivity}}
10-11 01:13:18.377 17587-17587/com.minmedia.showroom V/ActivityThread: Resume ActivityRecord{a04ec5b token=android.os.BinderProxy@d7e8cf8 {com.minmedia.showroom/com.yalantis.ucrop.UCropActivity}} started activity: false, hideForNow: false, finished: false
10-11 01:13:18.377 17587-17587/com.minmedia.showroom D/ActivityThreadEui: check reason flags for activity window =com.yalantis.ucrop.UCropActivity reasonFlags=0
10-11 01:13:18.377 17587-17587/com.minmedia.showroom V/PhoneWindow: DecorView setVisiblity: visibility = 4 ,Parent =null, this =com.android.internal.policy.PhoneWindow$DecorView{2811836 I.E...... R.....ID 0,0-0,0}
10-11 01:13:18.377 17587-17587/com.minmedia.showroom D/WindowClient: Add to mViews: com.android.internal.policy.PhoneWindow$DecorView{2811836 I.E...... R.....ID 0,0-0,0}, this = android.view.WindowManagerGlobal@82327e8
10-11 01:13:18.378 17587-17587/com.minmedia.showroom E/OpenGLRenderer: PerfServiceNative_notifyRenderTime init fail!
10-11 01:13:18.378 17587-17607/com.minmedia.showroom D/OpenGLRenderer: CanvasContext() 0xd3927800
10-11 01:13:18.379 17587-17587/com.minmedia.showroom D/ViewRootImpl: hardware acceleration is enabled, this = ViewRoot{2614b85 com.minmedia.showroom/com.yalantis.ucrop.UCropActivity,ident = 13}
10-11 01:13:18.381 17587-17587/com.minmedia.showroom V/ActivityThread: Resuming ActivityRecord{a04ec5b token=android.os.BinderProxy@d7e8cf8 {com.minmedia.showroom/com.yalantis.ucrop.UCropActivity}} with isForward=true
10-11 01:13:18.381 17587-17587/com.minmedia.showroom V/PhoneWindow: DecorView setVisiblity: visibility = 0 ,Parent =ViewRoot{2614b85 com.minmedia.showroom/com.yalantis.ucrop.UCropActivity,ident = 13}, this =com.android.internal.policy.PhoneWindow$DecorView{2811836 V.E...... R.....ID 0,0-0,0}
10-11 01:13:18.381 17587-17587/com.minmedia.showroom V/ActivityThread: Scheduling idle handler for ActivityRecord{a04ec5b token=android.os.BinderProxy@d7e8cf8 {com.minmedia.showroom/com.yalantis.ucrop.UCropActivity}}
10-11 01:13:18.382 17587-17587/com.minmedia.showroom D/ActivityThread: ACT-LAUNCH_ACTIVITY handled : 0 / ActivityRecord{a04ec5b token=android.os.BinderProxy@d7e8cf8 {com.minmedia.showroom/com.yalantis.ucrop.UCropActivity}}
10-11 01:13:18.438 17587-17587/com.minmedia.showroom D/Surface: Surface::allocateBuffers(this=0xd3019600)
10-11 01:13:18.438 17587-17607/com.minmedia.showroom D/OpenGLRenderer: CanvasContext() 0xd3927800 initialize window=0xd3019608, title=com.minmedia.showroom/com.yalantis.ucrop.UCropActivity
10-11 01:13:18.438 17587-17607/com.minmedia.showroom D/Surface: Surface::connect(this=0xd3019600,api=1)
10-11 01:13:18.438 17587-17607/com.minmedia.showroom W/libEGL: [ANDROID_RECORDABLE] format: 1
10-11 01:13:18.450 17587-17587/com.minmedia.showroom E/TransformImageView: onFailure: setImageUri
                                                                                  java.lang.IllegalArgumentException: **Bounds for bitmap could not be retrieved from the Uri: [file:///storage/emulated/0/Pictures/image-6ff19b49-6ba2-4dc1-8b1a-43c2eb05c951.jpg]**
                                                                                      at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:113)
                                                                                      at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:41)
                                                                                      at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                      at java.lang.Thread.run(Thread.java:818)
10-11 01:13:18.455 17587-17607/com.minmedia.showroom D/IMGSRV: gralloc_register_buffer:1370: hnd=0xd9403320 ID=137895 fd=46 ref=1
10-11 01:13:18.458 17587-17599/com.minmedia.showroom I/ActivityThreadEui: schedulePauseActivity com.yalantis.ucrop.UCropActivity finished=true userLeaving=false configChanges=0 dontReport=false
10-11 01:13:18.474 17587-17607/com.minmedia.showroom D/IMGSRV: gralloc_register_buffer:1370: hnd=0xd9404360 ID=137896 fd=50 ref=1
10-11 01:13:18.496 17587-17587/com.minmedia.showroom V/InputMethodManager: onWindowFocus: null softInputMode=288 first=true flags=#81810100
10-11 01:13:18.496 17587-17587/com.minmedia.showroom V/InputMethodManager: START INPUT: com.android.internal.policy.PhoneWindow$DecorView{2811836 V.E...... R.....ID 0,0-1080,1920} ic=null tba=android.view.inputmethod.EditorInfo@12beaee controlFlags=#104
10-11 01:13:18.500 17587-17587/com.minmedia.showroom D/ActivityThread: ACT-AM_ON_PAUSE_CALLED ActivityRecord{a04ec5b token=android.os.BinderProxy@d7e8cf8 {com.minmedia.showroom/com.yalantis.ucrop.UCropActivity}}
10-11 01:13:18.503 17587-17600/com.minmedia.showroom I/ActivityThreadEui: scheduleResumeActivity com.minmedia.showroom.MainActivity

**Comment by minmedia** [comment]
I fixed
permissions issue: 
https://github.com/lucasferreira/react-native-android-permissions

Bounds for bitmap could not be retrieved from the Uri: 
https://github.com/Yalantis/uCrop/pull/192/commits/a71363d66e9ae83400c20e8e34eaee69ce2af5b9

**Comment by ivpusic** [comment]
try new version https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.10.0. It is about fixing this issue
