### ISSUE TITLE
multi select problem

### ISSUE THREAD

**Issue by Golddragon0614** [ivpusic/react-native-image-crop-picker#982]
I long press first item when multiple select.But I want to click first time,too.Help.Thank you

**Comment by cloudy-ninja** [comment]
I have the same issue. Could you help me to fix this issue?

**Comment by ericwhitefield** [comment]
Same problem. Users won't understand this, so multiple select is effectively broken.

**Comment by ivpusic** [comment]
this is limitation of built in android gallery which we use.

**Comment by Sammy-iiitb** [comment]
If that is a limitation in android gallery, are there any chances of this fix in next releases, otherwise there is no point of multi select if there is an issue with android gallery itself.

**Comment by ivpusic** [comment]
many android galleries do support multi select. unfortunately I cannot promise when this will be fixed

**Comment by Lylisa** [comment]
Same issue, users can not understand long press really ,there are prefer to on tap  press select the multiple images, hope can fix this in the next version ,thanks.
