### ISSUE TITLE
[QUESTIONS] Why Cocoapods is highly recommended for this?

### ISSUE THREAD

**Issue by Steffi3rd** [ivpusic/react-native-image-crop-picker#988]
I want to try this package but I don't have Cocoapods.
(I'm still a new one to React Native). 

- So I'm wondering why is highly recommended ? and recommended for this package ?

- Is it possible to add Cocoapods in a existing project ?

Until now, I always used `react-native link`

Thanks

**Comment by MateusAndrade** [comment]
Personally i found that using cocoads are more simple to manage your dependencies on IOS. Since using this aproach, you will only need to run a `pod install` or update to manage your IOS dependencies.

When i started using React-Native i have the same doubt, but by using a podile(cocopods) to manage my dependencies was a much better option than trying to manage 'them by hand'.

What turns out to be a bit confusing, is how to use cocoapods (or just pods). Since using them, you end up centralizing the installation of dependencies in IOS in one place. (You still need the react-native-link). The main advantage of using the pods is to have in one place defined their dependencies in IOS.

I think seeing this: #762 can give you a hand. Also, you can check on this [article](https://shift.infinite.red/beginner-s-guide-to-using-cocoapods-with-react-native-46cb4d372995) that helped me A LOT when i started using pods.

And here is a Podfile that was using on a project to clarify the things.

```ruby
`# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'project' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for project
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/DynamicLinks', '~> 5.3.0'
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTImage',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTLinkingIOS',
    'RCTSettings',
    'RCTVibration',  
  ]

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'
  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'

  target '####ProjectTarget' do
    inherit! :search_paths
    # Pods for testing
  end

  # very important to have, unless you removed React dependencies for Libraries 
  # and you rely on Cocoapods to manage it
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
  end
end
```

Hope it helps! =D

**Comment by paolospag** [comment]
@MateusAndrade @ivpusic 
Is it possible to only use `pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'` without rely on Cocoapods to manage React dependencies? Like this: 

```
target 'AppName' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AppName

  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'

  target 'AppNameTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

**Comment by MateusAndrade** [comment]
> @MateusAndrade @ivpusic
> Is it possible to only use `pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'` without rely on Cocoapods to manage React dependencies? Like this:
> 
> ```
> target 'AppName' do
>   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
>   # use_frameworks!
> 
>   # Pods for AppName
> 
>   pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'
> 
>   target 'AppNameTests' do
>     inherit! :search_paths
>     # Pods for testing
>   end
> 
> end
> ```

You can try this, but according to the docs of rn tis highly recommend to rely on on cocoapods or manage your dependencies without it.

I got a a lot of problems trying to manage a project without cocoapods on my dependencies after started using this. Btw, why you dont want use pods to manage your dependencies?

**Comment by paolospag** [comment]
@MateusAndrade 
I would like to use pod to manage my dependencies, like Vector Icons or Image Crop Picker in this way:
```
target 'AppName' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AppName

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'

  target 'AppNameTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```
but I don't want to install [React Core dependencies](https://github.com/ivpusic/react-native-image-crop-picker/blob/master/RNImageCropPicker.podspec#L17).
Honestly, I don't know if this is possible, I have never tried...  before trying I would like some confirmations on the operation

**Comment by MateusAndrade** [comment]
> @MateusAndrade
> I would like to use pod to manage my dependencies, like Vector Icons or Image Crop Picker in this way:
> 
> ```
> target 'AppName' do
>   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
>   # use_frameworks!
> 
>   # Pods for AppName
> 
>   pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
>   pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'
> 
>   target 'AppNameTests' do
>     inherit! :search_paths
>     # Pods for testing
>   end
> 
> end
> ```
> 
> but I don't want to install [React Core dependencies](https://github.com/ivpusic/react-native-image-crop-picker/blob/master/RNImageCropPicker.podspec#L17).
> Honestly, I don't know if this is possible, I have never tried... before trying I would like some confirmations on the operation

We can try at your own this approach. But im dont see a reason to dont install React Core Dependencies since you are using Podfiles. Using Podfiles you can even set specific versions, paths to your dependencies, etc.

**Comment by MateusAndrade** [comment]
Scince i dont see a reason to this pr stay open, If any mantainer wants to close this. I dont see any problem
