### ISSUE TITLE
Video Compression for android

### ISSUE THREAD

**Issue by harikrishna1213** [ivpusic/react-native-image-crop-picker#991]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.?.?
- react-native v0.?.?

### Platform
Tell us to which platform this issue is related

- iOS
- Android

### Steps to reproduce

1.

2.

3.

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by harikrishna1213** [comment]
Hi, I have used this library for selecting and compressing video. This library was simply good for video compressing in IOS. But couldn't able to compress in android. Please give any solution to compress video in android.

Thanks

**Comment by ivpusic** [comment]
video compression on android is currently not supported
