### ISSUE TITLE
cropperCircleOverlay doesn't create circular image

### ISSUE THREAD

**Issue by AlecZadikian9001** [ivpusic/react-native-image-crop-picker#996]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.24.0
- react-native v0.57.0

### Platform
iOS

### Expected behaviour
Following the example, I created an image picker with `cropperCircleOverlay` and `cropping` enabled. I expect to see the picker show up with the circular overlay, then when I press "Choose," the callback should be called with a circular image cut out from where the overlay was indicating (jpeg with white background or png with transparent, preferably png).

The docs aren't clear on whether the circular overlay is just an overlay or also used for cropping, but I'd expect the latter.

### Actual behaviour
The resulting image is square, cropped to the square area surrounding the circle.

### Steps to reproduce
```
const options = {
  width: 1024,
  height: 1024,
  compressImageMaxWidth: 1024,
  compressImageMaxHeight: 1024,
  avoidEmptySpaceAroundImage: true,
  cropping: true,
  cropperCircleOverlay: true,
  mediaType: "photo",
}
// triggered by button press:
ImagePicker.openPicker(options).then(image => {
    console.log({image});
    this_.setState({image: {uri: image.path}})
});
...
// in my render():
<Image style={{flex: 1, aspectRatio: 1}} source={this.state.image}/>
```
Also, checked the logged image, and opened that file in my Mac's file browser

### Attachments
the picker:
![Screen Shot 2019-04-28 at 3 05 54 PM](https://user-images.githubusercontent.com/5402886/56870653-64ad5400-69c7-11e9-8fac-5563d1194bf9.png)
the resulting image:
![Screen Shot 2019-04-28 at 3 05 58 PM](https://user-images.githubusercontent.com/5402886/56870657-67a84480-69c7-11e9-81df-40877a253e3e.png)

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by nihp** [comment]
@AlecZadikian9001 It not create a circular image. You need to add styles for that image to view in a circular shape.

<Image style={{ width: 100, height: 100, borderRadius: 50}} source={this.state.image}/>

Try with these styles
